#+title:      Dialog zw Theologie und Naturwissenschaften
#+date:       [2022-12-26 Mo 11:37]
#+filetags:   :science:theology:
#+identifier: 20221226T113745

[[denote:20221228T204513][A Klasse 2020-24]]

[[denote:20221230T193718][B Klasse 2020-24]]

[[denote:20221228T204149][C Klasse 2020-24]]

[[denote:20221228T205258][A Klasse 2019-23]]

* Kompetenzbeschreibung
[[#A2]] Menschen und ihre Lebensorientierungen - Sich mit den großen Fragen der Menschen auseinandersetzen können
[[#A2_KB1]] Die Schüler können die Frage nach dem Woher anhand biblischer Schöpfungsvorstellungen und naturwissenschaftlicher Konzepte bearbeiten und deren Vereinbarkeit argumentativ darlegen.

* AB / UH
[[#A2_UH1]] Dialog zwischen Theologie und Naturwissenschaften 

* Wiederholung


* Erarbeitung
Eine überschätzte Spezies | Doku Reupload | ARTE
[[https://www.youtube.com/watch?v=N3xjGxqKpwM]]

[[http://webcompetent.org/was-ist-der-mensch-noch-dass-du-seiner-gedenkst/#more-8881][Was ist der Mensch noch, dass du seiner gedenkst? - webcompetent % %]]

** Was ist der Mensch noch, dass du seiner gedenkst?
Der Jahreswechsel wird häufig von einer Rückschau auf das vergangene Jahr und Vorsätzen begleitet. Die Frage nach den guten Vorsätzen, könnte auch lauten: „Wer bin ich und wie möchte ich sein?“ Stärker verallgemeinert führt uns diese Reflexion zur Frage nach dem Wesen des Menschen überhaupt. Weder auf der Ebene des Individuums noch auf der der Spezies lassen sich Antworten ohne Relationen und Kontexte finden. Denn eigentlich müsste man die obigen Fragen präzisieren und fragen, wer man für andere ist und sein möchte und welches Verhältnis der Mensch zu seinen Mitgeschöpfen, zur gesamten Schöpfung und zu Gott hat.

Beide Schöpfungsmythen am Anfang der Bibel setzen den Menschen ins Verhältnis zur damals bekannten Ordnung und nutzen zwangsläufig und selbstverständlich das damalige Wissen über den Kosmos. Dass der Mensch nun Krone und Mittelpunkt der Schöpfung sei, ist eine häufig anzutreffende Verkürzung, welche das biblische Menschenbild nur unzureichend beschreiben kann. Der hier vorgestellte Videoclip „Eine überschätzte Spezies“ zeichnet ein völlig anderes Bild, wenn er den Menschen auf Basis unseres heutigen Wissens einzuordnen versucht. Dabei machen die Autoren eigentlich nichts anderes als die Verfasser der biblischen Überlieferung und es stellt sich die Frage, welche Bedeutung biologisches und kosmologisches Wissen für die Beantwortung zentraler Fragen der Anthropologie eigentlich hat.

Die Frage, wie bedeutsam der Mensch als biologische Art ist, unterscheidet sich von der Frage, ob meine eigene Existenz von Bedeutung ist. Ist die Sinnfrage eine Sache des Denkens oder des Fühlens? Ermöglicht, erschwert oder behindert unser Wissen um die Beschaffenheit der Welt religiöse Sinnstiftung, ist sie davon abgekoppelt oder hat sie nicht zwingend eine vertiefte Auseinandersetzung mit allem was uns umgibt zur Voraussetzung. Und was ist der Mensch dann noch, wenn er gar nicht mehr so besonders dasteht.

Im Folgenden wird der Versuch unternommen sich dem Verhältnis zwischen belebtem sowie unbelebtem Kosmos und der Anthropologie didaktisch zu nähern.

** Mögliche Vertiefungsaufgaben zum Film
Auch die Autoren des 1. Schöpfungsmythos haben für ihren Text auf die Vorstellungen der damals bekannten Welt zurückgegriffen. Aktualisiert dieses Weltwissen in Gen 1-2,4a und setzt euch damit auseinander, ob die Aktualisierungen auch die Rolle des Menschen im Text verändert.
    
Versetzt euch in die Autoren des 1. Schöpfungsmythos hinein. Wie würden diese reagieren, wenn man sie mit unserem heutigen Wissen über das Leben und den Kosmos konfrontiert? Würden Sie ihren Schöpfungsmythos umschreiben oder verwerfen? Stellt eure Überlegungen in Form eines Textes (kreatives Schreiben, Dialog...) oder eines szenischen Spiels um.

Plant in Auseinandersetzung mit dem Film einen eigenen Film. Konzeptioniert werden kann dieser als Fortsetzung (Kapitel 11 — Ethische Schlussfolgerungen) oder als Gegenentwurf, in welchem die Bedeutung des Menschen hervorgehoben werden kann.

Setzt euch mit den folgenden Bibeltexten auseinander: Gottes Antwort aus dem Wettersturm (Hiob 38ff), Hiobs Antwort (Hiob 42,1 – 6) und Ps 8. Wählt passende Verse aus, welche ihr als Kommentar zu einem Kapitel des Films bei einem erneuten Sehen einsprecht (technisch: Anhalten oder Stummschalten möglich). Begründet im Anschluss euer Konzept.

** Theologische Deutung und weitere Inhaltliche Verknüpfungen zum Weiterarbeiten
- Verhältnis von Glauben und Wissen, von Religion und Naturwissenschaft, Komplementäres Modell, Die sogenannten Kränkungen der Menschheit
- Theodizee und Naturwissenschaft als Reaktion auf Abhängigkeit von der Natur: theologische Deutung der SARS-CoV-2-Pandemie
- Menschenbild, Weltbild und ethische Begründungen: Umgang mit der Natur, mit den Mitgeschöpfen; Ego vs. Eco (siehe Medien)
- Sonderstellung des Menschen: Doku "Von Affen und Menschen" (siehe Medien) – Tierethik, Speziesismus, Utilitarismus von Singer und Singers Personbegriff, Great Ape Project

  

* Hefteintrag
