#+title:      A Klasse 2021-25
#+date:       [2022-12-28 Mi 20:51]
#+filetags:   :2a:Project:
#+identifier: 20221228T205119
#+CATEGORY: golling

[[file:~/NMS_Golling/Lehrplan_2023.pdf]]

* 2a 07:45-08:35
<%%(org-class 2022 9 12 2023 7 3 1 18)>

** Judentum
Film (USB Festplatte)

** Erste Lesung: Apg 6,1-7
Zur 1. Lesung: In der Gemeinde von Jerusalem gab es neben den „Hebräern“ (aramäischsprechenden Judenchristen) auch „Hellenisten“ (griechischsprechende Judenchristen). Unter diesen gab es eine Anzahl Witwen, die sich aus Frömmigkeit in Jerusalem niedergelassen hatten und teilweise in Armut lebten. Für sie wurden als Vertrauensmänner der Gemeinde die Diakone aufgestellt; sie hatten keine besondere liturgische Funktion wie später in der Kirche, ihre Aufgabe war es vielmehr für die Witwen und überhaupt die Armen zu sorgen.

** Psalm 33

** Zweite Lesung: 1. Petr 2,4-9
Zur 2. Lesung: Christus ist der lebendige Eckstein des neuen Tempels, der Kirche Gottes. Er wurde „weggeworfen“, getötet, aber er wurde auferweckt. Wer an ihn glaubt, wird wie er von Gott geehrt; er hat teil am Licht und Leben Gottes. Durch Christus sind wir Gott nahe und können ihm als eine heilige Priesterschaft das Opfer des Lobes und des Dankes darbringen.

Austausch über die Lesungen (im RU wieder vermehrt in der Bibel; abgewechselt mit Spielen)

** Evangelium vom So (5. Sonntag der Osterzeit): Joh 10,1-10
Zum Evangelium: Die Jünger haben Mühe, den Weggang Jesu zu begreifen. Jesus tröstet sie: Ich komme wieder, ich hole euch heim zu mir. Auch das ist schwer zu verstehen. Thomas fragt nach dem Weg; Philippus bittet: Zeig uns den Vater. Jesus selbst ist der Weg, der Zugang zu Gott („die Tür“: Joh 10, 9). Und er ist das Bild des Vaters; Gottes eigene Art, sein Wesen und seine Hinwendung zu den Menschen sind in Jesus sichtbar geworden.

* 2a 07:45-08:35
<%%(org-class 2022 9 14 2023 7 5 3)>

[[denote:20221226T111248][Apostel Paulus]] + [[denote:20230403T101428][Auferstehung]]

Reli-Buch
Kapitel 6 - Judentum

Film Judentum.

* Reflexionen


* 2A [KV Bernhard Moser]

#+Name: 2021-students
| First    | Last         | Name                | Note | Heft | Mitarbeit | LZK |
|----------+--------------+---------------------+------+------+-----------+-----|
| Marie    | Aigner       | [[MarieAigner][Marie Aigner]]        |      |      |           |     |
| Marko    | Bijelonjic   | [[MarkoBijelonjic][Marko Bijelonjic]]    |      |      |           |     |
| Sarah    | Brandstätter | [[SarahBrandstätter][Sarah Brandstätter]]  |      |      |           |     |
| Julia    | Bretschu     | [[JuliaBretschu][Julia Bretschu]]      |      |      |           |     |
| Matteo   | Eckhardt     | [[MatteoEckhardt][Matteo Eckhardt]]     |      |      |           |     |
| Diana    | Eibl         | [[DianaEibl][Diana Eibl]]          |      |      |           |     |
| Oliver   | Kurz         | [[OliverKurz][Oliver Kurz]]         |      |      |           |     |
| Elisa    | Mayr         | [[ElisaMayr][Elisa Mayr]]          |      |      |           |     |
| Alisa    | Meisl        | [[AlisaMeisl][Alisa Meisl]]         |      |      |           |     |
| Carolina | Schlager     | [[CarolinaSchlager][Carolina Schlager]]   |      |      |           |     |
| Marie    | Schmidt      | [[MarieSchmidt][Marie Schmidt]]       |      |      |           |     |
| Annika   | Schröcker    | [[AnnikaSchröcker][Annika Schröcker]]    |      |      |           |     |
| Lea      | Stoß         | [[LeaStoß][Lea Stoß]]            |      |      |           |     |
| Manuel   | Stoß         | [[ManuelStoß][Manuel Stoß]]         |      |      |           |     |
| Johanna  | Strubreiter  | [[JohannaStrubreiter][Johanna Strubreiter]] |      |      |           |     |
| Laurenz  | Walcher      | [[LaurenzWalcher][Laurenz Walcher]]     |      |      |           |     |
| Lorenz   | Wallinger    | [[LorenzWallinger][Lorenz Wallinger]]    |      |      |           |     |
| Jana     | Wenger       | [[JanaWenger][Jana Wenger]]         |      |      |           |     |
| Luca     | Zemmer       | [[LucaZemmer][Luca Zemmer]]         |      |      |           |     |
| Karlo    | Zivkovic     | [[KarloZivkovic][Karlo Zivkovic]]      |      |      |           |     |
| Robert   | Zivkovic     | [[RobertZivkovic][Robert Zivkovic]]     |      |      |           |     |
#+TBLFM: $4=vmean($5..$>)
#+TBLFM: $3='(concat "[[" $1 $2 "][" $1 " " $2 "]]")
#+TBLFM: $4='(identity remote(2021-22-Mitarbeit,@@#$2))

#+BEGIN_SRC python :var table=2021-students :results output raw
  print('* Mitarbeit')
  for student in table:
      first = student[0]
      last = student[1]
      email = first + '.' + last + '@golling.schule'
      print('** ' + first + last + '\n\n')
#+END_SRC

#+RESULTS:

* Mitarbeit
** MarieAigner


** MarkoBijelonjic


** SarahBrandstätter


** JuliaBretschu


** MatteoEckhardt


** DianaEibl


** OliverKurz


** ElisaMayr


** AlisaMeisl


** CarolinaSchlager


** MarieSchmidt


** AnnikaSchröcker


** LeaStoß


** ManuelStoß


** JohannaStrubreiter


** LaurenzWalcher


** LorenzWallinger


** JanaWenger


** LucaZemmer


** KarloZivkovic


** RobertZivkovic




* Reflexionen                                                   :Reflexionen:

** Wie gehe ich mit Unterrichtsstörungen um?

Wow, das wird immer schlimmer. Liegt es an mir? Liegt es (nur) an den Schülern? Auf jeden Fall werde ich von den Schülern (meist den Buben) häufig unterbrochen. Da dies in einigen Klassen vorkommt, stellt sich für mich doch die Frage, ob es irgendwie auch an mir hängt. Oder am Fach?

Bernhard (KV) hat mir gesagt, dass es ihm ähnlich ergeht: er bemerkt einen Unterschied zwischen Mathematik und Geografie. Also liegt es auch am Fach.

Heute habe ich die gesamte Klasse schreiben lassen; das werde ich nächste Stunde genauso machen.

Ich frage mich: "Woher kommt diese Unart, den Lehrer nicht mal ausreden zu lassen; nebenbei Privatgespräche abzuhalten; ...? Woher lernen die Kinder dieses Verhalten?" Meist schauen sich die Kinder dies von Erwachsenen oder Film, TV, etc ab.

** ein Eintrag


