#+title:      B Klasse 2022-26
#+date:       [2022-12-30 Fr 19:34]
#+filetags:   :1b:Project:
#+identifier: 20221230T193456
#+CATEGORY: golling
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib

* Jahresplanung
[[denote:20230621T073313][01 Golling]]


* 1b 10:40-11:30
<%%(org-class 2022 9 13 2023 7 4 2)>

Film über Burschen in Palästina / Meer ...


* 1b 11:35-12:25
<%%(org-class 2022 9 16 2023 7 7 5 23)>

Film über Jesus / Judentum / ...?


* Supplierstunde 1b BU (Hannes Lacher) 10:40-11:30
<%%(org-class 2023 3 8 2023 7 5 3 25)>
aktueller Stoff: Säugetiere / Fische.
Buch S. 104ff

Buch S. 106 / 107
Arbeitsheft S. 54

* Reflexionen

** [[denote:20221226T162523][Grundgebete]]
PERIOD: [2023-01-27 Fr 11:35]

Die Klasse hat sich bei mir für ihr recht schlimmes Verhalten entschuldigt, sie hat einen kleinen Brief geschrieben. Leider hat die versprochene Besserung nicht lange angehalten; aber das wird schon noch, davon bin ich überzeugt.

Thema heute: Vater unser.


* 1B [KV Martin Pock]

#+Name: 2021-students
| First     | Last       | Name               | Note | Heft | Mitarbeit | LZK | Stören |
|-----------+------------+--------------------+------+------+-----------+-----+--------|
| Lorenz    | Aschauer   | [[Lorenz Aschauer][Lorenz Aschauer]]    |    2 |      |           |     |        |
| Stefan    | Atanasov   | [[Stefan Atanasov][Stefan Atanasov]]    |    2 |      |           |     |        |
| Lela      | Dent       | [[Lela Dent][Lela Dent]]          |    1 |      |           |     |        |
| Emma      | Gonschorek | [[Emma Gonschorek][Emma Gonschorek]]    |    1 |      |           |     |        |
| Marie     | Hofer      | [[Marie Hofer][Marie Hofer]]        |    1 |      |           |     |        |
| Hubert    | Keinrad    | [[Hubert Keinrad][Hubert Keinrad]]     |    1 |      |           |     |        |
| Nena      | Langenfeld | [[Nena Langenfeld][Nena Langenfeld]]    |    1 |      |           |     |        |
| Bernhard  | Neureiter  | [[Bernhard Neureiter][Bernhard Neureiter]] |    2 |      |           |     |        |
| Lucian    | Rainer     | [[Lucian Rainer][Lucian Rainer]]      |      |      |           |     | xxx    |
| Manuel    | Reiter     | [[Manuel Reiter][Manuel Reiter]]      |    1 |      |           |     |        |
| Emma      | Riebler    | [[Emma Riebler][Emma Riebler]]       |    1 |      |           |     |        |
| Annika    | Seiwald    | [[Annika Seiwald][Annika Seiwald]]     |    1 |      |           |     |        |
| Valerian  | Seling     | [[Valerian Seling][Valerian Seling]]    |    2 |      |           |     |        |
| Theresa   | Steiner    | [[Theresa Steiner][Theresa Steiner]]    |    1 |      |           |     |        |
| Valentina | Struber    | [[Valentina Struber][Valentina Struber]]  |    1 |      |           |     |        |
| Felix     | Wenger     | [[Felix Wenger][Felix Wenger]]       |    1 |      |           |     |        |
| Leon      | Zemmer     | [[Leon Zemmer][Leon Zemmer]]        |    1 |      |           |     | xx     |
| Fabian    | Zorzi      | [[Fabian Zorzi][Fabian Zorzi]]       |    1 |      |           |     |        |
#+TBLFM: $4=vmean($5..$>)
#+TBLFM: $3='(concat "[[" $1 " " $2 "][" $1 " " $2 "]]")
#+TBLFM: 

#+BEGIN_SRC python :var table=2021-students :results output raw
print('* Mitarbeit')
for student in table:
    first = student[0]
    last = student[1]
    email = first + '.' + last + '@golling.schule'
    print('** ' + first + ' ' + last + '\n\n')  
#+END_SRC

#+RESULTS:
* Mitarbeit
** Lorenz Aschauer


** Stefan Atanasov


** Lela Dent


** Emma Gonschorek


** Marie Hofer


** Hubert Keinrad


** Nena Langenfeld


** Bernhard Neureiter


** Lucian Rainer


** Manuel Reiter


** Emma Riebler


** Annika Seiwald


** Valerian Seling


** Theresa Steiner


** Valentina Struber


** Felix Wenger


** Leon Zemmer


** Fabian Zorzi


* Jahresplanung

| Datum           | Stoff                                                     | Anmerkungen |
|-----------------+-----------------------------------------------------------+-------------|
| <2023-09-11 Mo> | [[denote:20230619T073700][[SW01] Jahresstoff / ich stehe in den Schuhen des Anderen]] | [[#A1_KB1]]     |
| <2023-09-18 Mo> | [[denote:20230619T074010][[SW02] Eine Gemeinschaft, die uns stärkt]]                  |             |


* Kompetenzbereiche und Kompetenzdimensionen

** Kompetenzmodell und -bereiche
Das Kompetenzmodell für den katholischen Religionsunterricht beinhaltet schulstufenübergreifend drei inhaltsbezogene Kompetenzbereiche und fünf handlungsorientierte Kompetenzdimensionen. Kompetenzbereiche sind inhaltlich geprägte nähere Umschreibungen von Sachgebieten, in denen religiöse  Kompetenzen erworben werden. Sie werden durch je zwei Leitkompetenzen konkretisiert:

**** A Menschen und ihre Lebensorientierungen
:PROPERTIES:
:CUSTOM_ID: A
:ID:       6b68956f-aff0-48b7-8b7a-8352ffd83ea6
:END:
***** A1 Beziehung verantwortungsvoll gestalten können – zu sich selbst, zu anderen, zur Schöpfung
:PROPERTIES:
:CUSTOM_ID: A1
:ID:       78dc1f2b-f2f0-4b14-9b57-2db17bc10edc
:END:
****** Kompetenzbeschreibung:
:PROPERTIES:
:CUSTOM_ID: A1_KB1
:ID:       633ff781-4a7b-41d9-a50c-1d470d29dcf9
:END:
Die Schülerinnen und Schüler können sich in ihrer gottgeschenkten Einzigartigkeit wahrnehmen und wissen um die Bedeutung von (Selbst-) Vertrauen für ein gelingendes (Zusammen-)Leben.

****** Anwendungsbereiche
:PROPERTIES:
:CUSTOM_ID: A1_AB1
:ID:       c470b3f6-0462-4ca9-93ee-bb308dc3de3a
:END:

****** Unterrichtshinweise
:PROPERTIES:
:CUSTOM_ID: A1_UH1
:ID:       22cd8479-45a9-4274-9d57-f2143f13feda
:END:
Ich und die anderen:
 - Selbstvertrauen, [[#Die Welt der Gefühle]] [[#Vertrauen]]
 - Freundschaft, [[#Freundschaft]] [[#treuer Freund]]
 - Empathie und Perspektivenwechsel, [[#Schuhe des Anderen]] 
 - Teamfähigkeit, [[#Gemeinschaft]] [[#eine gute Gemeinschaft]]
 - Nähe und Distanz,
 - Zärtlichkeit und Sexualität

****** Kompetenzbeschreibungen
:PROPERTIES:
:ID:       b708f918-fcec-4f12-8a1f-1477eee3b382
:END:
****** Anwendungsbereiche
:PROPERTIES:
:ID:       3e9b622d-27c5-41ca-a2ac-396c15ca3e8e
:END:
****** Unterrichtshinweise
:PROPERTIES:
:ID:       dc3759a8-aa6f-449a-a598-3b36f7dd20d8
:END:

***** A2 Sich mit den großen Fragen der Menschen auseinandersetzen können
:PROPERTIES:
:CUSTOM_ID: A2
:ID:       1b855fa1-537a-4d14-af4e-4db124066a28
:END:
****** Kompetenzbeschreibungen
:PROPERTIES:
:CUSTOM_ID: A2_KB1
:ID:       e43fcd56-1bbc-4d49-8177-29bbca2204b5
:END:
Die Schülerinnen und Schüler können für sie bedeutsame Fragen diskutieren und über existentielle Lebensfragen philosophieren und theologisieren.  

****** Anwendungsbereiche
:PROPERTIES:
:CUSTOM_ID: A2_AB1
:ID:       f63585d7-167b-41e0-b890-4a64789a47bb
:END:

****** Unterrichtshinweise
:PROPERTIES:
:CUSTOM_ID: A2_UH1
:ID:       abce94a7-090d-40a6-87f7-7d1f2c2f1712
:END:
Beantwortbare und letztlich unbeantwortbare Fragen: [[#Fragen unseres Lebens]]
- Wer ist Gott? Existiert Gott? [[#Große Fragen große Antworten]]
- Existiert überhaupt etwas? [[#Harte Fakten gute Gedanken]]
- Wer ist der Mensch?
- Gott ist gut, warum gibt es das Böse?
- Der Sinn des Lebens?
- ...


****** Kompetenzbeschreibungen
:PROPERTIES:
:ID:       9a88f216-edc2-4d93-83b8-ade69ab32f9b
:END:
****** Anwendungsbereiche
:PROPERTIES:
:ID:       1212b27e-4e79-4aae-ae4a-dec9dc19cff5
:END:
****** Unterrichtshinweise
:PROPERTIES:
:ID:       4df40b65-bb7c-4edc-8765-e9f2ca13f0ec
:END:

**** B Gelehrte und gelebte Bezugsreligion
:PROPERTIES:
:CUSTOM_ID: A1_AB1
:ID:       d3e26f28-04ab-4caf-929b-30f8104a6f94
:END:
***** B3 Grundlagen und Leitmotive des christlichen Glaubens kennen und für das eigene Leben deuten können
:PROPERTIES:
:CUSTOM_ID: B3
:ID:       5a06e31e-7c5f-40e6-8f40-1c52abe8ac85
:END:
****** Kompetenzbeschreibungen
:PROPERTIES:
:CUSTOM_ID: B3_KB1
:ID:       ab8712e8-e47c-4041-b35f-f2bfce72d9c5
:END:
Die Schülerinnen und Schüler verfügen über erweiterte Grundkenntnisse zur Bibel und können sie als inspiriertes Zeugnis des Dialogs Gottes mit den Menschen deuten. 

****** Anwendungsbereiche
:PROPERTIES:
:CUSTOM_ID: B3_AB1
:ID:       83b05343-cbd8-424a-b9ce-a9bd614834b5
:END:
Biblisch-hermeneutische Kompetenz: die biblischen Schriften und ihre Entstehung, Zeugnisse der Lebensrelevanz der Bibel [[#Bibel_NT]]

****** Unterrichtshinweise
:PROPERTIES:
:CUSTOM_ID: B3_UH1
:ID:       efc71c11-8d7b-409e-826f-3b3fa266987e
:END:
 - Altes Testament
 - Neues Testament, [[#Bibelarbeit]] [[#Jesus Mensch und Gott]]
 - historisch-geografisches Umfeld;
 - biblische Motive im Alltag: eigene Erfahrungen und Populärkultur [[#David Jonathan]]


****** Kompetenzbeschreibungen
:PROPERTIES:
:CUSTOM_ID: B3_KB2
:ID:       95fc3b05-097d-4eab-835b-58f0f33a744b
:END:
Die Schülerinnen und Schüler können Leben und Handeln Jesu in Grundlinien beschreiben und als Basis christlichen Glaubens kommunizieren.

****** Anwendungsbereiche
:PROPERTIES:
:CUSTOM_ID: B3_AB2
:ID:       9d409c4f-9998-447a-84f7-2200b98cfeab
:END:
Historischer Jesus – Christus des Glaubens 

****** Unterrichtshinweise
:PROPERTIES:
:CUSTOM_ID: B3_UH2
:ID:       3f1238e5-4484-4cfd-a3f9-6f92fe3feebf
:END:
Lukasevangelium in Auswahl 

***** B4 Kirchliche Grundvollzüge kennen und religiös-spirituelle Ausdrucksformen gestalten können
:PROPERTIES:
:CUSTOM_ID: B4
:ID:       c95753a7-df03-42fa-bad6-379d4fa492b3
:END:
****** Kompetenzbeschreibungen
:PROPERTIES:
:CUSTOM_ID: B4_KB1
:ID:       43fa526e-1311-4f84-82e2-8e060b51cfec
:END:
Die Schülerinnen und Schüler kennen Reichtum und Vielfalt spiritueller und liturgischer Ausdrucksformen und können sie in ihrer Bedeutung nachvollziehen und gestalten. 

****** Anwendungsbereiche
:PROPERTIES:
:CUSTOM_ID: B4_AB1
:ID:       2584b2ea-3528-4b91-9ee2-17fb3522ad6b
:END:

****** Unterrichtshinweise
:PROPERTIES:
:CUSTOM_ID: B4_UH1
:ID:       889a212d-c6d9-49a6-9676-fab4daf9bcd8
:END:
 - Kurzformeln des Glaubens [[#Kirche_Gebet]]
 - Grundgebete: [[#Ave Maria]] [[#Vaterunser]]
 - Stille, Meditation, [[#Vielfalt Gebet]]
 - Psalmen, Lieder,
 - körperliche Ausdrucksformen des Gebets [[#Menschen beten]] [[#Dankbarkeit]]
 - Arten / Formen des Gebets:[[#Menschen beten]] [[#Gebetsformen]]

   
****** Kompetenzbeschreibungen
:PROPERTIES:
:CUSTOM_ID: B4_KB2
:ID:       e5bae3b3-693a-4ff9-a5bb-f67b93286435
:END:
Die Schülerinnen und Schüler können Taufe und Eucharistie als Ausdruck der Zugehörigkeit zur kirchlichen Gemeinschaft verstehen. 

****** Anwendungsbereiche
:PROPERTIES:
:CUSTOM_ID: B4_AB2
:ID:       bdd62bea-22b6-4a9f-a6a5-ab46e9102a9a
:END:
Das Glaubensbekenntnis [[#Credo]]

****** Unterrichtshinweise
:PROPERTIES:
:CUSTOM_ID: B4_UH2
:ID:       b533284a-4f28-4966-94e8-2029045b2495
:END:
 - Zeichen und Formen von Zugehörigkeit, [[#Gemeinsam Kirche]]
 - Jesu Mahlgemeinschaften und die Feier der Eucharistie [[#Eucharistie]]


**** C Religiöse und weltanschauliche Vielfalt in Gesellschaft und Kultur 
:PROPERTIES:
:CUSTOM_ID: C
:ID:       3a74a64c-c5f4-422b-a41c-21d29c51a389
:END:
***** C5 Medien, Kunst und Kultur im Kontext religiöser Weltwahrnehmung interpretieren, beurteilen und gestalten können
:PROPERTIES:
:CUSTOM_ID: C5
:ID:       ef1da82c-65f3-41bf-b3da-0a42b8bca3dd
:END:
****** Kompetenzbeschreibungen
:PROPERTIES:
:CUSTOM_ID: C5_KB1
:ID:       77e07b32-82b3-4c7a-bdf4-87b0b3477d60
:END:
Die Schülerinnen und Schüler können das Kirchenjahr mit seinen Festen als Rhythmus des Lebens verstehen und mitgestalten.  

****** Anwendungsbereiche
:PROPERTIES:
:CUSTOM_ID: C5_AB1
:ID:       4413ef13-dd55-4af2-bbf9-526c226e63e5
:END:

****** Unterrichtshinweise
:PROPERTIES:
:CUSTOM_ID: C5_UH1
:ID:       19dcea2d-e073-47d7-8b94-a93354aa3010
:END:
 - Fest- und Feierkultur in Familie, Gemeinschaft und Gesellschaft [[#Feierkultur]]
 - Strukturierung und Prägung der Zeit durch säkulare und religiöse Feste (Kalender), [[#Kirchenjahr]] [[#Feste Kirchenjahr]]
 - Marienfeste, [[#Advent_Maria]]
 - vielfältige Zugänge zum Feiern von Weihnachten [[#Advent]] [[#Weihnachten]] [[#Sterndeuter]]
 - Ostern [[#Ostern]]


****** Kompetenzbeschreibungen
:PROPERTIES:
:CUSTOM_ID: C5_KB2
:ID:       34334035-529e-4423-a3c3-195fe66ffdb0
:END:

****** Anwendungsbereiche
:PROPERTIES:
:CUSTOM_ID: C5_AB2
:ID:       84fe8b02-8d36-471f-ac39-718fec481ce8
:END:

****** Unterrichtshinweise
:PROPERTIES:
:CUSTOM_ID: C5_UH2
:ID:       0d64d603-6d96-4f40-8a05-efc9dd82d71f
:END:


***** C6 Unterschiedlichen Lebensweisen und Glaubensformen reflexiv begegnen können
:PROPERTIES:
:CUSTOM_ID: C6
:ID:       a208bd4f-fc32-44e4-83cf-f0b0576b30d0
:END:
****** Kompetenzbeschreibungen
:PROPERTIES:
:CUSTOM_ID: C6_KB1
:ID:       1576269f-8eec-4642-a767-2f60b7379865
:END:
Die Schülerinnen und Schüler können Gemeinsames und Unterscheidendes, Verbindendes und Trennendes von Konfessionen und Religionen benennen und sich damit respektvoll auseinandersetzen. 

****** Anwendungsbereiche
:PROPERTIES:
:CUSTOM_ID: C6_AB1
:ID:       9e459664-5a74-48f2-8b9b-7dd1918fad0b
:END:


****** Unterrichtshinweise
:PROPERTIES:
:CUSTOM_ID: C6_UH1
:ID:       9b1194dc-9111-44d2-ac51-9f320bf6c7d1
:END:
 - Einheit in Vielfalt, [[#Einigkeit Vielfalt]] [[#Vielfalt]]
 - Respekt, Toleranz, [[#Vielfalt Religionen]]
 - Umgang mit Intoleranz und Vorurteilen [[#Übungsteil Vielfalt]]
 - Religionen stellen sich vor [[#Judentum Isalm Christentum]]

****** Kompetenzbeschreibungen
:PROPERTIES:
:CUSTOM_ID: C6_KB2
:ID:       7a4ab7f6-5d04-4a52-89d6-a3766987a5e8
:END:

****** Anwendungsbereiche
:PROPERTIES:
:CUSTOM_ID: C6_AB2
:ID:       3c261ba5-3587-4c8a-8354-29cd34360224
:END:

****** Unterrichtshinweise
:PROPERTIES:
:CUSTOM_ID: C6_UH2
:ID:       c8d1a73d-cbd9-4705-b75f-5e9b12da732b
:END:



**** Kompetenzdimensionen 
beschreiben die Handlungsmodi der Aneignung der Kompetenzen und finden sich in den Kompetenzbeschreibungen wieder:
 - Wahrnehmen und beschreiben religiös bedeutsamer Phänomene (Perzeption)
 - Verstehen und deuten religiös bedeutsamer Sprache und Glaubenszeugnisse (Kognition)
 - Gestalten und handeln in religiösen und ethischen Fragen (Performanz)
 - Kommunizieren und (be)urteilen von Überzeugungen mit religiösen Argumenten und im Dialog (Interaktion)
 - Teilhaben und entscheiden – begründete (Nicht-)Teilhabe an religiöser und gesellschaftlicher Praxis (Partizipation)

*** Zentrale fachliche Konzepte
Folgende Leitideen, strukturiert in Begriffspaaren, kennzeichnen die zentralen fachlichen Konzepte des katholischen Religionsunterrichts. 

**** Lebensrealitäten und Transzendenz
Christlicher Glaube versteht den Menschen in seiner Bio-grafie  und  in  seinen  Lebensbezügen  als  transzendentes  Wesen und erschließt Wege der Sinnfindung durch Trans-zendenzbezug.

**** Gottesliebe und Menschenliebe
Das  jüdisch-christliche  Gottes- und Menschenbild steht für eine lebensbejahende Grundhaltung zu sich selbst, den Mitmenschen und der Welt. Das  Beziehungsgeschehen zwischen Gott und Mensch und der Menschen untereinander ist getragen von der bedingungslosen Liebe Gottes. Unabhängig von Fähigkeiten und erbrachten Leistungen ist der Mensch in seiner Würde unantastbar.

**** Jesus der Christus
Das  Christentum orientiert sich am Reden und Handeln Jesu, das die vergebende und heilende Zuwendung Gottes zu den Menschen zeigt. In seiner den Tod überwindenden Auferstehung kann in der Brüchigkeit des Lebens Versöhnung und Erlösung erfahrbar werden. 

**** Freiheit und Offenbarung
Quellen der Offenbarung sind die Bibel und die kirchliche Tradition in ihrer Vielfalt. Auf der darin grundgelegten Freiheit des Menschen basiert die Achtung der Religionsfreiheit jeder Schülerin und jedes Schülers.

**** Zusage und Verantwortung
Ausgehend vom Verdankt-Sein allen Lebens wissen sich Christinnen und Christen beauftragt und befähigt Verantwortung in der Welt zu übernehmen. Dabei leiten sie Hoffnungsperspektiven, die auf biblischen Zusagen aufbauen.

*** Didaktische Grundsätze
In der Mitte des Religionsunterrichts stehen die Schülerin-nen und Schüler, ihr Leben, ihr Glaube.

Für den katholischen Religionsunterricht sind das Prinzip der Korrelation, das die wechselseitige Erschließung von Glauben und Leben meint, und das Prinzip des „Ganzen im Fragment“, das sich der Elementarisierung und dem exemplarischen Lernen verpflichtet weiß, zentral. 

Die didaktisch reflektierte Setzung von Schwerpunkten ist besonders bei einstündig geführten Klassen und im schul-stufenübergreifenden Unterricht notwendig.

Bezugnehmend auf das Kompetenzmodell sind folgende religionsdidaktische Grundsätze hervorzuheben:

*Fokus: Religiöse Sprache und Symbole*
Die Alphabetisierung in religiöser Sprache umfasst das Erkennen und Verstehen religiöser Sprachformen und das Erschließen vielfältiger Symbole in ihrer Mehrdimensionalität. Eine individuelle und kreative Ausdrucksfähigkeit wird gefördert.

*Fokus: Philosophieren und Theologisieren*
Der Religionsunterricht fördert die Fragekompetenz, initiiert Suchbewegungen im religiös-existenziellen Kontext und schult die Argumentationsfähigkeit. Er verpflichtet nicht auf einen Glauben, vielmehr fördert er die Entscheidungsfähigkeit der Schülerinnen und Schüler in religiösen und ethischen Belangen.

*Fokus: Actio und Contemplatio*
Performatives Lernen zielt ab auf das reflektierende Erleben religiöser Vollzüge und ethischen Handelns. Die Erfahrungsbezogenheit des Religionsunterrichts wird in Gebet, Stille und Meditation sowie in gemeinsamen Feiern, Aktionen und Projekten erlebbar.

*Fokus: Beziehung und Resonanz*
Im Beziehungsgeschehen zwischen Gott, Mensch und Welt angelegt, umfasst schulische religiöse Bildung eine biografische und narrative Komponente und vollzieht sich besonders im Lernen voneinander, miteinander und über-einander. 

*** Hinweise zum Lehrplan
Der Lehrplan für katholische Religion umfasst drei Kompetenzbereiche (A, B und C). Jeder dieser Bereiche wird jahrgangsübergreifend durch je zwei Leitkompetenzen (1-6) konkretisiert. 

**** KB – Kompetenzbeschreibungen
Den Leitkompetenzen sind schulstufenspezifische Kompetenzbeschreibungen (KB) zugeordnet, die angeben, welche Kompetenzen von allen Schülerinnen und Schülern erworben werden sollen. In jedem Schuljahr sind alle im Kompetenzmodell genannten Kompetenzdimensionen (Perzeption, Kognition, Performanz, Interaktion, Partizipation) zu berücksichtigen.Der Lehrplan für katholische Religion umfasst drei Kompetenzbereiche (A, B und C).Jeder dieser Bereiche wird jahrgangsübergreifend durch je zwei Leitkompetenzen (1-6) konkretisiert. 

**** AB – Anwendungsbereiche
Inhaltlich konkretisiert werden die Kompetenzbeschreibungen durch Anwendungsbereiche (AB). Diese benennen repräsentative Beispiele für Themenfelder, anhand derer Kompetenzen erworben werden. Wo solche benannt sind, sind sie verbindlich zu behandeln. Weitere Anwendungsbereiche können frei gewählt werden.Wo keine Anwendungsbereiche benannt sind, ist es Aufgabe der Lehrerinnen und Lehrer Anwendungsbereiche zu definieren.

**** UH – Unterrichtshinweise
Unterrichtshinweise (UH) sind als Ergänzungen zu den Fachlehrplänen gedacht. Sie geben Empfehlungen für die Umsetzung des kompetenzorientierten Lehrplans und unterstützen bei der Unterrichtsplanung.






