#+title:      Ausbildung Philosophie
#+date:       [2022-12-17 Sa 22:10]
#+filetags:   :philosophy:
#+identifier: 20221217T221005

* Philosophie im Kloster
Von Jänner 1998 bis Ausgust 2011 lebte ich als Mönch in einer römisch-katholischen Klostergemeinschaft. Ihr Name ist "Communauté Saint Jean", benannt nach dem Apostel Johannes, der nach der Tradition auf der Insel Patmos das Buch der Offenbarung schrieb und der Autor des vierten Evangeliums nach Johannes ist.

In den ersten Jahren im Kloster lebte ich in dem Noviziat in Saint-Jodard, einem kleinen Dorf in Frankreich in der Nähe der Stadt Roanne. Dort drfte ich das Klosterleben intensiv kennenlernen und studierte vor allem Philosophie. Die Vorlesungen trugen Namen wie "Philosophie der Kunst und Arbeit", "Ethik", "Philosophie des Menschen als Lebenwesen" oder "Metaphysik".

Diese Ausbildung orientierte sich sehr stark an der Lehre des Aristoteles. Deshalb wurden auch seine Hauptwerke studiert: "Nikomachische Ethik", "Über die Seele" oder "Metaphysik". Aber auch die Vorsokratiker, Sokrates oder Platon wurden gelesen.

Der Gründer dieser Gemeinschaft, P. Marie-Dominique Philippe o.p., entwickelte ausgehend von Aristoteles seine eigene Philosophie. Diese beruht auf den großen Erfahrungen des Menschen: wie zum Beispiel die Erfahrung der Arbeit und der Kunst, oder die Erfahrung der Liebe in der Freundschaft. Durch die Sinne wie das Sehen oder Hören stellt sich der Mensch Fragen wie "Was ist das?", "Woher kommt das? Was ist sein Ursprung?", ... Ein wichtiger Bestandteil dieser Philosophie ist das sogenannte Existenzurteil (französisch: jugement d'existence "ceci est"): "Dies ist, es existiert."

Ziel und Aufgabe dieser Philosophie ist es, in den einzelnen Bereichen wie der Arbeit und Kunst, oder der Ethik, nach den Prinzipien zu suchen: z.B. was ist das Prinzip in der Kunst? Was treibt den Künstler an, dieses Kunstwerk zu realisieren? In der Kunst wäre das die Idee. Sie steuert den ganzen Prozess der Arbeit des Künstlers: die Wahl des Rohmaterials (Stein oder Holz), die Auswahl der Werkzeuge, etc.

P. Marie-Dominique Philippe hat in seinem Buch "Lettre à un ami" seine Lehre dargelegt. Da diese Ausbildung schon sehr lange zurückliegt, fällt es mir schwer, sie gut zu erklären. Ich habe persönlich sehr viel davon profitiert. Allerdings erlebte ich auch an einigen Mitbrüdern, wie diese Lehre, wenn sie falsch verstanden wird, zu einer großen Verengung des Denkens führen kann. Mitbrüder kamen in ihrer Suche nach der Wahrheit zu der falschen Überzeugung, dass nur sie alleine im Besitz der Wahrheit seien. Alle anderen Philosophen, selbst Sokrates und Platon, hätten sich geirrt. Nur die Lehre des P. Marie-Dominique Philippe sei die wahre und einzige Philosophie. 

Wir können die Wahrheit jedoch niemals besitzen, sondern sie nur suchen - oder uns von ihr finden lassen.

Ich kehrte für 8 Jahre nach Österreich zurück und lebte in einem kleinen Kloster östlich von Wien. Dort kümmerte ich mich um die Jugendlichen und durfte mit meinen Talenten (Singen und Gitarre spielen) die Gottesdienste gestalten.

2009 verließ ich aufs Neue meine Heimat Österreich und kehrte nach Frankreich zurück. Diesmal lebte ich im Mutterhaus der Gemeinschaft in Rimont, einem sehr kleinen Dorf in der Burgund, in dwr Nähe von Chalon-sur-Saône. Hier studierte ich für zwei Jahre Theologie.

Gegen Ende der zwei Jahre lernte ich Isabelle, meine jetzige Ehefrau kennen. Ich stand vor der Entscheidung, entweder im Kloster zu bleiben oder mit dieser wunderbaren Frau ein gemeinsames Leben zu beginnen.

Diese Entscheidung fiel mir nicht leicht. Da ich mir aber bereits seit cirka drei Jahren ähnliche Fragen gestellt hatte, konnte ich nun meine Entscheidung treffen. Ich sprach darüber mit dem Generalprior der Gemeinschaft und verließ das Klosterleben, reiste nach Österreich und bereitete das gemütliche Nest für unsere gemeinsame Zukunft in Österreich vor. Kurze Zeit später folget mir Isabelle nach Österreich und wir heirateten am 30.6.2012.

Seither leben wir im Süden der Stadt Salzburg (meiner ursprünglichen Heimat) in Grödig, einem großen Dorf. Uns wurden zwei wunderbare Kinder geschenkt: Gabriel (10 Jahre) und Leopold (5 Jahre).



* Übersetzung:
From January 1998 to August 2011 I lived as a monk in a Roman Catholic monastic community. Its name is "Communauté Saint Jean", named after the Apostle John who, according to tradition, wrote the Book of Revelation on the island of Patmos and is the author of the fourth Gospel according to John.

During my first years in the monastery, I lived in the novitiate in Saint-Jodard, a small village in France near the city of Roanne. There I was allowed to get to know monastic life intensively and studied philosophy above all. The lectures had names like "Philosophy of Art and Work", "Ethics", "Philosophy of Man as a Living Being" or "Metaphysics".

This education was very much oriented towards the teachings of Aristotle. That is why his main works were studied: "Nicomachean Ethics", "On the Soul" or "Metaphysics". But the Pre-Socratics, Socrates or Plato were also read.

The founder of this community, Fr. Marie-Dominique Philippe o.p., developed his own philosophy based on Aristotle. This is based on the great experiences of man: such as the experience of work and art, or the experience of love in friendship. Through the senses, such as seeing or hearing, man asks himself questions such as "What is this?", "Where does this come from? What is its origin?", ... An important component of this philosophy is the so-called existential judgement (French: jugement d'existence "ceci est"): "This is, it exists".

The aim and task of this philosophy is to search for the principles in the individual fields such as work and art, or ethics: e.g. what is the principle in art? What drives the artist to realise this work of art? In art, that would be the idea. It drives the whole process of the artist's work: the choice of raw material (stone or wood), the choice of tools, etc.

P. Marie-Dominique Philippe has explained his teaching in his book "Lettre à un ami". As this teaching dates back a long time, it is difficult for me to explain it well. I have personally benefited a lot from it. However, I also experienced in some confreres how this teaching, if misunderstood, can lead to a great narrowing of thinking. In their search for truth, confreres came to the false conviction that they alone were in possession of the truth. All other philosophers, even Socrates and Plato, would have been wrong. Only the teaching of Father Marie-Dominique Philippe was the true and only philosophy. 

However, we can never possess the truth, but only seek it - or let ourselves be found by it.

I returned to Austria for 8 years and lived in a small monastery east of Vienna. There I took care of the young people and was allowed to organise the church services with my talents (singing and playing the guitar).

In 2009 I left my home country Austria again and returned to France. This time I lived in the Motherhouse of the Community in Rimont, a very small village in Burgundy, near Chalon-sur-Saône. Here I studied theology for two years.

Towards the end of the two years I met Isabelle, my present wife. I was faced with the decision of either staying in the monastery or starting a life together with this wonderful woman.

This decision was not easy for me. But since I had been asking myself similar questions for about three years, I could now make my decision. I talked about it with the Prior General of the community and left the monastic life, travelled to Austria and prepared the cosy nest for our future together in Austria. A short time later Isabelle followed me to Austria and we got married on 30.6.2012.

Since then we have been living in the south of the city of Salzburg (my original home) in Grödig, a large village. We were given two wonderful children: Gabriel (10 years) and Leopold (5 years).


