#+title:      B Klasse 2021-25
#+date:       [2022-12-30 Fr 19:36]
#+filetags:   :2b:Project:
#+identifier: 20221230T193609
#+CATEGORY: golling

* 2b 10:40-11:30
<%%(org-class 2022 9 12 2023 7 3 1 18)>

** Evangelium vom So (4. Sonntag der Osterzeit): Joh 10,1-10
Zum Evangelium: Hirt und Herde sind bei einem Hirtenvolk selbstverständliche Bezeichnungen für Herrscher und Volk, auch für Lehrer und Gemeinde. Im Alten Testament wird Gott der Hirt seines Volkes genannt (Ps 23; Ps 95, 7; Ez 34). Wenn Jesus nun sich als den guten Hirten bezeichnet und als die Tür zum Leben, so liegt darin ein ungeheurer Anspruch: Er selbst ist für die Menschen die Offenbarung Gottes; es gibt keine rettende Wahrheit und keinen Weg zum Leben außer ihm. Wer in der Gemeinde als Hirt und Lehrer aufgestellt ist, steht im Dienst und unter dem Gericht dieses "guten Hirten".

** Erste Lesung: Apg 2,14a.16-31
Zur 1. Lesung: Die Pfingstrede des Petrus ist eine Missions- und Bekehrungspredigt, die erste, die uns im Neuen Testament überliefert wird. Die entscheidende Aussage ist: Jesus lebt; ihr habt ihn gekreuzigt, aber Gott hat ihn zum Herrn und Christus gemacht. Das ist die Nachricht, zu der jeder, der sie hört, Stellung nehmen muss. Allen wird das Heil angeboten, Israel zuerst, aber auch "denen in der Ferne", das heißt allen Völkern der Erde.

** Psalm 23

** Zweite Lesung: 1. Petr 2,20b-25
Zur 2. Lesung: Was der erste Petrusbrief den Christen sagt, die als Sklaven leben müssen, ist alles andere als eine "Sklavenmoral". Wer in einer heidnischen Welt als Christ lebt, wird Schläge bekommen, auch wenn er kein Sklave ist. Aber das erniedrigt nicht ihn. Er kann auf Christus schauen: auf den, der unsere Not gelitten und unsere Sünden getragen hat; er heilt unsere Wunden, er ist der gute Hirt.

Austausch über die Lesungen (im RU wieder vermehrt in der Bibel; abgewechselt mit Spielen)

* 2b 07:45-08:35
<%%(org-class 2022 9 15 2023 7 6 4)>

Neues Kapitel im Buch: Kap. 6 - Vielfalt, die uns eint; Judentum, als Volk erwählt
Stammbaum meiner Familie, mein Lebensbaum

* Supplierstunde 2b PH 11:35-12:25
<%%(org-class 2023 1 25 2023 7 5 3 12)>

nächste Stunde (nach Ostern): *LZK* - gestern <2023-03-29 Mi 11:35-12:25> waren einige Schüler der Klasse ziemlich frech (Andreas + Augustin).

Buch S. 28: Arbeit in der Physik
- Arbeit: Kraft wirkt auf einen Körper, dieser verändert seine Lage, seinen Ort, oder seine Form.

- Hubarbeit, Reibungsarbeit, Verformungsarbeit, Beschleunigungsarbeit.

- Formel: W = F * s [Einheit: 1 Joule (Newtonmeter) = 1 Newton * 1 m(eter)]

- Leistung:
  wie viel Arbeit pro Zeit

  P = W / t [Einheit: 1 Watt = 1J pro Sekunde]

  Z.B. Leistungsangaben bei Elektrogeräten, Autos, etc ...

Video Harald Lesch über Energie
Energieformen
Rechenbeispiele


* Reflexionen                                                   :Reflexionen:

** [[id:02_SW01][[SW01] Mit jedem redest du anders / Das war ein Missverständnis!]]
Datum: <2022-09-15 Do 07:45>

Diese Stunde ist entfallen - Klasse 2b ist auf zweitägigem Ausflug.


* 2B [KV Wolfgang Bachmayer]


#+Name: 2021-students
| First    | Last               | Name                     | Note | Mitarbeit | Heft | LZK |
|----------+--------------------+--------------------------+------+-----------+------+-----|
| Anja     | Breinlinger        | [[AnjaBreinlinger][Anja Breinlinger]]         |      |           |      |     |
| Dalya    | Durukan            | [[DalyaDurukan][Dalya Durukan]]            |      |           |      |     |
| Azra     | Hant               | [[AzraHant][Azra Hant]]                |      |           |      |     |
| Hannah   | Hauser             | [[HannahHauser][Hannah Hauser]]            |      |           |      |     |
| Matthias | Holler             | [[MatthiasHoller][Matthias Holler]]          |      |           |      |     |
| Andreas  | Hollweger          | [[AndreasHollweger][Andreas Hollweger]]        |      |           | V    |     |
| Jonas    | Jarnig             | [[JonasJarnig][Jonas Jarnig]]             |      |           |      |     |
| Fabian   | Klöß               | [[FabianKlöß][Fabian Klöß]]              |      |           |      |     |
| Evelyn   | Nestler            | [[EvelynNestler][Evelyn Nestler]]           |      |           |      |     |
| Julia    | Schlager-Weidinger | [[JuliaSchlager-Weidinger][Julia Schlager-Weidinger]] |      |           |      |     |
| Felix    | Schmegner          | [[FelixSchmegner][Felix Schmegner]]          |      |           |      |     |
| Annika   | Schmitzberger      | [[AnnikaSchmitzberger][Annika Schmitzberger]]     |      |           |      |     |
| Kristina | Sokic              | [[KristinaSokic][Kristina Sokic]]           |      |           |      |     |
| Augustin | Sommer             | [[AugustinSommer][Augustin Sommer]]          |      |           |      |     |
| Phillipp | Spagolla           | [[PhillippSpagolla][Phillipp Spagolla]]        |      |           |      |     |
| Emma     | Tikvic             | [[EmmaTikvic][Emma Tikvic]]              |      |           |      |     |
| Selina   | Weiss              | [[SelinaWeiss][Selina Weiss]]             |      |           |      |     |
| Samuel   | Wittner            | [[SamuelWittner][Samuel Wittner]]           |      |           | V    |     |
#+TBLFM: $4=vmean($5..$>)
#+TBLFM: $3='(concat "[[" $1 $2 "][" $1 " " $2 "]]")
#+TBLFM: $4='(identity remote(2021-22-Mitarbeit,@@#$4))

#+BEGIN_SRC python :var table=2021-students :results output raw
print('* Mitarbeit')
for student in table:
    first = student[0]
    last = student[1]
    email = first + '.' + last + '@golling.schule'
    print('** ' + first + last + '\n\n')
#+END_SRC

#+RESULTS:
* Mitarbeit
** AnjaBreinlinger


** DalyaDurukan
PH 1 

** AzraHant
PH 1 

** HannahHauser
PH 1 


** MatthiasHoller
PH 1 

** AndreasHollweger
PH 1 

** JonasJarnig
PH (morgen)

** FabianKlöß
PH 1 

** EvelynNestler
PH 1 

** JuliaSchlager-Weidinger
PH 1 

** FelixSchmegner
PH 1 

** AnnikaSchmitzberger
PH 1 

** KristinaSokic
PH 1 

** AugustinSommer
PH (krank)

** PhillippSpagolla
PH 1 

** EmmaTikvic
PH 1 

** SelinaWeiss
PH (krank)

** SamuelWittner
PH 1 

** Vivienne
PH 1 
