#+title:      Zärtlichkeit Sexualität
#+date:       [2022-12-26 Mo 15:50]
#+filetags:   :mensch:
#+identifier: 20221226T155054

* Weblinks
[[https://www.youcat.org/de/credopedia/vorehelicher-sex/]]

[[https://www.youcat.org/de/credopedia/begierde-gier/]]

[[https://www.youcat.org/de/credopedia/ehebruch/]]


* Schizophrenie unserer Zeit
Auf der einen Seite wollen wir sexuelle Freizügigkeit, viele Teenager - oder schon ab 10, 11, 12 Jahren - haben bereits sexuelle Erfahrungen gesammelt. Wir wollen, dass Priester heiraten dürfen.

Auf der anderen Seite liegt die Scheidunsgrate bei 35.76 % in ganz Österreich. Wir unterstützen die Grünen und denken oft "links", die allerdings Frühsexualisierung der Kinder vorantreiben. Ein Teichmeister kann sich durch Krankheit vom Gerichtsprozess davondrücken, jetzt wird nimmer darüber berichtet. (Wie viele Grünen waren in pädophilen Kreisen zuhause?)

Ich denke an die sog. Rhetorikseminare der AKS in Salzburg - alles ein Vorwand für ersten Drogenkonsum und erste sexuelle Kontakte.

Warum setzen die Linken auf Sexualität? Wer früh sexualisiert wird, verliert schnell jeden Respekt vor Autorität; und dann geht's sehr oft um Pädophilie...


