#+title:      Sakramente
#+date:       [2022-12-26 Mo 11:08]
#+filetags:   :theology:
#+identifier: 20221226T110823

* Lösungen zu den Arbeitsaufträgen - sichtbares Zeichen

1 Erklärung der Begriffe und Handlungen: 

    Segen: Die göttliche Gnade wird für jemanden oder etwas durch Gebetsworte, Formeln, Gesten erbittet und soll Glück und Gelingen bringen.
    
    Aschenkreuz: Die Asche ist ein Symbol für die Vergänglichkeit. Mit dem Aschenkreuz auf der Stirn bekennen die Gläubigen öffentlich ihre Bereitschaft zu Umkehr und Buße.
    
    Weihrauch: Der Weihrauch steht für Reinigung, Verehrung und Gebet.
    
    Hand auflegen: Die Hand (oder beide Hände) werden einem Menschen oder Gegenstand aufgelegt, um diesen zu segnen bzw. auch um eine Heilung von Krankheiten zu erbitten.
    
    Räuchern: Das Räuchern soll eine Verbindung zu Gott versinnbildlichen. Es ist ein spirituelles Ritual mit folgenden Wirkungen: Reinigung, Segnung, Heilung, ...
    
    Umarmung: Bei einer Umarmung findet eine Kommunikation ohne Worte statt. Sie bringt zum Ausdruck. Menschen umarmen sich auch um Vertrautheit, Freundschaft, Zuneigung, Liebe, Anerkennung, Unterstützung, Ermutigung oder Trost. auszudrücken.
    
    Prozession: Ein feierlicher Umzug der aus religiösem Anlass von einer Menschengruppe veranstaltet wird. Eine Prozession ist ein religiöses Ritual die bestimmten Regeln folgt.
    Das Wort Prozession leitet sich vom lateinischen procedere ab und bedeutet „vorrücken, voranschreiten“. Z.B. an Fronleichnam, Christi Himmelfahrt, Beerdigungen, ...
    
    Eheringe: Sind ein Symbol für die Treue, Liebe, Verbundenheit und Beständigkeit. Sie haben keinen Anfang und kein Ende und deuten auf die Unendlichkeit der Ehe hin.
    
    Weihwasser: Weihwasser ist ein Wasser, über das vom Priester ein Segensgebet gesprochen wird. (Salz wird dem Wasser beigefügt).
    Das Weihwasser ist ein Segenszeichen der katholischen Kirche und wird beim Sakrament der Taufe, bei einer Segnung, als auch beim Eintreten in eine katholische Kirche zur Erinnerung an die eigene Taufe (Taufgedächtnis) verwendet.
    
    Wallfahrt: Ist eine aus verschiedenen religiösen Motiven (z. B. Buße, Suche nach Heilung, Bitte um Gottes Segen) unternommene Wanderung, oder Fahrt zu einem Wallfahrtsort bzw. einer heiligen Stätte.

2 Mögliche Beispiele, die die Nähe Gottes erfahrbar machen können, sind:

    Segnung von Gegenständen
    Weihe
    Gebet
    Bittgänge
    Andachten, etc. 

3 Dieser Arbeitsauftrag ist sehr persönlich und individuell. 
Die Schüler*innen sollen eine Handlung, ein Wort oder ein Ding in der linken Hälfte (orange umrandet) des Reises gestalten. Dabei steht es ihnen frei, ob sie malen, schreiben, oder eine andere kreative Art wählen, um es zu gestalten. Dieser Arbeitsauftrag ist die Vorbereitung auf den ersten Arbeitsauftrag des Unterkapitels 4.4 – „Die spürbare Wirkung“.

4 Dieser Arbeitsauftrag zielt auf die religiöse Sprachentwicklung der Schüler*innen ab. Es werden in der Diskussion persönliche Erfahrungen gesammelt, dabei ist zu beachten, dass kein Zwang auf die Schüler*innen ausgeübt wird und auch negative, ablehnende Haltungen, bei der Frage nach der Nähe Gottes, zugelassen werden sollen.

* Lösungen zu den Arbeitsaufträgen - spürbare Wirkung

1 Dieser Arbeitsauftrag ist sehr persönlich und individuell, da die Schüler*innen den zweiten Teil des Kreises (blau umrandet) kreativ gestalten sollen. Es soll darauf hingewiesen werden, dass nicht irgendeine Wirkung eines Sakramentes dort sein sollte, sondern eine passende Wirkung, die sich auf den Arbeitsauftrag 3 der vorhergehenden Seite bezieht. Wenn z.B. Eheringe gewählt wurden, sollte im blauen Teil Liebe darinstehen. Es können auch mehrere Wirkungen passen: z.B. Weihwasser: Begleitung, Stärkung oder Schutz etc.

2 Weitere Wirkungen die Menschen durch die sieben Sakramente erfahren können sind: Dankbarkeit, Versöhnung, Hilfe, Begeisterung, Heilung, Vertrauen, Wiedergutmachung, anderen dienen, …
Für diesen Arbeitsauftrag kann auch der Anhang: „Religion für mich – Die sieben Sakramente“ (Seite 131 bis 135) verwendet werden.
