#+title:      B Klasse 2020-24
#+date:       [2022-12-30 Fr 19:37]
#+filetags:   :4b:Project:
#+identifier: 20221230T193718
#+CATEGORY: golling

* Jahresplanung
[[denote:20230621T073603][04 Golling]]

* 4b 07:45-08:35
<%%(org-class 2023 9 12 2024 7 6 2)>

* 4b 07:45-08:35
<%%(org-class 2023 9 13 2024 7 7 3)>

[[denote:20230711T002844][[SW01] Jesus ist die Quelle unseres Lebens]]

Achtung: das ist die "schwierige" Klasse. Tipp von Charly: Bitte den Hl. Geist bevor du die Klasse betrittst.

Von Anfang an klar und "streng" sein.


* 4B [KV Erwin Essl]

#+Name: 2021-students
| First      | Last         | Name                  | Note | Mitarbeit | Heft | LZK |
|------------+--------------+-----------------------+------+-----------+------+-----|
| Maximilian | Fischhofer   | [[Maximilian Fischhofer][Maximilian Fischhofer]] |      |           |      |     |
| Hannah     | Höllbacher   | [[Hannah Höllbacher][Hannah Höllbacher]]     |      |           |      |     |
| Maximilian | Fischhofer   | [[Maximilian Fischhofer][Maximilian Fischhofer]] |      |           |      |     |
| Hannah     | Höllbacher   | [[Hannah Höllbacher][Hannah Höllbacher]]     |      |           |      |     |
| Thomas     | Krallinger   | [[Thomas Krallinger][Thomas Krallinger]]     |      |           |      |     |
| Fabian     | Lienbacher   | [[Fabian Lienbacher][Fabian Lienbacher]]     |      |           |      |     |
| Lena       | Malter       | [[Lena Malter][Lena Malter]]           |      |           |      |     |
| Sophia     | Mayr         | [[Sophia Mayr][Sophia Mayr]]           |      |           |      |     |
| Florian    | Peroutka     | [[Florian Peroutka][Florian Peroutka]]      |      |           |      |     |
| Andreas    | Rußegger     | [[Andreas Rußegger][Andreas Rußegger]]      |      |           |      |     |
| Valerie    | Schönauer    | [[Valerie Schönauer][Valerie Schönauer]]     |      |           |      |     |
| Marlene    | Seidl        | [[Marlene Seidl][Marlene Seidl]]         |      |           |      |     |
| Anna       | Spitzelseder | [[Anna Spitzelseder][Anna Spitzelseder]]     |      |           |      |     |
| Florian    | Steiner      | [[Florian Steiner][Florian Steiner]]       |      |           |      |     |
| Karin      | Struber      | [[Karin Struber][Karin Struber]]         |      |           |      |     |
| Lukas      | Wagenhofer   | [[Lukas Wagenhofer][Lukas Wagenhofer]]      |      |           |      |     |
#+TBLFM: $4=vmean($5..$>)
#+TBLFM: $3='(concat "[[" $1 " " $2 "][" $1 " " $2 "]]")
#+TBLFM: $5='(identity remote(Mitarbeit,@@#$2))

#+BEGIN_SRC python :var table=2021-students :results output raw
  print('* Mitarbeit')
  for student in table:
      first = student[0]
      last = student[1]
      email = first + '.' + last + '@golling.schule'
      print('** ' + first + ' ' + last + '')
      print(':PROPERTIES:')
      print(':EMAIL: ' '[[mailto: ' + first + ' ' + last + ' <' + email + '>]]')
      print(':END: ')
      print('\n\n')
#+END_SRC

#+RESULTS:
* Mitarbeit

#+Name: Mitarbeit
| Name                  | Note | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |
|-----------------------+------+---+---+---+---+---+---+---+---+---+----|
| [[Maximilian Fischhofer][Maximilian Fischhofer]] |      |   |   |   |   |   |   |   |   |   |    |
| [[Hannah Höllbacher][Hannah Höllbacher]]     |      |   |   |   |   |   |   |   |   |   |    |
| [[Maximilian Fischhofer][Maximilian Fischhofer]] |      |   |   |   |   |   |   |   |   |   |    |
| [[Hannah Höllbacher][Hannah Höllbacher]]     |      |   |   |   |   |   |   |   |   |   |    |
| [[Thomas Krallinger][Thomas Krallinger]]     |      |   |   |   |   |   |   |   |   |   |    |
| [[Fabian Lienbacher][Fabian Lienbacher]]     |      |   |   |   |   |   |   |   |   |   |    |
| [[Lena Malter][Lena Malter]]           |      |   |   |   |   |   |   |   |   |   |    |
| [[Sophia Mayr][Sophia Mayr]]           |      |   |   |   |   |   |   |   |   |   |    |
| [[Florian Peroutka][Florian Peroutka]]      |      |   |   |   |   |   |   |   |   |   |    |
| [[Andreas Rußegger][Andreas Rußegger]]      |      |   |   |   |   |   |   |   |   |   |    |
| [[Valerie Schönauer][Valerie Schönauer]]     |      |   |   |   |   |   |   |   |   |   |    |
| [[Marlene Seidl][Marlene Seidl]]         |      |   |   |   |   |   |   |   |   |   |    |
| [[Anna Spitzelseder][Anna Spitzelseder]]     |      |   |   |   |   |   |   |   |   |   |    |
| [[Florian Steiner][Florian Steiner]]       |      |   |   |   |   |   |   |   |   |   |    |
| [[Karin Struber][Karin Struber]]         |      |   |   |   |   |   |   |   |   |   |    |
| [[Lukas Wagenhofer][Lukas Wagenhofer]]      |      |   |   |   |   |   |   |   |   |   |    |
#+TBLFM: $2=vmean($3..$>)
#+TBLFM: $1='(identity remote(2021-students,@@#$3))

** Maximilian Fischhofer
:PROPERTIES:
:EMAIL: [[mailto: Maximilian Fischhofer <Maximilian.Fischhofer@golling.schule>]]
:END: 

*** Link zur UE: [[file:~/RoamNotes/main/03_Golling.org::#Herbstferien3][file:~/RoamNotes/main/03_Golling.org::#Herbstferien3]]
so wie Andreas, Thomas und Lukas: stört, legt ein provozierendes Verhalten an den Tag. Man redet sie direkt an - und erhält ein provozierendes "Okay, okay, okay" mit einem präpotenten Grinsen zurück.

Hat sein Heft vergessen.

*** [[denote:20230327T101329][[SW29] Die Erlösung durch das Kreuz]]
PERIOD: [2023-03-27 Mo 09:35]

Maxi, Thomas und Fabian arbeiten gemeinsam in einer Gruppe. Im Moment wird dort nur gelacht, und Blödsinn gemacht. Vielleicht trügt der Anschein?


** Hannah Höllbacher
:PROPERTIES:
:EMAIL: [[mailto: Hannah Höllbacher <Hannah.Höllbacher@golling.schule>]]
:END: 



** Leon Keser
:PROPERTIES:
:EMAIL: [[mailto: Leon Keser <Leon.Keser@golling.schule>]]
:END: 

beweist sich nicht

*** [[file:~/RoamNotes/main/02_Golling.org::#Auferstehung][file:~/RoamNotes/main/02_Golling.org::#Auferstehung]]
Datum: <2022-04-04 Mo>

In der heutigen Stunde war es generell sehr schwierig und mühsam. Vor allem die Burschen "auf meiner Linken" und die drei Burschen "in der letzten Reihe" haben massiv gestört. Da ich ein eher ruhiger Typ bin, bringt es nicht viel, auf einmal herumzubrüllen und laut zu werden. Wenn zB Hannes oder Christoph das machen, dann "passt" es zu ihnen. Die Schüler werden dann wirklich ruhig. Bei mir...?

Dazu kommt noch die emotionale Reaktion von Birgit auf eine Diskussion über das Thema "Kirche" (in die sie sich unaufgefordert eingemischt hat). Ich denke, dass Birgit deshalb wieder die Geschichte mit dem abgesagten Ostergottesdienst aufgewärmt hat - und darüber zornig wird; obwohl Elisabeth darauf ziemlich gelassen reagiert hat.

Im Moment also hab ich kaukm Lust auf meine Arbeit - von allen Seiten verspüre ich Widerstand, Kritik und schon Attacken gegen meine Person.

Ich hab mich sicher nicht richtig verhalten, weil ich es verabsäumt hatte, Elisabeth zu kontaktieren - und vergessen habe, au den SA Plan zu schauen.

*** [[file:~/RoamNotes/main/02_Golling.org::#Wiederholung Jahresstoff][file:~/RoamNotes/main/02_Golling.org::#Wiederholung Jahresstoff]]
Datum: <2022-06-27 Mo>

Das ist heute leider komplett daneben gegangen. Schade. Leon hat uns die ganze, schöne Filmstunde ruiniert - aber nicht nur er.

*** Link zur UE: [[file:~/RoamNotes/main/03_Golling.org::#Wegbegleiter][file:~/RoamNotes/main/03_Golling.org::#Wegbegleiter]]

Hat trotz Aufforderung und SchoolFox Nachricht sein Heft nicht in Ordnung gebracht (dh er hat die "zesrtörten" Seiten schlecht herausgeschnitten und sie nicht nachgemacht.)

Erneute Nachricht an die Eltern - was noch?

*** Link zur UE: [[file:~/RoamNotes/main/03_Golling.org::#Herbstferien3][file:~/RoamNotes/main/03_Golling.org::#Herbstferien3]]

Hm, unkonzentriert ... wie damit umgehen?

*** Link zur UE: [[file:~/RoamNotes/main/03_Golling.org::#Wegbegleiter][file:~/RoamNotes/main/03_Golling.org::#Wegbegleiter]]

Aha: also muss ich vorher mu4e aufrufen, einen Link zu einem Mail herstellen. Dann funktioniert auch org-store-link wieder.

*** [[file:~/RoamNotes/main/03_Golling.org::*Medienkonsum und Entwicklung des Gehirns][Medienkonsum und Entwicklung des Gehirns]]
Datum: <2022-09-19 Mo>

hat Reli-Heft und Buch vergessen.

*** [[file:~/RoamNotes/main/02_Golling.org::*\[SW28\] Die Klagepsalmen / Die letzte Woche in Jerusalem][[SW28] Die Klagepsalmen / Die letzte Woche in Jerusalem]]
Datum: <2022-03-25 Fr>

Komisch: vor der vierten Stunde, am Ende der Pause gab es im Stiegenhaus eine lauten, spitzen Schrei. Mir schien es, als käme er von einem Schüler - einer Schülerin der 2B. Ich fragte in allen 2. Klassen nach - keiner war es. Die vierten Klassen fallen auch aus ...

Alle Indizien weisen auf Leon hin und Daniel ... Schüler aus der 2B.

*** [[denote:20230711T002844][[SW01] Jesus ist die Quelle unseres Lebens]]
:PROPERTIES:
:CAPTURED: [2023-09-13 Mi 08:54]
:CLASS: [2023-09-13 Mi 07:45] 1. Stunde
:END:

Leon hat gleich in der ersten Stunde wieder "ordentlich" begonnen. Er hat zuerst das gemeinsame Gebet gestört und während dem Unterricht mit einer "Papierklatsche" Lärm gemacht. Als ich die Klasse verlassen hatte, hat ein anderer (?) Schüler ebenfalls mit der Papierklatsche Lärm gemacht.

Ich hab den Vorfall im schwarzen Buch vermerkt und werde noch die Mutter von leon verständigt.

** Thomas Krallinger
:PROPERTIES:
:EMAIL: [[mailto: Thomas Krallinger <Thomas.Krallinger@golling.schule>]]
:END: 

*** [[file:~/RoamNotes/main/03_Golling.org::*Medienkonsum und Entwicklung des Gehirns][Medienkonsum und Entwicklung des Gehirns]]
Datum: <2022-09-19 Mo>

hat Reli-Heft und Buch vergessen.

beweist sich nicht

*** Verhalten und Mitarbeit
Die Religionsnote setzt sich v.a. aus der Mitarbeit / Heftführung zusammen. Und diese ist bei Thomas eben nicht so gut, dass ich ihm ein Sehr Gut oder Gut geben kann. Ich mache beuwsst keinen Test - die Schüler haben schon genug Fächer, in denen sie geprüft werden. Im Gegenzug erwarte ich aber eine viel aktivere Teilnahme am Unterricht. In Religion ist Raum und Zeit für viele Themen und Austausch zu vielen Themen. 

Seit dem Gespräch zum Elternsprechtag hat sich leider das Verhalten von Thomas nicht gebessert. Im Gegenteil. Wie ich es angekündigt hatte, habe ich daher für mehrere Schüler als Verhaltensnote ein WZ beantragt. Dies wurde einstimmig von allen Lehrern der 3b bestätigt.

Auch andere Lehrer der Klasse klagen über das schlechte Verhalten in dieser Klasse. Daher wurde u.a. ein zusätzlicher Tisch in die Klasse gestellt, um Schüler trennen zu können.

Thomas und die anderen Burschen stören nicht nur meinen / unseren Unterricht, machen dadurch ein ruhiges Lernen unmöglich. Sondern sie verhindern auch, dass jene, die gerne wollen, am Unterricht teilnehmen können.

Wenn ein Schüler (massiv) den Unterricht stört und er eine dementsprechende Verhaltensnote erhält, dann kann er nicht gleichzeitig eine gute Leistung im Unterricht bringen. Die Religionsnote ergibt sich auch logischerweise aus dem Verhalten, v.a. da ich besnders auf die Mitarbeit großen Wert lege.

Es kann sein, dass ich in der ersten und zweiten Klasse zu gutmütig war, und manche Noten zu leichtfertig verschenkt habe. Ich gab den Kindern einen Vertrauensvorschuss und dachte, dass die Kinder dies mit guter Mitarbeit beantworten würden. Ich wurde enttäuscht und das kann ich jetzt nicht mehr machen.

Etwas Positives: alle betroffenen Burschen haben verstanden - wenn sie ihr Verhalten ändern und besser mitarbeiten, können sie sich ihre Note verbessern. Ich kann keine guten Noten einfach herschenken.

*** Auswirkungen auf Lehrer
Habe Pflicht, dem Lehrplan entsprechend zu unterrichten. Störendes Verhalten hindert mich daran. Ist eigentlich eine Beleidigung gegenüber dem Lehrer, wenn sich dieser besonders viel Mühe bei der Vorbereitung gegeben hat. Als weitere Folge kann der Lehrer seine Freude am Unterricht verlieren und kommt nur mehr ungern in diese Klasse. 

*** Auswirkungen auf Klasse
Durch sein Verhalten hat Thomas im ersten Semester vor allem auch seine Mitschüler vom Lernen abgehalten. Man muss ihm zu gute halten, dass er trotz seines Störens klug genug ist, rechtzeitig aufzuhören. Und dennoch stört er.

Durch das oftmalige Ermahnen geht kostbare Unterrichtszeit verloren. Das wirkt sich negativ auf alle aus: dem Schüler selbst, den Mitschülern und den Lehrer.

*** Auswirkungen auf sich selbst
Durch sein Stören kann er weniger gut aufpassen und überhört wichtige Lerninhalte. Es stimmt, dass sich Thomas seit dem ersten Semester gesteigert hat, aber dies rechtfertigt noch kein "Sehr Gut".

*** Leistungsbeurteilung
Für ein "Sehr Gut" sind v.a. erforderlich:
"Mit „Sehr gut“ sind Leistungen zu beurteilen, mit denen der Schüler die nach Maßgabe des Lehrplanes gestellten Anforderungen in der Erfassung und in der Anwendung des Lehrstoffes sowie in der Durchführung der Aufgaben *in weit über das Wesentliche hinausgehendem Ausmaß* erfüllt und, wo dies möglich ist, *deutliche* Eigenständigkeit beziehungsweise die Fähigkeit zur selbständigen Anwendung seines Wissens und Könnens auf für ihn neuartige Aufgaben zeigt."

Für ein "Gut":
"Mit „Gut“ sind Leistungen zu beurteilen, mit denen der Schüler die nach Maßgabe des Lehrplanes gestellten Anforderungen in der Erfassung und in der Anwendung des Lehrstoffes sowie in der Durchführung der Aufgaben in über das Wesentliche hinausgehendem Ausmaß erfüllt und, wo dies möglich ist, merkliche Ansätze zur Eigenständigkeit beziehungsweise bei entsprechender Anleitung die Fähigkeit zur Anwendung seines Wissens und Könnens auf für ihn neuartige Aufgaben zeigt."

Wenn ich also im Unterricht Fragen stelle und die Schüler zur Mitarbeit auffordere, dann kommt von Thomas eben eine gute Mitarbeit - für ein Sehr Gut reicht es nicht. Thomas hat noch das vierte und letzte Schuljahr an der Mittelschule - noch genug Zeit, um sich zu beweisen.

*** P.S.
Im Übrigen lasse ich mich nicht unter Druck setzen - oder gar erpressen. Würde ich hier nachgeben, wäre dies das Ende meine Laufbahn als Lehrer; oder ich müsste mir eine neue Schule suchen. Das würde sich herumsprechen und wäre nicht nur ein Schaden für mich, sondern für die gesamte Schule. Ein "Gut" ist keine Katastrophe, sondern eine gute Note (auch in Religion). Ich hab den Schülern klar kommuniziert, dass sie sich im zweiten Semester durch entsprechende Mitarbeit ihre Note verbessern können (von 3 auf 2). Und das hat Thomas getan, er hat wirklich in diesem Semster besser mitgearbeitet und sich bemüht, daher hat er sich das "Gut" verdient. Ich lade Thomas ein, diesen Weg weiterzugehen - so bliebt er auf einem guten Weg.

Was würde Thomas lernen, wenn ich jetzt nachgeben würde? "Ich kann mir durch Intervention eine sehr gute Note ergattern?" Welche Auswirkungen hätte mein Nachgeben auf das Verhalten der Klasse im nächsten Schuljahr? Jeder Respekt wäre komplett weg! Nein, deshalb gebe ich hier nicht nach. Frau Gruber und meine Inspektorin stärken mir den Rücken, ich stehe nicht alleine da.

Das "Gut" bildet die Leistung und Mitarbeit des gesamten Jahres ab. Und im ersten Semester war seine Mitarbeit weniger gut, eben befriedigend, im zweiten Semester besser, mcht insgesamt ein "Gut". 



** Fabian Lienbacher
:PROPERTIES:
:EMAIL: [[mailto: Fabian Lienbacher <Fabian.Lienbacher@golling.schule>]]
:END: 



** Lena Malter
:PROPERTIES:
:EMAIL: [[mailto: Lena Malter <Lena.Malter@golling.schule>]]
:END: 



** Sophia Mayr
:PROPERTIES:
:EMAIL: [[mailto: Sophia Mayr <Sophia.Mayr@golling.schule>]]
:END: 



** Florian Peroutka
:PROPERTIES:
:EMAIL: [[mailto: Florian Peroutka <Florian.Peroutka@golling.schule>]]
:END: 



** Andreas Rußegger
:PROPERTIES:
:EMAIL: [[mailto: Andreas Rußegger <Andreas.Rußegger@golling.schule>]]
:END: 



** Valerie Schönauer
:PROPERTIES:
:EMAIL: [[mailto: Valerie Schönauer <Valerie.Schönauer@golling.schule>]]
:END: 



** Marlene Seidl
:PROPERTIES:
:EMAIL: [[mailto: Marlene Seidl <Marlene.Seidl@golling.schule>]]
:END: 



** Anna Spitzelseder
:PROPERTIES:
:EMAIL: [[mailto: Anna Spitzelseder <Anna.Spitzelseder@golling.schule>]]
:END: 



** Florian Steiner
:PROPERTIES:
:EMAIL: [[mailto: Florian Steiner <Florian.Steiner@golling.schule>]]
:END: 



** Karin Struber
:PROPERTIES:
:EMAIL: [[mailto: Karin Struber <Karin.Struber@golling.schule>]]
:END: 



** Lukas Wagenhofer
:PROPERTIES:
:EMAIL: [[mailto: Lukas Wagenhofer <Lukas.Wagenhofer@golling.schule>]]
:END: 


* Reflexionen

** [[denote:20221226T113745][Dialog zw Theologie und Naturwissenschaften]]
PERIOD: [2023-02-02 Do 08:40]

Diese Stunde war echt grausam - fast die gesamte Klasse, va die Burschen haben mich komplett ingnoriert. Als ich "endlich" die Stimme erhob, haben sich ein paar der Burschen diebisch darüber gefreut (ist das nicht dämonisch?). Die Stunden in dieser Klasse lassen mich jedesmal erschöpft zurück.

Mit Manuela Gruber haben wir darüber gesprochen. Die Kinder werden pro Jahrgang nicht braver, eher schlimmer. Ich muss auf mich schauen - so viele Lehrer geben erschöpft und ausgebrannt auf. Deshalb: schau auf dich, damit dir dies nicht passiert. An manchen Tagen kann Manuela mir helfen, sie wird dann draußen sitzen und jene Schüler abfangen, die ich hinausschicke.

** Reaktion von Florian Steiner's Mutter über SchoolFox
Verhalten von Florian hat sich eben nicht verbessert.
Und daher ist auch die Note (3) gerechtfertigt.
Alle Burschen - auch Florian - haben verstanden, dass sie sich ihre Note durch ein besseres Verhalten und bessere Mitarbeit im Unterricht verbessern können.

** Gespräch mit Fr. Krallinger
Reli-Note ist peinlich für Familie. Ich hab meinen Standpunkt dargelegt.
[[denote:20230310T173200][Gespräch Krallinger]]


** [[denote:20230323T100317][[SW28] Was ist das Kreuz für dich?]]
PERIOD: [2023-03-23 Do 08:40]

Das war heute emotional sehr anstrengend. Die erste Hälfte der Stunde war "buisness as usual": extrem störendes Verhalten der Schüler, teilweise bereits "Lehrer ignorieren". Ich hab in der Folge die Schüler "ignoriert", da schreien nix nutzt. Nach einer sehr emotionalen Rede meinerseits war der Rest der Stunde wesentlich besser.

Thema: Sinn und Bedeutung der Arbeit für den Menschen - In D: Arbeitsbedingungen in den großen Textilfirmen; BO Tage der Schüler; Pleite von zwei Modefirmen; Pleite dreier großen Banken (SVB, noch eine andere US Bank, Credit Suisse, ...)

Maxi ändert sich gar nicht - scheinbar ist die Reli Note Zuhause völlig egal. Schaut sich seine Mama überhaupt das Zeugnis an? Thomas und Lukas ändern sich zum Besseren.
                                                 

** [[id:03_SW01][[SW01] Wer möchte ich sein – wer bin ich?]]
Datum: <2022-09-15 Do 08:40>

Für dieses capture: C-1 C-n-c (das fügt das "date at point" der agenda ein) ... in den Header ein C-n-i und Link zu Stunde/Vorbereitung.

Das war eigentlich eine gute Stunde; ein paar Burschen in der ersten Reihe wurden unruhig sobald ich ihnen den Rücken zukehrte. Ich hab sie darauf hingewiesen. Leon kann ich am Mo+Do zu Manuela schicken (was er gar nicht mag).

