#+title:      Trinität
#+date:       [2022-12-26 Mo 16:56]
#+filetags:   :bibel:theology:
#+identifier: 20221226T165610

* Einstieg
Wir sprechen über die Dreifaltigkeit, da Gott sich durch [[denote:20221226T110720][Jesus]] ([[denote:20230102T223430][Jesus Christus Mensch]]) als dreifaltig offenbart hat. 

1 Für die Schüler in dieser Altersgruppe befinden sich gerade in einer gravierenden religiösen Entwicklungsphase und so verändert sich gerade die Gottesvorstellung der frühen Kindheit weiter. Meist ist diese noch lückenhaft und je nach sozialer Lage, kann sich die Entwicklung unterschiedlich vollziehen. Der Comic greift diese Thematik auf und fordert die Schüler*innen heraus über ihr eigenes Gottesbild nachzudenken. In der Diskussion ist es wichtig, dass hier den Gedanken und Vorstellungen der Schüler*innen viel Raum gegeben wird und kein Gottesbild favorisiert wird.

2 Dieser Arbeitsauftrag ist sehr persönlich und individuell, jedoch sehr einfach gehalten. Er dient dazu die Schüler zum Nachdenken über ihre eignen Gottesvorstellung anzuregen und dieser Vorstellung eine Sprache zu geben.

3 Dieser Arbeitsauftrag zielt darauf ab, dass sich die Schüler was ihre Gottesvorstellungen betrifft gerade in einer Übergangsphase sind in der ihnen aber sehr wohl bewusst ist, dass sich seit ihrer frühen Kindheit auf diesem Gebiet schon einiges verändert hat. Es sind die ersten Ansätze der Reflexion der eigenen Glaubensvorstellungen vorhanden und sollen behutsam weiterentwickelt werden.

4 Dieser Arbeitsauftrag zielt auf den Austausch der unterschiedlichen Gottesvorstellungen ab. Bei der Diskussion über solche persönlichen Ansichten sind Toleranz und respektvolles Zuhören grundlegende Werte, die eingeübt werden. Es biete sich an, dass auch Hintergründe ("Warum ist das bei dir so?") ergründet werden. Es sollte jedoch auch eine Ablehnende Gottesvorstellung in der Diskussion einen Platz haben dürfen.

* Von Gott sprechen
1 Folgende Gottesvorstellungen / Erfahrungen können aus den Bibeltexten ([[denote:20221226T110706][Bibel]]) herausgelesen werden:

 - Genesis 1,27 – Gott der Schöpfer – Frage: Woher kommt der Mensch?
 - Ijob 37,2.4 – Gott als mächtiger Sturm, als lauter Donner – Erklärung nach
 - Jesaja 66,13 – Gott der Tröster (männlich) – Wie geht der Mensch mit Leid/Trauer um?
 - 1 Johannes 4,16b – Gott ist die Liebe – Erfahrungen mit den Gefühlen
 - Matthäus 6,9 – Gott als Vater – Beziehungen leben
 - Psalm 22,10 – Gott als Mutter (weiblich) – Geborgenheit in der Familie
 - Ezechiel 34,11 – Gott als der Hirte – Vertrauen, es kümmert sich jemand

2 Die Bilder dieses Arbeitsauftrages wurden von Schüler zwischen 11 und 13 Jahren an der PMS Michaelbeuern gezeichnet und könnten folgenden Bibelstellen zugeordnet werden:

 - Bild 1 "Gott als Mann/Frau" - Gen 1,27
 - Bild 2 "Gott als Frau mit Herzen darum" - Ps 22,10 und 1 Joh 4,16b
 - Bild 3 "Gott als großes Herz" - 1 Joh 4,16b; Ez 34,11; Ijob 37,2.4; Mt 6,9
 - Bild 4 "Gott schemenhafte Figur" - Gen 1,27; Ijob 37,2.4;

Eigenschaften Gottes die genannt werden können:
Gott ist die Liebe, Gott ist wie ein barmherziger Vater, Gott ist ein Tröster, Gott ist eine Kraft, Gott ist der Schöpfer, Gott ist fürsorglich wie eine Mutter, Gott ist ein verantwortungsvoller Hirte, ...

3 Folgende Gottesvorstellungen und Aussagen könnten miteinander verbunden werden:

  - Gott der Schöpfer – Gott steuert alles was auf der Welt passiert ...
  - Gott als mächtiger Sturm, als lauter Donner – Gott sieht und hört alles,...
  - Gott der Tröster – Gott ist wie meine Mutter ...
  - Gott ist die Liebe
  - Gott als Vater –Ich stelle mir Gott als alten Mann mit langem Bart vor ...
  - Gott als Mutter (weiblich) – Gott ist wie meine Mutter ...
  - Gott als der Hirte
  - Bild 4 "Gott schemenhafte Figur" – Ich kann mir Gott gar nicht vorstellen
  - Bild 2 "Gott als Frau mit Herzen darum" – Ich stelle mir Gott wie ein helles Licht vor…
  - Bild 3 "Gott als großes Herz" – Gott ist für mich ganz anders ...
  - Bild 4 "Gott schemenhafte Figur" - Gott ist für mich ganz anders ...

  Die Schüler können aber meist noch viele weitere Verbindungen herstellen. Dieser Arbeitsauftrag leitet eine Übung der religiösen Sprachkompetenz ein, aus der sich ein Philosophieren und Theologisieren entwickeln kann.

4 Bei diesem Arbeitsauftrag sollen die Schüler*innen ihre persönliche und individuelle Gottesvorstellung auf kreative Weise zum Ausdruck bringen.

* YouCat "Dreifaltigkeit"
Nr. 35, 36, 122, 165.

(S. 291):
- Gott ist Liebe 33
- Gott, Heiliger Geist 38, 113-129
- Gott, der Schöpfer 41, 44, 330
- Gott, der Sohn 39
- Gott, der Vater 37
- etc ...

* Videos 3MC "Dreifaltigkeit"
Ab Folge 12: [[https://www.youtube.com/watch?v=uumCTFrUniE]]

* Dreifaltigkeit und Gebet
Kreuzzeichen

Vaterunser

Glaubensbekenntnis

... jedes christliche Gebet steht im Zeichen, unter den Namen des dreifaltigen Gottes: im Heiligen Geist, durch Jesus zum Vater.
