#+title:      Jesus von Nazareth: Band II: Vom Einzug in Jerusalem bis zur Auferstehung
#+date:       [2023-04-05 Mi 11:20]
#+filetags:   :bib:jesus:
#+identifier: 20230405T112018
#+reference:  Ratzinger.2011

* Kapitel 9: Die Auferstehung Jesu aus dem Tod (S. 265-302)
"Ist aber Christus nicht auferweckt worden, dann ist unsere Verkündigung leer und euer Glaube sinnlos." (1 Kor 15,14f)

Ohne der Auferstehung kann man aus der christlichen Überlieferung heraus jede Menge Überlegungen über Gott und den Menschen anstellen - der christliche Glaube ist tot.

Jesus ist dann eine religiöse Persönlichkeit, seine Autorität reicht aber nur soweit, wie uns seine Botschaft einsichtig ist.

Er ist kein Maßstab mehr; der Maßstab ist dann nur unser eigenes Urteil, das von seinem Urteil auswählt, was uns hilfreich erscheint. Unser Urteil ist dann die letzte Instanz.

Nur wenn Jesus auferstanden ist, ist wirklich Neues geschehen, das die Welt und die Situation des Menschen verändert. Dann hat sich Gott wirklich gezeigt.

Für die Jünger - ist es nicht einfach zu sagen. Eine neue Realität, sprengte ihren Erfahrungshorizont.

Jesu Auferstehung ist nicht eine wiederbelebte Leiche - das wäre in der Tat belanglos.

Neutestamentliche Zeugnisse sind klar: Es war hingegen der Ausbruch in eine ganz neue Art des Lebens, jenseits von Stirb und Werde, eine neue Möglichkeit des Menschseins, die alle angeht. (1 Kor 15,16.20) Die Auferstehung Jesu ist entweder universal, oder sie ist nicht.

Jesu Auferstehung geschieht mitten in der weitergehenden alten Welt - und nicht wie der jüdische Glaube es in einer neuen Welt erwartete. So wie niemand an einen gekreuzigten Messias dachte, musste man nun die Schrift vom Kreuz her neu lesen. Die Auferstehung beglaubigte Jesus als Gesandter Gottes. Kreuz und Auferstehung in der Schrift suchen und finden. Glaube an Jesus als Sohn Gottes.

Voraussetzung: Jesu Auferstehung so real wie das Kreuz. Jünger überwältigt von der Wirklichkeit. Jesus lebt, er ist es wirklich. Jesus war (ist) von Gott her neu und für immer Lebender. Und doch ganz er selbst. Eigenart der Auferstehungszeugnisse: ein Paradox, überschreitet alle Erfahrungen und dennoch ganz real da ist.

** Zwei Arten der Zeugnisse - die Bekenntnistradition
Das Wesentliche in kurzen Formeln zusammengefasst. Z.B.: "Der Herr ist wahrhaft auferstanden und dem Simon erschienen." (Lk 24,34): das Ereignis und sein Zeuge. Röm 10,9 - das Bekenntnis bewirkt Heil. Bekenntnis wird Leben. Das wichtigste Bekenntnis: 1 Kor 15!

Paulus geht es mit Nachdruck auch um die wörtliche Treue in der Weitergabe (Tradition). Inhalt und Wortlaut! universale Verbindlichkeit und Einheitlichkeit des Glaubens. 

*** Der Tod Jesu
Jesus ist "für unsere Sünden" "gemäß der Schrift" gestorben. Alles, was an Jesus geschieht, ist Erfüllung der Schrift. Jesu Tod am Kreuz gehört in die Geschichte Gottes mit seinem Volk hinein. Viertes Gottesknechtlied bei Jesaja - Jesu Tod ist ein Tod "für". Er kommt aus der Demut Gottes, Vollzug der Liebe, ... ein Sühnedienst. Tod, der Versöhnung schafft und Licht für die Völker. 

*** Die Frage des leeren Grabes
"und ist begraben worden" - Jesu Grab war bekannt. Blieb er im Grab?

Ist das leere Grab unerheblich? Es ist ja kein Beweis für die Auferstehung. Stimmt. Aber ist die Auferstehung mit dem Leichnam Jesu im Grab vereinbar? Die Apostel hätten niemals Jesu Auferstehung verkünden können, wenn Jesu Leichnam noch im Grab gelegen wäre. Das leere Grab ist eine grundlegende Bedingung für den Auferstehungsglauben. 

*** Der dritte Tag 

** Die Erzähltradition

*** Die Erscheinungen Jesu an Paulus 

*** Die Erscheinungen Jesu in den Evangelien

** Zfg: Wesen der Auferstehung und ihre geschichtliche Bedeutung


