#+title:      Auferstehung
#+date:       [2023-04-03 Mo 10:14]
#+filetags:   jesus:ostern:
#+identifier: 20230403T101428
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+TODO: TODO(t) STARTED(s!) WAITING(w@/!) APPT(a) PROJ(p) NOTIZ(n) NEXT(x) BESPROCHEN(b) DELEGATED(g@/!) | DONE(d!) CANCELED(c@)
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org

Wie "behandle" ich das Thema Auferstehung im RU? Es ist der wesentliche und zentrale Glaubensinhalt des Christentums. Was sollen die Schüler mitnehmen? Die Auferstehung Jesu ist kein frommes Märchen, keine Massenpsychose der Jünger, etc ... Sie ist ein historisches Ereignis.

Ich sollte wohl das Kapitel in "Jesus von Nazareth" von B16 erneut druchlesen.

* Citar denote links zu bibliographischen Notizen:
[[denote:20230405T112018][Jesus von Nazareth: Band II: Vom Einzug in Jerusalem bis zur Auferstehung]]

[[denote:20230405T113926][Neues Lexikon der katholischen Dogmatik]]

[[denote:20230405T113751][Bibeltheologisches Wörterbuch]]

[[denote:20230405T113850][Herders Neues Bibellexikon]]


* Bibel

** Auferstehung in den Evangelien

- Mt 28
- Mk 16
- Lk 24
- Joh 20 + 21

** Apostelgeschichte

- Apg 2 (Predigt Petrus)
- ... Bekehrung des Hauptmanns Cornelius
- Apg 9 (Bekehrung des Paulus ?)
- Apg ... Missionsreisen des Paulus

** Paulusbriefe

- 1 Kor 15 (u.v.a.m.)

* Materialien

** YouCat Firmbuch

S. 48ff (Begleitbuch) + Firmbuch S. 46ff

** Youcat Glaubenskurs
Warum das Kreuz? S. 47

Warum lassen sich Christen taufen? S. 62

Warum ist die Heilige Messe das zentrale Ereignis der Kirche? S. 83

Was bedeutet "Du sollst den Sonntag heiligen?" S. 126

** YouCat
104 - 108
152, 153

** YouTube-Videos
Johannes Hartl "Auferstehung, leeres Grab, ...":

Teil 1 [[https://www.youtube.com/watch?v=qVyiSLjKj80]]

Teil 2 [[https://www.youtube.com/watch?v=QHEKYZYoCbY]]

Teil 3 [[https://www.youtube.com/watch?v=r7YJOBtnK5w]]

Kathmedia deutsch 
[[https://www.youtube.com/watch?v=37G_apGr12Y]]

[[https://www.youtube.com/watch?v=sZMFHzhNMew]]

[[https://www.youtube.com/watch?v=xF5WQ15cAzY]]


* Ideen

** Auferstehung und Natur
Fotos machen und Gedanken dazu schreiben über Auferstehung 

** Predigten von EB Lackner zu Ostern

*** Glauben als Balanceakt

In der nächtlichen Predigt ging der Erzbischof auf die Frage nach der angemessenen Betrachtungsweise des Ostergeheimnisses ein und widmete sich auch dem Wesen des Glaubens der Jetztzeit. Er sehe zwei Gefahren im heutigen Glauben, so der Erzbischof: "Die einen banalisieren – ‚der liebe Gott wird mich schon hineinlassen in den Himmel‘. Ja, ich glaube auch an die unendliche Barmherzigkeit Gottes, aber man muss vor Gott und auch vor sich selbst bestehen." Die anderen, so Lackner weiter, täten "das genaue Gegenteil, gießen den Glauben in Beton. Sie meinen zu wissen, wie Glauben punktgenau zu funktionieren hat. Beide Wege laufen allerdings quer zur Spur Jesu." Glaube sei ein Balanceakt, der vom Aufmerken auf Gott und von der Sehnsucht lebe. Die Christinnen und Christen hätten "eine Botschaft für die Welt". Diese Botschaft der Auferstehung, so schloss er, müsse gerade heute, in einer Zeit von Unfrieden, Unzufriedenheit, schweren Nöten, Krieg und Katastrophen neu verkündet werden.

*** Golgotha heute

Im Hochamt am Morgen des Ostersonntag schloss Erzbischof Lackner an diesen Gedanken an: Christinnen und Christen hätten einen "Auftrag für die Welt". So wie der auferstandene Christus Maria von Magdala geboten habe, ihn nicht festzuhalten, sollten die Gläubigen von ihren eigenen Vorstellungen und Erwartungen Abstand nehmen um "im Angesicht Gottes und seines wunderbaren Erlösungswerks einfach da zu sein". Auferstehungsglaube beinhalte aber auch ein "Element von Widerständigkeit"; man dürfe sich in diesem Glauben nicht damit abfinden, dass in nur wenigen hundert Kilometern Entfernung nach wie vor ein Angriffskrieg tobe und auch andere Teile der Welt von Krieg und Katastrophen erschüttert seien. "Wir wollen, so wie die Frauen auf dem gottlosen Hügel Golgotha einst ausharrten, auf den heutigen Hügeln schwerster Nöte betend, bittend und helfend da sein." Der Friede des Auferstandenen sei "unsere Mission bei allem, was wir tun und wirken".

Weitere Ideen:
Die Lebenserwartung war zur Zeit Jesu viel kürzer als heute - und dennoch finden wir in der Bibel so gut wie kaum das Verb "rennen, laufen". Wenn es aber vorkommt - so wie heute am Ostersonntag - dann muss sich etwas Außergewöhnliches ereignet haben. Maria, Johannes und Petrus laufen hin und her ... 

"Halte mich nicht fest!" - Erzbischof Lackner indes deutete die Worte Jesu als Mahnung, keine voreiligen Schlüsse zu ziehen und Ansprüche zu stellen. Wenn Jesus sich diesen an ihn herangetragenen Vorstellungen und Erwartungen entzieht, so werde darin der allem Verstehen, Erklären und Erzählen vorausgehende Akt des Glaubens sichtbar. In ihrem Ausharren am leeren Grab zeige Maria von Magdala dies eindrucksvoll auf: "Auferstehungsglaube bedeutet, Gott nahe zu bleiben, auch wenn dieser menschenfreundliche Gott bei den Menschen zunehmend an Bedeutung verliert", so Lackner. 

** Sieben Schritte zum Frieden

*** Zeit für Stille und Dankbarkeit

Nehmen Sie sich jeden Tag fünf bis zehn Minuten Zeit, um in Ruhe über Ihre gegenwärtige Situation und die Menschen in Ihrem Umfeld nachzudenken. Danken Sie bewusst für alle, die um Sie herum sind. Für die, die Ihnen Gutes tun, aber auch für jene, die Sie herausfordern.

*** Eine motivierende geistliche Lektüre

Suchen Sie sich ein gutes Buch zum Thema Frieden oder lesen Sie einfach Texte aus der Heiligen Schrift. Sehr zu empfehlen sind die Psalmen 34, 85 oder 147. Auch im Buch der Sprichwörter finden Sie Interessantes über den Frieden. 

*** Ein alter Freund. Eine alte Freundin

Versuchen Sie jemanden telefonisch zu erreichen, den Sie früher zu Ihren Freunden gezählt haben. In Krisenzeiten können wir wieder Kontakt zu einst eng vertrauten Menschen aufnehmen. Wie der andere wohl darauf reagiert? 

*** Sie warten auf uns

Papst Franziskus sagte in einer Botschaft: „Wie viele kranke und alte Menschen leben zu Hause und warten auf Besuch!“ Wer aus Ihrer Nähe würde sich über einen Besuch freuen? Der Dienst des Trostes kann die Aufgabe eines jeden Getauften sein.

*** Konflikt – Den ersten Schritt tun

Machen Sie den ersten Schritt zur Versöhnung in einem Konflikt. Sei es in der Familie, mit den Nachbarn, am Arbeitsplatz oder mit Freundinnen und Bekannten. Es macht nichts, wenn Ihr Versuch nicht gleich funktioniert oder fürs Erste keine Frucht bringt. Entscheidend ist Ihre signalisierte Bereitschaft zum Frieden und zur Versöhnung. 

*** Ist schon gut

Oft sind wir im Verzeihen zu schnell, sodass sich keine echte Vergebung einstellen möchte. „Vergeben“ und „Verzeihen“ werden im Volksmund oft parallel benutzt. Umgangssprachlich bedeuten beide „dem anderen nicht mehr böse sein“, obwohl er etwas falsch gemacht hat. Der Verletzte lässt den Schuldigen ziehen, ohne eine Wiedergutmachung einzufordern. Dennoch gibt es einen Unterschied. Vergeben Sie deshalb im Stillen, bevor Sie zu jemanden sagen „Ist schon gut“. Schnell und von Herzen zu vergeben ist die Folge einer bewussten inneren Auseinandersetzung, nicht der schnellen Worte.

*** Beim Aufstehen und zum Niederlegen

Beginnen Sie den Tag mit einem bewussten Lächeln und beenden Sie ihn mit einer ehrlichen Gewissenserforschung. Das erste Lächeln signalisiert: Ich wünsche mir und allen, denen ich begegne, das gute Leben. Die Gewissenserforschung heißt: Ich bin bereit zu Ehrlichkeit und Konsequenz. Dabei soll das, was gelungen ist, genauso zur Sprache kommen, wie das, was schief gelaufen ist. Eine authentische Gewissenserforschung ermöglicht beides: die eigenen Taten, Worte und Werke ernst und sich selbst nicht zu wichtig zu nehmen.

* Für den Unterricht

Die Bibeltexte gemeinsam lesen - selbst für die Apostel war die Begegnung mit dem Auferstandenen eine Erfahrung, die all ihre bisherigen Erfahrungen auf den Kopf stellte. Nicht umsonst blieb Jesus 40 Tage bei ihnen. 
