#+title:      Webpages
#+date:       [2023-12-18 Mo 08:15]
#+filetags:   :capture:
#+STARTUP: showall
#+identifier: 20231218T081552

* Bildung ohne Schule - 
:PROPERTIES:
:CREATED: [2024-01-05 Fr 19:30]
:SOURCE: https://multipolar-magazin.de/artikel/bildung-ohne-schule
:END:
In Deutschland gibt es Schätzungen zufolge 1.000 Freilerner – Kinder, die unter Anleitung ihrer Eltern lernen, ohne eine Schule zu besuchen. In Österreich sind es rund 150, dazu kommen dort einige Tausend sogenannte „Homeschooler“. Was steckt dahinter?

* Das Corona-Tribunal - apolut.net 
:PROPERTIES:
:CREATED: [2024-01-05 Fr 19:32]
:SOURCE: https://apolut.net/das-corona-tribunal/
:END:
War´s das? Nach drei Jahren schwerster Beschädigungen der Demokratie bis hin zur Abschaffung, der Liquidierung, des Grundgesetzes durch eine Bund-Länderkonferenz, der Malträtierung unserer Kinder durch Isolierung, Bildungskastration und Maskenquälerei – soll es das jetzt gewesen sein? Nach drei Jahren der Krankheitsdiktatur, der Mediengleichschaltung, der Zwangs-Spritzung mit einem Stoff, der bestenfalls nicht sehr schädlich ist und in vielen Fällen zum Tod geführt hat; da soll die Schwammdrüber-Zeit beginnen?

* Kathedrale von Autun – Wikipedia
:PROPERTIES:
:CREATED: [2024-01-08 Mo 08:46]
:SOURCE: [[https://de.wikipedia.org/wiki/Kathedrale_von_Autun]]
:END:
Die Kathedrale von Autun ist eine romanische Bischofskirche für das Bistum Autun in der Bourgogne-Franche-Comté. Die dreischiffige Basilika ist dem Patronat des heiligen Lazarus anvertraut. Mit reichem Fassadenschmuck markiert sie den höchsten Platz der Oberstadt von Autun. Seit 1949 trägt sie den Titel einer päpstlichen Basilica minor. Das Kulturdenkmal wurde 1840 als Monument historique klassifiziert. 

* Traum der Könige, Burgund, römische Baukunst
:PROPERTIES:
:CREATED: [2024-01-08 Mo 09:31]
:SOURCE: https://www.kunst-meditation.it/gislebertus-traum-der-konige/
:END:
Das romanische Kapitell „Traum der Könige“ in der Kathedrale von Autun in Burgund gehört zu den berühmtesten Darstellungen dieser Art. Meister Gislebertus hat es um 1220 aus Stein gemeißelt. Zu sehen sind der Engel Gabriel und die Heiligen drei Könige. Über ihnen schwebt der Stern von Bethlehem. Mit dem ausgestreckten Zeigefinger der linken Hand weist der Engel energisch auf den Stern, mit dem Zeigefinger der rechten Hand berührt er zart den Ringfinger des obersten Königs. Das Thema ist nicht der Schlaf oder der Traum der drei Könige, sondern das Erwachen aus der Dunkelheit und der Aufbruch in das Licht!

* [[https://tkp.at/2024/02/20/australien-erlaubt-gen-banane/][Australien erlaubt Gen-Banane]] :website:

[2024-02-20 Di 21:19] 

Für die Wissenschaftler ist es die erste gentechnisch veränderte Banane der Welt, die für Konsumenten zugelassen wurde.

* Australien erlaubt Gen-Banane
:PROPERTIES:
:CREATED: [2024-02-20 Di 21:19]
:SOURCE: https://tkp.at/2024/02/20/australien-erlaubt-gen-banane/
:END:
Australische Kunden werden bald gentechnische manipulierte Bananen im Supermarkt vorgesetzt bekommen. Die GMO-Banane, die gegen die sogenannte „Panama-Krankheit“ resistent sein soll, darf freigesetzt werden und wurde für den menschlichen Konsum erlaubt. Die Sorte QCAV-4 ist laut den Wissenschaftlern die „erste gentechnisch veränderte Banane der Welt und wird die erste gentechnisch veränderte Frucht sein, die von der australischen Regierung für den Anbau in Australien zugelassen wird“. Die GMO-Banane könnte langfristig die klassischen Bananen auch in Europa ablösen.

* [[https://tkp.at/2024/02/20/australien-erlaubt-gen-banane/][Australien erlaubt Gen-Banane]] :website:

[2024-02-20 Di 21:26] 

** Australien erlaubt Gen-Banane
:PROPERTIES:
:CUSTOM_ID: australien-erlaubt-gen-banane
:CLASS: title-heading-left fusion-responsive-typography-calculated
:style: margin:0;--fontSize:38;line-height:1.15;
:END:

20. Februar 2024von [[https://tkp.at/autoren/thomas-oysmueller/][Thomas Oysmüller]]2,4 Minuten Lesezeit

*Für die Wissenschaftler ist es die erste gentechnisch veränderte Banane der Welt, die für Konsumenten zugelassen wurde.*

Australische Kunden werden bald gentechnische manipulierte Bananen im Supermarkt vorgesetzt bekommen. Die GMO-Banane, die gegen die sogenannte „Panama-Krankheit“ resistent sein soll, darf freigesetzt werden und wurde für den menschlichen Konsum erlaubt. Die Sorte QCAV-4 ist laut den Wissenschaftlern die „erste gentechnisch veränderte Banane der Welt und wird die erste gentechnisch veränderte Frucht sein, die von der australischen Regierung für den Anbau in Australien zugelassen wird“. Die GMO-Banane könnte langfristig die klassischen Bananen auch in Europa ablösen.

<<taboola-mid-article-thumbnails>>

**** Gen-Zeitalter
:PROPERTIES:
:CUSTOM_ID: gen-zeitalter
:CLASS: fusion-responsive-typography-calculated
:style: --fontSize: 20; line-height: 1.2;
:fontsize: 20
:lineheight: 24px
:END:
Die Banane ist durch die Panama-Krankheit (TR4), eine Pilzkrankheit, die den Bananenstauden die Nährstoffe entzieht und letztlich tötet, weltweit bedroht. Die Gen-Banane, wird als „Reserveoption“ verkauft und als „wichtiger Schritt zum Aufbau eines Sicherheitsnetzes für die weltweiten Cavendish-Bananen vor TR4.“ Zum Essen sei sie „sicher“, heißt es in einem Nebensatz im aktuellen Bericht im Fachmagazin /[[https://www.abc.net.au/news/2024-02-16/australia-approves-first-genetically-modified-banana-panama-tr4/103476986?utm_source=Live+Audience&utm_campaign=379f11e430-briefing-dy-20240219&utm_medium=email&utm_term=0_b27a691814-379f11e430-51699044][Nature]]/ zur Zulassung.

Man habe „ein Bananengen von einer Banane auf eine andere übertragen“, was „nicht ungewöhnliches“ sei, heißt es aus der Wissenschaft. Bisher sei TR4 in Australien auch „ziemlich gut unter Kontrolle“, die GMO-Banane wird also nicht gebraucht: „Das kann sich jedoch ändern, so dass dies wirklich unser Sicherheitsnetz ist“, sagte Professor Dale, der die Forschung leitet.

* „Das Gericht in Kiew hat bestätigt: Maidan-Scharfschützen schossen aus dem Hotel Ukraina“ -
:PROPERTIES:
:CREATED: [2024-02-28 Mi 09:21]
:SOURCE: https://multipolar-magazin.de/artikel/katchanovski-maidan-scharfschutzen
:END:
Vor zehn Jahren sorgte ein Scharfschützenmassaker an Polizisten und
Maidan-Aktivisten für eine hochexplosive Atmosphäre auf dem Kiewer
Maidan und leitete den zwei Tage später folgenden Putsch gegen die
ukrainische Regierung ein. Der Politikwissenschaftler Ivan
Katchanovski von der Universität Ottawa erläutert im Interview mit
Multipolar den Tathergang, die vorliegenden Beweise, die fragwürdige
Rolle der ARD und die Erkenntnisse eines kürzlich ergangenen Kiewer
Gerichtsurteils zu dem Massenmord. Die Richter stellten faktisch fest:
Rechtsextreme Maidankämpfer schossen aus dem Hotel Ukraina und sind
für den Tod von mindestens zehn Menschen verantwortlich.

* Full article: The “snipers’ massacre” on the Maidan in Ukraine
:PROPERTIES:
:CREATED: [2024-02-28 Mi 09:22]
:SOURCE: https://www.tandfonline.com/doi/full/10.1080/23311886.2023.2269685
:END:
This study analyzes which party of the conflict was involved in the
2014 Maidan massacre in Ukraine. The massacre of Maidan protesters and
the police on 20 February 2014 was a turning point in Ukrainian
politics. This mass killing led to the overthrow of the Ukrainian
government and spiraled into a civil war in Donbas, Russian military
intervention in Crimea and Donbas, the Russian annexation of Crimea,
and conflicts between Ukraine and Russia and between the West and
Russia that Russia drastically escalated by launching its illegal
invasion of Ukraine in February 2022.

* [[https://multipolar-magazin.de/artikel/narziss-und-narzissmus][Narziss und Narzissmus -]] :website:

[2024-02-28 Mi 09:42] 

** Narziss und Narzissmus
:PROPERTIES:
:CUSTOM_ID: narziss-und-narzissmus
:END:

Narzissmus gilt als Krankhaftigkeit eines Einzelnen -- ein Unheil, das jedermann in Beziehungen, Wirtschaft und Politik zu spüren bekommt. Eine narzisstische Aufblähung ist jedoch der Versuch, mittels einer Rolle zu gesellschaftlicher Anerkennung und Bedeutung zu kommen. Diese Rolle ist ein Kompromiss zwischen dem Wunsch, als eigenständiger Mensch anerkannt zu werden und den Erwartungen, die in einer auf Herrschaft gründenden Gesellschaft an den Einzelnen gestellt werden. Die Pathologisierung des Einzelnen behindert die Erkenntnis, dass der Diener den Mächtigen bezeugt.

[[https://multipolar-magazin.de/autorenarchiv?autor=Jeannette%20Fischer][JEANNETTE FISCHER]], 27. Februar 2024, [[https://multipolar-magazin.de/artikel/narziss-und-narzissmus#diskussion][0 Kommentare]], [[https://multipolar-magazin.de/media/pdf/narziss-und-narzissmus.pdf][PDF]]

Die Figur des Narziss tauchte ursprünglich in der griechischen Mythologie auf und wurde vom römischen Dichter Publius Ovidius Naso (43 v. Chr. Bis 17 n. Chr.), kurz Ovid, im dritten Buch seiner Metamorphosen ausführlich beschrieben, eingebettet in eine wortgewaltige Poesie. Es ist der Jüngling, der im Teich sein Spiegelbild sieht und sich in dieses verliebt. Er kann es jedoch weder berühren noch küssen, weil sein Spiegelbild sich ihm zwar auch nähert, im Moment der Berührung jedoch entzieht. Das Begehren ist also gegenseitig.

Dass das Begehren des Narziss -- wie von Ovid beschrieben -- ihm selber gilt, wird heutzutage von vielen Menschen genüsslich zitiert und bissig kommentiert; der Narziss ist zum Objekt einer permanenten Stigmatisierung geworden. Die Rede ist von einem narzisstischen Zeitalter, in dem führende Politiker und Politikerinnen, wichtige Player in Wirtschaft und Gesellschaft dank dieser Eigenschaft zu Macht gelangen -- oder erst dank ihrer so genannten narzisstischen Veranlagung in solche Positionen hineingewählt beziehungsweise hineinbefördert werden.

**** Moderne Bösewichte
:PROPERTIES:
:CUSTOM_ID: moderne-bösewichte
:END:
Ein Narzisst, so der gängige Kanon, ist ein Selbstverliebter und ein tendenziell rücksichtsloser Mensch, weil er das Gegenüber verkennt, es in seiner Eigenheit und Eigenständigkeit nicht wahrnimmt, missachtet und für seine eigenen Zwecke missbraucht, sodass andere Menschen für ihn nur interessant sind, wenn er sie instrumentalisieren kann. Narzissten sind die modernen Bösewichte.

Jahrzehnte vor Ovid ist von dem griechischen Dichter Parthenios von Nikaia, der 73 v. Chr. als Kriegsgefangener nach Rom kam, eine Narziss-Erzählung überliefert, die aufzeigt, dass sich der junge Narziss dem Dasein als Geliebter erwachsener Männer -- eine nicht unübliche Praxis im alten Athen -- verweigert hat. Bei Ovid heißt es (zirka 1 bis 8 n. Chr.):

#+begin_quote
„So hatte Narziss diese (die Nymphe Echo, Anm. JF) enttäuscht, so auch andere Wasser- und Bergnymphen, so vorher den Umgang mit Männern gemieden. Daher hatte einer von ihnen, der verschmäht worden war, die Hände zum Äther erhoben und gesagt: 'So soll es auch ihm in der Liebe ergehen, so soll auch er, was er liebt, nicht bekommen.' Sprach's, und Rhamnusia (Göttin des Zornes, Anm. JF) gewährte die gerechte Bitte.“

#+end_quote

Es wäre also seine Pflicht gewesen, das Begehren der Nymphen und Männer zu befriedigen. Diese Strafe nun, keinen Menschen für das eigene Begehren zu finden, ist in ihrer Grausamkeit unübertroffen. Für Narziss bedeutet sie, dass er in sich selber eingeschlossen bleibt, dass er nur noch sich selber als Gegenüber hat, dass er -- so Ovid -- später an seinem eigenen Feuer, an seiner eigenen Libido sterben wird:

#+begin_quote
„Wie gelbes Wachs an einem schwachen Feuer und wie der morgendliche Rauhreif an der warmen Sonne schmilzt, so schwindet er dahin, von Liebe ausgezehrt und langsam nagt an ihm ein verborgenes Feuer.“

#+end_quote

Setzt man eine Bindungsstruktur voraus, eine intersubjektive, in der der eine Mensch den anderen als Nicht-Ich, als different, als anders anerkennt, dann zeigt dieses Epos eine Struktur des Gefälles: Der eine hat dem anderen seine Wünsche zu erfüllen, ungeachtet seiner eigenen und tut er das nicht, wird er bestraft, in dem er der Bindung zu missen hat. Und ohne Bindung werden wir verrückt oder wir sterben, dies hat Ovid zu recht erkannt.

Einem in sich eingeschlossenen Menschen -- wie hier Narziss -- wird die Angst im Seitenwagen ein unbeirrter Begleiter sein, er wird immer auf der Suche nach Bindung sein, nach einer Bindung, die sein Subjektsein anerkennt, außerhalb einer Instrumentalisierung in die Wünsche und Bedürfnisse der anderen. Er wird in Rollen schlüpfen, welche ihm einen vermeintlichen Ausweg aus der Einsamkeit versprechen, mit welchen er seinem Auftrag, die Erwartungen des anderen zu erfüllen und dennoch nicht zu verschwinden darin, gerecht werden kann.

**** Anerkennung einer Rolle, nicht des Individuums
:PROPERTIES:
:CUSTOM_ID: anerkennung-einer-rolle-nicht-des-individuums
:END:
Rollen, die eine große gesellschaftliche Akzeptanz haben, äußern sich bei uns in den Superlativen: Bester zu sein, Berühmteste zu sein, Reichster zu sein, Mächtigste zu sein. Die Anerkennung wird hier nicht ausbleiben, ja, die wird gewiss sein mit diesen Attributen. Die Anerkennung einer Rolle gleitet jedoch an der Anerkennung als Subjekt vorbei. Narziss bleibt einsam zurück und zusammen mit der Angst wird er weiterhin versuchen, in den Superlativen mitzuspielen, sich diesen Platz zu sichern. Es ist sein Versuch, der Bindungslosigkeit zu entkommen. Damit wird er -- vielleicht unwissentlich -- die bestehenden Machtverhältnisse tradieren, die sich seiner als autonomes und eigenständig denkendes und handelndes Subjekt entledigen und in den Dienst eines anderen Narrativ führen, dessen Erwartungen und Bedürfnisse nun zu erfüllen sind.

Wenn Narzisse nun auf eine Gesellschaft treffen, die gerade ihre Merkmale benötigt, um die Herrschaftsverhältnisse und deren Intensionen zu sichern oder gar zu konsolidieren, dann werden sie sich in diesen Strukturen einnisten und sich darin ein Fortkommen ermöglichen können.

Der deutsche Historiker Eduard Fuchs (1870-1940) rollt in Band 3 seiner illustrierten Sittengeschichte die Epoche des Absolutismus in Frankreich auf, er nennt sie 'Die galante Zeit' -- also die Zeit unter Ludwig XIII. bis zur Französischen Revolution und der Hinrichtung von Ludwig XVI. Diese Zeit darf guten Gewissens als eine narzisstische bezeichnet werden. Er schreibt: „Weit sind die Hallen, unermesslich die Säle und Galerien. Alle Wände sind von der Decke bis zum Fußboden Kristall und blenden mit ihren Spiegelreihen. Die Repräsentation, die Pose fordert den Spiegel.“ Und dann den gewichtigen Satz:

#+begin_quote
„Die historische Situation gebiert die fürstliche Selbstherrlichkeit, genau wie sie sie korrigiert, und nicht die Person formt das Schema ihrer Zeit.“

#+end_quote

Hierzu sei angemerkt, dass sich beide bedingen, beziehungsweise die Frage nach dem Anfang müßig ist und nur dazu dienen mag, Sündenböcke an den Pranger zu stellen, nicht zuletzt, um sich der eigenen Verantwortung zu entziehen. Zur Illustration dieser Aussage erwähnt Fuchs die finanziellen Ausgaben von Marie Antoinette für ihre engsten Freundinnen und kommentiert bissig, es sei rentabel gewesen, zu den direkten Freunden der Herrscherfamilie zu zählen. „Die Königstreue war darum häufig der unverhüllte Ausfluss der Furcht, von der wohlgefüllten Staatskrippe wieder vertrieben zu werden.“ Der König und die Königin brauchen ihre Entourage, um ihre Macht zu erhalten, genauso wie der Hofstaat den König und die Königin. Der Diener bezeugt den Mächtigen.

Warum also sollte der Sonnenkönig Ludwig XIV. sich nicht mit seiner Rolle identifizieren, wenn er laut Eduard Fuchs in der Kathedrale von Versailles als Einziger den Priester und den Altar sehen durfte und die Sitzordnung so angelegt war, dass alle adligen Höflinge während der Messe ihn anzuschauen, ihn anzubeten hatten? Beschert ihm das nicht Macht, Ansehen und Beziehungen, die sein verkümmertes Ich verdecken? Fuchs schreibt unmissverständlich: „Und Ludwig war, wie wir bereits wissen, ein kompletter Strohkopf, der nicht einmal lesen und schreiben konnte.“

Dass Adelstitel vererbbar waren und immer noch sind, ist angesichts der damit verbundenen Privilegien verständlich. Diese sichern die gesellschaftliche Rolle und damit eine Machtposition. So erhält sich der Machtdiskurs, so erhalten sich die Rollen, die in Demokratien nicht mehr vom Adel oder Klerus tradiert werden, sondern von globalen Unternehmen, Institutionen und Verwaltungen mit ihren Führern und Führerinnen. Die Rollen bleiben also dieselben, sie werden einfach anders in Szene gesetzt, mit anderen Kostümen und einem anderen Bühnenbild.

* [[https://multipolar-magazin.de/artikel/narziss-und-narzissmus][Narziss und Narzissmus -]] :website:
:PROPERTIES:
:CREATED: [2024-02-28 Mi 09:45]
:SOURCE: https://multipolar-magazin.de/artikel/narziss-und-narzissmus
:END:


** Narziss und Narzissmus
:PROPERTIES:
:CUSTOM_ID: narziss-und-narzissmus
:END:

Narzissmus gilt als Krankhaftigkeit eines Einzelnen -- ein Unheil, das jedermann in Beziehungen, Wirtschaft und Politik zu spüren bekommt. Eine narzisstische Aufblähung ist jedoch der Versuch, mittels einer Rolle zu gesellschaftlicher Anerkennung und Bedeutung zu kommen. Diese Rolle ist ein Kompromiss zwischen dem Wunsch, als eigenständiger Mensch anerkannt zu werden und den Erwartungen, die in einer auf Herrschaft gründenden Gesellschaft an den Einzelnen gestellt werden. Die Pathologisierung des Einzelnen behindert die Erkenntnis, dass der Diener den Mächtigen bezeugt.

[[https://multipolar-magazin.de/autorenarchiv?autor=Jeannette%20Fischer][JEANNETTE FISCHER]], 27. Februar 2024, [[https://multipolar-magazin.de/artikel/narziss-und-narzissmus#diskussion][0 Kommentare]], [[https://multipolar-magazin.de/media/pdf/narziss-und-narzissmus.pdf][PDF]]

Die Figur des Narziss tauchte ursprünglich in der griechischen Mythologie auf und wurde vom römischen Dichter Publius Ovidius Naso (43 v. Chr. Bis 17 n. Chr.), kurz Ovid, im dritten Buch seiner Metamorphosen ausführlich beschrieben, eingebettet in eine wortgewaltige Poesie. Es ist der Jüngling, der im Teich sein Spiegelbild sieht und sich in dieses verliebt. Er kann es jedoch weder berühren noch küssen, weil sein Spiegelbild sich ihm zwar auch nähert, im Moment der Berührung jedoch entzieht. Das Begehren ist also gegenseitig.

Dass das Begehren des Narziss -- wie von Ovid beschrieben -- ihm selber gilt, wird heutzutage von vielen Menschen genüsslich zitiert und bissig kommentiert; der Narziss ist zum Objekt einer permanenten Stigmatisierung geworden. Die Rede ist von einem narzisstischen Zeitalter, in dem führende Politiker und Politikerinnen, wichtige Player in Wirtschaft und Gesellschaft dank dieser Eigenschaft zu Macht gelangen -- oder erst dank ihrer so genannten narzisstischen Veranlagung in solche Positionen hineingewählt beziehungsweise hineinbefördert werden.

**** Moderne Bösewichte
:PROPERTIES:
:CUSTOM_ID: moderne-bösewichte
:END:
Ein Narzisst, so der gängige Kanon, ist ein Selbstverliebter und ein tendenziell rücksichtsloser Mensch, weil er das Gegenüber verkennt, es in seiner Eigenheit und Eigenständigkeit nicht wahrnimmt, missachtet und für seine eigenen Zwecke missbraucht, sodass andere Menschen für ihn nur interessant sind, wenn er sie instrumentalisieren kann. Narzissten sind die modernen Bösewichte.

Jahrzehnte vor Ovid ist von dem griechischen Dichter Parthenios von Nikaia, der 73 v. Chr. als Kriegsgefangener nach Rom kam, eine Narziss-Erzählung überliefert, die aufzeigt, dass sich der junge Narziss dem Dasein als Geliebter erwachsener Männer -- eine nicht unübliche Praxis im alten Athen -- verweigert hat. Bei Ovid heißt es (zirka 1 bis 8 n. Chr.):

#+begin_quote
„So hatte Narziss diese (die Nymphe Echo, Anm. JF) enttäuscht, so auch andere Wasser- und Bergnymphen, so vorher den Umgang mit Männern gemieden. Daher hatte einer von ihnen, der verschmäht worden war, die Hände zum Äther erhoben und gesagt: 'So soll es auch ihm in der Liebe ergehen, so soll auch er, was er liebt, nicht bekommen.' Sprach's, und Rhamnusia (Göttin des Zornes, Anm. JF) gewährte die gerechte Bitte.“

#+end_quote

Es wäre also seine Pflicht gewesen, das Begehren der Nymphen und Männer zu befriedigen. Diese Strafe nun, keinen Menschen für das eigene Begehren zu finden, ist in ihrer Grausamkeit unübertroffen. Für Narziss bedeutet sie, dass er in sich selber eingeschlossen bleibt, dass er nur noch sich selber als Gegenüber hat, dass er -- so Ovid -- später an seinem eigenen Feuer, an seiner eigenen Libido sterben wird:

#+begin_quote
„Wie gelbes Wachs an einem schwachen Feuer und wie der morgendliche Rauhreif an der warmen Sonne schmilzt, so schwindet er dahin, von Liebe ausgezehrt und langsam nagt an ihm ein verborgenes Feuer.“

#+end_quote

Setzt man eine Bindungsstruktur voraus, eine intersubjektive, in der der eine Mensch den anderen als Nicht-Ich, als different, als anders anerkennt, dann zeigt dieses Epos eine Struktur des Gefälles: Der eine hat dem anderen seine Wünsche zu erfüllen, ungeachtet seiner eigenen und tut er das nicht, wird er bestraft, in dem er der Bindung zu missen hat. Und ohne Bindung werden wir verrückt oder wir sterben, dies hat Ovid zu recht erkannt.

Einem in sich eingeschlossenen Menschen -- wie hier Narziss -- wird die Angst im Seitenwagen ein unbeirrter Begleiter sein, er wird immer auf der Suche nach Bindung sein, nach einer Bindung, die sein Subjektsein anerkennt, außerhalb einer Instrumentalisierung in die Wünsche und Bedürfnisse der anderen. Er wird in Rollen schlüpfen, welche ihm einen vermeintlichen Ausweg aus der Einsamkeit versprechen, mit welchen er seinem Auftrag, die Erwartungen des anderen zu erfüllen und dennoch nicht zu verschwinden darin, gerecht werden kann.

**** Anerkennung einer Rolle, nicht des Individuums
:PROPERTIES:
:CUSTOM_ID: anerkennung-einer-rolle-nicht-des-individuums
:END:
Rollen, die eine große gesellschaftliche Akzeptanz haben, äußern sich bei uns in den Superlativen: Bester zu sein, Berühmteste zu sein, Reichster zu sein, Mächtigste zu sein. Die Anerkennung wird hier nicht ausbleiben, ja, die wird gewiss sein mit diesen Attributen. Die Anerkennung einer Rolle gleitet jedoch an der Anerkennung als Subjekt vorbei. Narziss bleibt einsam zurück und zusammen mit der Angst wird er weiterhin versuchen, in den Superlativen mitzuspielen, sich diesen Platz zu sichern. Es ist sein Versuch, der Bindungslosigkeit zu entkommen. Damit wird er -- vielleicht unwissentlich -- die bestehenden Machtverhältnisse tradieren, die sich seiner als autonomes und eigenständig denkendes und handelndes Subjekt entledigen und in den Dienst eines anderen Narrativ führen, dessen Erwartungen und Bedürfnisse nun zu erfüllen sind.

Wenn Narzisse nun auf eine Gesellschaft treffen, die gerade ihre Merkmale benötigt, um die Herrschaftsverhältnisse und deren Intensionen zu sichern oder gar zu konsolidieren, dann werden sie sich in diesen Strukturen einnisten und sich darin ein Fortkommen ermöglichen können.

Der deutsche Historiker Eduard Fuchs (1870-1940) rollt in Band 3 seiner illustrierten Sittengeschichte die Epoche des Absolutismus in Frankreich auf, er nennt sie 'Die galante Zeit' -- also die Zeit unter Ludwig XIII. bis zur Französischen Revolution und der Hinrichtung von Ludwig XVI. Diese Zeit darf guten Gewissens als eine narzisstische bezeichnet werden. Er schreibt: „Weit sind die Hallen, unermesslich die Säle und Galerien. Alle Wände sind von der Decke bis zum Fußboden Kristall und blenden mit ihren Spiegelreihen. Die Repräsentation, die Pose fordert den Spiegel.“ Und dann den gewichtigen Satz:

#+begin_quote
„Die historische Situation gebiert die fürstliche Selbstherrlichkeit, genau wie sie sie korrigiert, und nicht die Person formt das Schema ihrer Zeit.“

#+end_quote

Hierzu sei angemerkt, dass sich beide bedingen, beziehungsweise die Frage nach dem Anfang müßig ist und nur dazu dienen mag, Sündenböcke an den Pranger zu stellen, nicht zuletzt, um sich der eigenen Verantwortung zu entziehen. Zur Illustration dieser Aussage erwähnt Fuchs die finanziellen Ausgaben von Marie Antoinette für ihre engsten Freundinnen und kommentiert bissig, es sei rentabel gewesen, zu den direkten Freunden der Herrscherfamilie zu zählen. „Die Königstreue war darum häufig der unverhüllte Ausfluss der Furcht, von der wohlgefüllten Staatskrippe wieder vertrieben zu werden.“ Der König und die Königin brauchen ihre Entourage, um ihre Macht zu erhalten, genauso wie der Hofstaat den König und die Königin. Der Diener bezeugt den Mächtigen.

Warum also sollte der Sonnenkönig Ludwig XIV. sich nicht mit seiner Rolle identifizieren, wenn er laut Eduard Fuchs in der Kathedrale von Versailles als Einziger den Priester und den Altar sehen durfte und die Sitzordnung so angelegt war, dass alle adligen Höflinge während der Messe ihn anzuschauen, ihn anzubeten hatten? Beschert ihm das nicht Macht, Ansehen und Beziehungen, die sein verkümmertes Ich verdecken? Fuchs schreibt unmissverständlich: „Und Ludwig war, wie wir bereits wissen, ein kompletter Strohkopf, der nicht einmal lesen und schreiben konnte.“

Dass Adelstitel vererbbar waren und immer noch sind, ist angesichts der damit verbundenen Privilegien verständlich. Diese sichern die gesellschaftliche Rolle und damit eine Machtposition. So erhält sich der Machtdiskurs, so erhalten sich die Rollen, die in Demokratien nicht mehr vom Adel oder Klerus tradiert werden, sondern von globalen Unternehmen, Institutionen und Verwaltungen mit ihren Führern und Führerinnen. Die Rollen bleiben also dieselben, sie werden einfach anders in Szene gesetzt, mit anderen Kostümen und einem anderen Bühnenbild.

* [[https://apolut.net/im-elysee-wird-zu-heiss-geduscht/][Im Élysée wird zu heiß geduscht - apolut.net]] :website:
:PROPERTIES:
:CREATED: [2024-02-28 Mi 09:54]
:SOURCE: https://apolut.net/im-elysee-wird-zu-heiss-geduscht/
:END:
Frankreich bleibt sich treu. Einmal Beresina, immer Beresina; einmal Versailles, immer Versailles. Anders sind die gestrigen Aussagen des französischen Präsidenten zum Ukraine-Krieg nicht zu werten. Sie scheinen typisch zu sein, was die Methode anbetrifft. Erinnern wir uns an die nach Paris eingeladene Libyen-Konferenz. Dort sollte über ein Vorgehen gegen dieses nordafrikanische Land erst beraten werden. Die eingeladenen Staatschefs waren noch nicht gelandet, als die französischen Bomber gen Tripolis flogen.

Jetzt sind es in Napoleon-Manier die europäischen Bodentruppen, die in den Krieg eingreifen sollen. Wie bei Napoleon und Hitler, als die Deutschen verbluten durften, von anderen Völkern ganz zu schweigen. Auf die Europäer und damit auch auf die Deutschen kommt die Frage zu, die bekannt klingt:

#+begin_quote
„Wollt ihr den französischen Krieg in Europa?”

#+end_quote

Joe Biden kann sich freuen. Es findet sich wieder jemand, der in die vom Kongress geschlagene Bresche springt. Nur ja kein Kriegsende und kein Friede, bedingungslose Kapitulation für Moskau.

* [[https://erzabtei-beuron.de/schott/schott_anz/index.html][Tagesimpuls - Erzabtei Beuron]] :website:
:PROPERTIES:
:CREATED: [2024-02-29 Do 08:39]
:SOURCE: https://erzabtei-beuron.de/schott/schott_anz/index.html
:END:

„Für uns Menschen /ist die Lebensspanne zwischen Geburt und Tod der Zeitraum, in dem wir den Anruf Gottes hören und uns entscheiden müssen. Dieser Zeitraum ist die begrenzte Frist, innerhalb deren alles passieren muss, worauf es ankommt. Er ist die begrenzte Frist, in der wir - wie die fünf Brüder des Gleichnisses - am Kreuzweg stehen und wo wir alles gewinnen und alles verlieren können. Wir haben nicht die Verheißung, dass diese Frist verlängert werden könne und dass wir sie darum vertrödeln dürften, dass es also noch so etwas wie Nachholkurse im Jenseits gäbe./

/Der reiche Mann hat gewusst, was er tat, als er aus der Hölle heraus Abraham anflehte, seinen fünf Brüdern zu sagen: ,Eure Uhr läuft ab.‘ Es gibt keinen anderen Weg zu Gott, als dass wir seinen Ruf ernst nehmen: ,Heute (heute!), wo ihr meine Stimme hört, verstockt eure Herzen nicht!‘“ (Helmut Thielicke)./

* org-protocol.el – Intercept calls from emacsclient to trigger custom actions
:PROPERTIES:
:CREATED: [2024-05-09 Do 17:41]
:SOURCE: https://orgmode.org/worg/org-contrib/org-protocol.html
:END:

* org-protocol.el – Intercept calls from emacsclient to trigger custom actions
:PROPERTIES:
:CREATED: [2024-05-09 Do 17:42]
:SOURCE: https://orgmode.org/worg/org-contrib/org-protocol.html
:END:
GNU/Linux setup

Most common desktop environments (Gnome, KDE et al) comply with the XDG Desktop Entry Specification. This means setting up emacsclient as the org-protocol handler using a .desktop file can be regarded as a, in most cases, standard way to set this up in most common desktop environments. 

* alphapapa/org-protocol-capture-html: Capture HTML from the browser selection into Emacs as org-mode content
:PROPERTIES:
:CREATED: [2024-05-09 Do 17:47]
:SOURCE: https://github.com/alphapapa/org-protocol-capture-html
:END:

* Chinas Präsident Xi Jinping zu Besuch in Ungarn nach Serbien und Frankreich
:PROPERTIES:
:CREATED: [2024-05-09 Do 17:48]
:SOURCE: https://tkp.at/2024/05/09/chinas-praesident-xi-jinping-zu-besuch-in-ungarn-nach-serbien-und-frankreich/
:END:
** Chinas Präsident Xi Jinping zu Besuch in Ungarn nach Serbien und Frankreich
:PROPERTIES:
:CUSTOM_ID: chinas-präsident-xi-jinping-zu-besuch-in-ungarn-nach-serbien-und-frankreich
:CLASS: title-heading-left fusion-responsive-typography-calculated
:style: margin:0;--fontSize:38;line-height:1.15;
:END:

9. Mai 2024von [[https://tkp.at/autoren/peter-f-mayer/][Dr. Peter F. Mayer]]3,8 Minuten Lesezeit

***** China hat wieder ein Statement in Richtung Europa abgegeben. Präsident Xi Jinping besuchte Frankreich, Serbien und nun Ungarn. Er traf am Abend des 8. Mai in Budapest ein und wurde am Flughafen von Viktor Orbán empfangen. Der Besuch dient auch dazu, den 75. Jahrestag der diplomatischen Beziehungen zwischen Budapest und Peking zu begehen
:PROPERTIES:
:CUSTOM_ID: china-hat-wieder-ein-statement-in-richtung-europa-abgegeben.-präsident-xi-jinping-besuchte-frankreich-serbien-und-nun-ungarn.-er-traf-am-abend-des-8.-mai-in-budapest-ein-und-wurde-am-flughafen-von-viktor-orbán-empfangen.-der-besuch-dient-auch-dazu-den-75.-jahrestag-der-diplomatischen-beziehungen-zwischen-budapest-und-peking-zu-begehen
:CLASS: fusion-responsive-typography-calculated
:lang: de-AT
:style: --fontSize: 19; line-height: 1.55; --minFontSize: 19;
:fontsize: 19
:lineheight: 29.45px
:END:

* „Die zweite Aufklärung“ -
:PROPERTIES:
:CREATED: [2024-05-09 Do 17:50]
:SOURCE: https://multipolar-magazin.de/artikel/die-zweite-aufklaerung
:END:
** „Die zweite Aufklärung“
:PROPERTIES:
:CUSTOM_ID: die-zweite-aufklärung
:END:

Als „Brücke zum 18. Jahrhundert“ betitelte der 2003 verstorbene amerikanische Kommunikationswissenschaftler Neil Postman sein letztes Buch (deutsch: „Die zweite Aufklärung“). Er erläuterte darin, inwiefern an Ideen aus jener Zeit wieder angeknüpft werden könnte. Multipolar erinnert daran.

[[https://multipolar-magazin.de/autorenarchiv?autor=Achim%20Wittenberg][ACHIM WITTENBERG]], 8. Mai 2024, [[https://multipolar-magazin.de/artikel/die-zweite-aufklaerung#diskussion][0 Kommentare]], [[https://multipolar-magazin.de/media/pdf/die-zweite-aufklaerung.pdf][PDF]]

Im Vorwort formuliert Postman eine kurze Definition des Zeitalters der Aufklärung: „Eine philosophische Bewegung des achtzehnten Jahrhunderts, die sich vom Standpunkt des Rationalismus aus vornehmlich mit der Kritik bislang gültiger Lehren und Institutionen beschäftigte.“ Er schildert zur Illustration eine Anekdote aus dem New York des Jahres 1735: Ein Zeitungsverleger wird vor Gericht der Verleumdung (des Königs/der Regierung?) beschuldigt, da er kritisch auf Missstände hingewiesen hatte. Da die Missstände -- auch den Geschworenen -- offenkundig sind, wird er freigesprochen -- anders als dies in früheren Zeiten der Fall gewesen wäre, wo auch berechtigte Kritik an der Obrigkeit geahndet wurde.

**** Erfindungen und Fortschrittsglauben
:PROPERTIES:
:CUSTOM_ID: erfindungen-und-fortschrittsglauben
:END:
Die Aufklärung sieht Postman als Zeit, in der der Fortschrittsglauben als Geschichts- und Naturgesetz erfunden wurde. Postman sieht diesen Glauben durch das 20. Jahrhundert allerdings beendet: Vernünftige Menschen würden erkennen, dass Fortschritt oder Niedergang von den Handlungen der Menschen abhingen. Dennoch würden viele weiter von einem ständigen Fortschritt ausgehen, der allein dadurch begründet sei, dass es technische Innovationen gebe. Diese Menschen glaubten, dass technischer Fortschritt automatisch auch Fortschritt für die Menschheit bedeute. Postman vermutet dahinter die Angst, anzuerkennen, dass die Menschen selbst für das Schicksal Verantwortung tragen -- und es eben auch verschlechtern können.

Das 19. Jahrhundert sei vom Fortschrittsglauben geprägt gewesen. Geologie und Biologie schienen dies mit der Evolutionslehre zu bestätigen: Karl Marx bat Charles Darwin um ein Vorwort zu „Das Kapital“ -- erfolglos. Das 19. Jahrhundert brachte die Erfindung der Erfindung. Die Menschen lernten damals, wie man Dinge erfindet -- die Frage nach dem Warum verlor an Bedeutung. Der Gedanke, dass man etwas tun solle, wenn man es tun könnte, sei im 19. Jahrhundert geboren worden. Das 20. Jahrhundert bringe aber schon zu Beginn das Ende des allgemein anerkannten Fortschrittsglaubens (Lewis Mumford 1923, William Ralph Inge 1920). Postman vermutet das Blutbad des 1. Weltkrieges, die Gedanken von Nietzsche und Freud oder die Vorahnung von Kommunismus und Faschismus als Ursache. Es sei unübersehbar geworden, dass Fortschritt nicht naturgesetzlich unausweichlich, sondern, wenn, dann nur als bewusste Entscheidung von Menschen möglich ist.

Es bleibe jedoch bei vielen Menschen die Vorstellung, „daß technologische Innnovation ein Synonym für moralischen, gesellschaftlichen und seelischen Fortschritt sei. Es ist, als wäre die Frage, was uns zu besseren Menschen macht, zu schwer, zu komplex -- und sogar zu absurd, als daß wir ihr noch nachgehen können.“ Im Geiste des 18. Jahrhunderts, also der Aufklärung, sind laut Postmans jedoch folgende Anfragen im Voraus an jegliche technische Innovation zu stellen -- die von den verantwortlichen Unternehmern in ihrer Fixierung auf Gewinn jedoch nicht gestellt würden: „Wir dürfen nicht vergessen, daß unsere bedeutendsten Radikalen immer unsere Unternehmer waren.“ (S. 65):

- Die Lösung zu welchem Problem ist diese Innovation?

- Wessen Problem ist das?

- Für /wen/ (Menschen und Institutionen) bedeutet die Einführung dieser Innovation /welche/ Nachteile (und überwiegen diese die Vorteile)?

- Welche Art Leute und Institutionen könnten in der Folge technologischen Wandels zu besonderer wirtschaftlicher und politischer Macht gelangen?

- Welche sprachlichen Veränderungen werden durch neue Technologien erzwungen, was wird durch derlei Veränderungen gewonnen und was verloren?

Die letzte Frage illustriert Postman mit der Analyse der Bedeutung des Wortes „Gemeinschaft“, das früher ein Zusammenleben von Menschen bezeichnet hat, das durch Verhandlung und „gegenseitiges Entgegenkommen“ (Tocqueville) ermöglicht wurde. Heute, im Internet bezeichne „Gemeinschaft“ („community“) hingegen nur noch eine Gruppe von Menschen mit gleichen Interessen.

* „Die zweite Aufklärung“ -
:PROPERTIES:
:CREATED: [2024-05-09 Do 17:54]
:SOURCE: https://multipolar-magazin.de/artikel/die-zweite-aufklaerung
:END:
Postman unterscheidet mit Blick auf das 18. Jahrhundert zwischen Philosophen, die gleichsam als Einsiedler auf der Suche nach ewigen Wahrheiten waren -- wie Hume oder Kant -- und /philosophes/ (wie Diderot, Voltaire, Rousseau und fast allen amerikanischen Vertretern der Aufklärung), die von einer gemeinsamen Erzählung ausgehend den gesellschaftlichen und politischen Wandel hin zu Menschenrechten und einer republikanischen Ordnung vorantrieben. Die geistesgeschichtlichen Wurzeln dieser von den /philosophes/ geglaubten Erzählung sei zum einen der Glaube an einen -- von diesen meist deistisch verstandenen -- Schöpfergott (der etwa in der amerikanischen Unabhängigkeitserklärung als Ursache für Menschenrechte und Vorsehung fungiert) und zum anderen die griechische und vor allem die römische Antike. Die Machtkompromisse der römischen Republik würden der direkten Demokratie Griechenlands vorgezogen. Postmans Version dieser, seiner Ansicht nach noch heute glaubenswerten, Erzählung (S. 134f.):

#+begin_quote
„[Die /philosophes/] schrieben an einer Erzählung, deren Zentrum Skepsis, Vernunft und das Naturrecht ausmachten, denen sie noch die Kraft eines göttlichen Prinzips hinzufügten. Auf das Risiko hin, ihre Erzählung gewaltig zu vereinfachen (und vielleicht einige wichtige Einzelheiten auszulassen), lege ich im folgenden meine Version dieser Erzählung vor:

#+end_quote

#+begin_quote
Das Universum wurde von einem gütigen und einzigen Gott erschaffen, der den Menschen den Verstand und die Inspiration gab, seine Schöpfung (in Grenzen) zu verstehen, sowie das Recht, frei zu sein, menschliche Autoritäten in Frage zu stellen und sich in dem von Gott und Natur gegebenen Rahmen selbst zu regieren. Sinn der Menschheit ist es, Gottes Schöpfung zu achten und ihrer Ehrfurcht gebietenden Präsenz mit Demut zu begegnen sowie mit Aufrichtigkeit und Mitgefühl gegenüber anderen nach Wegen zu Glück und Frieden zu suchen. (...)

#+end_quote

#+begin_quote
Sie begriffen, daß ein vulgärer Relativismus, also der Gedanke, daß Werte nur historische Vorurteile sind, zu Hoffnungslosigkeit und Untätigkeit führen müßte.“

#+end_quote

Postman stellt dieser Erzählung mit Bezug auf Bertrand Russell eine „naturwissenschaftliche“ gegenüber beziehungsweise zur Seite:


* Der Lehrer-Coach - Respekt im Unterricht
:PROPERTIES:
:CREATED: [2024-05-28 Di 09:34]
:SOURCE: https://www.guterunterricht.de/respekt
:END:
Respekt erlangen

Das Problem:

 

„Ich kann mich manchmal nicht durchsetzen, es dauert viel zu lange, bis die Schüler zuhören., Schüler begegnen mir und Mitschülern respektlos, distanzlos, sie gehorchen nicht, reagieren nicht oder zu langsam auf Anweisungen und Aufträge …“

Natürlich gab und gibt es Lehrer, die sich im Unterricht „Respekt“ verschaffen, indem sie ein Klima der Angst und Unterdrückung erzeugen, wie z.B. in dem in der Presse ausführlich berichteten Fall einer Realschule, in der Sechsen wie am Fließband bereits für das geringste Fehlverhalten verteilt wurden.

Wenn Schüler dann spuren, ist das allerdings kein Ausdruck von Respekt. Aber: Schüler wollen Lehrer, vor denen sie wirklich Respekt haben. Das meinen Schüler auch, wenn sie sich „strenge“ Lehrer wünschen! Keine (letztlich hilflosen) Tyrannen, Zyniker, Brüller oder Unterdrücker, sondern Persönlichkeiten, vor denen man wirklich Respekt haben muss und kann.

Was können Lehrer tun, um echten Respekt zu erhalten und um eine Atmosphäre gegenseitigen Respekts im Klassenraum herzustellen?

* „Die zweite Aufklärung“ -
:PROPERTIES:
:CREATED: [2024-06-12 Mi 13:01]
:SOURCE: https://multipolar-magazin.de/artikel/die-zweite-aufklaerung
:END:

Juhuu, das klappt mit dem ~Nyxt-Browser~; es ist nur komisch, dass die Tastenkombination ~C-c o c~ nicht funktioniert.
