#+title:      Gespräch Dir VS Grödig
#+date:       [2023-03-15 Mi 07:42]
#+filetags:   :leopold:memo:
#+identifier: 20230315T074215

Leopold in die Vorschule?

Tel.: +43 6246 7226310

* Meine Gedanken
Hab mit vielen Menschen, die Leopold kennen, gesprochen:
- niemand versteht das (wir, Oma - Lehrerin, Kindergarten-Gruppen-Leiterin Marion)
- Leopold kennt das Alphabeth, kann seinen Namen schreiben, schreibt für Mama die Einkaufsliste
- hat letzten Sonntag von sich aus verstanden, dass Wörter aus Silben bestehen und dies wichtig fürs Lesen ist.
- Vorgestern hat er auf dem Heimweg vom KG auf Englisch bis 100 gezählt (2x)
- er will lesen, schreiben und rechnen lernen.
- Er ist wie eine Flamme, wenn man sie füttert, brennt sie heller. Vorschule würde diese Flamme ersticken. Das wäre für ihn eine Riesenenttäuschung. 
- Der Test war nach dem Mittagessen, wo er einfach immer müde ist und Ruhe will und braucht. Würden sie den Test am Vormittag wiederholen, wäre das Ergenis sicher ein anderes.


* Memo
VS war sich nach Test unsicher, da Leopold eher in der Aufmerksamkeit etwas "schwach" war. In den einzelnen Bereichen wie Sprache, Mathematik, etc war Leopold immer in der Mitte, oder darüber. In Mathematik sogar weit darüber (maximal).

Nach unserem Gespräch haben wir uns darauf geeinigt, dass Leopold in die erste Klasse eingeschrieben wird.
