#+title:      [SW33] Gottes Gegenwart feiern / Übungsteil
#+date:       [2023-06-19 Mo 14:52]
#+filetags:   :01:sw33:
#+identifier: 20230619T145222


* Kompetenzbeschreibung
[[#B4]] Gelehrte und gelebte Bezugsreligion: Kirchliche Grundvollzüge kennen und religiös-spirituelle Ausdrucksformen gestalten können
[[#B4_KB2]] Die Schülerinnen und Schüler können Taufe und Eucharistie als Ausdruck der Zugehörigkeit zur kirchlichen Gemeinschaft verstehen.

* AB / UH 
[[#B4_UH2]] Jesu Mahlgemeinschaften und die Feier der Eucharistie


* Wiederholung


* Erarbeitung

** Eucharistiefeier
RB Seite 78 + Übungsteil

** Lösungen zu den Arbeitsaufträgen
a. Alle einzusetzenden Wörter im Messablauf sind hier der Reihe nach angegeben. Alle fett gedruckten Wörter sind bereits ausgefüllte Felder. Die in Klammer gesetzten Sätze sind die dazu gehörenden Antworten, die in den Sprechblasen ausgefüllt werden müssen.

*Einzug*

Eröffnung (Und mit deinem Geiste!)

Kyrie (Herr, erbarme dich!)

*Gloria*

Tagesgebet (Amen)

Lesungen (Dank sei Gott!)

Evangelium (Ehre sei dir oh Herr) (Lob sei dir Christus!)

*Glaubensbekenntnis*

Fürbitten

Gabenbereitung

*Hochgebet* (Wir haben sie beim Herrn) (Das ist würdig und recht!)

*Wandlung* (esset – Leib – trinket – Vergebung)

Vaterunser

Friedensgruß (Und mit deinem Geiste!)

Agnus Dei (Seht das Lamm Gottes, das hinwegnimmt die Sünde der Welt!)

Kommunion (Amen!)

*Schlussgebet*

Segen (Dank, sei Gott dem Herrn!)


b. Ergänzung der Gebete:

- Reich, Wille, Erden
- Angesicht, gnädig
- Gnade, Herr
- Vater, Sohn, Heiligen Geist
- Vater, Schöpfer, Himmels
- Hirt, fehlen
- unser, geheiligt, Name
- Werkzeug, Friedens, liebe, hasst

* Hefteintrag
Das nehme ich mit:

1 Dieser Kompetenzcheck zielt auf die Kompetenzbeschreibung "Die Schülerinnen und Schüler kennen Reichtum und Vielfalt spiritueller und liturgischer Ausdrucksformen und können sie in ihrer Bedeutung nachvollziehen und gestalten." des Lehrplans ab. Die Bearbeitung / Beantwortung sollte vor allem darauf abzielen, die verschiedenen Ausdruckformen von Gebeten verstehen und deuten zu können.

Zu diesen Ausdrucksformen gehören die Grundgebete, Kurzformeln des Glaubens, Stille und Meditation, Psalmen und Lieder, sowie körperliche Ausdrucksformen des Gebets.


2 Dieser Kompetenzcheck zielt auf die Kompetenzbeschreibung "Die Schülerinnen und Schüler können Taufe und Eucharistie als Ausdruck der Zugehörigkeit zur kirchlichen Gemeinschaft verstehen." im Lehrplan ab. Eine mögliche Bearbeitung/Beantwortung fassen die Ergebnisse der Unterkapitel 4.10, 4.11 sowie 13 zusammen.

Die Antworten sollten die im Lehrplan genannten Faktoren Zeichen und Formen von Zugehörigkeit sowie der Mahlgemeinschaft Jesu und die Feier der Eucharistie reflektieren und miteinander in Beziehung setzen Der Kompetenzcheck kann auch durch "Religion für mich" dem Ablauf der Messe ergänzt werden.


3 Dieser Kompetenzcheck zielt auf den Anwendungsbereich – das Glaubensbekenntnis, aus der Kompetenzbeschreibung "Die Schülerinnen und Schüler können Taufe und Eucharistie als Ausdruck der Zugehörigkeit zur kirchlichen Gemeinschaft verstehen" im Lehrplan ab. Eine mögliche Bearbeitung/Beantwortung kann durch die in dem Kapitel vorgestellte Methode "Verstehen: Glaubensaussagen deuten" bearbeitet werden.
