#+title:      Was ist der Mensch noch, dass du seiner gedenkst?
#+date:       [2023-01-24 Di 21:29]
#+filetags:   :science:theology:
#+identifier: 20230124T212901

Der Jahreswechsel wird häufig von einer Rückschau auf das vergangene Jahr und Vorsätzen begleitet. Die Frage nach den guten Vorsätzen, könnte auch lauten: „Wer bin ich und wie möchte ich sein?“ Stärker verallgemeinert führt uns diese Reflexion zur Frage nach dem Wesen des Menschen überhaupt. Weder auf der Ebene des Individuums noch auf der der Spezies lassen sich Antworten ohne Relationen und Kontexte finden. Denn eigentlich müsste man die obigen Fragen präzisieren und fragen, wer man für andere ist und sein möchte und welches Verhältnis der Mensch zu seinen Mitgeschöpfen, zur gesamten Schöpfung und zu Gott hat.

Beide Schöpfungsmythen am Anfang der Bibel setzen den Menschen ins Verhältnis zur damals bekannten Ordnung und nutzen zwangsläufig und selbstverständlich das damalige Wissen über den Kosmos. Dass der Mensch nun Krone und Mittelpunkt der Schöpfung sei, ist eine häufig anzutreffende Verkürzung, welche das biblische Menschenbild nur unzureichend beschreiben kann. Der hier vorgestellte Videoclip „Eine überschätzte Spezies“ zeichnet ein völlig anderes Bild, wenn er den Menschen auf Basis unseres heutigen Wissens einzuordnen versucht. Dabei machen die Autoren eigentlich nichts anderes als die Verfasser der biblischen Überlieferung und es stellt sich die Frage, welche Bedeutung biologisches und kosmologisches Wissen für die Beantwortung zentraler Fragen der Anthropologie eigentlich hat.

Die Frage, wie bedeutsam der Mensch als biologische Art ist, unterscheidet sich von der Frage, ob meine eigene Existenz von Bedeutung ist. Ist die Sinnfrage eine Sache des Denkens oder des Fühlens? Ermöglicht, erschwert oder behindert unser Wissen um die Beschaffenheit der Welt religiöse Sinnstiftung, ist sie davon abgekoppelt oder hat sie nicht zwingend eine vertiefte Auseinandersetzung mit allem was uns umgibt zur Voraussetzung. Und was ist der Mensch dann noch, wenn er gar nicht mehr so besonders dasteht.

Im Folgenden wird der Versuch unternommen sich dem Verhältnis zwischen belebtem sowie unbelebtem Kosmos und der Anthropologie didaktisch zu nähern.
