#+title:      Webpages
#+date:       [2023-12-18 Mo 08:15]
#+filetags:   :capture:
#+STARTUP: showall
#+identifier: 20231218T081552

* Bildung ohne Schule - 
:PROPERTIES:
:CREATED: [2024-01-05 Fr 19:30]
:SOURCE: https://multipolar-magazin.de/artikel/bildung-ohne-schule
:END:
In Deutschland gibt es Schätzungen zufolge 1.000 Freilerner – Kinder, die unter Anleitung ihrer Eltern lernen, ohne eine Schule zu besuchen. In Österreich sind es rund 150, dazu kommen dort einige Tausend sogenannte „Homeschooler“. Was steckt dahinter?

* Das Corona-Tribunal - apolut.net 
:PROPERTIES:
:CREATED: [2024-01-05 Fr 19:32]
:SOURCE: https://apolut.net/das-corona-tribunal/
:END:
War´s das? Nach drei Jahren schwerster Beschädigungen der Demokratie bis hin zur Abschaffung, der Liquidierung, des Grundgesetzes durch eine Bund-Länderkonferenz, der Malträtierung unserer Kinder durch Isolierung, Bildungskastration und Maskenquälerei – soll es das jetzt gewesen sein? Nach drei Jahren der Krankheitsdiktatur, der Mediengleichschaltung, der Zwangs-Spritzung mit einem Stoff, der bestenfalls nicht sehr schädlich ist und in vielen Fällen zum Tod geführt hat; da soll die Schwammdrüber-Zeit beginnen?

* Kathedrale von Autun – Wikipedia
:PROPERTIES:
:CREATED: [2024-01-08 Mo 08:46]
:SOURCE: [[https://de.wikipedia.org/wiki/Kathedrale_von_Autun]]
:END:
Die Kathedrale von Autun ist eine romanische Bischofskirche für das Bistum Autun in der Bourgogne-Franche-Comté. Die dreischiffige Basilika ist dem Patronat des heiligen Lazarus anvertraut. Mit reichem Fassadenschmuck markiert sie den höchsten Platz der Oberstadt von Autun. Seit 1949 trägt sie den Titel einer päpstlichen Basilica minor. Das Kulturdenkmal wurde 1840 als Monument historique klassifiziert. 

* Traum der Könige, Burgund, römische Baukunst
:PROPERTIES:
:CREATED: [2024-01-08 Mo 09:31]
:SOURCE: https://www.kunst-meditation.it/gislebertus-traum-der-konige/
:END:
Das romanische Kapitell „Traum der Könige“ in der Kathedrale von Autun in Burgund gehört zu den berühmtesten Darstellungen dieser Art. Meister Gislebertus hat es um 1220 aus Stein gemeißelt. Zu sehen sind der Engel Gabriel und die Heiligen drei Könige. Über ihnen schwebt der Stern von Bethlehem. Mit dem ausgestreckten Zeigefinger der linken Hand weist der Engel energisch auf den Stern, mit dem Zeigefinger der rechten Hand berührt er zart den Ringfinger des obersten Königs. Das Thema ist nicht der Schlaf oder der Traum der drei Könige, sondern das Erwachen aus der Dunkelheit und der Aufbruch in das Licht!

* [[https://tkp.at/2024/02/20/australien-erlaubt-gen-banane/][Australien erlaubt Gen-Banane]] :website:

[2024-02-20 Di 21:19] 

Für die Wissenschaftler ist es die erste gentechnisch veränderte Banane der Welt, die für Konsumenten zugelassen wurde.

* Australien erlaubt Gen-Banane
:PROPERTIES:
:CREATED: [2024-02-20 Di 21:19]
:SOURCE: https://tkp.at/2024/02/20/australien-erlaubt-gen-banane/
:END:
Australische Kunden werden bald gentechnische manipulierte Bananen im Supermarkt vorgesetzt bekommen. Die GMO-Banane, die gegen die sogenannte „Panama-Krankheit“ resistent sein soll, darf freigesetzt werden und wurde für den menschlichen Konsum erlaubt. Die Sorte QCAV-4 ist laut den Wissenschaftlern die „erste gentechnisch veränderte Banane der Welt und wird die erste gentechnisch veränderte Frucht sein, die von der australischen Regierung für den Anbau in Australien zugelassen wird“. Die GMO-Banane könnte langfristig die klassischen Bananen auch in Europa ablösen.

* [[https://tkp.at/2024/02/20/australien-erlaubt-gen-banane/][Australien erlaubt Gen-Banane]] :website:

[2024-02-20 Di 21:26] 

** Australien erlaubt Gen-Banane
:PROPERTIES:
:CUSTOM_ID: australien-erlaubt-gen-banane
:CLASS: title-heading-left fusion-responsive-typography-calculated
:style: margin:0;--fontSize:38;line-height:1.15;
:END:

20. Februar 2024von [[https://tkp.at/autoren/thomas-oysmueller/][Thomas Oysmüller]]2,4 Minuten Lesezeit

*Für die Wissenschaftler ist es die erste gentechnisch veränderte Banane der Welt, die für Konsumenten zugelassen wurde.*

Australische Kunden werden bald gentechnische manipulierte Bananen im Supermarkt vorgesetzt bekommen. Die GMO-Banane, die gegen die sogenannte „Panama-Krankheit“ resistent sein soll, darf freigesetzt werden und wurde für den menschlichen Konsum erlaubt. Die Sorte QCAV-4 ist laut den Wissenschaftlern die „erste gentechnisch veränderte Banane der Welt und wird die erste gentechnisch veränderte Frucht sein, die von der australischen Regierung für den Anbau in Australien zugelassen wird“. Die GMO-Banane könnte langfristig die klassischen Bananen auch in Europa ablösen.

<<taboola-mid-article-thumbnails>>

**** Gen-Zeitalter
:PROPERTIES:
:CUSTOM_ID: gen-zeitalter
:CLASS: fusion-responsive-typography-calculated
:style: --fontSize: 20; line-height: 1.2;
:fontsize: 20
:lineheight: 24px
:END:
Die Banane ist durch die Panama-Krankheit (TR4), eine Pilzkrankheit, die den Bananenstauden die Nährstoffe entzieht und letztlich tötet, weltweit bedroht. Die Gen-Banane, wird als „Reserveoption“ verkauft und als „wichtiger Schritt zum Aufbau eines Sicherheitsnetzes für die weltweiten Cavendish-Bananen vor TR4.“ Zum Essen sei sie „sicher“, heißt es in einem Nebensatz im aktuellen Bericht im Fachmagazin /[[https://www.abc.net.au/news/2024-02-16/australia-approves-first-genetically-modified-banana-panama-tr4/103476986?utm_source=Live+Audience&utm_campaign=379f11e430-briefing-dy-20240219&utm_medium=email&utm_term=0_b27a691814-379f11e430-51699044][Nature]]/ zur Zulassung.

Man habe „ein Bananengen von einer Banane auf eine andere übertragen“, was „nicht ungewöhnliches“ sei, heißt es aus der Wissenschaft. Bisher sei TR4 in Australien auch „ziemlich gut unter Kontrolle“, die GMO-Banane wird also nicht gebraucht: „Das kann sich jedoch ändern, so dass dies wirklich unser Sicherheitsnetz ist“, sagte Professor Dale, der die Forschung leitet.

* „Das Gericht in Kiew hat bestätigt: Maidan-Scharfschützen schossen aus dem Hotel Ukraina“ -
:PROPERTIES:
:CREATED: [2024-02-28 Mi 09:21]
:SOURCE: https://multipolar-magazin.de/artikel/katchanovski-maidan-scharfschutzen
:END:
Vor zehn Jahren sorgte ein Scharfschützenmassaker an Polizisten und
Maidan-Aktivisten für eine hochexplosive Atmosphäre auf dem Kiewer
Maidan und leitete den zwei Tage später folgenden Putsch gegen die
ukrainische Regierung ein. Der Politikwissenschaftler Ivan
Katchanovski von der Universität Ottawa erläutert im Interview mit
Multipolar den Tathergang, die vorliegenden Beweise, die fragwürdige
Rolle der ARD und die Erkenntnisse eines kürzlich ergangenen Kiewer
Gerichtsurteils zu dem Massenmord. Die Richter stellten faktisch fest:
Rechtsextreme Maidankämpfer schossen aus dem Hotel Ukraina und sind
für den Tod von mindestens zehn Menschen verantwortlich.

* Full article: The “snipers’ massacre” on the Maidan in Ukraine
:PROPERTIES:
:CREATED: [2024-02-28 Mi 09:22]
:SOURCE: https://www.tandfonline.com/doi/full/10.1080/23311886.2023.2269685
:END:
This study analyzes which party of the conflict was involved in the
2014 Maidan massacre in Ukraine. The massacre of Maidan protesters and
the police on 20 February 2014 was a turning point in Ukrainian
politics. This mass killing led to the overthrow of the Ukrainian
government and spiraled into a civil war in Donbas, Russian military
intervention in Crimea and Donbas, the Russian annexation of Crimea,
and conflicts between Ukraine and Russia and between the West and
Russia that Russia drastically escalated by launching its illegal
invasion of Ukraine in February 2022.

* [[https://multipolar-magazin.de/artikel/narziss-und-narzissmus][Narziss und Narzissmus -]] :website:

[2024-02-28 Mi 09:42] 

** Narziss und Narzissmus
:PROPERTIES:
:CUSTOM_ID: narziss-und-narzissmus
:END:

Narzissmus gilt als Krankhaftigkeit eines Einzelnen -- ein Unheil, das jedermann in Beziehungen, Wirtschaft und Politik zu spüren bekommt. Eine narzisstische Aufblähung ist jedoch der Versuch, mittels einer Rolle zu gesellschaftlicher Anerkennung und Bedeutung zu kommen. Diese Rolle ist ein Kompromiss zwischen dem Wunsch, als eigenständiger Mensch anerkannt zu werden und den Erwartungen, die in einer auf Herrschaft gründenden Gesellschaft an den Einzelnen gestellt werden. Die Pathologisierung des Einzelnen behindert die Erkenntnis, dass der Diener den Mächtigen bezeugt.

[[https://multipolar-magazin.de/autorenarchiv?autor=Jeannette%20Fischer][JEANNETTE FISCHER]], 27. Februar 2024, [[https://multipolar-magazin.de/artikel/narziss-und-narzissmus#diskussion][0 Kommentare]], [[https://multipolar-magazin.de/media/pdf/narziss-und-narzissmus.pdf][PDF]]

Die Figur des Narziss tauchte ursprünglich in der griechischen Mythologie auf und wurde vom römischen Dichter Publius Ovidius Naso (43 v. Chr. Bis 17 n. Chr.), kurz Ovid, im dritten Buch seiner Metamorphosen ausführlich beschrieben, eingebettet in eine wortgewaltige Poesie. Es ist der Jüngling, der im Teich sein Spiegelbild sieht und sich in dieses verliebt. Er kann es jedoch weder berühren noch küssen, weil sein Spiegelbild sich ihm zwar auch nähert, im Moment der Berührung jedoch entzieht. Das Begehren ist also gegenseitig.

Dass das Begehren des Narziss -- wie von Ovid beschrieben -- ihm selber gilt, wird heutzutage von vielen Menschen genüsslich zitiert und bissig kommentiert; der Narziss ist zum Objekt einer permanenten Stigmatisierung geworden. Die Rede ist von einem narzisstischen Zeitalter, in dem führende Politiker und Politikerinnen, wichtige Player in Wirtschaft und Gesellschaft dank dieser Eigenschaft zu Macht gelangen -- oder erst dank ihrer so genannten narzisstischen Veranlagung in solche Positionen hineingewählt beziehungsweise hineinbefördert werden.

**** Moderne Bösewichte
:PROPERTIES:
:CUSTOM_ID: moderne-bösewichte
:END:
Ein Narzisst, so der gängige Kanon, ist ein Selbstverliebter und ein tendenziell rücksichtsloser Mensch, weil er das Gegenüber verkennt, es in seiner Eigenheit und Eigenständigkeit nicht wahrnimmt, missachtet und für seine eigenen Zwecke missbraucht, sodass andere Menschen für ihn nur interessant sind, wenn er sie instrumentalisieren kann. Narzissten sind die modernen Bösewichte.

Jahrzehnte vor Ovid ist von dem griechischen Dichter Parthenios von Nikaia, der 73 v. Chr. als Kriegsgefangener nach Rom kam, eine Narziss-Erzählung überliefert, die aufzeigt, dass sich der junge Narziss dem Dasein als Geliebter erwachsener Männer -- eine nicht unübliche Praxis im alten Athen -- verweigert hat. Bei Ovid heißt es (zirka 1 bis 8 n. Chr.):

#+begin_quote
„So hatte Narziss diese (die Nymphe Echo, Anm. JF) enttäuscht, so auch andere Wasser- und Bergnymphen, so vorher den Umgang mit Männern gemieden. Daher hatte einer von ihnen, der verschmäht worden war, die Hände zum Äther erhoben und gesagt: 'So soll es auch ihm in der Liebe ergehen, so soll auch er, was er liebt, nicht bekommen.' Sprach's, und Rhamnusia (Göttin des Zornes, Anm. JF) gewährte die gerechte Bitte.“

#+end_quote

Es wäre also seine Pflicht gewesen, das Begehren der Nymphen und Männer zu befriedigen. Diese Strafe nun, keinen Menschen für das eigene Begehren zu finden, ist in ihrer Grausamkeit unübertroffen. Für Narziss bedeutet sie, dass er in sich selber eingeschlossen bleibt, dass er nur noch sich selber als Gegenüber hat, dass er -- so Ovid -- später an seinem eigenen Feuer, an seiner eigenen Libido sterben wird:

#+begin_quote
„Wie gelbes Wachs an einem schwachen Feuer und wie der morgendliche Rauhreif an der warmen Sonne schmilzt, so schwindet er dahin, von Liebe ausgezehrt und langsam nagt an ihm ein verborgenes Feuer.“

#+end_quote

Setzt man eine Bindungsstruktur voraus, eine intersubjektive, in der der eine Mensch den anderen als Nicht-Ich, als different, als anders anerkennt, dann zeigt dieses Epos eine Struktur des Gefälles: Der eine hat dem anderen seine Wünsche zu erfüllen, ungeachtet seiner eigenen und tut er das nicht, wird er bestraft, in dem er der Bindung zu missen hat. Und ohne Bindung werden wir verrückt oder wir sterben, dies hat Ovid zu recht erkannt.

Einem in sich eingeschlossenen Menschen -- wie hier Narziss -- wird die Angst im Seitenwagen ein unbeirrter Begleiter sein, er wird immer auf der Suche nach Bindung sein, nach einer Bindung, die sein Subjektsein anerkennt, außerhalb einer Instrumentalisierung in die Wünsche und Bedürfnisse der anderen. Er wird in Rollen schlüpfen, welche ihm einen vermeintlichen Ausweg aus der Einsamkeit versprechen, mit welchen er seinem Auftrag, die Erwartungen des anderen zu erfüllen und dennoch nicht zu verschwinden darin, gerecht werden kann.

**** Anerkennung einer Rolle, nicht des Individuums
:PROPERTIES:
:CUSTOM_ID: anerkennung-einer-rolle-nicht-des-individuums
:END:
Rollen, die eine große gesellschaftliche Akzeptanz haben, äußern sich bei uns in den Superlativen: Bester zu sein, Berühmteste zu sein, Reichster zu sein, Mächtigste zu sein. Die Anerkennung wird hier nicht ausbleiben, ja, die wird gewiss sein mit diesen Attributen. Die Anerkennung einer Rolle gleitet jedoch an der Anerkennung als Subjekt vorbei. Narziss bleibt einsam zurück und zusammen mit der Angst wird er weiterhin versuchen, in den Superlativen mitzuspielen, sich diesen Platz zu sichern. Es ist sein Versuch, der Bindungslosigkeit zu entkommen. Damit wird er -- vielleicht unwissentlich -- die bestehenden Machtverhältnisse tradieren, die sich seiner als autonomes und eigenständig denkendes und handelndes Subjekt entledigen und in den Dienst eines anderen Narrativ führen, dessen Erwartungen und Bedürfnisse nun zu erfüllen sind.

Wenn Narzisse nun auf eine Gesellschaft treffen, die gerade ihre Merkmale benötigt, um die Herrschaftsverhältnisse und deren Intensionen zu sichern oder gar zu konsolidieren, dann werden sie sich in diesen Strukturen einnisten und sich darin ein Fortkommen ermöglichen können.

Der deutsche Historiker Eduard Fuchs (1870-1940) rollt in Band 3 seiner illustrierten Sittengeschichte die Epoche des Absolutismus in Frankreich auf, er nennt sie 'Die galante Zeit' -- also die Zeit unter Ludwig XIII. bis zur Französischen Revolution und der Hinrichtung von Ludwig XVI. Diese Zeit darf guten Gewissens als eine narzisstische bezeichnet werden. Er schreibt: „Weit sind die Hallen, unermesslich die Säle und Galerien. Alle Wände sind von der Decke bis zum Fußboden Kristall und blenden mit ihren Spiegelreihen. Die Repräsentation, die Pose fordert den Spiegel.“ Und dann den gewichtigen Satz:

#+begin_quote
„Die historische Situation gebiert die fürstliche Selbstherrlichkeit, genau wie sie sie korrigiert, und nicht die Person formt das Schema ihrer Zeit.“

#+end_quote

Hierzu sei angemerkt, dass sich beide bedingen, beziehungsweise die Frage nach dem Anfang müßig ist und nur dazu dienen mag, Sündenböcke an den Pranger zu stellen, nicht zuletzt, um sich der eigenen Verantwortung zu entziehen. Zur Illustration dieser Aussage erwähnt Fuchs die finanziellen Ausgaben von Marie Antoinette für ihre engsten Freundinnen und kommentiert bissig, es sei rentabel gewesen, zu den direkten Freunden der Herrscherfamilie zu zählen. „Die Königstreue war darum häufig der unverhüllte Ausfluss der Furcht, von der wohlgefüllten Staatskrippe wieder vertrieben zu werden.“ Der König und die Königin brauchen ihre Entourage, um ihre Macht zu erhalten, genauso wie der Hofstaat den König und die Königin. Der Diener bezeugt den Mächtigen.

Warum also sollte der Sonnenkönig Ludwig XIV. sich nicht mit seiner Rolle identifizieren, wenn er laut Eduard Fuchs in der Kathedrale von Versailles als Einziger den Priester und den Altar sehen durfte und die Sitzordnung so angelegt war, dass alle adligen Höflinge während der Messe ihn anzuschauen, ihn anzubeten hatten? Beschert ihm das nicht Macht, Ansehen und Beziehungen, die sein verkümmertes Ich verdecken? Fuchs schreibt unmissverständlich: „Und Ludwig war, wie wir bereits wissen, ein kompletter Strohkopf, der nicht einmal lesen und schreiben konnte.“

Dass Adelstitel vererbbar waren und immer noch sind, ist angesichts der damit verbundenen Privilegien verständlich. Diese sichern die gesellschaftliche Rolle und damit eine Machtposition. So erhält sich der Machtdiskurs, so erhalten sich die Rollen, die in Demokratien nicht mehr vom Adel oder Klerus tradiert werden, sondern von globalen Unternehmen, Institutionen und Verwaltungen mit ihren Führern und Führerinnen. Die Rollen bleiben also dieselben, sie werden einfach anders in Szene gesetzt, mit anderen Kostümen und einem anderen Bühnenbild.

* [[https://multipolar-magazin.de/artikel/narziss-und-narzissmus][Narziss und Narzissmus -]] :website:
:PROPERTIES:
:CREATED: [2024-02-28 Mi 09:45]
:SOURCE: https://multipolar-magazin.de/artikel/narziss-und-narzissmus
:END:


** Narziss und Narzissmus
:PROPERTIES:
:CUSTOM_ID: narziss-und-narzissmus
:END:

Narzissmus gilt als Krankhaftigkeit eines Einzelnen -- ein Unheil, das jedermann in Beziehungen, Wirtschaft und Politik zu spüren bekommt. Eine narzisstische Aufblähung ist jedoch der Versuch, mittels einer Rolle zu gesellschaftlicher Anerkennung und Bedeutung zu kommen. Diese Rolle ist ein Kompromiss zwischen dem Wunsch, als eigenständiger Mensch anerkannt zu werden und den Erwartungen, die in einer auf Herrschaft gründenden Gesellschaft an den Einzelnen gestellt werden. Die Pathologisierung des Einzelnen behindert die Erkenntnis, dass der Diener den Mächtigen bezeugt.

[[https://multipolar-magazin.de/autorenarchiv?autor=Jeannette%20Fischer][JEANNETTE FISCHER]], 27. Februar 2024, [[https://multipolar-magazin.de/artikel/narziss-und-narzissmus#diskussion][0 Kommentare]], [[https://multipolar-magazin.de/media/pdf/narziss-und-narzissmus.pdf][PDF]]

Die Figur des Narziss tauchte ursprünglich in der griechischen Mythologie auf und wurde vom römischen Dichter Publius Ovidius Naso (43 v. Chr. Bis 17 n. Chr.), kurz Ovid, im dritten Buch seiner Metamorphosen ausführlich beschrieben, eingebettet in eine wortgewaltige Poesie. Es ist der Jüngling, der im Teich sein Spiegelbild sieht und sich in dieses verliebt. Er kann es jedoch weder berühren noch küssen, weil sein Spiegelbild sich ihm zwar auch nähert, im Moment der Berührung jedoch entzieht. Das Begehren ist also gegenseitig.

Dass das Begehren des Narziss -- wie von Ovid beschrieben -- ihm selber gilt, wird heutzutage von vielen Menschen genüsslich zitiert und bissig kommentiert; der Narziss ist zum Objekt einer permanenten Stigmatisierung geworden. Die Rede ist von einem narzisstischen Zeitalter, in dem führende Politiker und Politikerinnen, wichtige Player in Wirtschaft und Gesellschaft dank dieser Eigenschaft zu Macht gelangen -- oder erst dank ihrer so genannten narzisstischen Veranlagung in solche Positionen hineingewählt beziehungsweise hineinbefördert werden.

**** Moderne Bösewichte
:PROPERTIES:
:CUSTOM_ID: moderne-bösewichte
:END:
Ein Narzisst, so der gängige Kanon, ist ein Selbstverliebter und ein tendenziell rücksichtsloser Mensch, weil er das Gegenüber verkennt, es in seiner Eigenheit und Eigenständigkeit nicht wahrnimmt, missachtet und für seine eigenen Zwecke missbraucht, sodass andere Menschen für ihn nur interessant sind, wenn er sie instrumentalisieren kann. Narzissten sind die modernen Bösewichte.

Jahrzehnte vor Ovid ist von dem griechischen Dichter Parthenios von Nikaia, der 73 v. Chr. als Kriegsgefangener nach Rom kam, eine Narziss-Erzählung überliefert, die aufzeigt, dass sich der junge Narziss dem Dasein als Geliebter erwachsener Männer -- eine nicht unübliche Praxis im alten Athen -- verweigert hat. Bei Ovid heißt es (zirka 1 bis 8 n. Chr.):

#+begin_quote
„So hatte Narziss diese (die Nymphe Echo, Anm. JF) enttäuscht, so auch andere Wasser- und Bergnymphen, so vorher den Umgang mit Männern gemieden. Daher hatte einer von ihnen, der verschmäht worden war, die Hände zum Äther erhoben und gesagt: 'So soll es auch ihm in der Liebe ergehen, so soll auch er, was er liebt, nicht bekommen.' Sprach's, und Rhamnusia (Göttin des Zornes, Anm. JF) gewährte die gerechte Bitte.“

#+end_quote

Es wäre also seine Pflicht gewesen, das Begehren der Nymphen und Männer zu befriedigen. Diese Strafe nun, keinen Menschen für das eigene Begehren zu finden, ist in ihrer Grausamkeit unübertroffen. Für Narziss bedeutet sie, dass er in sich selber eingeschlossen bleibt, dass er nur noch sich selber als Gegenüber hat, dass er -- so Ovid -- später an seinem eigenen Feuer, an seiner eigenen Libido sterben wird:

#+begin_quote
„Wie gelbes Wachs an einem schwachen Feuer und wie der morgendliche Rauhreif an der warmen Sonne schmilzt, so schwindet er dahin, von Liebe ausgezehrt und langsam nagt an ihm ein verborgenes Feuer.“

#+end_quote

Setzt man eine Bindungsstruktur voraus, eine intersubjektive, in der der eine Mensch den anderen als Nicht-Ich, als different, als anders anerkennt, dann zeigt dieses Epos eine Struktur des Gefälles: Der eine hat dem anderen seine Wünsche zu erfüllen, ungeachtet seiner eigenen und tut er das nicht, wird er bestraft, in dem er der Bindung zu missen hat. Und ohne Bindung werden wir verrückt oder wir sterben, dies hat Ovid zu recht erkannt.

Einem in sich eingeschlossenen Menschen -- wie hier Narziss -- wird die Angst im Seitenwagen ein unbeirrter Begleiter sein, er wird immer auf der Suche nach Bindung sein, nach einer Bindung, die sein Subjektsein anerkennt, außerhalb einer Instrumentalisierung in die Wünsche und Bedürfnisse der anderen. Er wird in Rollen schlüpfen, welche ihm einen vermeintlichen Ausweg aus der Einsamkeit versprechen, mit welchen er seinem Auftrag, die Erwartungen des anderen zu erfüllen und dennoch nicht zu verschwinden darin, gerecht werden kann.

**** Anerkennung einer Rolle, nicht des Individuums
:PROPERTIES:
:CUSTOM_ID: anerkennung-einer-rolle-nicht-des-individuums
:END:
Rollen, die eine große gesellschaftliche Akzeptanz haben, äußern sich bei uns in den Superlativen: Bester zu sein, Berühmteste zu sein, Reichster zu sein, Mächtigste zu sein. Die Anerkennung wird hier nicht ausbleiben, ja, die wird gewiss sein mit diesen Attributen. Die Anerkennung einer Rolle gleitet jedoch an der Anerkennung als Subjekt vorbei. Narziss bleibt einsam zurück und zusammen mit der Angst wird er weiterhin versuchen, in den Superlativen mitzuspielen, sich diesen Platz zu sichern. Es ist sein Versuch, der Bindungslosigkeit zu entkommen. Damit wird er -- vielleicht unwissentlich -- die bestehenden Machtverhältnisse tradieren, die sich seiner als autonomes und eigenständig denkendes und handelndes Subjekt entledigen und in den Dienst eines anderen Narrativ führen, dessen Erwartungen und Bedürfnisse nun zu erfüllen sind.

Wenn Narzisse nun auf eine Gesellschaft treffen, die gerade ihre Merkmale benötigt, um die Herrschaftsverhältnisse und deren Intensionen zu sichern oder gar zu konsolidieren, dann werden sie sich in diesen Strukturen einnisten und sich darin ein Fortkommen ermöglichen können.

Der deutsche Historiker Eduard Fuchs (1870-1940) rollt in Band 3 seiner illustrierten Sittengeschichte die Epoche des Absolutismus in Frankreich auf, er nennt sie 'Die galante Zeit' -- also die Zeit unter Ludwig XIII. bis zur Französischen Revolution und der Hinrichtung von Ludwig XVI. Diese Zeit darf guten Gewissens als eine narzisstische bezeichnet werden. Er schreibt: „Weit sind die Hallen, unermesslich die Säle und Galerien. Alle Wände sind von der Decke bis zum Fußboden Kristall und blenden mit ihren Spiegelreihen. Die Repräsentation, die Pose fordert den Spiegel.“ Und dann den gewichtigen Satz:

#+begin_quote
„Die historische Situation gebiert die fürstliche Selbstherrlichkeit, genau wie sie sie korrigiert, und nicht die Person formt das Schema ihrer Zeit.“

#+end_quote

Hierzu sei angemerkt, dass sich beide bedingen, beziehungsweise die Frage nach dem Anfang müßig ist und nur dazu dienen mag, Sündenböcke an den Pranger zu stellen, nicht zuletzt, um sich der eigenen Verantwortung zu entziehen. Zur Illustration dieser Aussage erwähnt Fuchs die finanziellen Ausgaben von Marie Antoinette für ihre engsten Freundinnen und kommentiert bissig, es sei rentabel gewesen, zu den direkten Freunden der Herrscherfamilie zu zählen. „Die Königstreue war darum häufig der unverhüllte Ausfluss der Furcht, von der wohlgefüllten Staatskrippe wieder vertrieben zu werden.“ Der König und die Königin brauchen ihre Entourage, um ihre Macht zu erhalten, genauso wie der Hofstaat den König und die Königin. Der Diener bezeugt den Mächtigen.

Warum also sollte der Sonnenkönig Ludwig XIV. sich nicht mit seiner Rolle identifizieren, wenn er laut Eduard Fuchs in der Kathedrale von Versailles als Einziger den Priester und den Altar sehen durfte und die Sitzordnung so angelegt war, dass alle adligen Höflinge während der Messe ihn anzuschauen, ihn anzubeten hatten? Beschert ihm das nicht Macht, Ansehen und Beziehungen, die sein verkümmertes Ich verdecken? Fuchs schreibt unmissverständlich: „Und Ludwig war, wie wir bereits wissen, ein kompletter Strohkopf, der nicht einmal lesen und schreiben konnte.“

Dass Adelstitel vererbbar waren und immer noch sind, ist angesichts der damit verbundenen Privilegien verständlich. Diese sichern die gesellschaftliche Rolle und damit eine Machtposition. So erhält sich der Machtdiskurs, so erhalten sich die Rollen, die in Demokratien nicht mehr vom Adel oder Klerus tradiert werden, sondern von globalen Unternehmen, Institutionen und Verwaltungen mit ihren Führern und Führerinnen. Die Rollen bleiben also dieselben, sie werden einfach anders in Szene gesetzt, mit anderen Kostümen und einem anderen Bühnenbild.

* [[https://apolut.net/im-elysee-wird-zu-heiss-geduscht/][Im Élysée wird zu heiß geduscht - apolut.net]] :website:
:PROPERTIES:
:CREATED: [2024-02-28 Mi 09:54]
:SOURCE: https://apolut.net/im-elysee-wird-zu-heiss-geduscht/
:END:
Frankreich bleibt sich treu. Einmal Beresina, immer Beresina; einmal Versailles, immer Versailles. Anders sind die gestrigen Aussagen des französischen Präsidenten zum Ukraine-Krieg nicht zu werten. Sie scheinen typisch zu sein, was die Methode anbetrifft. Erinnern wir uns an die nach Paris eingeladene Libyen-Konferenz. Dort sollte über ein Vorgehen gegen dieses nordafrikanische Land erst beraten werden. Die eingeladenen Staatschefs waren noch nicht gelandet, als die französischen Bomber gen Tripolis flogen.

Jetzt sind es in Napoleon-Manier die europäischen Bodentruppen, die in den Krieg eingreifen sollen. Wie bei Napoleon und Hitler, als die Deutschen verbluten durften, von anderen Völkern ganz zu schweigen. Auf die Europäer und damit auch auf die Deutschen kommt die Frage zu, die bekannt klingt:

#+begin_quote
„Wollt ihr den französischen Krieg in Europa?”

#+end_quote

Joe Biden kann sich freuen. Es findet sich wieder jemand, der in die vom Kongress geschlagene Bresche springt. Nur ja kein Kriegsende und kein Friede, bedingungslose Kapitulation für Moskau.

