#+title:      Judentum
#+date:       [2023-05-21 So 09:41]
#+filetags:   :judentum:weltreligionen:
#+identifier: 20230521T094148

Hier sammle ich alles zum Thema Judentum.

* Überblick (RB 2 S. 119)
1 Bild 1: Auf diesem Bild ist eine jüdische Rabbinerin zu sehen. Für uns Katholiken ist es ein eher ungewöhnlicher Anblick, eine Frau zu sehen, die einen Gottesdienst leitet.

Bild 2: Hier kann man einen orthodoxen Jungen beim Lesen der Tora sehen. Erst nach der Bar-Mizwa/Bat-Mizwa dürfen Jüdinnen und Juden diese studieren, lesen und daraus während des Gebetes am Sabbat vorlesen.

Bild 3: Diese „Stolpersteine“ erinnern uns an jüdische Opfer im Zweiten Weltkrieg. Zirka 6 Millionen Juden kamen damals grauenvoll ums Leben. Bis heute erinnern wir uns an diese grausame und furchtbare Zeit und tragen Mitverantwortung, dass so etwas nie wieder passieren darf.

Bild 4: Hier sind jüdische Männer beim Gebet in der Synagoge abgebildet. Sie tragen die typische Kopfbedeckung: die Kippa. Diese symbolisiert die, dass Gott über dem Menschen ist und uns beschützt. Das Tragen der Kippa ist für jüdische Männer keine Bürde, sie empfinden es als Ehre.


2 Die Methode „Ein Thema erforschen“ ist auf Seite 126/127 zu finden. (B)*

Gläubige weltweit: ca. 15 Mio (Stand 2020)

Gläubige in Österreich: ca. 10 000 (Stand 2020)

Alter: (wie alt ist die Religion)

Gotteshaus: Synagoge

Heilige Schriften: Tanach (AT): Tora (erste 5 Bücher Mose), Propheten (Newiim), Schhriften - Psalmen, Weisheit (Ketuvim); Talmud (Erklärungen).

[[https://www.religionen-entdecken.de/lexikon/h/heilige-schriften-im-judentum]]

Oberhaupt: Rabbinerinnen / Rabbiner


3 Es ist vielen nicht bewusst, wie sehr uns auch heute noch Teile der jüdischen Sprache beeinflussen. Einige Beispiele hierfür wären:                        (O)**

Quelle: [[https://de.wikipedia.org/wiki/Liste_deutscher_W%C3%B6rter_aus_dem_Hebr%C3%A4ischen_und_Jiddischen]]

| jüdisch                | deutsch                       | Bedeutung              |
|------------------------+-------------------------------+------------------------|
| zocken                 | abzocken                      | jemanden übervorteilen |
| mis                    | mies                          | schlecht / verächtlich |
| Chaverim               | Haberer                       | Kumpel                 |
| plejte                 | pleite                        | zahlungsunfähig sein   |
| shiker                 | schicker (angeschickert sein) | angetrunken sein       |
| Schlimasel / masel tov | Schlamassel / Massel          | Unglück / Glück        |
| Rosch                  | Guten Rutsch                  | Neujahrwünsche         |

	
* Ein Volk, ein Gott
1 Dieser Arbeitsauftrag ist sehr persönlich und individuell. 
Das Sch’ma Jisrael ist das wichtigste Gebet der Juden, ähnlich unserem Vater Unser. Es handelt vom tiefen Glauben an den einen Gott und, dass Jüdinnen und Juden diesen auch an ihre Kinder weitergeben soll. Dieser tiefe Glaube entsteht im Herzen und soll zum äußeren Zeichen an Stirn und Handgelenk (Gebetsriemen) als auch an jedem Ein-/Ausgang des Hauses/der Wohnung (Mesusa) befestigt werden.

2 Wie in Arbeitsauftrag 1 beschrieben, wären das die wichtigsten Aussagen des Sch‘ma Jisrael. In dem Gebet geht es um einen tiefen, inneren Glauben, den die Jüdinnen und Juden leben.

3 Bei diesem Auftrag wird es die unterschiedlichsten Empfindungen der Schüler*innen geben. Es wäre von Vorteil, sich im Vorfeld das Sch’ma Jisrael in seiner Originalsprache (YouTube) anzuhören, um selbst ein bisschen Gefühl für die Sprachmelodie zu bekommen.

4 Das Sch’ma Jisrael ist das Bekenntnis der Jüdinnen und Juden zu dem ewigen, einzigen Gott. Es ist also das Glaubensbekenntnis dieser Religion. Für Jüdinnen und Juden ist es prinzipiell nichts Anstößiges oder Furchtbares, wenn wir Christen*innen dieses Gebet mit dem dazugehörigen Respekt in der Kirche beten oder rezitieren. Es ist allerdings nicht auszuschließen, dass streng gläubige Jüdinnen und Juden das als geschmacklos empfinden.

* Feste

[[https://www.religionen-entdecken.de/]]

** Chanukka
[[https://tvthek.orf.at/profile/Archiv/7648449/Familientreffen-an-Chanukka/6934863/Familientreffen-an-Chanukka/14608868]]

** Pessach
[[https://tvthek.orf.at/profile/Archiv/7648449/Pessach-mit-Familie-Molcho/14039979/Pessach-mit-Familie-Molcho/14635107]]

** Koscher Essen
[[https://tvthek.orf.at/profile/Archiv/7648449/Ernaehrung-im-Judentum-Was-ist-koscher/6918065/Ernaehrung-im-Judentum-Was-ist-koscher/14608757]]

** Jom Kippur
[[https://tvthek.orf.at/profile/Archiv/7648449/Jom-Kippur-Versoehnungstag/6917441/Jom-Kippur-Versoehnungstag/14608795]]

** Laubhüttenfest / Sukkot
[[https://tvthek.orf.at/profile/Archiv/7648449/Laubhuetten-als-Symbol-des-Lebens/7020983/Laubhuetten-als-Symbol-des-Lebens/14651150]]

[[https://tvthek.orf.at/profile/Archiv/7648449/Sukkot-Feier-in-Wien/7435555/Sukkot-Feier-in-Wien/14608769]]

** Schabbat - Tora
[[https://tvthek.orf.at/profile/Archiv/7648449/Ueber-den-Schoepfungsmythos-der-Thora/6918515/Ueber-den-Schoepfungsmythos-der-Thora/14621088]]

[[https://tvthek.orf.at/profile/Archiv/7648449/Heilige-Schriften-Die-Thora/6918373/Heilige-Schriften-Die-Thora/14621094]]



