#+title:      Pädagogische Konferenz
#+date:       [2023-06-12 Mo 16:01]
#+filetags:   :konferenz:schule:
#+identifier: 20230612T160124

Hier steht die Einleitung.

* Begrüßung

* Tagesordnung
Danke für die Sportwoche

* Induktion
3 Stellen
junge Kollegen - wer betreut sie?

* Neue Lehrer
www.getyourteacher...

- Amtsverschwiegenheit
- keine Geschenkannahme


* Kaserer
...Ziel / zu schwammig

* Doch 3 erste Klassen

** 1a Eva

** 1b Mirjam

** 1c Gertraud

* Schulärztin
warum Impfpass? ein kann

* Waldchampignon

* Pinguin

* Notenkonferenz
Notenschluss 26. Juni
29.6.

* Induktiosnphase NEU
Stufenplan (cf siehe ppp)

Mentoring: Feedback; vor- und nachbesprechen
Willkommensmappe für neue Lehrer (z.B. von den Junglehrer erstellt, da sie mehr Erfahrungen haben.)

4.9.-8.9. an der PH und einen Tag an der MS

* Bewerbungsverfahren

* Amtsverschwiegenheit
Was in der Schule z.B. über Schüler besprochen wird, bleibt in der Schule.

* Keine Geschenkannahme
Bewirtungen, etc... 3 K's

* Verwendungsbeschränkung
Ehepaar etc darf nicht an der gleichen Schule Direktor und Lehrerin sein. Beide Lehrer geht schon. Ausnahmen müssen öffentlich gemacht werden.

* Quereinstieg
30 im L Salzburg; päd. Ausbildung nachholen, nur in zertifizierten Fächern. (M Lehramt, Geschichte so: M + GS)

* Elternverein
sponsert ein Eis zum Schulschluß

Schüler ist besonders freundlich, etc. (insgesamt 6 Schüler) auszeichnen: AS Gutscheine.

* Waldchampignon Tage
jede Gruppe ein Lehrer 

* Vivienne
erhält jede Woche eine Anzeige
keine Polizei
Schule hat alles gemacht
Jugendamt kommt am Freitag?

* Interessensfächer
wer ist die 6. Lehrperson für Ernährung, Sport und Gesundheit

2.-5.4.

Projektwoche - Termin ... va Englisch? ev nach Semesterferien?

(ab 14 Teilnehmer wird geteilt.)

* Sportwoche
Ossiachersee (Sportwoche): neuer Pächter, neues Angebot
Lignano (Sportwoche): Woche vor Pfingsten

* Bernadette Lienbacher
neue Lehrerin

* Wolfi geht
Nachfolge geregelt, übernimmt Lena

* Sportbewerb
vielleicht diesen Kindern HÜ etc erlassen und nix nachschreiben lassen

* Digitales Lernen
vll mehr Kollegen dabei?
ohne Anmeldung; echt viele interessante Vorschläge; ...

Geräteinitiative - machen bei 3. Klassen nicht mit.
daher ab nächstem Jahr gibt es keine Lehrergeräte, da fehlen uns 9 Geräte.
Julia hat Unmut bei BD und BM deponiert

Jeder schiebt sich den schwarzen Peter zu: Land - Bund - Gemeinde.

3 Geräte stehen uns doch noch zu.

Neue Geräte eher den neuen, jungen Kollegen. Verlässt ein L die Schule, bleibt Gerät in der Schule.

--> Fortbildungsidee

Kennenlernen anderer Kollegen, man trifft sich wieder, Austausch

Wo Laptop jeden Tag da sein muss, wird er auch mehr eingesetzt - leichte Schultasche: Lückentext über Teams.

* Planer nächstes Jahr
Design Barbara
gleicher Verlag

Abgabeschluss für Deckblatt: nächster Freitag

* Lehrerausflug
Herbst - Anfang Oktober
Wohin: Wien oder Bregenz oder Amsterdam (alles mit Zug)

* Abschlussessen
nach Abschlussfeier am Do.
