#+title:      [SW09] Große Fragen - große Antworten
#+date:       [2023-06-19 Mo 08:54]
#+filetags:   :01:sw09:
#+identifier: 20230619T085426


* Kompetenzbeschreibung
CLOSED: [2023-06-19 Mo 08:55]
[[#A2]] Menschen und ihre Lebensorientierungen - Sich mit den großen Fragen der Menschen auseinandersetzen können
[[#A2_KB1]] Die Schülerinnen und Schüler können für sie bedeutsame Fragen diskutieren und über existentielle Lebensfragen philosophieren und theologisieren.

* AB / UH
[[#A2_UH1]] Beantwortbare und letztlich unbeantwortbare Fragen:
- Wer ist Gott? Existiert Gott?
- Existiert überhaupt etwas?
- Wer ist der Mensch?
- Gott ist gut, warum gibt es das Böse?
- Der Sinn des Lebens?
- ...


* Wiederholung
2.2 Große Fragen
Dieses Kapitel sammelt große Fragen, die von Menschen gestellt werden und sucht (u.a. in Verbindung mit 2.3) nach hilfreichen Antwortversuchen. Dabei wird vor allem auf die Unterscheidung von beantwortbaren und letztlich unbeantwortbaren Fragen geachtet.

2.3 Große Antworten?
Diese Seite "spiegelt" 2.2 und bietet Antworten bzw. Antwortversuche an. Einige davon können direkt zugeordnet werden, andere sind mehrdeutig bzw. mehrmals als "richtige" Antwort passend. In Kombination mit 2.2 kann so reflektiert werden, welche Antworten eindeutig sind, welche jedoch immer im Status des Versuchs bleiben.

* Erarbeitung
RB S. 30-31

** Lösungsvorschläge für die Arbeitsaufträge (S. 30):
1 Dieser Arbeitsauftrag ist sehr persönlich und individuell. Die Schüler*innen ergänzen zu den – am besten zuvor besprochenen/gelesenen Fragestellungen – weitere Fragen, die sie schon länger bewegen.

2 Auch dieser Arbeitsauftrag ist sehr individuell. Je nach Gruppe werden viele, wenige und vor allem unterschiedliche Antworten auf Fragen gefunden bzw. formuliert werden können. Auch hier lohnt sich immer wieder die Unterscheidung in „normale“ und „große“ Fragen.

3 Auch für diesen Arbeitsauftrag kann es keine allgemeingültige Lösung geben. Erneut ist darauf zu achten, den Schüler*innenn bestenfalls Vorschläge zu machen, aber nicht vorzugeben, auf welche Fragen es mehrdeutige oder verschiedene Antworten geben könnte. Auch daran lässt sich die Unterscheidung hin zu „großen Fragen“ erneut festmachen.

** Lösungsvorschläge für die Arbeitsaufträge (S. 31):
1 Auf konkrete Fragen können hier einige konkrete Antworten gefunden werden. Auch hier kann immer wieder thematisiert werden, dass viele dieser Fragen nur eine Seite der Fragestellung beleuchten können. Die Fragestellung „Warum müssen alle Lebewesen einmal sterben?“ könnte z.B. auch theologisch betrachtet werden. Die Zuordnungen hier beziehen sich zunächst auf objektive, naturwissenschaftliche Aussagen:

    - „Wie viel wiegt die Erde?“ - „ca. 5,9 Millionen Milliarden Milliarden…“
    - „Warum gibt es Tag und Nacht?“ - „Die Erde bewegt sich um die Sonne.“ und „Die Erde dreht sich um die eigene Achse.“
    - „Warum müssen alle Lebewesen irgendwann sterben?“ - „Die Zellen aller Lebewesen altern und sterben mit der Zeit ab.“
    - „Wann ist die Erde entstanden?“ - „Vor etwa vier Milliarden Jahren.“
    - „Warum fallen Dinge zu Boden, wenn man sie auslässt?“ - „Aufgrund der Schwerkraft…“
    - „Wie viele verschiedene Lebewesen gibt es auf der Erde?“ - „Viele Lebewesen der Erde sind noch unbekannt...“

2 Dieser Arbeitsauftrag reflektiert näher, welche Fragen beantwortbar sind und welche unbeantwortbar bleiben. Es lohnt sich hier, mögliche Gründe dafür zu diskutieren: Fehlt uns dazu noch ein spezielles Wissen? Handelt es sich um Fragen, auf die es keine endgültigen Antworten geben kann?

3 Ausmaß und Art der hier von den Schüler*innenn eingetragenen Fragestellungen hängt sehr stark von Vorwissen, Interessen und Kompetenzen der einzelnen Kinder ab. Es kann sich anbieten, weitere konkrete Antworten zu suchen oder auch Antwortversuche auf „große Fragen“ aufzunehmen.


* Hefteintrag

