#+title:      [SW01] Jahresstoff / ich stehe in den Schuhen des Anderen
#+date:       [2023-06-19 Mo 07:37]
#+filetags:   :01:sw01:
#+identifier: 20230619T073700

[[denote:20230621T073313][01 Golling]]

* Kompetenzbeschreibung
[[#A1]] Menschen und ihre Lebensorientierungen: Beziehung verantwortungsvoll gestalten können – zu sich selbst, zu anderen, zur Schöpfung
[[#A1_KB1]] Die Schülerinnen und Schüler können sich in ihrer gottgeschenkten Einzigartigkeit wahrnehmen und wissen um die Bedeutung von (Selbst-) Vertrauen für ein gelingendes (Zusammen-)Leben.

* AB / UH
[[#A1_UH1]] Ich und die anderen: Empathie und Perspektivenwechsel

* Wiederholung
Hier kommt ein neuer Text hin. - Nachher verwende ich magit ... Und jetzt füge ich noch etwas hinzu.

Vorstellen des RU in der NMS Golling.

 - Organisatorisches: Heft / Überprüfung
 - Anforderungen bzgl Benotung: Mitarbeit (jede Stunde), Heftführung (regelmäßig kontrolliert; vollständig? sauber? kreativ? ...); eventuell LKZ / Test
 - Themen
 - Was ist mir als Lehrer wichtig?
 - Was erwarten sich die Schüler?

Im RU kann und werde ich den Schülern Glaubens*wissen* vermitteln. Aber nicht nur das. Es muss um die Schüler gehen; wie können die Schüler eine Verbindung zwischen ihrem Leben und dem christlichen Glauben herstellen? Wie sehr (oder: wie wenig) sind die Schüler christlich-kirchlich sozialisiert? Der christliche Glaube ist kein Hut, den man sich am Sonntag beim Kirchgang aufsetzt. Er ist integraler Bestandteil meiner Person (wenn ich getauft bin). Jesus Christus - Er muss in der Mitte des RU stehen. Ich muss als RL das Evangelium Jesu Christi verkünden, Zeuge der Wahrheit sein. Ja, es gibt sie: DIE Wahrheit. Nicht ich - als Mensch - werde sie finden, sondern es ist die Wahrheit, die mich finden wird; denn die Wahrheit ist eine Person: Jesus Christus, der Sohn Gottes (c) Ambrosius, im Film "Augustinus".

Der Ablauf der Stunde muss klar sein.

Beispiel:

 - Gebet
 - Rückblick / Whg von letzter Stunde / Aufzeichnungen der Mitarbeit
 - Hinführung
 - Schüler erarbeiten neues Thema / Aufzeichnungen der Heftarbeit
 - Zusammenfassung
 - Hefteintrag / Aufzeichnungen
 - Offene Fragen / Was habt ihr gelernt?

[[https://www.reli.ch/schuhe-mit-alltagsgegenstaenden-religion-lernen/]]

Nach den obigen Texten aus dem Lehrplan - die ich den Schülern durchaus vorlesen kann -, stehen sowohl Jesus Christus als auch die Schüler in der Mitte des RU. Welche religiöse Erfahrungen, welches religiöse Wissen bringen die Schüler mit? Was ist ihnen neu? Wie können wir unsere Erfahrungen im Lichte des Evangeliums deuten? Gott offenbart sich in Jesus Christus.

[[id:734cb1fc-3d8f-4cb1-b937-e0f9707a34b1][Kompendium der soziallehre der kirche]]

[Ich weiß nicht, wieviel die Schüler (in allen Klassen) von der aktuellen Krise innerhalb der katholischen Kirche mitbekommen. Ein unfassbares Skandal in der katholischen Kirche in den USA, Täter waren Priester, Ordensleute und Bischöfe (?); Vertuschung durch Priester und Bischöfe; Papst Franziskus hat(te) unter seinen Beratern Kardinal McCarrick, der von dem Skandal wusste, selbst Täter war(?); Papst B16 erlegte McCarrick Sanktionen auf; Papst Franziskus hob diese wieder auf; etc ... Es ist keine Krise des Vertrauens, sondern des Glaubens. Der Papst ist auch dann der Papst, wenn er ein grottenschlechter Papst ist.]

* Erarbeitung
Einander kennenlernen - Namensschilder? fixer Sitzplan für mich; Schüler immer mit Vornamen anreden.

Grundlagen:
 - Was ist Glaube?
 - Jesus
 - Gott
 - Hl. Schrift
 - Kirche
 - Jahresfestkreis verstehen
 - etc...

Hm, den RU auf diese Art zu beginnen, wird für die Kinder zu abstrakt sein. Besser ist es, die Kinder zu fragen, was sie sich vom RU erwarten bzw welche Themen sie auf welche Art in der VS erarbeitet haben (Sitzkreis etc). Andererseits werde ich die Schüler bitten, bei Unklarheiten sofort Fragen zu stellen.

In der ersten Stunde: 1. Heftseite wunderschön gestalten ("Jesus Christus", Themen-ABC, ...): zum Thema "Jesus" Wörter von A bis Z finden.

SOFORT Aufzeichnungen machen: Mitarbeit, Heft, Schulsachen vollständig? 

Immer gemeinsam beten: Lieder, Gebete, Stille, ...

* Hefteintrag
Jahresfestkreis ins Heft zeichnen
Farblich gestalten
