#+title:      Feste
#+date:       [2023-02-24 Fr 10:54]
#+filetags:   :feiern:gesellschaft:
#+identifier: 20230224T105457

* Comic
Die Aussage, die sich direkt auf das Zitat "Man muss die Feste feiern, wie sie fallen" (u.a. im Comic) bezieht, regt zur Auseinandersetzung mit dem "Timing" von Festen an. Der Spruch verweist darauf, dass man die Gelegenheit zum Feiern nutzen sollte, wo sie sich bietet. Feste sind gerade dadurch definiert, dass sie zeitlich, aber auch inhaltlich an bestimmte Anlässe gebunden sind. Sie geben dem Fest seine Bedeutung – fehlen sie oder verschieben sie sich, fehlt oder wandelt sich auch diese Bedeutung. Auch das wird im Comic mit dem Motiv des Feste-Würfelns angesprochen. Mit den Schüler*innen lässt sich diese Thematik am besten anhand konkreter Beispiele besprechen – z.B.: Kann man Weihnachten auch im Sommer feiern? Funktioniert Erntedank im Winter? etc. Oft kommen verschiedene Ausprägungen (Bräuche etc.) zur Sprache, die die genannten Feste genau zu diesen Festen machen. Interessant kann ein Blick in andere Kulturen sein – etwa dorthin, wo Weihnachten wirklich mitten im Sommer gefeiert wird (z.B. in Australien und anderen Ländern der Südhalbkugel).

* Privat - staatlich - kirchlich
2 Die Trennung in die Kategorien „privat“, „staatlich“ und „kirchlich“ ist für manche Feste eindeutiger, für andere kann es sich anbieten, auch mehrfärbige Berge zu gestalten und zu diskutieren. So wird Weihnachten als kirchliches, oft jedoch auch als (rein) privates Fest gefeiert. Ein möglicher Lösungsvorschlag:

- Namenstag: kirchlich, privat
- Staatsfeiertag: staatlich
- Firmung: kirchlich, privat
- Taufe: kirchlich, privat
- Hochzeit: privat, kirchlich
- Fasching: privat
- Erstkommunion: kirchlich, privat
- Weihnachten: kirchlich, privat
- Pfingsten: kirchlich
- Geburtstag: privat
- Ostern: kirchlich, privat

Es fällt somit auf, dass viele kirchliche Feste auch privat gefeiert werden – und umgekehrt. Ein Hinweis darauf, dass das Kirchenjahr genau diese Höhepunkte des Lebens strukturell begleitet, bietet sich hier bereits als Ausblick an.

* Meine Feste Hitliste
Dieser Arbeitsauftrag ist sehr persönlich und individuell. Wichtig ist, den Schüler hier keine Reihung vorzugeben (z.B. "Ostern ist wichtiger als ...") oder Reihungen zu kritisieren. Es lohnt sich, die Schüler*innen nach den Beweggründen für die Reihung bzw. der Einstufung eines bestimmten Festes als Nr. 1 zu fragen.

* Vorfreude auf ein Fest
Auch dieser Arbeitsauftrag ist sehr persönlich und individuell. Eventuell ist für manche Schüler eine Erklärung (evtl. anhand eines Beispiels) notwendig, um das Sprichwort zu erschließen.
