#+title:      [SW28] Die Bitten unseres Lebens / Das Vaterunser
#+date:       [2023-06-19 Mo 09:29]
#+filetags:   :01:sw28:
#+identifier: 20230619T092912


* Kompetenzbeschreibung
[[#B4]] Gelehrte und gelebte Bezugsreligion: Kirchliche Grundvollzüge kennen und religiös-spirituelle Ausdrucksformen gestalten können
[[#B4_KB1]] Die Schülerinnen und Schüler kennen Reichtum und Vielfalt spiritueller und liturgischer Ausdrucksformen und können sie in ihrer Bedeutung nachvollziehen und gestalten.

* AB / UH 
[[#B4_UH1]] Grundgebete / Vaterunser

* Wiederholung
RB über das Vater Unser

4.8 Das Vaterunser

Das Vaterunser ist das bekannteste Gebet des Christentums und das einzige, das nach dem Neuen Testament Jesus Christus selbst seine Jünger gelehrt hat.

Der Name „Vaterunser“ kommt aus der lateinischen Übersetzung. Die ersten beiden Wörter heißen dort „Pater noster“, wörtlich übersetzt „Vater unser“.

Zusammen mit dem Credo und den Zehn Geboten galt es als eine der Grundlagen, die jeder getaufte Christ lernen und wissen sollte. Da das Vaterunser von Jesus selbst gelehrt worden ist, wird es auch das „Gebet des Herrn“ genannt.

Es wird von Christen aller Konfessionen in den verschiedenen Sprachen auf der ganzen Welt gebetet.

In der Bibel findet man eine längere Version im Matthäusevangelium (Mt 6,9-15). Im Lukasevangelium (Lk 11,2-4) gibt es eine kürzere Version mit fünf Bitten.

Es gibt  mit dem Text des Vaterunsers sehr viele Lieder und Musikstücke, sogar eine ganze Oper wurde über das Gebet geschrieben.

* Erarbeitung

Text aus Lk und Mt lesen - und den Kontest dazu beachten:
 - Mt Bergpredigt; VU steht genau in der Mitte des Textes
 - Lk: "Herr, lehre uns beten!" - Jesus lehrt den Jüngern das VU.
 
* Hefteintrag
Vater Unser ins Heft schreiben und zu jeder Zeile eine schöne Zeichnung.

1 Dieser Arbeitsauftrag verbindet Kapitel 4.7 und 4.8 miteinander. Die Bitten des Lebens sollen mit den Bitten des Vaterunsers verglichen werden.
Als Beispiel wäre die Bitte "Ich möchte zu jemandem beten können, den ich beim Namen nennen kann." mit Punkt 1 "Wir dürfen unser Gebet direkt an einen väterlichen und mütterlichen Gott richten: Vater unser im Himmel" in Verbindung gebracht.

2 Das erweiterte Vaterunser in verteilten Rollen mit Pausen zu lesen bewirkt eine ganz besondere Atmosphäre in der Klasse. Wichtig ist das die einzelnen Strophen dabei von zwei verschiedenen Personen gelesen wird. In Klassen mit vielen Schüler*innen kann auch noch die Doxologie "Denn dein ist das Reich und die Kraft und die Herrlichkeit" angefügt werden. Anschließend können über die einzelnen Bitten gemeinsam nachgedacht werden. Auch eine Diskussion über das Vaterunser in den verschiedenen Sprachen auf Seite 72 eignen sich zur Weiterarbeit.

3 Dieser Arbeitsauftrag zielt auf die Gemeinschaft in der Kirche ab. Sich beim Gebet die Hände zu reichen drückt Gemeinschaft und Frieden aus. Hände werden beim Gebet gereicht, um zu trösten, um aufzurichten, um Mut zu machen, um zu heilen. Jeder gehört dazu, keiner wird ausgeschlossen.

4 Dieser Arbeitsauftrag greift die Methode auf den Seiten 94-95 "Ein Bild erschließen" auf. Diese basiert auf drei Schritten: Wahrnehmen – Beschreiben – Deuten

Mögliche Fragen die den Schülern beim Bild "Vater und Sohn" erschließen helfen könnten sind:

- Welche Farben siehst du auf diesem Bild?
- Welche Formen kannst du erkennen?
- Wo kommen diese Formen noch vor?
- Was geschieht in dem Bild? Erkennst du eine Handlung?
- Welche Wirkung erzeugt das Bild?
- Welche Gefühle hast du beim Betrachten des Bildes?

Wofür könnte das Schwarze Komma stehen? Wofür das Rote?
