#+title:      [SW04] Wofür Jesus streitet / Liebe, eine Grundhaltung
#+date:       [2023-06-19 Mo 21:03]
#+filetags:   :02:sw04:
#+identifier: 20230619T210331


* Kompetenzbeschreibung
[[#A1]] Menschen und ihre Lebensorientierungen - Beziehung verantwortungsvoll gestalten können – zu sich selbst, zu anderen, zur Schöpfung

[[#A1_KB2]] Die Schülerinnen und Schüler können vielfältige Formen von Liebe unterscheiden und sich mit der eigenen Geschlechtlichkeit auseinandersetzen.

* AB / UH
[[#A1_UH2]] Liebe als christliche Grundhaltung,

* Wiederholung


* Erarbeitung 
Die verschiedenen Arten der Liebe:
- Agape (christliche Liebe; geistig)
- Philia (Freundschaftsliebe)
- Eros (sinnliche Liebe)

1 Christliche Agape kann vieles bedeuten. Auf jene Bibelstelle bezogen, findet man in nahezu jedem Vers eine "Anleitung" wie man die christliche Agape leben kann:
- Liebe ohne Heuchelei
- gegenseitige Achtung
- helfen, wenn jemand in Not ist
- Gastfreundschaft
- Verfolger nicht verfluchen, sondern segnen
- Anteilnahme
- Demut
- nicht Böses mit Bösem vergelten
- Frieden halten
- Nicht Rache ausüben
- Hunger und Durst stillen
- Böses durch Gutes besiegen
- sich an staatliche Gewalt halten
- Gehorsam
- Steuern zahlen
- nichts schuldig bleiben
- an die Gebote halten

ehrenhaft sein, ohne Streit, Eifersucht, Maßlosigkeit, ohne Unzucht und Ausschweifungen

2 mögliche Antworten für diesen Arbeitsauftrag wären:
- S 12, Illustration Mutter und Lisa: beide Frauen vergreifen sich hier im Umgang mit der jeweils anderen. Die Mutter könnte sagen: "Lisa, bitte räume dein Zimmer auf" und Lisa könnte antworten: "Mama, ich habe gerade wirklich viel für die Schule zu tun, ich räume am Wochenende zusammen."
  
- S 14, der Chatverlauf: Diesen Chatverlauf könnte man tatsächlich in Giraffensprache umschreiben. Hier kämen dann Aussagen wie "Wir könnten einmal mit Elena sprechen, wie wir sie und sie sich besser in unsere Klassengemeinschaft einbringen können/kann." oder "Können wir sie im Turnunterricht unterstützen, damit sie sich leichter tut?"
  
- S 16, Die Sätze der Wolfssprache in Giraffensprache übersetzen: Ich würde mir wünschen, dass du pünktlich bist. Mir wäre es wichtig, dass du nächstes Mal besser aufpassen würdest. Spielen macht uns allen mehr Spaß, wenn jeder einmal den Ball bekommen könnte. Ich bin heute ein wenig gereizt, bitte sei etwas leiser.

3 Die verschiedenen Symbole können auch unterschiedlich gedeutet werden. Das Herz mit dem Kreuz in der Hand könnte "Ein Herz für andere haben!" bedeuten, das Herz mit den Figuren rund herum kann als "Gemeinschaft leben" gedeutet werden, die Hände, die sich in der Mitte sich halten als "zusammenhelfen, Zusammenhalt", der Große, der den Kleinen umarmt als „andere beschützen“, der lachende und der traurige Smiley als "trösten", der Regenschirmhalter als "andere unterstützen, helfen", Die Hand mit dem Geldstück als „spenden“ und der Erdball mit dem Herz als "auf die Schöpfung achten, Klimaschutz" .
die drei freien Kästchen sind für jeden Schüler frei wählbar. Man kann auch den im Auftrag 1 genannten Bibeltext zu Hilfe nehmen.

4 Caritas ist das lateinische Wort für Agape, also die Liebe Gottes zu den Menschen und die Liebe der Menschen zu Gott. Die katholische Organisation Caritas hilft Menschen, die am Rande der Gesellschaft stehen (Obdachlose, Migranten/Migrantinnen, Flüchtlingen, Suchterkrankte, ...). Die Menschen, die oft auch ehrenamtlich sich bei der Caritas engagieren, leben vorbildliche und lebendige Agape vor.

5 Elisabeth von Thüringen: Sie teilte ihre Kleidung, kümmerte sich um Arme und Kranke, half den Menschen, spendete einen Großteil ihres Vermögens, gründete ein Krankenhaus, arbeitete dort als Krankenschwester

6 Die meisten Heiligen lebten vollkommen mit der christlichen Grundhaltung der Agape.

7,8 Diese beiden Aufträge sind individuell zu lösen.


* Heftarbeit

