#+title:      [SW35] Durstrecken unseres Lebens / Grund zu feiern
#+date:       [2023-06-19 Mo 14:54]
#+filetags:   :01:sw35:
#+identifier: 20230619T145418


* Kompetenzbeschreibung
[[#C5]] Religiöse und weltanschauliche Vielfalt in Gesellschaft und Kultur: Medien, Kunst und Kultur im Kontext religiöser Weltwahrnehmung interpretieren, beurteilen und gestalten können

Die Schülerinnen und Schüler können das Kirchenjahr mit seinen Festen als Rhythmus des Lebens verstehen und mitgestalten.

* AB / UH
[[#C5_UH1]] Feierkultur

* Wiederholung


* Erarbeitung

** Feste dieser Welt
1 Die richtige Nummerierung der Zuordnungstexte lautet:

    6 Seit 1940 wird jedes Jahr im August die größte öffentliche Tomatenschlacht der Welt gefeiert.
    2 Das aus dem Hinduismus stammende Frühlingsfest wird auch das „Fest der Farben“ genannt.
    5 Über sechs Millionen Besucherinnen und Besucher feiern von Ende September bis Anfang Oktober das größte Volksfest der Welt.
    4 An diesem Tag wird ein Bischof gefeiert, der den christlichen Glauben auf die „grüne Insel“ gebracht hat.
    3 Die farbenfrohe Parade der Sambaschulen von Rio de Janeiro ist der Höhepunkt der Faschingszeit, die bis zum Aschermittwoch dauert.
    1 An den Festtagen Allerheiligen und Allerseelen wird mit bunten Verkleidungen und Figuren an die Verstorbenen gedacht.

2 Dieser Arbeitsauftrag kann entweder frei oder angelehnt an die Kategorien von S. 89 bearbeitet werden. Während die freie Bearbeitung persönliche und individuelle Antworten provoziert, könnte eine Zuordnung auf Basis der Kategorien von S. 89 wie folgt aussehen: ¨¨

    Weil wir für etwas dankbar sind: Karneval, St. Patrick’s Day, Holi
    Weil wir zusammenkommen können: Oktoberfest, Holi, St. Patrick’s Day, Karneval, La Tomatina
    Weil wir an jemanden denken: Dia de los Muertos, St. Patrick’s Day
    Weil wir uns über etwas freuen: La Tomatina, Karneval, Holi

3 Dieser Arbeitsauftrag ist sehr persönlich und individuell. Je nach persönlicher Erfahrung der Schüler*innen können hier sehr unterschiedliche Feste genannt werden. Gerade in ländlichen Bereichen sind auch sehr regionale Feste und Bräuche verbreitet, die Kinder gerne miterleben und erzählen.

4 Gerade das Fest „La Tomatina“ und das Oktoberfest machen deutlich, dass Feste oft auch einen verschwenderischen Charakter haben. Thematisiert werden könnte neben der Genusssucht und Verschwendung vor allem die Problematik des Mülls, der fehlende Sinn hinter manchen Festen sowie das „immer Mehr“ bei Festen: Feste müssen immer größer werden, ständig Besucherrekorde brechen und „noch pompöser“ sein als im Vorjahr. Sofern sich die Schüler*innen an Feste während der Corona-Pandemie 2020/2021 erinnern können, kann hier thematisiert werden, wie sich Feste – z.B. Weihnachten und Ostern – in dieser Zeit von den Jahren davor und danach unterschieden haben. Es kann sich lohnen danach zu fragen, ob Feste im Kleineren oder Größeren mehr Sinn und Freude vermitteln können.


** ?
1 Dieser Arbeitsauftrag ist sehr persönlich und individuell. Die Schüler*innen nutzen hier die Illustration des Berges (vgl. Bild der „Gipfel“ auf S. 84) um anhand der Metapher des Berges den Anstieg zu Festen zu reflektieren. Mögliche Zuordnungen/Nennungen könnten sein:

- Stolpersteine: Schularbeiten, schlechte Noten, Stress, Streit, Langeweile, Verletzungen, ...
- Energiequellen: Freundinnen und Freunde, Familie, Sonne, Hobbys, gutes Essen, ...
- Weggabelungen: Entscheidungen (z.B. an welche Schule man geht), Streit oder Versöhnung, Lernen oder Freizeit, ...
- Gipfel: Persönliche Ziele, Feste oder Zeiten, auf die man sich besonders freut – z.B. Ferien, ein gutes Zeugnis, Feste im Jahr, ...

2 Die Bergsteigerin Gerlinde Kaltenbrunner beschreibt mit ihrem Zitat, dass das Bergsteigen immer ein Ganzes aus Anstieg, Gipfel und Abstieg ist. Als Metapher für das Leben könnte dieses Zitat bedeuten, dass es auch im Leben immer mühsame Anstiege und Durststrecken geben muss, um die Gipfel genießen zu können, sowie anschließende Abstiege, um einen erneuten Anstieg zu ermöglichen. Dauerhafte Gipfelerlebnisse nutzen sich ab. Auch Erkenntnisse der Glücksforschung (z.B. Wilhelm Schmid) bestätigen diese Erkenntnis: Glücksmomente sind nicht dauerhaft, für ein dauerhaftes Glück – im Sinne einer Zufriedenheit – braucht es auch immer wieder Erholungs- und Anstrengungsphasen. Nur so bleiben die besonderen Gipfel auch besonders. Mit Schüler*innenn kann hier etwa gefragt werden, wie ein Leben wäre, an dem sie jeden Tag Geburtstag haben. Nach einer ersten Euphorie merken die Kinder oft sehr schnell, dass sie die Besonderheit des Festes so nicht mehr erleben könnten.

3 Dieser Arbeitsauftrag ist sehr persönlich und individuell. Oft genannt werden positive wie negative Aspekte von Schule, Familie und Freundschaft (vgl. AA1).

4 Hier bietet sich eine Internetrecherche zur Person Gerlinde Kaltenbrunners an. Als eine der erfolgreichsten Extrembergsteigerinnen hat sie viele Gipfel erklommen, aber auch immer wieder mühsame Anstiege vor sich gehabt – und nicht selten den einen oder anderen Gipfelsturm abbrechen müssen. Auch diese speziellen Erfahrungen lassen sich als Metapher auf das Leben übertragen. Mit den Schüler*innenn kann besprochen werden, wie solche Enttäuschungen und Schwierigkeiten im Leben positiv wirken können.

* Hefteintrag
Die Stunden zum Thema "Maria" hole ich in der 1a und 1b nach. In der 1c habe ich heute 3 Stellen im NT zum Thema "Maria" angeschaut: Hochzeit von Kana, die wahren Verwandten Jesu, Magnifikat.
