#+title:      Jahresplanung
#+date:       [2023-06-22 Do 00:26]
#+filetags:   :jahresplanung:
#+identifier: 20230622T002636

Wie soll ich die Jahresplanung einbinden?

Auf der einen Seite habe ich die 10 Dateien für jede Klasse. Darin finde ich:
- den Stundenplan mit dem aktuellen Stoff
- die Klassenbuchliste: Noten, etc.
- Reflexionen zu den Stunden
- Aufzeichnungen der Mitarbeit zu jedem Schüler

Zuerst habe ich gedacht, dass ich die Jahresplanung in der org-agenda aufscheinen lasse. Aber das würde zu viele Dateien laden; v.a. würde die agenda mit unzähligen TODO headings überschwemmt.

Ausgehend von der Klassen-Datei soll ich einfachen Zugang zur Jahresplanung haben.

Außerdem soll die Jahresplanung nicht "in Stein gemeiselt" sein. Das heißt: eine Liste mit Datum / Schulwoche und dem Stoff (Titel der Datei). Die Dateien sollte ich leicht verschieben können. Wenn nun die SW im Datei-Namen vorkommt, wird es komisch. Oder doch nicht? Dies zu ändern, ist jetzt sehr aufwendig. Dieses Beispiel unterhalb sieht ja nicht so schlecht aus. Ich könnte in jeder Spalte eine Zeile verschieben...

Die Frage: eine Datei pro Schulstufe? Oder diese Planung in jedes Klassen-Datei?

* Jahresplannug 01

| Datum           | SW | Stoff                                                     |
|-----------------+----+-----------------------------------------------------------|
| <2023-09-11 Mo> | 01 | [[denote:20230619T073700][[SW01] Jahresstoff / ich stehe in den Schuhen des Anderen]] |
| <2023-09-18 Mo> | 02 | [[denote:20230619T074010][[SW02] Eine Gemeinschaft, die uns stärkt]]                  |
|                 |    |                                                           |

