#+title:      [SW27] Vielfalt unseres Betens / wie wir beten können
#+date:       [2023-06-19 Mo 09:27]
#+filetags:   :01:sw27:
#+identifier: 20230619T092702



* Kompetenzbeschreibung
[[#B4]] Gelehrte und gelebte Bezugsreligion: Kirchliche Grundvollzüge kennen und religiös-spirituelle Ausdrucksformen gestalten können
[[#B4_KB1]] Die Schülerinnen und Schüler kennen Reichtum und Vielfalt spiritueller und liturgischer Ausdrucksformen und können sie in ihrer Bedeutung nachvollziehen und gestalten.

* AB / UH 
[[#B4_UH1]] Arten / Formen des Gebets

* Wiederholung
4.5 Die Vielfalt des Betens
Diese Seite soll den Unterschied zwischen dem allgemeinen Gebet und dem persönlichen Gebet verdeutlichen. Beim persönlichen Gebet handelt es sich um das individuelle Gebe, das jede*r einzelne Christ*in persönlich an Gott richtet. Die kann durch ganz individuelle, eigene Worte oder auch durch vorgefertigte Gebete geschehen. Christliches Beten in der Kirche bedeutet Beten in Gemeinschaft mit Jesus Christus und den Mitmenschen.

4.6 Wie wir beten können
Beten soll nicht einfach so geschehen, sondern der Betende soll mit all seinen Gedanken, Worten und seinem Tun dabei sein. Jesus selbst lehrt in der Bibel den Jüngern das Beten. Wichtig ist das die Menschen das Gebet ehrlich meinen und nicht, dass sie nur versuchen, gut vor den anderen Menschen dazustehen. Den Schüler*innen soll vermittelt werden, dass Gott genauso auf die leisen Gebete hört, dass es nicht immer notwendig ist das Gebet laut auszusprechen. Man kann, wenn das Gebet ehrlich gemeint ist, nicht falsch beten. Es gibt keine falschen Worte aber jedoch ein falsches Handeln. Im Gebet geht es in erster Linie darum mit Gott in Beziehung zu kommen.

* Erarbeitung

** Vielfalt unseres Betens
1 Lösungsvorschlag:

Gebet 1 (Herr mache mich zu einem Werkzeug deines Friedens ...) könnte gebetet werden, bei offenen Konflikten und Streit.

Gebet 2 (Geheiligt werde dein Name) könnte gebetet werden, wenn etwas nicht so läuft wie man es gerne haben möchte.

Gebet 3 (Danke, mein Vater, ...) könnte, wenn das Wetter an einem besonderen Tag schön ist, z.B. bei einem Wandertag, gebetet werden.

Gebet 4 (Ehre sei dem Vater) wird bei vielen Anlässen gebetet. Ist auch ein Teil des Rosenkranzgebetes

Gebet 5 (Gegrüßet seist du, Maria) wird in vielen Familien am Heiligen Abend gebetet.

Gebet 6 (Komm Herr Jesus) Mittagsgebet; Gebet bei einer Mahlzeit

Gebet 7 (Der Herr segne und behüte dich) Immer, wenn jemand etwas Besonderes vorhat. Zum Beispiel vor einer Reise, vor einer Prüfung, etc.

2 Mit diesem Arbeitsauftrag werden feste Gebete den unterschiedlichen Lebenssituationen zugeordnet in der die Gemeinschaft besonders wichtig erscheint. Meist finden die Schüler*innen genügend Beispiele und Begründungen.

3 Dieser Arbeitsauftrag ist sehr persönlich und individuell. Es bietet sich allerdings eine Besprechung und/oder Diskussion der Hintergründe an ("Warum ist das bei dir so?").

4 Dieser Arbeitsauftrag kann genutzt werden, um für die Klasse eine Gebetssammlung anzulegen. Verschiedene Gebete als Vorlage können den Schülern helfen, selbst kreative Gebete zu verfassen.

** Wie wir beten können
1 Dieser Arbeitsauftrag ist sehr persönlich und Da die Schüler*innen die Fragen unterschiedlich verstehen und beantworten können. Die erste Frage Was bedeutet es beim Beten zu "heucheln" und zu "plappern"? zielt auf das zur Schau stellen, die Scheinheiligkeit, anderen etwas vormachen ab. Die zweite Frage "Warum ist es nicht gut, wenn wir beim Beten gesehen werden wollen" bezieht sich unter anderem darauf, etwas vorgeben zu wollen, dass nicht ernst gemeint ist. Bei der dritten Frage "Wie kann Beten gelingen?" finden die Schüler*innen meist gute Beispiele und Begründungen.

2 Dieser Arbeitsauftrag könnte auf diese Weise bearbeitet werden:
Dos: für dich alleine, in Ruhe, so dass es die anderen nicht unbedingt bemerken, mit wenig Worten, in Stille, ...
Don’ts: nicht öffentlich, nicht beten nur um gesehen zu werden, nicht plappern - ohne die Worte ernst zu nehmen, ...

3 Dieser Arbeitsauftrag dient zur Reflexion des Comics. Hilfreich ist eine erneute Betrachtung der einzelnen Bilder mittels Impulse, wie: Lisa sitzt alleine in der Kirchenbank. Sie hat nicht viele Worte. Stellt sie sich zur Schau? Will sie von anderen gesehen werden? Was macht sie richtig/falsch?

* Hefteintrag

Stell Dir vor - Du bist drei Jahre mit Jesus unterwegs und Du könntest Dir eine seiner Fähigkeiten aussuchen. Diese Fähigkeit würde Jesus Dir schenken. Was wäre das?

Was haben sich die Jünger ausgesucht? "Herr, lehre uns beten!" (Jesus hat den Jüngern auch die Fähigkeit geschenkt, Kranke zu heilen, Tote aufzuerwecken, Wunder zu wirken, etc ...)

[[https://www.youtube.com/watch?v=Zhst9zhHu70]]

Wir Menschen sind Gewohnheits"tiere":
 - ruhiger Ort
 - ruhige Zeit
 - Nimm dir Zeit: 20 Minuten
 - Mit wem triffst du dich? Mit Gott ...
 - Lies in der Bibel - lass dich ansprechen vom Text
 - Lass Gott Zeit zu antworten
 - Halte das aus! Stille lohnt sich ...

   
