#+title:      Konfuzius
#+date:       [2023-10-17 Di 08:33]
#+filetags:   :religion:
#+identifier: 20231017T083344

[[https://de.wikipedia.org/wiki/Konfuzius]]
Konfuzius – latinisiert aus Kong Fuzi (chinesisch 孔夫子, Pinyin Kǒng
Fūzǐ, W.-G. K'ung-fu-tzu – „Lehrmeister Kǒng“) – im Chinesischen auch
Kǒng Zǐ (孔子, K’ung-tzǔ – „Meister Kǒng“, veraltet nach Wilhelm
Kung-tse,[1]Vissière Kong-tseu[2]transkribiert) genannt, war ein
chinesischer Philosoph zur Zeit der Östlichen Zhou-Dynastie. Er lebte
vermutlich von 551 v. Chr. bis 479 v. Chr. und wurde unter dem Namen
Kong Qiu (孔丘, Kǒng Qiū, K’ung Ch’iu) in der Stadt Qufu im
chinesischen Staat Lu (der heutigen Provinz Shandong) geboren, wo er
auch starb. 

Das zentrale Thema seiner Lehren war die menschliche Ordnung, die
seiner Meinung nach durch Achtung vor anderen Menschen und
Ahnenverehrung erreichbar sei. Als Ideal galt Konfuzius der „Edle“
(jūnzĭ, 君子), ein moralisch guter Mensch. Edel kann der Mensch dann
sein, wenn er sich in Harmonie mit dem Weltganzen befindet: „Den
Angelpunkt zu finden, der unser sittliches Wesen mit der
allumfassenden Ordnung, der zentralen Harmonie vereint“, sah Konfuzius
als das höchste menschliche Ziel an. „Harmonie und Mitte, Gleichmut
und Ausgeglichenheit“ galten ihm als erstrebenswert. Den Weg hierzu
sah Konfuzius vor allem in der Bildung. 


