#+title:      [SW08] Geschaffen für das ewige Leben
#+date:       [2023-07-11 Di 00:35]
#+filetags:   :04:sw08:
#+identifier: 20230711T003525


* Kompetenzbeschreibung
[[#B3]] Gelehrte und gelebte Bezugsreligion - Grundlagen und Leitmotive des christlichen Glaubens kennen und für das eigene Leben deuten können
[[#B3_KB1]] Die Schüler können Leiden, Sterben und Auferstehung Jesu Christi als Hoffnungsbild für Menschen reflektieren.

* AB / UH
[[#B3_UH1]] österlicher Glaube als christliche Lebenshaltung

* Wiederholung


* Erarbeitung

[[id:56e0bc4a-61da-4d0e-9472-42e6d35d31d0][Ewiges Leben]]

[[id:36daae02-52dd-45c4-b0e8-1248f400cbbe][Ewiges_Leben]]

"Das ewige Leben beginnt mit der Taufe." Diese Aussage des YouCat ist das eigentliche Ziel dieser UE. 

Ist dieses Thema eigentlich für Jugendliche relevant? 

Wie komme ich mit ihnen darüber ins Gespräch? Allerheiligen und Allerseelen als Anlass ist zwar gegeben; in der 4B gab es einen tragischen Todesfall (ein Bursch hat seinen Vater verloren).

 - Welche Vorstellungen haben die Kinder vom "ewigen Leben"?
 - Welche Rolle spielt dieses Thema im Alltag der Kinder?

Theologischer Hintergrund:
Neues Lexikon der katholischen Dogmatik:
"Das E.L. ist das in Gott begründete Leben in Fülle, das aufgrund seiner Selbstmitteilung bereits irdisch anhebt und nach dem Tod vollendet wird." cite:Beinert2012 (S.206)

Der Glaube an Jesu Tod und Auferstehung prägt den Glauben an das E.L. neu. Da Jesus sein Leben für uns hingegeben hat, führt er uns zum Leben mit ihm. Jesus ist Herr über Lebende und Tote, sein Geist ist "lebendig machender Geist".

Themen:
- allgemeines und persönliches Gericht
- wieder einmal in der Bibel lesen ...
- Beten ...

Das Größte: Schüler zu einer persönlichen Beziehung mit Jesus führen.

Gemeinsames Bibellesen:
Lk 19, 1-10

[[id:04739c4d-3013-4c93-b807-5c74f28f9819][Jesus und Zachäus]]

* Hefteintrag
