#+title:      [SW42] Übungsteil
#+date:       [2023-06-19 Mo 15:00]
#+filetags:   :01:sw42:
#+identifier: 20230619T150019


* Kompetenzbeschreibung
[[#C6]] Religiöse und weltanschauliche Vielfalt in Gesellschaft und Kultur - Unterschiedlichen Lebensweisen und Glaubensformen reflexiv begegnen können
[[#C6_KB1]] Die Schülerinnen und Schüler können Gemeinsames und Unterscheidendes, Verbindendes und Trennendes von Konfessionen und Religionen benennen und sich damit respektvoll auseinandersetzen. 


* AB / UH
[[#C6_UH1]] Respekt Toleranz

* Wiederholung
[[file:KompSozial.2006.org][KompSozial.2006: Kompendium der soziallehre der kirche]]

* Erarbeitung

[[http://www.k-l-j.de/bibelstelle.htm]]
("Bibelstelle ziehen" generiert eine Bibelstelle.)


Wer ist Jesus dür Dich?

persönlich schönste Segens-Bibelstelle aufschreiben. 

Hl. Petrus und Hl. Paulus:
[[https://www.youcat.org/de/credopedia/minicat/heiliger-petrus-und-paulus/]]
Die Schlüsselgewalt des heiligen Petrus umfasst drei Momente:

- Das wichtigste ist die *Vergebung der Sünden:* Petrus hat die Vollmacht jede Sünde, und wenn sie noch so grauenhaft wäre, im Namen Jesu zu vergeben, weil Jesus will, dass alle Menschen gerettet werden und zur Erkenntnis der Wahrheit gelangen.

- Darüber hinaus die *Glaubensverkündigung:* Petrus hat ein Charisma in Bezug auf Glaubenswahrheiten und Sitten. Wir müssen nämlich zwei Dinge wissen, um das ewige Leben zu gelangen: Einerseits, was uns über Gott offenbart wurde — also, was wir über Ihn wissen dürfen— und zweitens, wie ich als Christ Leben zu leben habe.

- Drittens umfass die *Schlüsselgewalt d disziplinarischen Aspekte*. Die dem Petrus anvertraute Vollmacht ist so groß, dass selbst Paulus - dem Jesus selbst erschienen ist und der nie eine menschliche Offenbarung brauchte, sondern alles vom Herrn selbst erfahren hat - zu Petrus ging und um eine Bestätigung seiner Lehren bat, um sicher zu gehen, dass er — wie er sagt — nicht ins Leere läuft oder gelaufen ist (vgl. Gal 2,2). Erst nachdem Petrus seine Lehre bestätigt hatte, ging Paulus in die Welt hinaus und verkündete diese den Heiden.

[[https://www.youcat.org/de/credopedia/minicat/heiligsten-herzens-jesu/]]
    
* Hefteintrag

