#+title:      Elternsprechtag
#+date:       [2023-11-28 Di 15:28]
#+filetags:   :Project:schule:
#+identifier: 20231128T152836
#+CATEGORY: golling

* DONE Barbara Krallinger (Schüler Thomas Krallinger, 4b)
CLOSED: [2023-11-28 Di 18:02] SCHEDULED: <2023-11-28 Di 17:41-17:48>
:LOGBOOK:
- State "DONE"       from              [2023-11-28 Di 18:02]
:END:

Thomas - es läuft weentlich besser als letztes Jahr; die Gruppenarbeit scheint ihm und seinen Freunden gefallen zu haben (va das Erstellen eines Kahoots). 

* DONE Anita Egger (Schüler Tobias Egger, 3c)
CLOSED: [2023-11-28 Di 18:02] SCHEDULED: <2023-11-28 Di 18:16-18:23>
:LOGBOOK:
- State "DONE"       from              [2023-11-28 Di 18:02]
:END:

Hm; schwierig einzuschätzen. Er äußert manchmal recht "extreme" Ansichten, die dann teils von mir, besonders aber von seinen Mitschülern widerlegt werden. Manche dieser Ansichten kann ich einfach nicht für sich stehen lassen, da sie "gefährlich" sind. Er scheint mir etwas belehrungs-resistent zu sein (die ganze Welt ist dumm; wer bestimmte Parteien wählt sollte nicht wählen gehen dürfen; die Depperten dürfen nicht wählen gehen, ...) Scheint mir Provokation zu sein. Er kann lügen ohne mit der Wimper zu zucken.

Meinungsfreiheit kann kein Vorwand sein, anderen Menschen ihre Freiheit abzusprechen (Dumme dürfen nicht wählen gehen). 

In meine Stunde kam der KV einer Nachbarklasse: Tobias hat eine leere Plastikflasche in seiner Klasse entsorgt, indem er diese bei der Tür reingeworfen hat.

Ich hab ihn öfters ermahnt - er wiederholt meine Worte wie ein Papagei.

* Kerstin Jochinger (Schüler Rudolf Jochinger, 1b)
SCHEDULED: <2023-11-28 Di 18:37-18:44>

Bin ich überfragt - wer ist das?

* Monika Malter (Schüler Leonhard Malter, 2a) 
SCHEDULED: <2023-11-28 Di 18:44-18:51>

* Herr Struber (Schülerin Valentina Struber, 2b)
Fand es zu Beginn des Schuljahres sehr schade, als Valentina gemeint hat, dass sie sich abmelden will. Da sie die beste Schülerin in dieser Klasse in Religion ist. 
