#+title:      Golling
#+date:       [2023-01-03 Di 18:03]
#+filetags:   :Project:golling:
#+identifier: 20230103T180316
#+CATEGORY: golling


* Tasks

** Sprechstunde 09:35-10:25
<%%(org-class 2023 9 12 2024 7 6 3 26)>

** Supplierstunde 1a BE / Textiles Werken
<2023-09-22 Fr 09:35>--<2023-09-22 Fr 10:25>

** Supplierstunde 1a M (statt Eva, mit Bernadette L.)
<2023-09-27 Mi 09:35>--<2023-09-27 Mi 10:25>

** Fr. Weninger Schulbücher (Reduktionen, ...)
<2023-09-27 Mi 08:35>--<2023-09-27 Mi 09:30>
Rückmeldung von Mirjam: einige der BU-Bücher haben kein Etikett?

*** DONE [#A] Lieferscheine suchen, Bücher bestätigen
CLOSED: [2023-10-18 Mi 07:57]
:LOGBOOK:
- State "DONE"       from "TODO"       [2023-10-18 Mi 07:57]
:END:
Fr. Weninger wird mir die Kopien derLieferscheine nachschicken. Somit kann ich gelieferten Bücher bestätigen.

Teilbestätigung: Nur bei den geleiferten Büchern die Menge eingeben. ALLE ANDEREN Bücher auf "0" setzen.

Ordner anlegen: Pro Klasse, dann Fächer. Oder pro Fach, innerhalb pro Klasse?

** VS Hallein-Burgfried GTS 13:55-14:45
<%%(org-class 2023 9 13 2024 7 7 3 18)>

** Fachkonferenz Hallein Neualm
<2023-10-02 Mo 15:00>--<2023-10-02 Mo 18:15>

** Lehrerausflug nach Leogang
<2023-10-13 Fr 11:30>--<2023-10-13 Fr 20:00>
Gotik Museum - Essen

** Supplierstunde TD 1a (statt Erwin Essl)
<2023-11-17 Fr 09:35>--<2023-11-17 Fr 10:25>

Idee von Martin: aus Ton mit Keksformen Sterne, etc ausstechen, brennen ... als Weihnachtsdeko.


* Alte Termine

** Supplierstunde 1a ME
<2023-04-14 Fr 10:40>--<2023-04-14 Fr 11:30>

** Frau Weninger Schulbuchaktion
<2023-04-20 Do 09:45>--<2023-04-20 Do 11:00>

** Elternsprechtag MS Golling 
<2023-04-19 Mi 15:00>--<2023-04-19 Mi 18:00>
Frage: ist das überhaupt für mich möglich? Va da kaum Eltern zu mir kommen...

** Supplierstunde 2c ME (Sarah Blum)
<2023-04-24 Mo 11:35>--<2023-04-24 Mo 12:25>

Musikzeitschrift mir DVD;
Filmmusik Hans Zimmer (ab S. 60)
S. 70+71 Arbeitsblätter

** Supplierstunde 4b BU (Mirjam Seiwald)
<2023-04-26 Mi 12:30>--<2023-04-26 Mi 13:20>

Verdauung, ... Buch S. / Arbeitsblätter

** Supplierstunde 4a IKT (statt Manuela Singer; cf Teams)
<2023-05-03 Mi 10:40>--<2023-05-03 Mi 11:30>

Cf. Vorbereitung von Ela in der blauen Mappe

** Pädagogische Konferenz
<2023-05-04 Do 15:30>--<2023-05-04 Do 17:30>

** Supplierstunde 2c BSP
<2023-05-09 Di 11:35>--<2023-05-09 Di 12:25>

** Supplierstunde 1b D
<2023-05-10 Mi 08:40>--<2023-05-10 Mi 09:30>

** Supplierstunde 1b D
<2023-05-11 Do 10:40>--<2023-05-11 Do 11:30>
mit Manuela Singer
Thema: Sagen / direkte Rede

** Supplierstunde 3c D 
<2023-05-12 Fr 09:35>--<2023-05-12 Fr 10:25>
statt Gertraud V., mit Erwin 

** Supplierstunde 2c D (statt Erwin, mit Mirjam)
<2023-05-22 Mo 09:35>--<2023-05-22 Mo 10:25>

** Supplierstunde 1b D (statt Erwin, mit Manuela S.)
<2023-05-23 Di 09:35>--<2023-05-23 Di 10:25>

** Supplierstunde 1b E (statt Christoph, mit Barbara Eßl)
<2023-05-25 Do 09:35>--<2023-05-25 Do 10:25>

** Pädagogische Konferenz - QMS
<2022-12-15 Do 16:00>--<2022-12-15 Do 17:30>

** Weihnachtsgottesdienst MS Golling 
<2022-12-23 Fr 11:45>--<2022-12-23 Fr 12:30>

** Skitag 2b (Wolfi) Zauchensee
<2022-12-14 Mi 07:45>--<2022-12-14 Mi 14:00>

7:45 Treffpunkt am Bahnhof

** Supplierstunde 3a D
<2022-12-21 Mi 10:40>--<2022-12-21 Mi 11:30>

** Supplierstunde 1a D
<2022-12-22 Do 09:35>--<2022-12-22 Do 10:25>

** Supplierstunde 2b PH 
<2023-01-11 Mi 11:35>--<2023-01-11 Mi 12:25>

** Supplierstunde 4a IKT
<2023-02-01 Mi 10:40>--<2023-02-01 Mi 11:30>

** Supplierstunde 3a M
<2023-02-09 Do 09:35>--<2023-02-09 Do 10:25>
mit Hannes L. (statt Ulrike Gruber)

** Pädagogische Konferenz Jänner 2023
<2023-01-16 Mo 16:00>--<2023-01-16 Mo 18:00>

** Eislaufen 3b Salzburg 
<2023-02-21 Di 08:20>--<2023-02-21 Di 13:00>

** Pädagogische Konferenz
<2023-03-07 Di 16:00>--<2023-03-07 Di 17:30>

** Supplierstunde 4a M (für MB)
<2023-03-13 Mo 07:45>--<2023-03-13 Mo 08:35>

** Supplierstunde 4a M (für MB)
<2023-03-14 Di 07:45>--<2023-03-14 Di 08:35>
mit Irmi - beide 4. Klassen, beide Leistungsgruppen.

** Supplierstunde 4a BSP
<2023-03-15 Mi 11:35>--<2023-03-15 Mi 12:25>
Lt Eva muss ich nicht dabei sein.

** Supplierstunde 4a M (für MB)
<2023-03-16 Do 09:35>--<2023-03-16 Do 10:25>

** Supplierstunde 4a M (für MB)
<2023-03-17 Fr 08:40>--<2023-03-17 Fr 09:30>
Schularbeit - Irmi 4b; ich 4a.

** Treffen mit Fr. Krallinger
<2023-03-16 Do 10:40>--<2023-03-16 Do 11:00>

[[denote:20230310T173200][Gespräch Krallinger]]

** Supplierstunde 1b D (statt DA, mit Gertraud V.)
<2023-03-21 Di 09:35>--<2023-03-21 Di 10:25>

** Supplierstunde 1b D (statt DA, mit Martin)
<2023-03-22 Mi 08:40>--<2023-03-22 Mi 09:30>

** Supplierstunde 1b E (statt RC, mit LB)
<2023-03-23 Do 09:35>--<2023-03-23 Do 10:25>

** Supplierstunde 2c BSP (statt RC)
<2023-03-23 Do 10:40>--<2023-03-23 Do 11:30>
alleine? Christoph fragen...

** Supplierstunde 1a D (statt Si, mit Mirjam)
<2023-03-24 Fr 09:35>--<2023-03-24 Fr 10:25>

SÜ:
- Exzerpt zum Thema "Wasschbär" schreiben, ausgehend der (fast) fertigen Mindmap.
- Mindmap anhand des Infotextes ergänzen.

Quelle: Geolino, Tierlexikon. [[https://www.geo.de/geolino/tierlexikon/2557-rtkl-tierlexikon-waschbaer]]

** Seniorenheim Golling (BO Tage 3. Klassen)
<2023-03-22 Mi 09:45>--<2023-03-22 Mi 12:25>

mit: Kristina, Verena, Christina; Theresa, Melanie, Nikola, Mia, Alex.

** Ostergottesdienst (Pfr Schwarzenauer)
<2023-03-31 Fr 11:30>--<2023-03-31 Fr 12:30>

** Supplierstunde 2a BE (Sarah Blum)
<2023-04-13 Do 09:35>--<2023-04-13 Do 10:25>

** Pädagogische Konferenz MS Golling
<2023-06-12 Mo 16:00>--<2023-06-12 Mo 18:00>

** Supplierstunde 3a M (statt Hannes)
<2023-06-15 Do 09:35>--<2023-06-15 Do 10:25>

** Supplierstunde 4a IKT (statt Wolfi)
<2023-06-14 Mi 10:40>--<2023-06-14 Mi 11:30>

** Abschlussgottesdienst MS Golling
<2023-07-06 Do 08:00>--<2023-07-06 Do 08:45>

** Abschlussfeier 4. Klassen
<2023-07-06 Do 10:00>--<2023-07-06 Do 11:30>
Technik

** Mittagessen mit Lehrer Kollegen
<2023-07-06 Do 12:00>--<2023-07-06 Do 13:30>

** Supplierstunde 4a/b DG (statt Wolfi)
<2023-06-28 Mi 10:40>--<2023-06-28 Mi 11:30>

** Feststellungsprüfung Physik Vivienne
<2023-07-05 Mi 08:00>--<2023-07-05 Mi 09:00>

** Notenkonferenz
<2023-06-29 Do 15:00>--<2023-06-29 Do 18:00>

** Frau Weninger - Schulbücher nachbestellen
<2023-06-30 Fr 10:25>--<2023-06-30 Fr 11:30>
es gibt eine dritte erste Klasse: Klassenbuchlisten ausdrucken

Alle Fächer außer den Hauptfächern erhalten ein eBook (statt eBook+)

** Probe Abschlussfeier
<2023-07-04 Di 07:45>--<2023-07-04 Di 12:25>
Tontechnik

** Generalprobe Abschlussfeier
<2023-07-05 Mi 07:45>--<2023-07-05 Mi 12:25>
Tontechnik

** Aufräumen
<2023-07-07 Fr 07:45>--<2023-07-07 Fr 08:45>

** Abschlusskonferenz
<2023-07-07 Fr 09:00>--<2023-07-07 Fr 10:00>

** Aufräumen, Gottesdienst (Lieder)
<2023-07-03 Mo 07:45>--<2023-07-03 Mo 12:25>
Feststellungsprüfung Vivienne (?)

** TODO Lieder für Schulgottesdienst
<2023-07-02 So 21:00>--<2023-07-02 So 22:00>

** 1a
<2023-09-08 Fr 11:35>--<2023-09-08 Fr 12:25>

