#+title:      Jesus Weltreligionen
#+date:       [2023-06-13 Di 15:10]
#+filetags:   :jesus:weltreligionen:
#+identifier: 20230613T151033

Menschen verdienen immer Würde (oder Toleranz); Systeme sollen, müssen wir geistlich konfrontieren - aber Systemen dürfen wir nicht tolerant sein - auch den guten nicht.

Weltreligionen = Rettung durch Werke
- Wissen
- Moral
- Rituale

Religion = eigentlich wie ein Pflaster über ein verletztes Herz des Menschen.

Jesus = den Vater kennen; es geht um das Herz; eine Bewegung von oben nach unten. Das Christentum ist keine Religion, sondern die Rettung durch die Liebe eines Erlösers.

Jesus bringt das verletzte Herz des Menschen in Verbindung mit dem Vater.

Wenn du dich verlaufen hast, also du das Problem bist, dann kannst du dich nicht erlösen. Es geht nur, wenn jemand von außen an dich herantritt.

Alle Religionen führen zu Gott. Ach? Das sagt der Islam nicht, der Buddhismus nicht, der Hinduismus nicht. Keine Religion behauptet, dass alle Religionen gleich sind.

Andere Religionen wertschätzen. Wo immer Menschen sind, gibt es Gutes, Schönes und Wahres. Unser christlicher Glaube geht ja nicht an die Christen - sondern an Jesus Christus! "In Ihm sind alle Schätze der Weisheit und Erkenntnis verborgen." (Kol) In Christus, nicht in uns.

Wie Muslime ihre Gottesverehrung lebt, treibt mich zu größerer Verehrung Jesu an.


