#+title:      Die 7 Gaben des Heiligen Geistes | YOUCAT
#+date:       [2023-01-25 Mi 10:55]
#+filetags:   :theology:
#+identifier: 20230125T105526

Source: [[https://www.youcat.org/de/credopedia/gaben-des-heiligen-geistes/][Die 7 Gaben des Heiligen Geistes | YOUCAT]]
Created: [2023-01-25 Mi 10:54]

* Was sagt die Heilige Schrift?
Im neuen Testament gibt es gleich an verschiedenen Stellen Listen der „Gaben des Heiligen Geistes“, die sich zum Teil überschneiden -- etwa Röm 12,6-8; 1 Kor 12,8-10; 1 Kor 12,28-31; Eph 4,7.11f.; 1 Petr 4,10-11. Traditionell ist in der Kirche die Rede von „sieben“ Gaben des Heiligen Geistes. YOUCAT 310: „Die sieben Gaben des Heiligen Geistes sind: Weisheit, Einsicht, Rat, Stärke, Erkenntnis, Frömmigkeit und Gottesfurcht. Damit „begabt“ der Heilige Geist Christen; d.h., er schenkt ihnen, über ihre natürlichen Anlagen hinaus, bestimmte Kräfte und gibt ihnen die Chance, zu speziellen Werkzeugen Gottes in dieser Welt zu werden.“

* Bausteine für eine geistlich bewegte Kirche

** Weisheit
Unterscheidung der Geister: was kommt von Gott - und was nicht?

"Lass mich beten und eine Nacht darüber schlafen; dann kann ich ein Urteil darüber fällen."

** Einsicht
Bleib nicht an der Oberfläche, schau in die Tiefe! Was will Gott ir sagen? Hörendes Herz (Jünger von Emmaus, König Salomo). 

** Rat
Ratlosigkeit kann zu Kurzschlusshandlungen führen. Wir machen es - nicht Gott. Als Christ sind wir zur Geduld gerufen: wir warten in Vertrauen auf die Hand Gottes. Wenn die Stunde gekommen ist, wird uns deutlich werden, was das Richtige ist. (Mt 10,19-20)

** Stärke
Tapferkeit und prophetische Menschen. "Verkünde das Wort, tritt dafür ein, ob man es hören will oder nicht." (2 Tim 4,2) "Wer tapfer ist, tritt dauerhaft für das einmal erkannte Gute ein, selbst wenn er im Extremfall das eigene Leben opfern müsste." (YouCat 303)

** Erkenntnis
Jesus und die Samariterin am Jakobsbrunnen: Jesus kennt die Frau nicht und erfasst dennoch ihre Not. Besonders bei Beichtvätern und geistlichen Begleitern: innere Not des Anderen erfassen und den heilenden Weg zu weisen.

** Frömmigkeit
Fromm ist ein Mensch, wenn er Gott zum Mittelpunkt seines Denlens, Urteilens und Handelns gemacht hat. Hingabe an Gott. 

** Gottesfurcht
Das ist nicht "Angst vor Gott"!

Die Gottesfurcht ist der Anfang "der Erkenntnis" (Spr 1,7). Innere Haltung: unendliche Erhabenheit Gottes über das menschliche Denken und Handeln. Der Gottesfürchtige stellt den Willen Gottes über seine persönlichen Pläne; er tut alles, um nach Gottes Gebote zu leben und sie nicht zu übertreten.   
