#+title:      Mensch überschätzte Spezies
#+date:       [2023-01-04 Mi 00:24]
#+filetags:   :mensch:schöpfung:wissenschaften:
#+identifier: 20230104T002459

* Kompetenzbeschreibung
[[#A2]] Menschen und ihre Lebensorientierungen - Sich mit den großen Fragen der Menschen auseinandersetzen können
[[#A2_KB2]] Die Schüler können die über den Tod hinausgehende christliche Hoffnung beschreiben.

* AB / UH
[[#A2_AB2]] Biblisch-hermeneutische Kompetenz: eschatologische Bilder; Erlösungsglaube

* Wiederholung


* Erarbeitung
Eine überschätzte Spezies | Doku Reupload | ARTE
[[https://www.youtube.com/watch?v=N3xjGxqKpwM]]

[[http://webcompetent.org/was-ist-der-mensch-noch-dass-du-seiner-gedenkst/#more-8881][Was ist der Mensch noch, dass du seiner gedenkst? - webcompetent % %]]

** Einstieg
Eine vorausgreifende Diskussion einer biblischen, ethischen oder theologischen Problemfrage kann die Notwendigkeit aufzeigen sich mit dem Wesen des Menschen auseinanderzusetzen, etwa:

- Widerlegen die Erkenntnisse der modernen Wissenschaft den biblischen Schöpfungsbericht?
- Besitzt der Mensch das Recht andere Tiere zu gebrauchen und die Natur auszubeuten?
- Ist der Mensch die Krone der Schöpfung?
- Sind wir die Herrscher der Natur oder werden wir von der Natur beherrscht?

** Filmarbeit
Mögliche Aufgaben zur Erstbegegnung mit dem Film

- Setze dich mit der Grundaussage des Films auseinander. Ist der Mensch unbedeutend? Begründe deine Aussage und leite Schlussfolgerungen daraus ab.
- Gib dem Film und den einzelnen Kapiteln eigene Namen, die deiner Meinung nach besser passen.
- Erläutere die besondere Rolle des 10. Kapitels für die Gesamtkonzeption des Films. Setz dich dabei auch mit dem Zusammenhang von Wissen, Sinn und Ethik auseinander.
- Erstelle eine Mindmap / Collage, welche die Sicht des Videos auf den Menschen darstellt. Mögliche Titel: "Der Mensch in Raum und Zeit", "Der Mensch im Kosmos", "Was ist der Mensch?" (Auch eine arbeitsteilige Auseinandersetzung mit den einzelnen Kapiteln ist hier möglich, falls Zeitbedarf und Komplexität reduziert werden sollen.)

** Mögliche Vertiefungsaufgaben zum Film
Auch die Autoren des 1. Schöpfungsmythos haben für ihren Text auf die Vorstellungen der damals bekannten Welt zurückgegriffen. Aktualisiert dieses Weltwissen in Gen 1-2,4a und setzt euch damit auseinander, ob die Aktualisierungen auch die Rolle des Menschen im Text verändert.

Versetzt euch in die Autoren des 1. Schöpfungsmythos hinein. Wie würden diese reagieren, wenn man sie mit unserem heutigen Wissen über das Leben und den Kosmos konfrontiert? Würden Sie ihren Schöpfungsmythos umschreiben oder verwerfen? Stellt eure Überlegungen in Form eines Textes (kreatives Schreiben, Dialog...) oder eines szenischen Spiels um.

Plant in Auseinandersetzung mit dem Film einen eigenen Film. Konzeptioniert werden kann dieser als Fortsetzung (Kapitel 11 — Ethische Schlussfolgerungen) oder als Gegenentwurf, in welchem die Bedeutung des Menschen hervorgehoben werden kann.

Setzt euch mit den folgenden Bibeltexten auseinander: Gottes Antwort aus dem Wettersturm (Hiob 38ff), Hiobs Antwort (Hiob 42,1 – 6) und Ps 8. Wählt passende Verse aus, welche ihr als Kommentar zu einem Kapitel des Films bei einem erneuten Sehen einsprecht (technisch: Anhalten oder Stummschalten möglich). Begründet im Anschluss euer Konzept.

** Theologische Deutung und weitere Inhaltliche Verknüpfungen zum Weiterarbeiten
- Verhältnis von Glauben und Wissen, von Religion und Naturwissenschaft, Komplementäres Modell, Die sogenannten Kränkungen der Menschheit
- Theodizee und Naturwissenschaft als Reaktion auf Abhängigkeit von der Natur: theologische Deutung der SARS-CoV-2-Pandemie
- Menschenbild, Weltbild und ethische Begründungen: Umgang mit der Natur, mit den Mitgeschöpfen; Ego vs. Eco (siehe Medien)
- Sonderstellung des Menschen: Doku "Von Affen und Menschen" (siehe Medien) - Tierethik, Speziesismus, Utilitarismus von Singer und Singers Personbegriff, Great Ape Project

* Hefteintrag
