#+title:      [SW02] Die Berufung als Quelle meines Lebens
#+date:       [2023-07-11 Di 00:31]
#+filetags:   :04:sw02:
#+identifier: 20230711T003116


* Komepetenzbeschreibung
[[#A2]] Menschen und ihre Lebensorientierungen - Sich mit den großen Fragen der Menschen auseinandersetzen können
[[#A2_KB1]] Die Schüler können Perspektiven für ihr Leben entwickeln und  Zukunftspläne entwerfen. 

* AB / UH
[[#A2_UH1]] persönliche und berufliche Ziele


* Wiederholung


* Erarbeitung
Was ist eine Berufung?

"Berufung" – die betrifft doch nur wenige Auserwählte... Tatsächlich? Richtet sich Gottes Ruf nur an Priester, Ordensleute und Co.? Oder gibt es eine Berufung für alle Christen? Pastor Christian Olding geht dem Thema auf den Grund.

[[https://www.katholisch.de/video/25639-was-ist-berufung-glaubeleben]]

[[https://www.bibelwissenschaft.de/fileadmin/buh_bibelmodul/media/wibi/pdf/Berufung_NT___2018-09-20_06_20.pdf]]

als pdf (lokal):
[[file:~/NMS_Golling/Bibel_NT/Berufung_NT___2018-09-20_06_20.pdf]]

Auszug:

* Unvorbereiteter Ruf
Klassische Berufungsberichte begegnen in Mk 1,16-20 / Mt 4,18-22 (Berufung der beiden Brüderpaare Simon und Andreas sowie Jakobus und Johannes) sowie in Mk 2,14 / Mt 9,9 / Lk 5,27f (Berufung des Levi / Matthäus). Die Berichte weisen folgende Charakteristika
auf: Die Gerufenen werden namentlich identi ziert. Jesu Ruf erfolgt völlig unvermittelt und voraussetzungslos. Die Angesprochenen erfahren den Ruf in einer konkreten Arbeitssituation (Fischfang, Zoll). Sie reagieren auf den Ruf, indem sie widerspruchslos ihre Arbeit verlassen und umgehend Jesus nachfolgen. Jesu Ruf erscheint dergestalt als eindrücklicher performativer Akt, der göttliche Vollmacht indiziert. Eine rudimentäre Form dieser Berufungsform ndet sich in Joh 1,43, der Schilderung der Berufung des Philippus (s. ferner Lk 9,59f). In Mk 2,17 / Mt 9,13 wird das Berufungshandeln Jesu in allgemeiner Form auf alle Sünder ausgedehnt.

* Vorbereitete Berufung
Lk 5,1-11 schildert die Berufung des Simon (Andreas wird nicht erwähnt) und der beiden Zebedaiden Johannes und Jakobus in einer gegenüber Mk 1,16-20 deutlich veränderten
Form: Der Bericht ist situativ ausgestaltet, mit einem Geschenkwunder (reicher
Fischfang) versehen, auf Simon konzentriert und im Evangelium anders verortet. Die in Mk 1,21-39 nach der Jüngerberufung geschilderten Ereignisse gehen hier der Berufung voraus (Lk 4,31-44), was zur Folge hat, dass Simon und Jesus sich vor der Berufung bereits kannten (Lk 4,38f).

* Nachfolgeansinnen
In Mt 8,19f / Lk 9,57f; Mt 8,21f (anders Lk 9,59f: Ruf) und Lk 9,61f tritt jeweils ein
Nachfolgewilliger aus eigenem Entschluss mit der Bitte um Nachfolge an Jesus heran. Jesus konfrontiert die an ihn Herantretenden barsch und kompromisslos mit den radikalen Konsequenzen der Nachfolgeexistenz.

* Vermittlung.
Joh schildert die Berufung der ersten Jünger in Joh 1,35-51 in einer gegenüber Mk 1,16-20 und Lk 5,1-11 nochmals veränderten Form: Zunächst werden Andreas und ein Anonymus als Täuferjünger vermittels des Bekenntnisses des Täufers zu Nachfolgern Jesu. Simon kommt erst durch die Vermittlung seines Bruders Andreas, also nicht durch Jesu Ruf zu Jesus. Es folgt die Berufung von Philippus und Natanael (nicht der Zebedaiden!), wobei die des Natanael durch Vermittlung des Philippus geschieht. Die Jünger treten in den Szenen nicht als Berufstätige, sondern als den Messias Suchende auf, die ihre Heimat bereits verlassen haben.

Wikipedia:
Unter Berufung im religiös-spirituellen Sinn wird das Vernehmen/Verspüren einer inneren Stimme verstanden, die einen zu einer bestimmten Lebensaufgabe bewegt. So spricht man von einer Berufung zur Liebe und zum Leben (in Fülle), die im Herzen jedes einzelnen Menschen tief verankert ist.

Fortsetzung von Joh 4:

Was bedeutet "Berufung"? Wer ruft - wohin, wozu? Ein Beruf kann, muss nicht zur Berufung werden. Was passiert hier? Der Beruf erfüllt das Leben ganz. Das Leben des Menschen ist ganz auf den Beruf hingeordnet. 

Priester, Klosterleben als Berufung. Berufen zum König, Prophet im AT. Berufen zur Heiligkeit (für alle Christen). 

[[file:~/org/notes/2020-09-15-1123 Berufung.org]]

Y 73: Jesus von Nazareth trägt den Beinamen "Christus", der Gesalbte / Messias. Wir heißen Christen nach Christus - zum Ausruck unserer hohen Berufung.

Y 138: Laien und Kleriker haben gleichwertige, aber unterschiedliche Aufgaben. Laie: die ganze Welt auf das Reich Gottes auszurichten. Ihnen dienen die Kleriker, um sie zu leiten, lehren und zu heiligen. Jeder Christ hat die Aufgabe (Berufung), mit seinem eigenen Leben das Evangelium zu bezeugen. Jeder Mensch erhält von Gott einen persönlichen Auftrag, Gott geht mit ihm einen eigenen Weg: niemand kann sich die Aufgaben selbst anmaßen, jeder erhält den Auftrag von Gott. 

Y 139: Die Berufung der Laien besteht darin, sich in der Gesellschaft zu engagieren, damit das Reich Gottes unter den Menschen wachsen kann. Die Menschen um mich herum sollen das Evangelium kennen- und Christus lieben lernen. Prägung der Gesellschaft, Wirtschaft und Politik durch meinen Glauben. Engagement in der Kirche (Ministrant, Lektor, ...). 

Y 144: Aufgabe der Bischöfe - verantwortlich für ihre Diözese und Mitverantwortung für die ganze Kirche. Gemeinschaft der Bischöfe; für die ganze Kirche unter der Leitung des Papstes. Sie sind zuerst Apostel, denn Jesus hat sie persönlich berufen. 

Y 145: Berufung zum Leben in Armut, Keuschheit und Gehorsam - Gott ist Liebe. Leben wie Jesus. Denn die Welt ist nicht alles. Nur Gott macht uns ganz glücklich. 

Y 205: Firmung - der Seele wird ein Siegel aufgeprägt, prägt den Menschen als Christ: der Hl. Geist, die Kraft von oben. 

Y 250: Weihesakrament - Mittler zwischen Gott und Mensch. Nach Christus kann es ein Weihesakrament nur noch in Christus geben, in Christi Opfer am Kreuz und durch Christi Berufung und apostolische Sendung. Priester handelt "in persona Christi". Er ist ein Diener. 

Y 255: Diakon - repräsentiert Christus, der gekommen ist zu dienen (Dienst am Altar, am Wort und der Liebe). 

Y 265: Ehe - für alle? Nicht alle sind zur Ehe berufen - es gibt auch alleinlebende Menschen. Er kann sich um Menschen sorgen, für die sonst niemand Zeit hat. Berufung heißt aber nie, Ehe zu verachten. Freiwillige Ehelosigkeit nur in und aus Liebe. 

Y 340: Gottes Gnade zwingt uns nicht. Die Liebe Gottes will unsere freiwillige Zustimmung. 



* Hefteintrag
