#+title:      Pädagogische Konferenz
#+date:       [2023-10-09 Mo 16:18]
#+filetags:   :konferenz:
#+identifier: 20231009T161801

Hier folgt der Text

* Begrüßung
Lena, Sarah, Daniel - entschuldigt

* Herbert
Liebe Grüße von Irmi

* Tagesordnung
Geburtstagskinder

Fr. Kaserer - QMS - Birgit: wir haben genug; wir entwickeln uns; bis jetzt ist es Wortglauberei.

Digitalisierung: noch einmal überarbeiten.

Leitertagung - Krisensitzung (Suizide bei Kindern, ...)

IKM

1.1.2024: Personalabrechnung nur mehr online

aktuelle Termine:
- Fototermin auch Foto für Lehrer
- 13.10.: Zustiegstelle in Hallein
  - Essen selber zahlen

Budgetgespräch mit Gemeinde

Neue Tafeln Anschaffung

Birgit ist auf Rehab (8 Tage nicht da)

Herbstferien: 26.10.-5.11.

Bezirksmeisterschaft: Geräteturnen in Golling

* SEP
steht in Teams
ist überarbeitet
Ziele sind neu formuliert

* Krisenteam
5-6 Personen; 1-2 erfahrene Lehrer; ...

Läuft bei einem Kind etwas aus dem Ruder? so wie bis jetzt...

Wird nach Dingen gesucht, um ihre Existenz zu rechtfertigen; Dokumentiert.

* Kinderschutzrichtlinie

* Krisenteam
"Todo" Liste für Dummies

* Reiserechnungen
Tagesgebühren wurden angehoben

* Q(ualitäts)-Handbuch
Sammlung der wichtigsten Dokumente und Prozesse der Schule (SEP, Förderkonzept, ...) - Doku der Doku. Bestandsaufnahme - zufrieden? ergänzen?

Huch - traurig: jede Schuler ist Einzelkämpfer; was haben wir gemeinsam? was können wir gemeinsam erledigen?

Riesige Pflanzerei - aber wir müssen es liefern. Nullhandhabe, weil Ö-weit umzusetzen.
alle Direktoren könnten eine Plattform bilden: Austausch der Konzepte
Wer stellt was auf die Plattform? Alltag der Schule ist schon fordernd.

Schulversuch - wer will schon zerpflückt werden? Bei erster Kritik - 

* Lehrpläne
Gegenstände heißen neu:
- Geschichte und politische Bildung
- Geoegrafie und wirtschaftliche Bildung
- Biologie und Umweltbildung
- Musik
- Kunst und Gestaltung
- Technik und Design
- Bildungs- und Berufsorientierung


* Geometrisches Zeichnen
Autonome Stundentafel
- Pflichtgegenstand: in M integriert
Nicht schulautonome Stundentafel

* Umsetzungsbegleitung
- Fortbildnug PH
- MOOC (massive open online course)


* Kompetenzraster
sind Beuteilungsraster

(Wahnsinn an Folien - kein einziges praktisches Beispiel)

- Semester/Jahresplanung
- Unterrichtsplanung
- Reflexion des eigenen Unterrichts
- ?

Ziele:
- welche Ziele
- komp Unterricht
- Aufgaben / Lernkultur
- Lernsituation

www.paedagogikpaket.at


* IKM+
7./8. Schulstufe 20.11.-19.12.
- Deutsch / Lesen
- Mathematik
- Englisch


* IKM+ Fortbildung

* Digitalisierungskonzept

* Lernplattformen?
wer verwendet was?

- school4you; LearningsApps; eBooks; MORE e-Zone; ...

Kinder freuen sich nicht besonders über cyper-Homework. Sie mögen HÜ per Hand lieber. 

Schultaschen sind sehr schwer - eBooks; HÜ ist doch nur in Hauptfächern; mit Kindern reden; was nehme ich nach Hause? Was kann in der Schule bleiben?

Eigenverantwortung der Kinder.

* Mobbing
Was ist Mobbing? Was ist ein Konflikt?

* Allfälliges
Stolzlechner (16.4.)
1.+2. Stunde: 3abc
3.+4. Stunde: 4abc
5.+6. Stunde: 1ab

(17.4.)
1.+2. Stunde: 2ab

- 1. Klassen: Antarktis
- 2. Klassen: Megastädte der Welt
- 3. Klassen: Südsee
- 4. Klassen: Australien


* Neue Tafeln:
3a+3b: Smartboard austauschen - Bsp. VS: Whiteboard mit interaktivem Beamer. Innen: Whiteboard + Beamer (plus Stift). Oder Whiteboard mit Stift; außen Flügel mit Kreide. Preis: 6000 Euro.
Smartboard: über 10.000 Euro.

Wer arbeitet damit / gerne?

Plan: Pro Jahr 4 Klassen umrüsten (24.000-28.000 Euro mindestens)

Beamer sollten überall ausgetauscht werden

Nächstes Jahr: alle Rechner austauschen

Wo besteht Bedarf? Wo Smartboards kaputt sind - ja.
Sonst - nein: Englisch - Deutsch: kaum.

Kreidetafeln sind immer besser: schöneres Tafelbild.
Va ein guter Beamer - hier gäbe es ein Kombi-Paket.

Sparsamkeit - digital/Handwerk schätzen!
Konzentration von einer Mücke! PC Spiele Nächtelang - und dann keine Konzentration mehr in der Schule.

Keine Wertschätzung mehr, weil die Kinder viel von der Schule verwenden. Selbst Block mitbringen.

Julia vs Christoph: alte PCs, keine Updates mehr ab nächstem Jahr; warum Beamer und Tafeln austauschen, die funktionieren.

Gemeinde: Wünsche / Antworten. 

* Neuer Schüler ab Dezember (3. Klassen)
Schulbücher nachbestellen!
Papa starb an Gehirntumor; Mutter lag in der Intensivstation - war bei der Oma. Mutter zieht nach Golling.


* Skitag
13.12.

Erste Klassen? Zauchensee. Babylift. Jause!

Vorfühlen für den Skikurs.

* Pädag. Konferenz auf Di oder Do verschieben?

* Verschwiegenheitspflicht

* Keinem Schüler sagen: "Du bleibst Zuhause!"
Jeder Schüler muss in die Scule gehen.

* Bei Schüler Fahrrädern wurden Bremsen ausgehängt

* Mittagsaufsicht der VS bald nicht mehr

* Sportlehrer
Helferschein: Schwimmen / ohne Helferschein bei Wandertag nicht in die Nähe von Wasser; 3 Tage insgesamt.

Skifahren (Begleitlehrer Alpin)

* Englisch Theater
14.3., 08h30 Tunsaal 2.,3,4. Klassen (Dauer 1h)

* Mittagspause
heute viel Lärm, va wegen Tischfußball: in der Klasse oder draußen! Tür offen. Bei schönem Wetter draußen. Eventuell Sitzmöglichkeit? Martin zeigt es nächste Konferenz.

* Schlösser wurden manipuliert
Spints; 




