#+title:      Religionsunterricht
#+date:       [2023-12-06 Mi 08:44]
#+filetags:   :meta:
#+identifier: 20231206T084441


* Gedanken

** Burnout?
:PROPERTIES:
:CAPTURED: [2023-12-06 Mi 10:00]
:END:
Im Moment geht's mir sehr schlecht. So ziemlich alles ist entmutigend. Den Schülern interessiert das Fach gar nicht. Besonders die drei vierten Klassen: Null Bock auf alles. Selbst Themen, die sie selbst auswählen, bearbeiten sie halbherzig, die Ergebnisse sind großteils erbärmlich. Klassische RU Themen gehen sowieso nicht. Die Klasse 3b gehört hier ebenfalls dazu. In der 3a hat das Arbeiten vor Kurzem ganz gut geklappt; aber ich kann auch nicht immer Gruppenarbeit machen. 

Disziplinär wird es von Jahr zu Jahr schlimmer. Einziges Interesse sind PC, Games, Handy - man sieht kein Kind draußen spielen (in Golling, wie in Grödig). Fast alle sitzen vorm PC und zocken - so wie ihre Eltern. 

Warum soll ich mich für Kinder aufreiben und die Frohe Botschaft von Jesus verkünden, wenn diesen Kindern alles egal ist, sie dieser Botschaft gleichgültig gegenüber stehen und dann noch den Lehrer respektlos behandeln? Muss ich mir das gefallen lassen?

Meine Direktorin stärkt mich da gar nicht, sondern will mir vorschreiben, was ich unterrichten soll: "Sicher keine Bibelthemen wie zB Propheten; sondern Ethik, deshalb habe ich ja auch diese Mappe gekauft."

Sollte ich mich zum Wechsel entscheiden: es wäre eben meine x-te Entscheidung, die quasi daneben geht. 


** Selbständigkeit
:PROPERTIES:
:CAPTURED: [2023-12-06 Mi 13:24]
:END:
Das war heute wieder ein schwieriger Tag; wie erziehe ich Kinder zur Selbständigkeit? Die Kinder erwarten, dass ihnen alles auf dem Silbertablet präesentiert wird. Eine HÜ in Religion machen einige Schüler "ins Handy"; ein anderer bringt nur Stichworte auf einem "Kaaszettel"; zwei Mädels eineinhalb Seiten ausgedruckt, offensichtlich copy+paste aus Wikipedia. Also muss ich in einer dritten Klasse explizit jeden Arbeitsschritt angeben. Manchmal auch in einer vierten Klasse!

** Workflow
:PROPERTIES:
:CAPTURED: [2023-12-06 Mi 20:06]
:END:
Ich sollte mir einen Workflow überlegen, der etwas einfacher ist. Im Moment ist das Alles ziemlich unübersichtlich. War es mit =org-roam= besser? Der Wegfall der database ist hingegen schon ein Vorteil.

Reflexionen zu bestimmten Schülern kann ich mit =org-capture= zu dem betreffenden Schüler eintragen. Auch ein Eintrag in eine Tabelle ist möglich.

Wie verwalte ich aber meine eigenen Gedanken zum Unterricht? Hier in dieser Datei - die einzelnen Headlines kann ich per Auswahl anzeigen lassen, oder? Und wenn ich mir Gedanken zu bestimmten Themen mache - dann erstelle ich eine neue Notiz, oder erweitere bereits bestehende.

** Berufung
:PROPERTIES:
:CAPTURED: [2023-12-14 Do 12:49]
:END:
The Chosen - 3. Staffel - Zu Zweit:
"Um Großes zu tun, brauchst du nichts fühlen. - Jesus braucht uns nicht, er will uns."

Wo trage ich eigentlich meine laufenden Gednken ein? Idee: =inbox.org=

Begegnung Jesus mit (dem kleinen) Jakobus Thaddäus? - so stark; ... Warum soll jemand wie Jakobus, der humpelt, Kranke heilen? Er selbst hat Jesus noch nie um seine Heilung gebeten? ... "Du hast mich nicht geheilt. - Möchtest du geheilt werden? - Nur wenn es möglich ist. - Du weißt, dass es möglich ist. - Hör mir gut zu: Nach dem Willen des Vaters könnte ich dich heilen; es gibt schon so viele. Aber deine Geschichte: du bist nicht geheilt, und verkündest Gott. Leid und Schmerz geduldig ertragen und die Ewigkeit ohne Leiden. - ..."

** Weihnachten
:PROPERTIES:
:CAPTURED: [2023-12-20 Mi 14:09]
:END:
Mir geht's wirklich nicht gut. Je näher Weihnachten kommt, desto größer wird der Stesslevel. Vor allem dieser Druck, Geschenke machen zu *müssen*, ist erdrückend.

Auch wenn viele sagen: "Zu Weihnachten geht es doch nicht um Geschenke!" - so erwartet doch jeder Geschenke. Nur mal so ein Gedanke: Stell Dir vor - Du würdest wirklich gar kein (persönliches) Geschenk erhalten - was würde das mit dir machen? Wäre das immer noch ein schönes Fest für dich? Wirklich? Wenn du mit "Ja" antwortest: Hast du das schon einmal erlebt? Ich bin mir nicht so sicher. Ich habe es erlebt: vor ca zwei Jahren. Kein persönliches Geschenk! Und das Gefühl ist wirklich sch...

Und diese Weihnachten kann ich meinen Kindern eigentlich nix schenken, da mein Konto es nicht hergibt. Ich könnte, aber dann wird mein Konto eben sehr rot. Und meine Frau wünscht sich einen Monent der Entspannung zu zweit. Das heißt: Hotel, Restaurant, Kino, etc... kostet eben alles Geld. Das ich nicht habe...

Und das alles, gepaart mit der depperten Situation in der Schule, ist einfach zu viel für mich.


* TODOs

** TODO Berufswechsel
:PROPERTIES:
:CAPTURED: [2023-12-06 Mi 11:23]
:END:
Wo liegen meine Stärken und Schwächen? Warum ist es im Moment so frustrierend?

Talentecheck (online ist nicht seriös)

Alternative Jobs:
- Schulform wechseln: zB in die VS als RL
- Oder: Fach wechseln; dafür werde ich wohl eine Zusatzausbildung machen müssen.
- Schulbuchverlage
- Erwachsenenbildung
- Jugendeinrichtungen
- Buchhandel?
- Journalismus?
- oder ganz was anderes (wofür ich eine neue Ausbildung absolvieren müsste)

Vor einem Berufswechsel hab ich ziemliche Angst; würde es als erneutes Scheitern erleben. Und dann kommt die finanzielle Unsicherheit dazu. Und: ob ich überhaupt einen anderen Job finden werde?

Sollte ich bleiben - dann muss sich radikal was ändern? Da ich dies von den Kindern nicht erwarten kann - muss ich mich radikal ändern. Wie immer ... hmpf!

** TODO Workflow
:PROPERTIES:
:CAPTURED: [2023-12-06 Mi 20:24]
:END:

was ist zu tun?

* Ähnliche Notizen

#+BEGIN: denote-links :regexp "Unterricht" :missing-only t
- [[denote:20231020T091020][Ablauf Unterricht]]
#+END:



