#+title:      Notenkonferenz
#+date:       [2023-06-29 Do 15:12]
#+filetags:   :konferenz:schule:
#+identifier: 20230629T151229

* Begrüßung

* ...

* Leiterbericht + Vorausschau

** Bitte um weitere gute Zusammenarbeit

** Pädagogische Konferenz einmal im Monat
Termine: 9.10., 14.11., 13.12., 18.01.2024

** Lehrfächerverteilung
sobald fix ist, wer kommt.

** STB: BM, CR

** 1. Klassen Zusammensetzung
1a: MINT SM
1b: VG
1c: Hofer Eva

Materialliste?

** QMS:
SEPlan überarbeitet; Ziel fehlt noch; ...

* Fortbildung
Anmeldung nur bis 22.9.

* 2x David
erhalten Zeugnis

* Viviene
geht ins Poly, wenn sie dort erscheint

* Notenkonferenz

** 1a
kein WZ, kein 5

** 1b
Hannah P. - Klausel:
nur einmal 5: eigentlich in allen drei HF 5; aber nur auf ein 5 (wird im Sept. 13) reduziert; [Gewalt in der Familie, Lunggau, ProJuv in Golling, ...]. Wenn irgendwie möglich aufsteigen lassen. 
Kein SPF; Platz in der Sommerschule in Vigaun;

Angelika: hoch traumatisiert; schwebt zw Traum und Realität; über Papa 9 Halbgeschwister (bei div. Müttern); real: in der WG bleiben;

Barbara: fühlt sich in der Klasse wohl;

Hannes: positiver Eindruck;

Julia: bestätigt; ankommen lassen.

** 2a
kein NG; Leistungsänderungen: Karlo auf Standard AHS hinauf, mit Semster.
kein WZ; 5 (?) Z. ED nur SG, KS nur SG.

Fehlstunden: wann wird das übertragen von TA ins Zeugnis?

** 2b
NG: sechs alle Viviene, viele Nicht Beurteilt (daraus folgt Prüfungen, zuerst Feststellungsprüfung, dann WH Prüfung)

Andrea: sehr gutes Bsp. an Integration. 

Hannah: 1.0 / Viviene 4,85

Sind leistungswillig

2x Z
Viviene: NZ (400 Fehlstunden; 200 unentschuldigt ... Anzeige?)

Dalia: Abstufung AHS auf Standard in M

** 2c
1x Z (Rest SZ)

Noten: Kathi und Paula 1.0
der Rest okay

Tobi...

(Suizidfälle bei Kindern in den restl 2 Jahren drastisch erhöht)

Jonus fehlt viel, wird von Mutter entschuldigt.

** 3a
kein NG
Nico: AHS auf Standard in M

vier haben einen ND 1.0
andere viele 4

6x Z

** 3b
Valerie: auf AHS Niveau umgestuft

5x Z
Leon: WZ beantragt, von GE. Ein all zu oftes Ermahnen. Störung: emotional-sozial. Oftmals gelogen. Frau Keser behauptet, Leon wäre zusammengeschlagen worden. Komisch: denn hier wäre Polizei etc dagewesen. "Niemand glaubt uns!"

Manuela: Besserung sichtbar

Irmi: Unterschied zw Mutter und Schüler. Ja, schnabelt nach; aber ich berücksichtige auch seine Krankheit. 

** 3c
2x 1.0

Fabian:
- Aufstufung auf AHS in E
- GV möchte ihn in D aufstufen

Verhaltensnoten: 

** 4a
kein NG

Abstufung: niemand
Lara: 1.0
Melanie & Theresa: nur ein Gut 
keine Verhaltensnote

** 4b
kein NG

keine Umstufung

D: Khan und Christoph auf AHS

keine Verhaltensnote

David & David: nicht beurteilt, weil ao. Schüler 

* Nächste Woche

** Mo-Mi
alle unterwegs (außer die 4. Klassen)

(wo kann ich mit?)

** Do
08:00 Gottesdienst

ab 09:00: Fotos
10:00 Abschlussfeier

12:00 Mittagessen (Abfalter)

** Fr
alle um 07:45 alle da!

Zeugnisse
dritte Klassen räumen Turnsaal auf
alle Tisch im KZ leer 

09:00 Konferenz


* Klassenräume
11 Klassen

- welcher neue Klassenraum für eine erste Klasse? (Gruppenraum 2. Stock)
- Gruppenraum der vierten Klassen (in der Nähe der Bibliothek?)



* Kritik an Postbus
Lachhaft!
Man landet bei der Vermittlung in Wien!

So gut wie unmöglich, einen öffentlichen Bus zu checken. Privatbus kostet das doppelte bis dreifache.

Busfahrer lassen ganze Schulklassen stehen.
Post und ÖBB finden keine Fahrer.

Daher Ausflug planen mit Zug!


