#+title:      [SW28] Übergang: Die Kirche – das Haus Gottes? / Baustile Kirche
#+date:       [2023-03-21 Di 07:31]
#+filetags:   :02:jahresplanung:
#+identifier: 20230321T073127

* Kompetenzbeschreibung
[[#C5]] Religiöse und weltanschauliche Vielfalt in Gesellschaft und Kultur - Medien, Kunst und Kultur im Kontext religiöser Weltwahrnehmung interpretieren, beurteilen und gestalten können

[[#C5_KB1]] Die Schüler können christliche Motive in ihrer Lebenswelt wahrnehmen und sakrale Räume in ihrer Bedeutung für Menschen erschließen.  

* AB / UH
[[#C5_UH1]] Die Kirche als Haus Gottes

* Wiederholung


* Erarbeitung
1 Die Schüler*innen finden auf dieser Doppelseite Bilder von unterschiedlichen Kirchen. Sie erkennen anhand der Bilder, dass es deutliche Unterschiede in jedem Land / in jeder Kultur gibt. Einige Kirchenbauten können auch befremdlich auf die Schüler*innen wirken, es bietet sich daher an, im Klassengespräch darauf einzugehen.
1 4. Im Vergleich der Kirchen in der Umgebung der Schüler*innen und der Beispiele der Kirchen auf der Welt ist individuell.
Mögliche Gemeinsamkeiten /Unterschiede, die entdeckt werden können:  

Gemeinsamkeiten:

    Kreuz
    Turm
    großes Eingangstor
    besondere Fenster

Unterschiede:

    Baumaterial
    Architektur - Baustil
    Größe der Kirchenbauten
    Dächer 

2 Dieser Arbeitsauftrag soll die Schüler*innen zum Nachdenken bringen und sie auf die verschiedenen Baustiele aufmerksam machen.
Mögliche Gründe, die genannt werden können, sind:

    Baumaterial
    Bauweise der Kultur
    Zeit, in der die Kirchen erbaut worden sind (Epochen)
    örtliche Gegebenheiten (Berg, Ebene, Wüste, …)
    etc.

5 Die Bibel beschäftigt sich nicht direkt mit dem Kirchenbau. Die Antwort für wen die Kirche, „das Haus Gottes“ gebaut ist, kann mit Mt 18,20 beantworten: „Denn wo zwei oder drei in meinem Namen versammelt sind, da bin ich mitten unter ihnen.“
Die Kirche ist also ein Haus, in dem sich die Menschen versammeln, um mit Gott in Kontakt zu kommen.
3 Dieser Arbeitsauftrag soll eine Diskussion zwischen Einheitlichkeit und Individualität anregen. Pro und Contras werden erläutert, so könnte zum Beispiel die kulturelle Vielfalt auf der Welt als Schatz erkannt werden.
6 Dieser Arbeitsauftrag ist sehr persönlich  und  individuell und zielt auf die Kreativität der Schüler*innen ab.  Hier ist es wichtig den Schüler*innen zu vermitteln, dass es bei eigenen Vorstellungen kein falsch gibt, jedoch ihre Wahl gut überlegt und begründet werden sollte.

* Hefteintrag

