#+title:      Gnus tutorial
#+date:       [2023-02-17 Fr 18:53]
#+filetags:   :emacs:gnus:
#+identifier: 20230217T185336

Seit ein paar Tagen verwende ich Gnus für Gmail, reddit und maillists.

Mir fehlen noch die keybindings ... z.B. für nnreddit:

* nnreddit
[[https://github.com/dickmao/nnreddit]]

In your .emacs or init.el, use ONE of the following:

;; Applies to first-time Gnus users
(custom-set-variables '(gnus-select-method (quote (nnreddit ""))))

or, if you're an existing Gnus user,

;; Applies to existing Gnus users
(add-to-list 'gnus-secondary-select-methods '(nnreddit ""))

Then M-x gnus.

Initial setup should guide you through OAuth and find your existing subreddit subscriptions.

Select a subreddit via RET. Rapidly catch yourself up via N and P. Instantly catch-up with c.

Create a post via a.

Reply to articles with f or r. Include original with F.

Vote articles via R - (down), R = (up), or R 0 (retract).

From the *Group* buffer, press g to refresh all subreddits. M-g on a particular subreddit to refresh individually.

From the summary buffer, /o redisplays articles already read. x undisplays them.

S s edits articles.

S c cancels articles.

R g [subreddit] takes you to an unsubscribed subreddit.

You can subscribe to it via the u keybinding from the *Group* buffer [1].

Gnus beginners may find the interface bewildering. In particular, subreddits with no unread articles do not display. Use L to bring them out of hiding.


* Gnus

Gnus Refcard:
[[https://www.gnu.org/software/emacs/refcards/pdf/gnus-refcard.pdf]]

Gnus Guide:
[[https://github.com/redguardtoo/mastering-emacs-in-one-year-guide/blob/master/gnus-guide-en.org]]
