#+title:      Pädagogische Konferenz
#+date:       [2023-05-04 Do 15:35]
#+filetags:   :konferenz:schule:
#+identifier: 20230504T153525

Blasius

* Begrüßung

* Tagesordnung
Danke

** Skikurs
Org. 

** BO Tage
nur positive Rückmeldungen von den Betrieben

** Gemeinde dankt für Müllsammelaktion
es war weniger Müll als früher

** Für die Hochbeete
Mirjam und Martin

** Schulentwicklungsplan
wurde überarbeitet und abgeschickt

** 2 erste Klassen
MINT darf nicht separat geführt werden, muss aufgefüllt werden; es geht um einen Schüler für drei Klassen. Vll kommt noch einer? Geburtenschwacher Jahrgang

** Neuer Lehrplan im MOOC vorgestellt
M + E schon angeschaut

** Projekttage
3 Tage letzte Woche

** MOOC
anmelden über PH Burgenland
Modul 1
Modul 2
Modul 3
Modul 4

*** Home - Pädag-Paket
Lehrpläne
Komment
etc

** Stundentafel der MS
14 M (15)
14 E (15)

() subsidär - man ersetzt / tauscht Stunden?

Ist wohl viel Arbeit, also nehmen wir diese Tafel

Wir haben uns folgendes überlegt:
1. 29
2. 31
3. 32
4. 32
   
Oder wir nehmen 2 Stunden im Kreativen Bereich weg; und diese Fächer zweistündig.

Jeder soll sich die Tafel für sein Fach anschauen, was ist möglich? Es ist schwer.
Diese Tafel ist neu, geändert.

Bsp.: Werken mind 6; oder 7 Stunden. Dh 1 Stunde in der 4.
Wir könnten 2 Stunden Werken blocken (2 Gruppen); alle 2 Wochen; die Wochen dazwischen 2 Stunden BE (1 Gruppe).

Jeder Fachkoordinator will natürlich die maxi Zahl seiner Stunden. Wenn wir eine Stunde weniger E oder M haben, können wir dann auf schwache Schüler in der AHS Standard Gruppe nimmer Rücksicht nehmen.

Hannes: Physik und Chemie zusammenlegen; mehr Werken weil Industrie sucht Fachkräfte

Irmi: M wir kommen jetzt schon nicht zsamm; ...
Chemie geht nicht, aber Physik ein paar Stunden weniger?

*** Nicht zulässig
Religion, DG, UG streichen

Was über subsidiär hinausgeht, neues Fach, ... : Lehrplan selber schreiben.

*** Was ist neu zu schreiben
M und E für zwei Kompetenzbereiche einen Plan schreiben

* Allfälliges
** Interessensfächer
Im Turnsaal vorstellen und Kinder entscheiden

Oder: Eltern... kommen .... wohin?

*** Welche
- Englisch
- Tanz
- DG+
- Ernährung und Gesundheit
- Handwerkliches, Reparieren?


** Workshops HTL Sbg

** Schüler, nicht nach Wien
Paul 3a, Markus 3c, Davids 3b

** Mitarbeiter Gespräche

** Danke für IQES

** KEL Gespräche

** Wolfgang Bachmayer 2b

*** Felix Schädelbasisbruch (privat)
Die Verantwortung für die Lehrer und die Sorge um Felix ist einfach zu groß, wir können nix garantieren (irgendein Kind könnte ihn stoßen). Wenn da was passiert, ist alles aus. Wir brauchen eine ärztliche Bestätigung; wir wissen nicht, ob Felix das überhaupt schafft und dann einen größeren Schaden davonträgt.

Können wir als Schule überhaupt die Rückkehr verweigern, als Sorge um das Kind.

*** Projekttage 2b
Seewaldsee 4.7. Vormittag + 5.7. Nachmittag
Reisebus füllen (2. Klasse für den Bus)

*** Neue Schülerin Andrea 
Wie wird sie benotet? Semesternachricht + SA ergibt Note
Bücher?
D NG ... Standard eingestuft

*** Heizkörper in den Klassen
dürfen nicht verstellt werden (man *kann* nix verstellen)
Schulwart meint, Schüler hätten was verstellt.
Das Ding hinter dem Blech dient zur Entlüftung, Regelung über PC.

Wer da dreht, es wird kaputt! Deshalb: Finger weg!

** Lehrerausflug: wohin? Wann?

