#+title:      [SW34] Eine Welt die uns prägt / Die Feste unserer Welt
#+date:       [2023-06-19 Mo 14:53]
#+filetags:   :01:sw34:
#+identifier: 20230619T145319


* Kompetenzbeschreibung 
[[#C6]] Religiöse und weltanschauliche Vielfalt in Gesellschaft und Kultur - Unterschiedlichen Lebensweisen und Glaubensformen reflexiv begegnen können
[[#C6_KB1]] Die Schülerinnen und Schüler können Gemeinsames und Unterscheidendes, Verbindendes und Trennendes von Konfessionen und Religionen benennen und sich damit respektvoll auseinandersetzen. 

* AB / UH
[[#C6_UH1]] Einigkeit in Vielfalt

* Wiederholung

Barbara Eßl: welche Szene von "The Chosen" hat euch am besten gefallen? nachzeichnen...

** Startseite & Comic
Paul (?) wirft einen großen Würfel, auf dem verschiedene Feste markiert sind - der Würfel fällt (im Sommer) auf "Weihnachten". Er schmückt einen Baum mit Weihnachtsschmuck: "Man muss die Feste feiern, wie sie fallen."

* Erarbeitung
1 Die Aussage, die sich direkt auf das Zitat "Man muss die Feste feiern, wie sie fallen" (u.a. im Comic) bezieht, regt zur Auseinandersetzung mit dem "Timing" von Festen an. Der Spruch verweist darauf, dass man die Gelegenheit zum Feiern nutzen sollte, wo sie sich bietet. Feste sind gerade dadurch definiert, dass sie zeitlich, aber auch inhaltlich an bestimmte Anlässe gebunden sind. Sie geben dem Fest seine Bedeutung – fehlen sie oder verschieben sie sich, fehlt oder wandelt sich auch diese Bedeutung. Auch das wird im Comic mit dem Motiv des Feste-Würfelns angesprochen. Mit den Schülern lässt sich diese Thematik am besten anhand konkreter Beispiele besprechen – z.B.: Kann man Weihnachten auch im Sommer feiern? Funktioniert Erntedank im Winter? etc. Oft kommen verschiedene Ausprägungen (Bräuche etc.) zur Sprache, die die genannten Feste genau zu diesen Festen machen. Interessant kann ein Blick in andere Kulturen sein – etwa dorthin, wo Weihnachten wirklich mitten im Sommer gefeiert wird (z.B. in Australien und anderen Ländern der Südhalbkugel).

2 Die Trennung in die Kategorien "privat", "staatlich" und "kirchlich" ist für manche Feste eindeutiger, für andere kann es sich anbieten, auch mehrfärbige Berge zu gestalten und zu diskutieren. So wird Weihnachten als kirchliches, oft jedoch auch als (rein) privates Fest gefeiert. Ein möglicher Lösungsvorschlag:

- Namenstag kirchlich, privat
- Staatsfeiertag staatlich
- Firmung kirchlich, privat
- Taufe kirchlich, privat
- Hochzeit privat, kirchlich
- Fasching privat
- Erstkommunion kirchlich, privat
- Weihnachten kirchlich, privat
- Pfingsten kirchlich
- Geburtstag privat
- Ostern kirchlich, privat

Es fällt somit auf, dass viele kirchliche Feste auch privat gefeiert werden – und umgekehrt. Ein Hinweis darauf, dass das Kirchenjahr genau diese Höhepunkte des Lebens strukturell begleitet, bietet sich hier bereits als Ausblick an.

3 Dieser Arbeitsauftrag ist sehr persönlich und individuell. Wichtig ist, den Schüler hier keine Reihung vorzugeben (z.B. "Ostern ist wichtiger als...") oder Reihungen zu kritisieren. Es lohnt sich, die Schüler nach den Beweggründen für die Reihung bzw. der Einstufung eines bestimmten Festes als Nr. 1 zu fragen.

4 Auch dieser Arbeitsauftrag ist sehr persönlich und individuell. Eventuell ist für manche Schüler eine Erklärung (evtl. anhand eines Beispiels) notwendig, um das Sprichwort zu erschließen.

* Hefteintrag
Jessas - App ausprobieren...

Band 1: "RELI1" (Crashkurs Christentum/Kirchenjahr, Neues Testament/Jesus, Kirche/Sakramente)
