#+title:      [SW24] Eine Kirche die uns verbindet / Menschen beten
#+date:       [2023-06-19 Mo 09:20]
#+filetags:   :01:sw24:
#+identifier: 20230619T092006


* Kompetenzbeschreibung
[[#B4]] Gelehrte und gelebte Bezugsreligion: Kirchliche Grundvollzüge kennen und religiös-spirituelle Ausdrucksformen gestalten können
[[#B4_KB1]] Die Schülerinnen und Schüler kennen Reichtum und Vielfalt spiritueller und liturgischer Ausdrucksformen und können sie in ihrer Bedeutung nachvollziehen und gestalten.

* AB / UH 
[[#B4_UH1]] Arten / Formen des Gebets


* Wiederholung

** Startseite & Comic

Diese Seite ist der Einstieg in das Thema "Kirche – die Gemeinschaft der Glaubenden" erfahren. Es werden verschiedene Aspekte des Gebetes beleuchtet: Dank, Bitte, Klage Lob

Im Comic wird bereits sehr viel Offenheit und Raum gegeben sich dem Thema anzunähern.

Die verschiedenen Lebenssituationen der Schüler*innen und ihre Gefühle sollen im ersten Schritt betrachtet werden. Weiteres soll den Schüler*innen bewusst werden, dass wir Menschen Beziehungswesen sind, die immer mit jemand anderen bzw. mit Gott in Beziehung stehen.

** 4.1 Menschen beten

Für viele Schülerinnen und Schüler sind verschiedene Gebetsformen nicht mehr in ihrer Lebenswelt relevant. Um auf die Vielfalt des Betens aufmerksam zu machen sind Menschen in unterschiedlichen Situationen bei ihrem Gebet abgebildet.

Die Bilder regen dazu an die verschiedenen Formen des Gebetes zu benennen und darüber ins Gespräch zu kommen.


* Erarbeitung

** Comic
1 Für viele Schüler*innen ist es schwierig ein Gebet aus dem stehgreif zu formulieren. Oft fehlen ihnen die Struktur und die Worte. Diese Thematik greift der Comic auf und will auf eine heitere Art und Weise in das Thema Gebet und Glauben einsteigen. Der Comic kann hier als Diskussionsanregung dienen, um den eigenen spirituellen Erfahrungen, familiäre Gebetspraktiken nachzugehen. Auch Erwartungen, die im Gebet an Gott gestellt werden können, dadurch thematisiert werden.

2 Dieser Arbeitsauftrag soll den Schüler*innen deutlich machen, dass wir uns bei unseren Aussagen und auch in Gedanken immer in Beziehung mit jemand anderen bzw. Gott setzten. Der Arbeitsauftrag zielt auch auf die Gefühle der Schüler*innen in verschiedenen Situationen ab. Die Aussagen bzw. Fragen sollen den Schüler*innen helfen selber über ihre Sorgen, Ängste aber auch Freude nachzudenken und wie sie diese in Worten ausdrücken könnten.

3 Dieser Arbeitsauftrag vertieft den AA 2 ist sehr persönlich und individuell. Weiteres sollen die Schüler*innen darüber nachdenken an wen die Aussage gerichtet ist. Es bietet sich allerdings an danach ein Gespräch in der Klasse über die verschiedenen Aussagen zu führen.

4 Bei diesem Arbeitsauftrag sollen die Sprechblasen kategorisiert werden. Auch Mehrfachantworten sind möglich:

Was soll das? (Klage) - Bitte nicht schon wieder eine schlechte Note! (Bitte) - Ich wünsche mir so sehr, dass sich Mama und Papa wieder vertragen! (Bitte, Klage) - Ich fühle mich so allein… (Klage) - Danke, dass der Tag heute so gut gelaufen ist! (Dank, Lob) - Du bist wirklich der Beste! (Dank, Lob) - Bitte lass den Ball ins Tor gehen! (Bitte) - Ich brauche deine Hilfe! (Bitte)

[[https://www.rpi-loccum.de/material/lernwerkstatt/vorangegangene-ausstellungen/lwst_gebet]]

** Menschen beten
1 Dieser Arbeitsauftrag ist sehr persönlich und individuell. Damit es den Schülerinnen und Schülern leichter fällt ein passendes Gebet zu schreiben, kann man am Beginn dieses Arbeitsauftrages die einzelnen Bilder besprechen.

2 Lösungsvorschläge zu den Bildern:

Bild 1: Fußballfan der um den Sieg seiner Mannschaft bittet – Schal des Fußballclubs, Gesichtsbemalung

Bild 2: Menschen zünden an einem besonderen Gedenkort (z.B. Unfall) eine Kerze an und bringen damit ihre Gefühle zum Ausdruck und ihr Anliegen vor Gott

Bild 3: Ein Bittgebet oder Dankgebet für die gemeinsamen Mahlzeit, das vor oder nach dem Essen gesprochen wird. Die Tischgemeinschaft zeigt sich durch das reichen der Hände.

Bild 4: Zeigt ein Kind, dass für sich alleine betet. Welche Gefühle könnte dieses Kind haben. Worum könnte es bitten? Wofür könnte es sich bedanken?

Bild 5: Zeigt einige Mönche aus dem Kloster der Erzabtei St. Peter in Salzburg beim Chorgebet. Im Kloster unterbrechen die Mönche ihre Tätigkeiten und treffen sich neben dem Gottesdienst 4-mal am Tag zum Gebet:

     - Vigil (Nachtwache) und Laudes (Morgengebet)
     - Mittagshore (Mittagsgebet)
     - Vesper (Abendgebet)
     - Komplet (Gebet zur Nacht)

3 Anlässe, bei denen Menschen gemeinsam oder allein beten könnten sein:

     - Wenn etwas gefeiert wird: Taufe, Hochzeit, Weihnachten, Ostern, etc.
     - Wenn ein trauriger Anlass besteht: Beerdigung, Rosenkranz, Unfall, Katastrophe
     - Wenn Angst und Kummer jemanden bedrückt
     - Freude über ein besonderes Ereignis usw.

4 Dieser Arbeitsauftrag ist sehr persönlich und individuell. Es bietet sich allerdings eine Besprechung und/oder Diskussion der Hintergründe an ("Warum ist das bei dir so?").

* Hefteintrag
Siehe Arbeitsaufgaben 1-4 
