#+title:      Webpages
#+date:       [2023-12-18 Mo 08:15]
#+filetags:   :capture:
#+identifier: 20231218T081552

* Wie das Statistische Bundesamt die Zahlen zur Übersterblichkeit verfälscht hat - 

- Source :: https://multipolar-magazin.de/artikel/destatis-uebersterblichkeit

- Created :: [2023-12-18 Mo 10:02]

Von einer Übersterblichkeit wird gesprochen, wenn in einem Zeitraum mehr Menschen versterben als erwartet. Es wird ein Vorhersagewert (Anzahl der erwarteten Verstorbenen) mit dem Realwert (tatsächlich Verstorbene) verglichen. Ist die Differenz beider Werte positiv, so spricht man von Übersterblichkeit. 

* Steht Gesundheitsminister Lauterbach weiterhin zu seiner Aussage der „nebenwirkungsfreien“ Covid19-Impfung? 

- Source :: https://www.nachdenkseiten.de/?p=108263

- Created :: [2023-12-18 Mo 10:03]

Die Europäische Arzneimittel-Agentur (EMA) hat in einem Schreiben auf die Anfrage mehrerer EU-Parlamentarier dargelegt, dass von Beginn an klar war, dass die COVID-19-Impfstoffe nur dem Schutz der geimpften Person und nicht dem Fremdschutz dienen. Dazu hätten auch keinerlei Daten von den Herstellern vorgelegen. Ebenso spricht die EMA davon, dass sie im Zusammenhang mit der Impfung von zahlreichen Nebenwirkungen ausgeht. 

* Argentiniens neuer Präsident Milei bereitet Bevölkerung auf „Schocktherapie” vor 

- Source :: https://www.nachdenkseiten.de/?p=108277

- Created :: [2023-12-18 Mo 10:06]

Der neue Präsident Argentiniens, Javier Milei, hat dem Land anlässlich
seiner Amtseinführung seine Agenda und sein Regierungskabinett
vorgestellt. „Heute beginnt in Argentinien eine neue Ära, heute endet
eine lange Ära des Niedergangs, und wir beginnen mit dem Wiederaufbau
des Landes”, erklärte der sich selbst als „anarchokapitalistisch”
bezeichnende Milei. Der Weg einer Schocktherapie sei dafür der einzig
mögliche. Von Stephan Hollensteiner.

* „Gemeinsam für den Frieden“ 

- Source :: https://www.nachdenkseiten.de/?p=108298

- Created :: [2023-12-18 Mo 10:09]

Die Resolution 377 A(V) der UN-Vollversammlung (UNGA) besagt, dass alle UN-Mitgliedsstaaten innerhalb von 24 Stunden zu einer „dringenden Sondersitzung“ einberufen werden können, „wenn der Sicherheitsrat wegen fehlender Einstimmigkeit der ständigen Mitglieder seine Hauptverantwortung für die Wahrung des Weltfriedens und der internationalen Sicherheit in einem Fall nicht wahrnimmt, in dem eine Bedrohung des Friedens, ein Friedensbruch oder eine Angriffshandlung vorzuliegen scheint (….)“. Die Resolution trägt den Titel „Gemeinsam für den Frieden“ und wurde erstmals am 3. November 1950 angenommen. Damals ging es um den Korea-Krieg.

