#+title:      Inbox
#+date:       [2023-01-03 Di 18:01]
#+filetags:   :Project:
#+identifier: 20230103T180136
#+CATEGORY: inbox

* TODO [#A] Teacher Assistent eintragen

* Themen für Schule 

* Birthdays
:ROPERTIES:
:CATEGORY: Ann
:END:
%%(diary-remind '(org-anniversary 1969  5 25) -7) Isabelle ist %d Jahre alt
%%(diary-remind '(org-anniversary 1973  5 28) -7) Matthias ist %d Jahre alt
%%(diary-remind '(org-anniversary 2012  2 12) -7) Gabriel ist %d Jahre alt
%%(diary-remind '(org-anniversary 2017  2 10) -7) Leopold ist %d Jahre alt
%%(diary-remind '(org-anniversary 1940  1 31) -7) Vati ist %d Jahre alt
%%(diary-remind '(org-anniversary 1943  2 1) -7) Mutti ist %d Jahre alt
%%(diary-remind '(org-anniversary 1975  8 10) -7) Veronika ist %d Jahre alt
%%(diary-remind '(org-anniversary 1977  3 11) -7) Michael ist %d Jahre alt

* Install and try Vertico, consult and consult-org-roam

[[https://systemcrafters.cc/emacs-tips/streamline-completions-with-vertico/][System Crafters - Vertico]]

[[https://github.com/minad/vertico][Github - Vertico]]

[[https://github.com/minad/consult][Github - consult]]

[[https://github.com/jgru/consult-org-roam][Github - consult-org-roam]]

Ich hab den Schritt gewagt - bis jetzt bin ich sehr zufrieden. Der Umstieg war spannend und ich habe für alle bisherigen helm-Funktionen Alternativen in Vertico / Consult gefunden. Laut den Beschreibungen verwenden beide Pakete die vorhandenen Funtkionen in Emacs. Außerdem ist Vertico modular aufgebaut, es ladet nur jene Funtkionen, die man benötigt bzw konfiguriert. Helm hingegen bringt seine eigene "Struktur" mit und ist va voll-gestopft mit Funktionen, auch mit jenen, die man persönlich nicht braucht.

Mir kommt vor, dass Vertico eine bessere Performance hat - aber der Unterschied mag auch eine rein subjektive Wahrnehmung sein.

Es ist jedes Mal ein großes Aha-Erlebnis, wenn ich neue Funtkionen in Emacs entdecke. Emacs ist doch tatsächlich eine großartige Software!

Bei meinem ersten Versuch klappte Vertico & Co noch nicht auf eine Weise, die mich zufrieden gestellt hatte. Durch einen Fehler in meiner Konfiguration habe ich Emacs komplett neu installiert und von Anfang an auf Vertico gesetzt. Und siehe da: jetzt rennt das Ganze ziemlich stabil. Außerdem ist es immer gut, etwas Neues in Emacs auszuprobieren - ich lerne immer wieder dazu. Das hält lebendig. Ich habe noch orderless hinzugefügt, weiters citar / citar-org-roam, consult-notes, ... jetzt passt es ziemlich gut. Gefällt mir im Ganzen besser als helm.

Der kleine Wermutstropfen, dass ich zuerst mu4e öffnen muss, ein Mail mit =org-roam-capture= verlinken muss - damit später org-insert-link funtkioniert, hat ein Gutes: ich lese aufmerksamer meine Mails.

* Von Org-Roam zu Denote

Ich habe einen weiteren Schritt gewagt: =org-roam= (und seine dazugehörigen Pakete) habe ich aus meiner init.el entfernt und durch das großartige Paket =denote.el= ersetzt. Die =org-roam-capture= - Tempples habe ich in =org-capture= integriert. Dadurch hat sich nicht nur die Startzeit von Emacs wesentlich verbessert (von 2.5 Sekunden auf ca 1.12 Sekunden), auch die allgemeine Performance ist viel schneller und prompter.

=org-protocol= hat nicht mehr gut funktioniert, da war =org-roam-protocol= doch besser. Nun habe ich es mit =org-protocol-capture-html= geschafft. Falls es komische Meldungen geben sollte, kann ich dies mit einem 'M-x server-start' wieder beheben.

Des weiteren hab ich org-agenda derart verbessert: nur jene Denote-files, die "project" als keyword / filetag besitzen, werden als org-agenda-file in die agenda geladen. Für den Stundenplan habe ich die einzelnen Stunden auf die 10 Klassen-Denote-files verteilt. Somit kann ich, wenn ich in einer bestimten Klasse bin, beim Anklicken der betreffenden Stunde in der agenda, direkt das Klassen-file öffnen. Dort befindet sich die aktuelle Stundenvorbereitung, die Schülerliste, etc. 

Ich hab ein wenig mit Hyperbole experimentiert - aber darin keinen Gewinn entdeckt. Außerdem ist das Paket riesig (an Speicherplatz: fast 1GB!). Also: wieder deinstalliert. Es kann für manche wirklich gut sein. Ich werde mich erst mit Denote und dem neuen Setup anfreunden, bevor ich Neues ausprobiere.

* TODO Schulbücher bestellen
DEADLINE: <2023-07-07 Fr 21:00>

- Manuela Gruber: siehe Liste
- 3b: ein Schüler mehr
- 4a: eine Schülerin mehr
  
