#+title:      [SW26] Durststrecken unseres Lebens
#+date:       [2023-03-04 Sa 11:51]
#+filetags:   :01:jahresplanung:
#+identifier: 20230304T115142

* Arbeitsafutrag 1
Dieser Arbeitsauftrag ist sehr persönlich und individuell. Die Schüler*innen nutzen hier die Illustration des Berges (vgl. Bild der „Gipfel“ auf S. 84) um anhand der Metapher des Berges den Anstieg zu Festen zu reflektieren. Mögliche Zuordnungen/Nennungen könnten

** Stolpersteine:
Schularbeiten, schlechte Noten, Stress, Streit, Langeweile, Verletzungen, …
 
** Energiequellen:
Freundinnen und Freunde, Familie, Sonne, Hobbys, gutes Essen, …

** Weggabelungen:
Entscheidungen (z.B. an welche Schule man geht), Streit oder Versöhnung, Lernen oder Freizeit, …

** Gipfel:
Persönliche Ziele, Feste oder Zeiten, auf die man sich besonders freut – z.B. Ferien, ein gutes Zeugnis, Feste im Jahr, …

* Arbeitsauftrag 2
Die Bergsteigerin Gerlinde Kaltenbrunner beschreibt mit ihrem Zitat, dass das Bergsteigen immer ein Ganzes aus Anstieg, Gipfel und Abstieg ist. Als Metapher für das Leben könnte dieses Zitat bedeuten, dass es auch im Leben immer mühsame Anstiege und Durststrecken geben muss, um die Gipfel genießen zu können, sowie anschließende Abstiege, um einen erneuten Anstieg zu ermöglichen. Dauerhafte Gipfelerlebnisse nutzen sich ab. Auch Erkenntnisse der Glücksforschung (z.B. Wilhelm Schmid) bestätigen diese Erkenntnis: Glücksmomente sind nicht dauerhaft, für ein dauerhaftes Glück – im Sinne einer Zufriedenheit – braucht es auch immer wieder Erholungs- und Anstrengungsphasen. Nur so bleiben die besonderen Gipfel auch besonders. Mit Schüler*innenn kann hier etwa gefragt werden, wie ein Leben wäre, an dem sie jeden Tag Geburtstag haben. Nach einer ersten Euphorie merken die Kinder oft sehr schnell, dass sie die Besonderheit des Festes so nicht mehr erleben könnten.

* Arbeitsauftrag 3
Dieser Arbeitsauftrag ist sehr persönlich und individuell. Oft genannt werden positive wie negative Aspekte von Schule, Familie und Freundschaft (vgl. AA1).

* Arbeitsauftrag 4
Hier bietet sich eine Internetrecherche zur Person Gerlinde Kaltenbrunners an. Als eine der erfolgreichsten Extrembergsteigerinnen hat sie viele Gipfel erklommen, aber auch immer wieder mühsame Anstiege vor sich gehabt – und nicht selten den einen oder anderen Gipfelsturm abbrechen müssen. Auch diese speziellen Erfahrungen lassen sich als Metapher auf das Leben übertragen. Mit den Schüler*innenn kann besprochen werden, wie solche Enttäuschungen und Schwierigkeiten im Leben positiv wirken können.
