#+title:      Zeichen Symbole
#+date:       [2023-01-15 So 12:44]
#+filetags:   :kirche:theology:
#+identifier: 20230115T124407



* Arbeitsaufträge
1 Die Schüler*innen erklären in eigenen Worten den Unterschied zwischen einem Zeichen und Symbol. Sie festigen dadurch den Sachinhalt und stellen eine Beziehung zwischen den beiden Begriffen her.


2 Die Bilder werden durch ein  "S" - Symbol bzw. "Z" - Zeichen unterschieden:
Bild 1 „Herz“ – S
Bild 2 „Rotes Kreuz“ – Z
Bild 3 „Verkehrsschild: Fahrverbot“ – Z
Bild 4 „Daumen hoch“ – S
Bild 5 „Taube“ – S
Bild 6 „Sonne“ – S
Bild 7 „Mann/Frau“ – Z


3 Mögliche Titel für die Zeichen und Symbolde können sein:
Bild 1 „Herz“ – Liebe
Bild 2 „Rotes Kreuz“ – Rettung /Hilfe
Bild 3 „Verkehrsschild: Fahrverbot“ – Stopp/Fahrverbot
Bild 4 „Daumen hoch“ – Gut gemacht/Super
Bild 5 „Taube“ – Friede
Bild 6 „Sonne“ – Sonnenschein/Wärme/Sommer
Bild 7 „Mann/Frau“ – Toilette


4 Dieser Arbeitsauftrag ist persönlich und individuell. Die Auswahl der eingetragenen Symbole hängt stark vom Vorwissen der Schüler*innen ab. Für manche Schüler*innen ist es hilfreich, wenn verschiedene Symbole oder Zeichen im Klassenverband mündlich gesammelt werden.


5 Dieser Arbeitsauftrag ist für diese Schulstufe eine sehr anspruchsvolle Aufgabe. Für die Diskussion ist grundlegend, dass die Begriffe „Logo“ und „Emoji“ erläutert werden.
Logo: Das Wort Logo stammt vom griechischen Wort „logos“ ab und bedeutet „Wort“. Es ist ein grafisches Zeichen, dass ein bestimmtes Subjekt (z.B.: eine Marke, Unternehmen, …) repräsentiert. Ein Logo vermittelt den „ersten Eindruck“ lange bevor wir uns mit der Bedeutung bewusst auseinandersetzten.
Emoji: Dieser Ausdruck leitet sich vom Begriff Emoticon ab. Dieser setzt sich aus „emotion“ (Gefühl) und „icon“ (: Zeichen) zusammen und beschreibt kurze Zeichenfolgen aus Buchstaben, Zahlen und Symbolen, die wiederum Mimik (Gesichtsausdrücke) darstellen sollen.
Mit Emojis können Emotionen ausgedrückt und Aussagen verstärkt werden, damit das Gegenüber besser weiß, was gesagt werden will. Genutzt werden die Emojis in allen möglichen Messenger Diensten und sozialen Netzwerken, wie etwa WhatsApp, Twitter, Snapchat, etc.


6 Mögliche Erklärung für den höheren Wert des zerbrochenen Steines könnte lauten:
„Die beiden Hälften des Steines stehen für die Erinnerung an die gemeinsame Urlaubszeit und den Beginn der Freundschaft der beiden Mädchen.“


7 Weitere Symbole für Freundschaft, Liebe oder Gemeinschaft die genannt werden können sind:

    Herz bzw. zwei ineinander verschlungene Herzen
    Hände, die sich gereicht werden
    Herz mit Pfeil
    Puzzleteile, die ineinandergreifen
    Ying und Yang-Zeichen
    Menschen, die sich umarmen
    Ring
    Unendlichkeitszeichen
    Kussmund
    Rose
    Love

    
8 Mögliche Lösungsvorschläge: 
Bei den Beispielen werden zuerst die "sichtbare Tatsache"  und dann das "unsichtbare Geheimnis" genannt:

    Herz - Liebe
    Hände, die sich gereicht werden - Freundschaft, Zusammenhalt
    Puzzleteile, die ineinandergreifen / Ying und Yang - Zueinanderpassen - Freundschaft
    Ring / Unendlichkeitszeichen - Kein Anfang und Ende - Unendlichkeit der Liebe bzw. Freundschaft
    Rose - Blume Liebe, Zuneigung, Schönheit
    Menschen, die sich umarmen - Keiner ist ausgeschlossen, Zusammengehörigkeit
    Kussmund, „Love“ - Verliebt sein 



