#+title:      [SW36] Lauf des Lebens / das Kirchenjahr
#+date:       [2023-06-19 Mo 14:55]
#+filetags:   :01:sw36:
#+identifier: 20230619T145518


* Kompetenzbeschreibung
[[#C5]] Religiöse und weltanschauliche Vielfalt in Gesellschaft und Kultur: Medien, Kunst und Kultur im Kontext religiöser Weltwahrnehmung interpretieren, beurteilen und gestalten können

Die Schülerinnen und Schüler können das Kirchenjahr mit seinen Festen als Rhythmus des Lebens verstehen und mitgestalten.

* AB / UH
[[#C5_UH1]] Kirchenjahr

* Wiederholung


* Erarbeitung

1 Hier genügt eine ungefähre Zuordnung. Bei der Farbenwahl bietet es sich an, sich an den Farben der auf S. 91 genannten Jahreszeiten zu orientieren.

2 Dieser Arbeitsauftrag hängt von den persönlichen Daten und dem Umfeld der Schüler*innen ab. Neben dem Geburtstag und dem Schulanfang können weitere wichtige Daten und Termine des Jahres genannt und markiert werden.

3 Dieser Arbeitsauftrag ergänzt AA2 um den Fokus auf Feste. Hier bieten sich vor allem Familienfeiern oder Feste in Schule und/oder Vereinen an.

4 Der Symbolgehalt von Farben ist Kindern oft erstaunlich vertraut. Genannt werden könnten etwa:

- Grün als Farbe der Hoffnung
- Schwarz als Farbe der Trauer
- Gelb oder Grün stehen oft für den Sommer
- Grün als Farbe der Natur
- Gold als Farbe des Reichtums
- Gold, Silber und Bronze als drei Farben des Sieges
   

5 Dieser Arbeitsauftrag ist stark abhängig davon, welche kirchlichen Feste die Schüler kennen. Kirchlich sozialisierte Kinder kennen hier oft nahezu alle im Jahreskreis wichtigen Feste, andere wiederum werden nur einige wenige (Ostern, Weihnachten, ...) nennen können.

6 Im Gegensatz zum sehr linearen Verständnis eines Jahres – wie es etwa der Kalender suggeriert – versteht sich das Kirchenjahr als Kreis, der sich schließt, um wieder neu zu beginnen. Für die hier genannte philosophische Fragestellung könnten sich Methoden und Ansätze des Philosophierens mit Kindern (vgl. Kapitel 2) anbieten. Verwiesen werden kann auch darauf, dass sich unterschiedliche Religionen und Kulturen auch das Leben entweder als Linie (z.B. Christentum, Judentum, Islam) oder als Kreis (z.B. Buddhismus und Hinduismus) vorstellen. Je nach Ansatz wirken Jahr und Leben so entweder als abgeschlossene Einheiten oder als Wiederholung.

* Hefteintrag

