#+title:      Gespräch Krallinger
#+date:       [2023-03-10 Fr 17:32]
#+filetags:   :3b:krallinger:
#+identifier: 20230310T173200

* Vorüberlegungen
Tipps von Manuela:
Du musst nicht jede Mitarbeit von Thomas belegen können.

Frage: warum kommen Sie jetzt um nach der Note zu fragen? Das erste Semester liegt schon etwas zurück.

Die Religionsnote setzt sich v.a. aus der Mitarbeit / Heftführung zusammen. Und diese ist bei Thomas eben nicht so gut, dass ich ihm ein Sehr Gut oder Gut geben kann. Ich mache beuwsst keinen Test - die Schüler haben schon genug Fächer, in denen sie geprüft werden. Im Gegenzug erwarte ich aber eine viel aktivere Teilnahme am Unterricht. In Religion ist Raum und Zeit für viele Themen und Austausch zu vielen Themen. 

Seit dem Gespräch zum Elternsprechtag hat sich leider das Verhalten von Thomas nicht gebessert. Im Gegenteil. Wie ich es angekündigt hatte, habe ich daher für mehrere Schüler als Verhaltensnote ein WZ beantragt. Dies wurde einstimmig von allen Lehrern der 3b bestätigt.

Auch andere Lehrer der Klasse klagen über das schlechte Verhalten in dieser Klasse. Daher wurde u.a. ein zusätzlicher Tisch in die Klasse gestellt, um Schüler trennen zu können.

Thomas und die anderen Burschen stören nicht nur meinen / unseren Unterricht, machen dadurch ein ruhiges Lernen unmöglich. Sondern sie verhindern auch, dass jene, die gerne wollen, am Unterricht teilnehmen können.

Wenn ein Schüler (massiv) den Unterricht stört und er eine dementsprechende Verhaltensnote erhält, dann kann er nicht gleichzeitig eine gute Leistung im Unterricht bringen. Die Religionsnote ergibt sich auch logischerweise aus dem Verhalten, v.a. da ich besnders auf die Mitarbeit großen Wert lege.

Es kann sein, dass ich in der ersten und zweiten Klasse zu gutmütig war, und manche Noten zu leichtfertig verschenkt habe. Ich gab den Kindern einen Vertrauensvorschuss und dachte, dass die Kinder dies mit guter Mitarbeit beantworten würden. Ich wurde enttäuscht und das kann ich jetzt nicht mehr machen.

Etwas Positives: alle betroffenen Burschen haben verstanden - wenn sie ihr Verhalten ändern und besser mitarbeiten, können sie sich ihre Note verbessern. Ich kann keine guten Noten einfach herschenken. 

* Memo
Es haben sich leider meine Befürchtungen bestätigt: Fr. Krallinger hat fersucht, mich "aufzublatteln"; kam mit Gesetzestexten, etc. Hmpf! Hat sie aber nicht geschafft.

Ich hab ihr die Situation dargelegt, wie "siehe oeben".

Manuela Gruber hat mich bestärkt - keine Sorgen machen.
