#+title:      [SW26] Arten von Gebeten / mit dem Körper beten
#+date:       [2023-06-19 Mo 09:24]
#+filetags:   :01:sw26:
#+identifier: 20230619T092443


* Kompetenzbeschreibung
[[#B4]] Gelehrte und gelebte Bezugsreligion: Kirchliche Grundvollzüge kennen und religiös-spirituelle Ausdrucksformen gestalten können
[[#B4_KB1]] Die Schülerinnen und Schüler kennen Reichtum und Vielfalt spiritueller und liturgischer Ausdrucksformen und können sie in ihrer Bedeutung nachvollziehen und gestalten.

* AB / UH 
[[#B4_UH1]] Arten / Formen des Gebets


* Wiederholung
4.3 Arten von Gebeten

Dieses Unterkapitel thematisiert, das das Beten in den verschiedensten Lebensbereichen seinen Platz findet. Der Vergleich zwischen dem einzelnen (persönlichen) und dem gemeinsamen (allgemeinem) Gebet macht deutlich, dass vor Gott sowohl für jedes einzelne Bedürfnis als auch alle Anliegen der Gemeinschaft vor Gott getragen werden kann. Bestimmte Gebetsstrukturen erleichtern sowohl das Formulieren eines persönlichen Gebetes als auch das in einer Gemeinschaft gesprochene Gebet.

* Erarbeitung

** Arten von Gebeten
1 Im Ausprobieren der einzelnen Gebetsarten soll den Schülerinnen und Schülern bewusst gemacht werden, das Beten verschiedene Bereiche des Lebens umfasst. Dieser Arbeitsauftrag zielt auch auf die Erfahrung der Kinder ab, welche sie beim Beten machen könnten. Der Unterschied von einem einzelnen Gebet und gemeinsamen Gebet soll durch das gemeinsame Sprechen deutlich gemacht werden.
Für Kinder ist es auch eine sehr bereichernde Erfahrung gemeinsam die Stille wahrzunehmen. Die Verwendung einer Klangschale erleichtert diese Übung.

2 Dieser Arbeitsauftrag ist sehr persönlich und individuell. Er zielt auf die Erfahrungen der Kinder ab, die sie in ihrem Leben zum Thema beten schon gemacht haben. Normalerweise finden sie genug Beispiele in welcher Lebenssituation welche Art von Gebet verwendet werden kann. Auch ihre Erfahrungen aus der Volksschule und aus ihrem familiären Umfeld fließen hier oft mit ein.

3 Dieser Arbeitsauftrag kann ein Bittgebet mit den vier Schritten des Impulses (S.64-65) formuliert werden. Hierbei wird der Grund-Aufbau (Anrede – Anliegen – Abschluss – Amen) noch einmal wiederholt und gefestigt werden. Wichtig ist das die Gebete der Schülerinnen und Schüler nicht verbessert werden, sondern dass die Sprache die sie verwenden genauso passt wie sie ist.

4 Dieser Arbeitsauftrag ist sehr persönlich und zielt auf die Erfahrungen und Erzählungen der Schüler*innen ab. Zunächst geht es darum die Schüler*innen über ihre eigenen Enttäuschungen, wenn Bitten und Wünsche nicht erfüllt werden zu reflektieren. Diese Reflexionen führen meist schnell in eine sehr spannende Diskussion. Für gewöhnlich finden sie zahlreiche Beispiele und auch gute Begründungen.

** Mit dem Körper beten
1 Lösungsvorschläge für die Zuordnungen:

Nr. 6 Bild 1: Hände

Nr. 7 Bild 2: Paul im Schneidersitz

Nr. 4 Bild 3: Lisa steht und hat ihre Hände gefaltet

Nr. 5 Bild 4: Elena stehend mit Wanderstock

Nr. 1 Bild 5: Theo stehend mit ausgebreiteten Händen

Nr. 3 Bild 6: Elena sitzend, Hände am Schoß liegend

Nr. 2 Bild 7: Paul kniend mit geschlossenen Augen

Nr. 8 Bild 8: Theo steht und hält die Hand zur Versöhnung entgegen.

2 Dieser Arbeitsauftrag soll sehr behutsam durchgeführt werden, damit kein Gelächter bzw. Unruhe entsteht. Obwohl jeder in der Klasse gefordert ist gemeinsam die Gebetshaltungen auszuprobieren gestaltet sich die Aufgabe sehr individuell. Es bietet sich allerdings eine Besprechung und/oder Diskussion der Hintergründe an: "Warum fühlst du dich in dieser Haltung wohl?"

3 Diese Arbeitsauftrag beschäftigt sich mit den Gefühlen und Erfahrungen der Schülerinnen und Schüler. Jeder Gebetshaltung kann je nach Gefühlslage sehr persönlich und individuell beantwortet werden. (Wenn der AA2 davor gemacht wurde kann dieser vertieft werden.) Den dargestellten Gebetshaltung können Gefühle, Stimmungen und Anliegen zugeordnet werden. Mögliche Beschreibungen könnten wie folgt aussehen:

    Bild - Hände reichen: Sich an den Händen zu fassen drückt Gemeinschaft aus. Man kann sich aneinander festhalten. Es gibt ein Gefühl der Sicherheit und Geborgenheit. Das Anliegen könnte sein: „Gemeinsam schaffen wir alles.“ „Wir halten zusammen.“ „Du gehörst dazu.“ Normalerweise ist die Stimmung gut, aber es gibt auch Momente, wo ich lieber keinem anderen die Hand gebe.

    Bild – Schneidersitz: Ich habe das Gefühl, ich bin ganz ruhig. Ich konzentriere mich auf das hier und jetzt. Mein Atem wird ruhig und herum herrscht Stille. Ich versuche in meinen Gedanken ganz bei Gott zu sein.
    
    Bild – Stehend Hände gefaltet: Ich fühle mich wohl und glücklich. Ich spüre den Boden unter meinen Füßen. Nichts macht mir Angst. Ich freue mich, dass ich Gott alles anvertrauen kann.
    
    Bild – Gehend mit Wanderstock: Auch wenn ich unterwegs bin fühle ich mich begleitet. Am Wanderstock kann ich mich festhalten. Er gibt mir Sicherheit. Ich freue mich auch auf neue Wege. Ich bin neugierig und mutig.
    
    Bild – stehend, Hände ausgebreitet: Beide Beine stehen sicher auf dem Boden. Freude, Neugierde, Erwartungen sind die Gefühle, die die Leitfigur ausdrückt. Sie könnte sagen: „Ich bin offen für alles was auf mich zukommt.“ „Ich bin mutig und stark.“
    
    Bild – sitzend: Die sitzende Haltung drückt wenig Bewegung aus. Die Hände ruhen auf den Oberschenkeln, nicht einmal die machen ein Geräusch. Dadurch kann man sich ganz auf das konzentrieren, was man hört. Die Figur drückt ein Gefühl der Ruhe und Entspannung aus. Vielleicht wartet sie achtsam auf Antworten.
    
    Bild – kniend: Wenn ein Mensch kniet macht er sich klein. Vieles ist sehr viel größer. Ehrfurcht und Demut sind die Gefühle, die ausgedrückt werden. Das Anliegen könnten verschiedene Bitten sein aber auch tiefe Dankbarkeit könnte hier vor Gott gebracht werden.
    
    Bild – stehend, rechte Hand abgewinkelt: Die Hand kann zweierlei gedeutet werden. Entweder man sieht darin eine „Hand aufs Herz“ oder sie wird dem Gegenüber als Entschuldigung ausgestreckt. Schuldgefühle oder auch Erleichterung können die Gefühle sein, die diese Leitfigur hat.

* Hefteintrag
