#+title:      [SW06] Eine gute Gemeinschaft
#+date:       [2023-06-19 Mo 07:43]
#+filetags:   :01:sw06:
#+identifier: 20230619T074359


* Kompetenzbeschreibung
[[#A1]] Menschen und ihre Lebensorientierungen: Beziehung verantwortungsvoll gestalten können – zu sich selbst, zu anderen, zur Schöpfung
[[#A1_KB1]] Die Schülerinnen und Schüler können sich in ihrer gottgeschenkten Einzigartigkeit wahrnehmen und wissen um die Bedeutung von (Selbst-) Vertrauen für ein gelingendes (Zusammen-)Leben.


* AB / UH
[[#A1_UH1]] Teamfähigkeit 


* Wiederholung


* Erarbeitung

** Info für Lehrer - Handeln: Gemeinsam entscheiden
Die – sicherlich an manchen Stellen herausfordernde – Methode "Gemeinsam entscheiden" basiert auf [[https://www.cap-lmu.de/akademie/praxisprogramme/betzavta-miteinander/]["Betzavta - Mehr als eine Demokratie"]], einem Ansatz des Demokratielernens, der "fünf Schritte demokratischer Entscheidungsfindungen" kennt. Im Hintergrund steht die Beobachtung, dass *Autoritäts-*, aber auch *Mehrheitsentscheidungen* oft besonders unzufriedene und frustrierte *Minderheiten* schaffen. Dies gilt insbesondere auch für Schulklassen, in denen entweder Autoritäten (Lehrer*innen, Eltern, Anführer*innen etc.) entscheiden, oder die Klasse in einem "demokratischen Prozess" eine Mehrheitsabstimmung durchführt, die Minderheiten oder spezielle Bedürfnisse oft "niederstimmen". 
Die Methode "Gemeinsam entscheiden" ist ein erster Schritt der Annährung an ein größeres Modell des *Demokratielernens*, das in allen vier Bänden von "Religion für uns" aufgegriffen wird. Es ist eine notwendige Vereinfachung, die im Laufe der folgenden Bände erweitert und vertieft werden wird.


*** Lösungsvorschläge (S. 21):
Im Folgenden soll anhand der oben abgebildeten Bedürfnisse Schritt für Schritt die Methodik der "vier Schritte zu einer gemeinsamen Entscheidung" besprochen und reflektiert werden. Anschließend kann diese Methode für ein weiteres Beispiel oder eine reale gemeinsame Entscheidung angewendet werden.

1 In einem ersten Schritt soll festgestellt werden, um welche Entscheidung es eigentlich geht – dieser Schritt ist notwendig, bevor überhaupt Optionen und Lösungsmöglichkeiten benannt werden, beugt er doch vorschnellen "faulen Kompromissen" vor, die keine Lösung sein können, weil das Problem noch gar nicht benannt ist. In diesem Beispiel ist die Frage relativ klar: Es geht um die gemeinsame Nachmittagsgestaltung – hier braucht es eine Entscheidung, welches Programm die vier Freundinnen und Freunde wählen.

2 Der zweite Schritt ist in dieser Methodik entscheidend: Anstatt Vorschläge zu sammeln und darüber abzustimmen bzw. die Schnelleren/Stärkeren entscheiden zu lassen, stehen hier die Bedürfnisse im Vordergrund. Diese dürfen nicht mit den einzelnen Optionen und deren "Favoriten" verwechselt werden: Bedürfnisse sollten so artikuliert werden, dass der wirkliche Wunsch, nicht seine Ausgestaltung in einem Programmpunkt zu Tage tritt. Als "Probe" können die Bedürfnisse auch begründet werden – ein "ich will XY" reicht hier nicht mehr aus, es braucht eine Verwurzelung im Bedürfnis.
In diesem Beispiel wären die Bedürfnisse etwa (von links nach rechts): "Ich möchte mein neues Kartenspiel ausprobieren", "Ich möchte meinen neuen Drachen ausprobieren", "Ich brauche Hilfe beim Lernen" und "Ich würde gerne das Wetter ausnützen und schwimmen gehen". 
Wichtig ist hierbei, dass es nicht um "entweder-oder", sondern um ein Nebeneinander von gleichwertigen Bedürfnissen geht: Jede*r hat das Recht auf eine freie Entfaltung der eigenen Bedürfnisse – die wirkliche gemeinsame Aushandlung und Entscheidung geschieht erst in den nächsten Schritten.

3 Im dritten Schritt verschaffen sich alle einen Überblick über alle Bedürfnisse – hier gilt vor allem: Jedes Bedürfnis ist gleich wichtig und jede*r hat grundsätzlich das gleiche Recht, seine/ihre Bedürfnisse zu erfüllen. Die Aushandlung und gemeinsame Entscheidung geschieht erst im nächsten Schritt. Hier steht der Austausch und das Äußern der Bedürfnisse im Vordergrund – dies ist vor allem wichtig, weil die Bedürfnisse leiserer oder zurückhaltenderer Schüler*innen sonst oft wenig Gehör finden oder abgetan werden.

4 Im vierten Schritt soll nun kreativ nach neuen Lösungen gesucht werden: Denkt man von den Bedürfnissen und nicht von den einzelnen Optionen weg, ergeben sich oft ganz neue Möglichkeiten, weil oft stillschweigende Annahmen verlassen werden. Ist es z.B. notwendig, dass der gesamte Nachmittag durchgehend gemeinsam verbracht wird? Ist es überhaupt für alle wichtig, dabei zu sein? Lassen sich die einzelnen Bedürfnisse auch neben- oder nacheinander erfüllen? Oder gibt es kreative "Gesamtlösungen" – etwa ein Nachmittag am See mit Spielen, Drachensteigen und gemeinsamen Lernen?
Schüler*innen sind für gewöhnlich sehr kreativ im Ausmalen von Lösungsoptionen. Wichtig ist, dass sie realistisch bleiben, schließlich geht es hier um wichtige gemeinsame Entscheidungskompetenzen. Die Annährung an die Bedürfnisorientierung ist hier nur ein erster Schritt. Den Schüler*innen soll vermittelt werden, dass es hilfreich sein kann, nicht die Optionen in den Vordergrund zu stellen (und sie vielleicht per Mehrheit durchzusetzen), sondern zunächst auf die einzelnen Bedürfnisse zu achten, die sich oft ungeahnt gut kombinieren lassen, sobald der Pfad des entweder-oders bzw. der Konkurrenz der einzelnen Optionen verlassen wird.

Film (YouTube): 
[[https://youtu.be/Z01AJLnv0Sc]]

* Hefteintrag
