#+title:      Jesus Quelle des Lebens
#+date:       [2023-01-03 Di 22:31]
#+filetags:   :jesus:sehnsucht:
#+identifier: 20230103T223143

* Komepetenzbeschreibung
[[#A2]] Menschen und ihre Lebensorientierungen - Sich mit den großen Fragen der Menschen auseinandersetzen können
[[#A2_KB1]] Die Schüler können Perspektiven für ihr Leben entwickeln und  Zukunftspläne entwerfen. 

* AB / UH
[[#A2_UH1]] Sehnsüchte und Lebensträume

* Wiederholung


* Erarbeitung
Jesus = Quelle meines Lebens; das klingt, ist doch sehr abstrakt.

"Ohne mich könnt ihr nichts tun." - Jesus ist hier sehr eindeutig: NICHTS. So lange wir das nicht verstanden haben, gehen wir am Wesentlichen des christlichen Glaubens vorbei. Wir sind als Geschöpfe total, komplett von Gott abhängig. Gott (Jesus) ist die Quelle unseres Lebens, des Friedens, der Freude, ... 

Quelle = Ursprung eines Flusses; frisch; lebendiges Wasser; ...

Joh 4: Jesus und die Samariterin

Das Wasser ist der Glaube, der ewiges Leben schenkt.

[[file:~/org/notes/2020-09-15-1042 Samariterin.org]]

Symbol Wasser:
 - Wasser ist Basis des Lebens (so wie Brot); das wissen besonders die Menschen, die in der Wüste wohnen (Zeitgenossen Jesu)
 - Genauso wesentlich ist Jesus schlicht und exklusiv Grundlage des ewigen Lebens.
 - Wasser ist nicht machbar, sondern eine Gabe der Natur - meistens kommt es "von oben". Wenn das Wasser nicht von der Quelle, Teich oder Fluss kommt, ist der Mensch am Ende. 
 - Somit ist Wasser ein Symbol für die Abhängigkeit von Gott.
 - Trinkbares Wasser ist "lebendiges" Wasser, dh das Wasser fließt oder sprudelt aus der Quelle.
 - Wassertrinken ist kein Selbstzweck, sondern dient dem Hervorbringen von Worten, Werken, ... Bei Pflanzen sind dies die Früchte. Die Wirkungen kann man sehen.
 - Kontrast zu Wein: er ist Luxus und zum Feiern da. Beide, Wasser und Wein durchdringen das Lebenwesen komplett. So soll uns auch Gott, der Hl. Geist durchdringen.

Die Frau versteht die Metapher wortwörtlich. Jesus sagt der Frau auf den Kopf zu, wie ihr Privatleben war / ist. Das kann nur Gott, also ist Gott in Jesus anwesend - er ist der Messias. 

Zwischen Juden und Samariter herrscht "Krieg"; sie betrachten sich gegenseitig als Ketzer. Juden (Männer) sprechen daher nicht mit Samariter, und noch weniger mit Frauen in der Öffentlichkeit - schon gar nicht mit einer samaritischen Frau an einem Brunnen. 

Die Frau kommt zu Mittag zum Brunnen, so sonst keiner kommt, da es zu heiß ist. Man schöpft Wasser in der Früh oder am Abend. Brunnen ist ein Ort der Begegnung - und einige Liebesgeschichten begannen an einem Brunnen (Isaak, Jakob). Die Samariterin will also allein sein, vielleicht hat sie etwas zu verbergen. 

* Hefteintrag

