#+title:      01 Golling
#+date:       [2023-06-21 Mi 07:33]
#+filetags:   :01:plan:Project:
#+identifier: 20230621T073313
#+CATEGORY: Topic 01

* Klassen
[[denote:20230708T143857][A Klasse 2023-27]]

[[denote:20230708T143945][B Klasse 2023-27]]

* Jahresplanung

** DONE [[denote:20230619T073700][[SW01] Jahresstoff / ich stehe in den Schuhen des Anderen]]
CLOSED: [2023-09-23 Sa 18:31] SCHEDULED: <2023-09-11 Mo>
:LOGBOOK:
- State "DONE"       from              [2023-09-23 Sa 18:31]
:END:

** DONE [[denote:20230619T074010][[SW02] Eine Gemeinschaft, die uns stärkt]]
CLOSED: [2023-09-25 Mo 08:33] SCHEDULED: <2023-09-18 Mo>
:LOGBOOK:
- State "DONE"       from              [2023-09-25 Mo 08:33]
:END:

** DONE [[denote:20230619T074058][[SW03] Was ich mir zutraue / Kann ich dir vertrauen?]]
CLOSED: [2023-09-30 Sa 12:04] SCHEDULED: <2023-09-25 Mo>
:LOGBOOK:
- State "DONE"       from              [2023-09-30 Sa 12:04]
:END:

** DONE [[denote:20230619T074141][[SW04] Wir sind eine Gemeinschaft]]
CLOSED: [2023-10-07 Sa 23:03] SCHEDULED: <2023-10-02 Mo>
:LOGBOOK:
- State "DONE"       from              [2023-10-07 Sa 23:03]
:END:

** [[denote:20230619T074226][[SW05] Das große Durcheinander]]
SCHEDULED: <2023-10-09 Mo>

** [[denote:20230619T074359][[SW06] Eine gute Gemeinschaft]]
SCHEDULED: <2023-10-16 Mo>

** DONE [SW07] Herbstferien1
SCHEDULED: <2023-10-23 Mo>

** [[denote:20230619T085157][[SW08] Fragen die uns bewegen (Kap. 2)]]
SCHEDULED: <2023-10-30 Mo>

** [[denote:20230619T085426][[SW09] Große Fragen - große Antworten]]
SCHEDULED: <2023-11-06 Mo>

** [[denote:20230619T085724][[SW10] Harte Fakten - gute Gedanken?]]
SCHEDULED: <2023-11-13 Mo>

** [[denote:20230619T085846][[SW11] Methode: Fragen stellen (philosophieren)]]

** [[denote:20230619T090127][[SW12] Beginn Advent - Singen von Adventliedern]]

** [[denote:20230619T090707][[SW13] Maria Empfängnis (8.12.)]]

** [[denote:20230619T090758][[SW14] Ave Maria]]

** [[denote:20230619T091059][[SW15] Jesus ist geboren / Weihnachtsgottesdienst]]

** DONE [SW16] Ferien

** DONE [SW17] Ferien

** [[denote:20230619T091440][[SW18] Jesus, der Mensch - Jesus der Christus]]

** [[denote:20230619T091611][[SW19] Bibel: Mit der Bibel arbeiten]]

** [[denote:20230619T091723][[SW20] Für einen treuen Freund gibt es keinen Preis]]

** [[denote:20230619T091826][[SW21] David und Jonathan]]

** [[denote:20230619T091911][[SW22] Wiederholung / Film]]

** DONE [SW23] Semsterferien

** [[denote:20230619T092006][[SW24] Eine Kirche die uns verbindet / Menschen beten]]

** [[denote:20230619T092126][[SW25] Über mein Leben nachdenken / Impuls: Dankbar sein]]

** [[denote:20230619T092443][[SW26] Arten von Gebeten / mit dem Körper beten]]

** [[denote:20230619T092702][[SW27] Vielfalt unseres Betens / wie wir beten können]]
   
** [[denote:20230619T092912][[SW28] Die Bitten unseres Lebens / Das Vaterunser]]

** [[denote:20230619T144913][[SW29] Die Gemeinschaft der Glaubenden]]

** DONE [SW30] Karwoche / Osterferien

** [[denote:20230619T145033][[SW31] Ich gehöre dazu / ein gemeinsamer Glaube]]

** [[denote:20230619T145125][[SW32] Jesus ist auferstanden / Osterfestkreis (Kap 5.7)]]

** [[denote:20230619T145222][[SW33] Gottes Gegenwart feiern / Übungsteil]]

** [[denote:20230619T145319][[SW34] Eine Welt die uns prägt / Die Feste unserer Welt]]

** [[denote:20230619T145418][[SW35] Durstrecken unseres Lebens / Grund zu feiern]]

** [[denote:20230619T145518][[SW36] Lauf des Lebens / das Kirchenjahr]]

** [[denote:20230619T145559][[SW37] Feste im Kirchenjahr / Übungsteil]]

** [[denote:20230619T145640][[SW38] Vielfalt, die uns eint / Wo ich Zuhause bin]]

** [[denote:20230619T145734][[SW39] Unsere Vielfalt]]

** [[denote:20230619T145818][[SW40] Vielfalt der Reigionen]]

** [[denote:20230619T145913][[SW41] Weltreligionen / Drei Konfessionen stellen sich vor]]

** [[denote:20230619T150019][[SW42] Übungsteil]]

** [[denote:20230623T174332][[SW43] Schulgottesdienst]]


* Kompetenzbereiche und Kompetenzdimensionen

** Kompetenzmodell und -bereiche
Das Kompetenzmodell für den katholischen Religionsunterricht beinhaltet schulstufenübergreifend drei inhaltsbezogene Kompetenzbereiche und fünf handlungsorientierte Kompetenzdimensionen. Kompetenzbereiche sind inhaltlich geprägte nähere Umschreibungen von Sachgebieten, in denen religiöse  Kompetenzen erworben werden. Sie werden durch je zwei Leitkompetenzen konkretisiert:

**** A Menschen und ihre Lebensorientierungen
:PROPERTIES:
:CUSTOM_ID: A
:ID:       6b68956f-aff0-48b7-8b7a-8352ffd83ea6
:END:
***** A1 Beziehung verantwortungsvoll gestalten können – zu sich selbst, zu anderen, zur Schöpfung
:PROPERTIES:
:CUSTOM_ID: A1
:ID:       78dc1f2b-f2f0-4b14-9b57-2db17bc10edc
:END:
****** Kompetenzbeschreibung:
:PROPERTIES:
:CUSTOM_ID: A1_KB1
:ID:       633ff781-4a7b-41d9-a50c-1d470d29dcf9
:END:
Die Schülerinnen und Schüler können sich in ihrer gottgeschenkten Einzigartigkeit wahrnehmen und wissen um die Bedeutung von (Selbst-) Vertrauen für ein gelingendes (Zusammen-)Leben.

****** Anwendungsbereiche
:PROPERTIES:
:CUSTOM_ID: A1_AB1
:ID:       c470b3f6-0462-4ca9-93ee-bb308dc3de3a
:END:

****** Unterrichtshinweise
:PROPERTIES:
:CUSTOM_ID: A1_UH1
:ID:       22cd8479-45a9-4274-9d57-f2143f13feda
:END:
Ich und die anderen:
 - Selbstvertrauen, [[#Die Welt der Gefühle]] [[#Vertrauen]]
 - Freundschaft, [[#Freundschaft]] [[#treuer Freund]]
 - Empathie und Perspektivenwechsel, [[#Schuhe des Anderen]] 
 - Teamfähigkeit, [[#Gemeinschaft]] [[#eine gute Gemeinschaft]]
 - Nähe und Distanz,
 - Zärtlichkeit und Sexualität

****** Kompetenzbeschreibungen
:PROPERTIES:
:ID:       b708f918-fcec-4f12-8a1f-1477eee3b382
:END:
****** Anwendungsbereiche
:PROPERTIES:
:ID:       3e9b622d-27c5-41ca-a2ac-396c15ca3e8e
:END:
****** Unterrichtshinweise
:PROPERTIES:
:ID:       dc3759a8-aa6f-449a-a598-3b36f7dd20d8
:END:

***** A2 Sich mit den großen Fragen der Menschen auseinandersetzen können
:PROPERTIES:
:CUSTOM_ID: A2
:ID:       1b855fa1-537a-4d14-af4e-4db124066a28
:END:
****** Kompetenzbeschreibungen
:PROPERTIES:
:CUSTOM_ID: A2_KB1
:ID:       e43fcd56-1bbc-4d49-8177-29bbca2204b5
:END:
Die Schülerinnen und Schüler können für sie bedeutsame Fragen diskutieren und über existentielle Lebensfragen philosophieren und theologisieren.  

****** Anwendungsbereiche
:PROPERTIES:
:CUSTOM_ID: A2_AB1
:ID:       f63585d7-167b-41e0-b890-4a64789a47bb
:END:

****** Unterrichtshinweise
:PROPERTIES:
:CUSTOM_ID: A2_UH1
:ID:       abce94a7-090d-40a6-87f7-7d1f2c2f1712
:END:
Beantwortbare und letztlich unbeantwortbare Fragen: [[#Fragen unseres Lebens]]
- Wer ist Gott? Existiert Gott? [[#Große Fragen große Antworten]]
- Existiert überhaupt etwas? [[#Harte Fakten gute Gedanken]]
- Wer ist der Mensch?
- Gott ist gut, warum gibt es das Böse?
- Der Sinn des Lebens?
- ...


****** Kompetenzbeschreibungen
:PROPERTIES:
:ID:       9a88f216-edc2-4d93-83b8-ade69ab32f9b
:END:
****** Anwendungsbereiche
:PROPERTIES:
:ID:       1212b27e-4e79-4aae-ae4a-dec9dc19cff5
:END:
****** Unterrichtshinweise
:PROPERTIES:
:ID:       4df40b65-bb7c-4edc-8765-e9f2ca13f0ec
:END:

**** B Gelehrte und gelebte Bezugsreligion
:PROPERTIES:
:CUSTOM_ID: A1_AB1
:ID:       d3e26f28-04ab-4caf-929b-30f8104a6f94
:END:
***** B3 Grundlagen und Leitmotive des christlichen Glaubens kennen und für das eigene Leben deuten können
:PROPERTIES:
:CUSTOM_ID: B3
:ID:       5a06e31e-7c5f-40e6-8f40-1c52abe8ac85
:END:
****** Kompetenzbeschreibungen
:PROPERTIES:
:CUSTOM_ID: B3_KB1
:ID:       ab8712e8-e47c-4041-b35f-f2bfce72d9c5
:END:
Die Schülerinnen und Schüler verfügen über erweiterte Grundkenntnisse zur Bibel und können sie als inspiriertes Zeugnis des Dialogs Gottes mit den Menschen deuten. 

****** Anwendungsbereiche
:PROPERTIES:
:CUSTOM_ID: B3_AB1
:ID:       83b05343-cbd8-424a-b9ce-a9bd614834b5
:END:
Biblisch-hermeneutische Kompetenz: die biblischen Schriften und ihre Entstehung, Zeugnisse der Lebensrelevanz der Bibel [[#Bibel_NT]]

****** Unterrichtshinweise
:PROPERTIES:
:CUSTOM_ID: B3_UH1
:ID:       efc71c11-8d7b-409e-826f-3b3fa266987e
:END:
 - Altes Testament
 - Neues Testament, [[#Bibelarbeit]] [[#Jesus Mensch und Gott]]
 - historisch-geografisches Umfeld;
 - biblische Motive im Alltag: eigene Erfahrungen und Populärkultur [[#David Jonathan]]


****** Kompetenzbeschreibungen
:PROPERTIES:
:CUSTOM_ID: B3_KB2
:ID:       95fc3b05-097d-4eab-835b-58f0f33a744b
:END:
Die Schülerinnen und Schüler können Leben und Handeln Jesu in Grundlinien beschreiben und als Basis christlichen Glaubens kommunizieren.

****** Anwendungsbereiche
:PROPERTIES:
:CUSTOM_ID: B3_AB2
:ID:       9d409c4f-9998-447a-84f7-2200b98cfeab
:END:
Historischer Jesus – Christus des Glaubens 

****** Unterrichtshinweise
:PROPERTIES:
:CUSTOM_ID: B3_UH2
:ID:       3f1238e5-4484-4cfd-a3f9-6f92fe3feebf
:END:
Lukasevangelium in Auswahl 

***** B4 Kirchliche Grundvollzüge kennen und religiös-spirituelle Ausdrucksformen gestalten können
:PROPERTIES:
:CUSTOM_ID: B4
:ID:       c95753a7-df03-42fa-bad6-379d4fa492b3
:END:
****** Kompetenzbeschreibungen
:PROPERTIES:
:CUSTOM_ID: B4_KB1
:ID:       43fa526e-1311-4f84-82e2-8e060b51cfec
:END:
Die Schülerinnen und Schüler kennen Reichtum und Vielfalt spiritueller und liturgischer Ausdrucksformen und können sie in ihrer Bedeutung nachvollziehen und gestalten. 

****** Anwendungsbereiche
:PROPERTIES:
:CUSTOM_ID: B4_AB1
:ID:       2584b2ea-3528-4b91-9ee2-17fb3522ad6b
:END:

****** Unterrichtshinweise
:PROPERTIES:
:CUSTOM_ID: B4_UH1
:ID:       889a212d-c6d9-49a6-9676-fab4daf9bcd8
:END:
 - Kurzformeln des Glaubens [[#Kirche_Gebet]]
 - Grundgebete: [[#Ave Maria]] [[#Vaterunser]]
 - Stille, Meditation, [[#Vielfalt Gebet]]
 - Psalmen, Lieder,
 - körperliche Ausdrucksformen des Gebets [[#Menschen beten]] [[#Dankbarkeit]]
 - Arten / Formen des Gebets:[[#Menschen beten]] [[#Gebetsformen]]

   
****** Kompetenzbeschreibungen
:PROPERTIES:
:CUSTOM_ID: B4_KB2
:ID:       e5bae3b3-693a-4ff9-a5bb-f67b93286435
:END:
Die Schülerinnen und Schüler können Taufe und Eucharistie als Ausdruck der Zugehörigkeit zur kirchlichen Gemeinschaft verstehen. 

****** Anwendungsbereiche
:PROPERTIES:
:CUSTOM_ID: B4_AB2
:ID:       bdd62bea-22b6-4a9f-a6a5-ab46e9102a9a
:END:
Das Glaubensbekenntnis [[#Credo]]

****** Unterrichtshinweise
:PROPERTIES:
:CUSTOM_ID: B4_UH2
:ID:       b533284a-4f28-4966-94e8-2029045b2495
:END:
 - Zeichen und Formen von Zugehörigkeit, [[#Gemeinsam Kirche]]
 - Jesu Mahlgemeinschaften und die Feier der Eucharistie [[#Eucharistie]]


**** C Religiöse und weltanschauliche Vielfalt in Gesellschaft und Kultur 
:PROPERTIES:
:CUSTOM_ID: C
:ID:       3a74a64c-c5f4-422b-a41c-21d29c51a389
:END:
***** C5 Medien, Kunst und Kultur im Kontext religiöser Weltwahrnehmung interpretieren, beurteilen und gestalten können
:PROPERTIES:
:CUSTOM_ID: C5
:ID:       ef1da82c-65f3-41bf-b3da-0a42b8bca3dd
:END:
****** Kompetenzbeschreibungen
:PROPERTIES:
:CUSTOM_ID: C5_KB1
:ID:       77e07b32-82b3-4c7a-bdf4-87b0b3477d60
:END:
Die Schülerinnen und Schüler können das Kirchenjahr mit seinen Festen als Rhythmus des Lebens verstehen und mitgestalten.  

****** Anwendungsbereiche
:PROPERTIES:
:CUSTOM_ID: C5_AB1
:ID:       4413ef13-dd55-4af2-bbf9-526c226e63e5
:END:

****** Unterrichtshinweise
:PROPERTIES:
:CUSTOM_ID: C5_UH1
:ID:       19dcea2d-e073-47d7-8b94-a93354aa3010
:END:
 - Fest- und Feierkultur in Familie, Gemeinschaft und Gesellschaft [[#Feierkultur]]
 - Strukturierung und Prägung der Zeit durch säkulare und religiöse Feste (Kalender), [[#Kirchenjahr]] [[#Feste Kirchenjahr]]
 - Marienfeste, [[#Advent_Maria]]
 - vielfältige Zugänge zum Feiern von Weihnachten [[#Advent]] [[#Weihnachten]] [[#Sterndeuter]]
 - Ostern [[#Ostern]]


****** Kompetenzbeschreibungen
:PROPERTIES:
:CUSTOM_ID: C5_KB2
:ID:       34334035-529e-4423-a3c3-195fe66ffdb0
:END:

****** Anwendungsbereiche
:PROPERTIES:
:CUSTOM_ID: C5_AB2
:ID:       84fe8b02-8d36-471f-ac39-718fec481ce8
:END:

****** Unterrichtshinweise
:PROPERTIES:
:CUSTOM_ID: C5_UH2
:ID:       0d64d603-6d96-4f40-8a05-efc9dd82d71f
:END:


***** C6 Unterschiedlichen Lebensweisen und Glaubensformen reflexiv begegnen können
:PROPERTIES:
:CUSTOM_ID: C6
:ID:       a208bd4f-fc32-44e4-83cf-f0b0576b30d0
:END:
****** Kompetenzbeschreibungen
:PROPERTIES:
:CUSTOM_ID: C6_KB1
:ID:       1576269f-8eec-4642-a767-2f60b7379865
:END:
Die Schülerinnen und Schüler können Gemeinsames und Unterscheidendes, Verbindendes und Trennendes von Konfessionen und Religionen benennen und sich damit respektvoll auseinandersetzen. 

****** Anwendungsbereiche
:PROPERTIES:
:CUSTOM_ID: C6_AB1
:ID:       9e459664-5a74-48f2-8b9b-7dd1918fad0b
:END:


****** Unterrichtshinweise
:PROPERTIES:
:CUSTOM_ID: C6_UH1
:ID:       9b1194dc-9111-44d2-ac51-9f320bf6c7d1
:END:
 - Einheit in Vielfalt, [[#Einigkeit Vielfalt]] [[#Vielfalt]]
 - Respekt, Toleranz, [[#Vielfalt Religionen]]
 - Umgang mit Intoleranz und Vorurteilen [[#Übungsteil Vielfalt]]
 - Religionen stellen sich vor [[#Judentum Isalm Christentum]]

****** Kompetenzbeschreibungen
:PROPERTIES:
:CUSTOM_ID: C6_KB2
:ID:       7a4ab7f6-5d04-4a52-89d6-a3766987a5e8
:END:

****** Anwendungsbereiche
:PROPERTIES:
:CUSTOM_ID: C6_AB2
:ID:       3c261ba5-3587-4c8a-8354-29cd34360224
:END:

****** Unterrichtshinweise
:PROPERTIES:
:CUSTOM_ID: C6_UH2
:ID:       c8d1a73d-cbd9-4705-b75f-5e9b12da732b
:END:



**** Kompetenzdimensionen 
beschreiben die Handlungsmodi der Aneignung der Kompetenzen und finden sich in den Kompetenzbeschreibungen wieder:
 - Wahrnehmen und beschreiben religiös bedeutsamer Phänomene (Perzeption)
 - Verstehen und deuten religiös bedeutsamer Sprache und Glaubenszeugnisse (Kognition)
 - Gestalten und handeln in religiösen und ethischen Fragen (Performanz)
 - Kommunizieren und (be)urteilen von Überzeugungen mit religiösen Argumenten und im Dialog (Interaktion)
 - Teilhaben und entscheiden – begründete (Nicht-)Teilhabe an religiöser und gesellschaftlicher Praxis (Partizipation)

*** Zentrale fachliche Konzepte
Folgende Leitideen, strukturiert in Begriffspaaren, kennzeichnen die zentralen fachlichen Konzepte des katholischen Religionsunterrichts. 

**** Lebensrealitäten und Transzendenz
Christlicher Glaube versteht den Menschen in seiner Bio-grafie  und  in  seinen  Lebensbezügen  als  transzendentes  Wesen und erschließt Wege der Sinnfindung durch Trans-zendenzbezug.

**** Gottesliebe und Menschenliebe
Das  jüdisch-christliche  Gottes- und Menschenbild steht für eine lebensbejahende Grundhaltung zu sich selbst, den Mitmenschen und der Welt. Das  Beziehungsgeschehen zwischen Gott und Mensch und der Menschen untereinander ist getragen von der bedingungslosen Liebe Gottes. Unabhängig von Fähigkeiten und erbrachten Leistungen ist der Mensch in seiner Würde unantastbar.

**** Jesus der Christus
Das  Christentum orientiert sich am Reden und Handeln Jesu, das die vergebende und heilende Zuwendung Gottes zu den Menschen zeigt. In seiner den Tod überwindenden Auferstehung kann in der Brüchigkeit des Lebens Versöhnung und Erlösung erfahrbar werden. 

**** Freiheit und Offenbarung
Quellen der Offenbarung sind die Bibel und die kirchliche Tradition in ihrer Vielfalt. Auf der darin grundgelegten Freiheit des Menschen basiert die Achtung der Religionsfreiheit jeder Schülerin und jedes Schülers.

**** Zusage und Verantwortung
Ausgehend vom Verdankt-Sein allen Lebens wissen sich Christinnen und Christen beauftragt und befähigt Verantwortung in der Welt zu übernehmen. Dabei leiten sie Hoffnungsperspektiven, die auf biblischen Zusagen aufbauen.

*** Didaktische Grundsätze
In der Mitte des Religionsunterrichts stehen die Schülerin-nen und Schüler, ihr Leben, ihr Glaube.

Für den katholischen Religionsunterricht sind das Prinzip der Korrelation, das die wechselseitige Erschließung von Glauben und Leben meint, und das Prinzip des „Ganzen im Fragment“, das sich der Elementarisierung und dem exemplarischen Lernen verpflichtet weiß, zentral. 

Die didaktisch reflektierte Setzung von Schwerpunkten ist besonders bei einstündig geführten Klassen und im schul-stufenübergreifenden Unterricht notwendig.

Bezugnehmend auf das Kompetenzmodell sind folgende religionsdidaktische Grundsätze hervorzuheben:

*Fokus: Religiöse Sprache und Symbole*
Die Alphabetisierung in religiöser Sprache umfasst das Erkennen und Verstehen religiöser Sprachformen und das Erschließen vielfältiger Symbole in ihrer Mehrdimensionalität. Eine individuelle und kreative Ausdrucksfähigkeit wird gefördert.

*Fokus: Philosophieren und Theologisieren*
Der Religionsunterricht fördert die Fragekompetenz, initiiert Suchbewegungen im religiös-existenziellen Kontext und schult die Argumentationsfähigkeit. Er verpflichtet nicht auf einen Glauben, vielmehr fördert er die Entscheidungsfähigkeit der Schülerinnen und Schüler in religiösen und ethischen Belangen.

*Fokus: Actio und Contemplatio*
Performatives Lernen zielt ab auf das reflektierende Erleben religiöser Vollzüge und ethischen Handelns. Die Erfahrungsbezogenheit des Religionsunterrichts wird in Gebet, Stille und Meditation sowie in gemeinsamen Feiern, Aktionen und Projekten erlebbar.

*Fokus: Beziehung und Resonanz*
Im Beziehungsgeschehen zwischen Gott, Mensch und Welt angelegt, umfasst schulische religiöse Bildung eine biografische und narrative Komponente und vollzieht sich besonders im Lernen voneinander, miteinander und über-einander. 

*** Hinweise zum Lehrplan
Der Lehrplan für katholische Religion umfasst drei Kompetenzbereiche (A, B und C). Jeder dieser Bereiche wird jahrgangsübergreifend durch je zwei Leitkompetenzen (1-6) konkretisiert. 

**** KB – Kompetenzbeschreibungen
Den Leitkompetenzen sind schulstufenspezifische Kompetenzbeschreibungen (KB) zugeordnet, die angeben, welche Kompetenzen von allen Schülerinnen und Schülern erworben werden sollen. In jedem Schuljahr sind alle im Kompetenzmodell genannten Kompetenzdimensionen (Perzeption, Kognition, Performanz, Interaktion, Partizipation) zu berücksichtigen.Der Lehrplan für katholische Religion umfasst drei Kompetenzbereiche (A, B und C).Jeder dieser Bereiche wird jahrgangsübergreifend durch je zwei Leitkompetenzen (1-6) konkretisiert. 

**** AB – Anwendungsbereiche
Inhaltlich konkretisiert werden die Kompetenzbeschreibungen durch Anwendungsbereiche (AB). Diese benennen repräsentative Beispiele für Themenfelder, anhand derer Kompetenzen erworben werden. Wo solche benannt sind, sind sie verbindlich zu behandeln. Weitere Anwendungsbereiche können frei gewählt werden.Wo keine Anwendungsbereiche benannt sind, ist es Aufgabe der Lehrerinnen und Lehrer Anwendungsbereiche zu definieren.

**** UH – Unterrichtshinweise
Unterrichtshinweise (UH) sind als Ergänzungen zu den Fachlehrplänen gedacht. Sie geben Empfehlungen für die Umsetzung des kompetenzorientierten Lehrplans und unterstützen bei der Unterrichtsplanung.

** Themengebiete (Kirchenjahr, Heilige Schrift, ...)


** Ziele formulieren


** Methoden entwickeln
Beispiel 4a: Ich hatte eine gute Diskussion mit den Schülern; sie wünschen sich eine andere Art von Unterricht. Sie wollen ein Thema selbständig erarbeiten. Das klappt vielleicht nicht in jeder Klasse. Bei den vierten Klassen liegt dies sicher mehr auf der Hand.


* Ablauf einer Stunde

 1. Andocken an letzte Stunde / Whg / Aufzeichnungen
 2. Hinführung zu neuem Thema
 3. Erarbeitung durch Schüler
 4. Verinnerlichung / Heftarbeit
 5. Was habt ihr gelernt? - offene Fragen.



* Checkbox [0/8]

  - [ ] Klasse?
  - [ ] Ideen
  - [ ] Themen
  - [ ] Ziele
  - [ ] Methoden
  - [ ] Materialen
  - [ ] Gitarre
  - [ ] Ablauf der Stunde


* Aufzeichnungen / Mitarbeit
In diesem org.-file zeichne ich die Mitarbeit der einzelnen Schüler auf.

Pro Schüler:
 - Datum
 - schriftliche Aufzeichnungen MIT tags :Mitarbeit: :Heft: :Verhalten:


* Footnotes

[fn:2] https://www.youcat.org/de/gebet/

[fn:1] [[https://www.erzabtei-beuron.de/schott/schott_anz/index.html][Lesungen des zweiten Adventsonntags Lesejahr A]]

bibliography:/home/matthias/RoamNotes/references/Literatur.bib
