#+title:      Eröffnungskonferenz
#+date:       [2023-09-11 Mo 10:05]
#+filetags:   :konferenz:
#+identifier: 20230911T100542
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+TODO: TODO(t) STARTED(s!) WAITING(w@/!) APPT(a) PROJ(p) NOTIZ(n) NEXT(x) BESPROCHEN(b) DELEGATED(g@/!) | DONE(d!) CANCELED(c@)
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width \linewidth
#+OPTIONS: toc:nil
#+export_file_name: ~/RoamNotes/exports/Protokoll Eröffnungskonferenz.html

test
* Begrüßung
Besonders Sylvia (Verwaltungsassistent)
2 Tage in der Woche

** Neue Lehrer:
Markus Grill
Stefanie Baumgartner
Daniel Graf
Anton Erlbacher
Bernadette Lienbacher

** Geburtstagskinder
Mgadalena, Manuela Gruber, Lena, ...

** Danke
Erstellung Stundenplan: Bernhard, Christoph, Herbert.

Wegen einem Schüler, statt 3x 1. Klasse jetzt 2x 1. Klassen.

Wunsch nach harmonischem Miteinander

** Änderungen der persönlichen Daten bekanntgeben

** Sokrates
Stundenplan könnte sich ändern ... sollte es ein Erstklassler sein; Problem, weil 2 Lehrer fehlen.

Mailadresse der Eltern eingeben

** Laptops werden ausgeteilt

** Trotz einer Klasse weniger
Kaum Stunden verloren.

Alle Stunden doppelt, sinnvoll besetzt.

** Unverbindliche Übungen
Wann findet Übung statt.
Erste Hilfe - im Winter, damit es im Frühjahr nicht zu viel wird.

Was ist für welche Klasse interessant?

*** Geräteturnen
Eva

*** Erste Hilfe (4. Klassen)
Bernadette Lienbacher

*** Forschen
Mirjam

*** GZ (3.+ 4.)
Ulli Gruber
1 Stunde und 1 Stunde

wird für weiterführende Schulen / Lehre benötigt.

Zuerst die 4., dann ev. auch 3. Klassen.

*** Darstellendes Spiel
Juni 2024, großes Theater
Getraud E.

*** Schülerliga
Daniel

*** Chor
Nina

** Fortbildungen
anmelden! 22.9.2023 

** Pädag. Hochschule
Neuzugänge: SozVers benötigt

Bei Rückmeldug auch sagen, wenn es nicht so toll war.

** Schülerzahlen
219 insgesamt

Zwei erste Klassen mit jeweils 25

** Administratives
- bitte Aufsicht einhalten
- mit Läuten beginnen und enden
- Kaputtes zahlt die Klassenkassa
- Tafel löschen / aufräumen / Sessel hinaufstellen
- Mit Kindern in die Gaderobe gehen
- Jause kaufen, Zweierreihe anstellen
- Heizung ist nicht anzufassen
- Pause: Fenster nur gekippt
- Standard-Gruppe: Klasse muss Raum verlassen und in ihren Klassenraum zurück.
- Nicht auf den Fensterbänken sitzen!
- kein Handy (off im Spint)
- Schulordnung / Schulpflicht
- Brandschutz: Martin
- Rauchverbot
- Frühwarnsystem
  - Verhalten
  - Pflichtverletzung in schwerwiegender Weise
  - Nicht Genügend
  - es muss vorher gefördert werden, vor Umstufung



** Schulfreie schulautonome Tage
3.11.2023, 10.5.2024, 31.5.2024

** Protokolle aller Konferenzen
auch online über Teams zur Verfügung stellen

** Kustos
BSP: Julia
Smartboard: Julia
Kopierer: Matthias (Julia, Birgit fragen)
Stundenplan: Christoph, Bernhard, Herbert
Homepage: GV, MSi, MS (gemeinsam mit VS)
Erste Hilfe: Christian, Bernadette

** Klassenforen:

*** 1. Klassen: 21.9., 19h00

*** 2. Klassen: 2.10., 18h00

*** 3. Klassen: 26.9. 19H00

*** 4. Klassen: 19.9. 19h00

** Schulforum
4.10., 19h00

** Elternsprechtag
noch nicht fixiert.

** päd konferenzen
9.10. 14.11. 12.12. 18.01
jeweils 16h00

** Tag der offenen Tür:
vor Weihnachten

7.12.2023

** Semesterkonferenz
5.2.2024 15h00

** Schitag
13.12.?



* Mehr Schulbücher

** 3a ein Schüler mehr

** 2b einer mehr 




* Wandertag
auf Freitag verschoben
Matthias Fuchs: bei 2a mit Manuela Si, ....

* Ab Mittwoch:
Unterricht nach Stundenplan (kein NM)

* WH Prüfung
Hannah Pickrahn 2b kam ohne Schreibmaterial, hat nicht bestanden
bekam aber Klausel
SPF greift nicht mehr, wegen Alter

Nach diesem Schuljahr in das Poly.
Schulpsychologentermin: hat SPF Erfolg?

* Spint Nr 3
Schloss ohne Schlüssel - auf schneiden

Martin: Hannah Nr 80?

* Schulgottesdienst
Di, 12.9., 8:00

* Eventplanungsteam:
Lehrerausflug, Skitag, Fasching:
Sarah, Stefanie, Sandra, Matthias

* Lehrerausflug:
Sonderausstellung Leogang "Perlen der Gotik" + Essen.
3 Termine: 22./29.9 oder 13.10. ab der 4. Stunde (ein Nachmittag); Bus.

* Gesundheitskabarett
Ingo Vogl, 8. Schulstufe (nur super, wenn es Ingo macht; sonst nicht)

* Allfälliges

** Angela L.
8 Schulen, ...
Arbeit mit verhaltensschwache / auffällige Schüler
einzeln oder Kleingruppen
soziales Lernen
Mobbing
Lernprobleme
-verweigerung
Chaos in Taschen und Heften
auffällig unauffällige Schüler
Eltern
für Lehrer

Anwesenheit: Mi, Do, Fr

** Barbara E.:
alle alles ausräumen

BE: Material bestellen - sagen
Textil: ebenfalls

** Kassen
Kaffee: Nina 20 nach Bedarf
Konferenz: 50 Euro 1x jährlich (gertraud)
Gemeinschaft: Magdalena 1x 50 Euro

** Instagram:
andere Schulen habens

wäre cool: News mit Fotos + Sätze

erkundigt: regelmäßig Einträge hochladen

verschiedene Bereiche

Bilder: Einverständniserklärung (HP, Instagram) einholen.

** 3. Klassen:
HipHop Veranstaltung Szene Salzburg; 15 / 20 Euro?
29.9, 11h00.

** Pausenaufsicht:
erster und zweiter Stock zu zweit.

** SchoolFox?

** gmail-Adresse von golling
bitte ersetzen auf aps / oder golling.schule

** Besprechungsraum / Ersatz?
Sprechstunde pro Lehrer anbieten, mit Voranmeldung (1 Woche vorher); Elternsprechtag weniger belastet.

** Turnsaalklasse
für VS?

** Jugendcoaching

** 4a Ebu
hätte Lehrstelle bekommen
geht jetzt in die HAK Hallein;
Mega Nachprüfungen
