#+title:      [SW03] Sinn der Arbeit
#+date:       [2023-07-11 Di 00:32]
#+filetags:   :04:sw03:
#+identifier: 20230711T003213
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+TODO: TODO(t) STARTED(s!) WAITING(w@/!) APPT(a) PROJ(p) NOTIZ(n) NEXT(x) BESPROCHEN(b) DELEGATED(g@/!) | DONE(d!) CANCELED(c@)
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width \linewidth
#+OPTIONS: toc:nil
#+export_file_name: ~/RoamNotes/exports/Sinn_der_Arbeit.html


* Komepetenzbeschreibung
Menschen und ihre Lebensorientierungen - Sich mit den großen Fragen der Menschen auseinandersetzen können
Die Schüler können Perspektiven für ihr Leben entwickeln und  Zukunftspläne entwerfen. 

* AB / UH
persönliche und berufliche Ziele

* Wiederholung


* Erarbeitung
Warum arbeitet der Mensch? Nur wg des Geldes; oder weil es zur Natur (?) des Menschen gehört? Cf Relibuch "Komm mit", ab S. 72 (kopieren).

Gen 3 sagt uns, dass ab dem Sündenfall die Arbeit mühsam ist - und vorher? Vielleicht soll ich es anders verstehen: ausgehend von der Erfahrung einer mühsamen Arbeit stellt sich der Mensch die Frage, warum das so ist. Hm, das scheint mir zu leicht und nicht gerade ein tiefsinniger Ansatz.

Die Arbeit ist eine Pflicht des Menschen: Auftrag des Schöpfers, Erhalt der Familie, Entfaltung der eigenen Menschlichkeit. Wir sind Erben der Arbeit von Generationen und zugleich Gestalter der Zukunft für all die Menschen, die nach uns leben werden.

Die Arbeit bestärkt den Menschen - nach dem Bild Gottes erschaffen - in der Tiefe seiner Identität. Der Mensch ist der Treuhänder des Universums. In seinem eigenen Wirken ist der Mensch dazu berufen, das Antlitz Gottes widerzuspiegeln.

DoCat:
[[file:~/Dokumente/DC_Studyguide_Deu_7.pdf][Eine Wirtschaft, die den Menschen dient]]

[[file:~/Dokumente/DC_Studyguide_Deu_6.pdf]]

Geht uns die Arbeit aus?

[[https://jugend-und-bildung.de/fileadmin/user_upload_sozialpolitik/PDFs/schaubild-geht-uns-die-arbeit-aus.pdf]]

[[https://www.brot-fuer-die-welt.de/fileadmin/mediapool/downloads/Bildungsmaterial/global-lernen/BfdW_GlobalLernen_Arbeit.pdf]]

[[file:~/NMS_Golling/GlobalLernen_MenschenwuerdigeArbeit-Print.indd - BfdW_GlobalLernen_Arbeit.pdf]]

Arten der Arbeit

Supplierstunde:
[[file:~/NMS_Golling/Die_schnelle_Stunde/Arbeitsunterlagen_Die schnelle Stunde Religion für die HS.pdf]]
 - Zukunft auf heute
 - 10 Wörter meines Lebens
 - Die Welt verändern


 
** Recht auf Arbeit
"Der naturgegebenen persönlichen Arbeitspflicht entspricht folgerichtig das naturgegebene persönliche Recht, durch Arbeit für das eigene Leben und das Leben der Seinen Vorsorge zu treffen" (Pius XII., Pfingstansprache 1941; Texte zur katholischen Soziallehre 160 f.).


** Katholische Soziallehre
Sechs Prinzipien:
- Personalität,
- Gemeinwohl,
- Solidarität,
- Subsidiarität,
- Nachhaltigkeit
- und die Option für die Armen

Pius (?) Enzyklika; Enzykliken von JP2 zu den Jahrestagen der ersten Enzyklika.

Kompendium der Soziallehre; DoCat


** Privateigentum
Von Natur aus kommt allen Menschen die gleiche Würde zu sowie bestimmte gottgegebene Rechte und Pflichten, die so fundamental sind, dass sie prinzipiell für alle gelten. Die Reichtümer der Erde sollen allen insgesamt und zugleich jedem einzelnen in der für ihn zuträglichen Weise zugute kommen. Niemand sollte so im Überfluss leben, dass er nicht mehr weiß, was er mit seinen Gütern anfangen kann; es sollte aber auch keinen Hunger und keine Armut geben, wo der Mensch das Nötigste für sein Leben entbehren muss. Beides widerspricht der ursprünglichen Absicht des Schöpfers. Im selben Artikel führt uns der Katechismus jedoch weiter und kommt zu einer Anerkennung des privaten Eigentums, sofern es diesem ursprünglichen Schöpfungszweck nicht widerspricht, sondern dessen Verwirklichung fördert und ihm dienlich ist. Es heißt wörtlich über die faktische bestehende Aufteilung der irdischen Güter:

"Die Erde ist jedoch unter die Menschen aufgeteilt, um die Sicherheit ihres Lebens zu gewährleisten, das in Gefahr schwebt, Mangel zu leiden und der Gewalttätigkeit zum Opfer zu fallen. Die Aneignung von Gütern ist berechtigt, um die Freiheit und Würde der Menschen zu sichern und jedem die Möglichkeit zu verschaffen, für seine Grundbedürfnisse und die Bedürfnisse der ihm Anvertrauten aufzukommen. Sie soll ermöglichen, dass unter den Menschen eine natürliche Solidarität besteht." (KKK 2402)

Die Kirche achtet daher das Recht auf Privateigentum, aber immer in Hinblick auf die Sozialpflichtigkeit des Eigentums:

2403 Das Recht auf das Privateigentum, das man auf gerechte Weise erworben oder bekommen hat, hebt die Tatsache nicht auf, dass die Erde ursprünglich der ganzen Menschheit übergeben worden ist. Dass die Güter für alle bestimmt sind, bleibt vorrangig, selbst wenn das Gemeinwohl erfordert, das Recht auf [Privateigentum] und den Gebrauch von Privateigentum zu achten.

Aus dieser Feststellung zieht der Katechismus eine wichtige Folgerung:

2404 "Darum soll der Mensch, der sich dieser Güter bedient, die äußeren Dinge, die er rechtmäßig besitzt, nicht nur als ihm persönlich zu eigen, sondern er muss sie zugleich auch als Gemeingut ansehen in dem Sinn, dass sie nicht ihm allein, sondern auch anderen von Nutzen sein können" (GS 69,1). Der Besitz eines Gutes macht dessen Eigentümer zu einem Verwalter im Dienst der Vorsehung; er soll es nutzen und den daraus erwachsenden Ertrag mit anderen, in erster Linie mit seinen Angehörigen, teilen.

* Hefteintrag
