#+title:      Mit jedem redest du anders
#+date:       [2023-01-03 Di 20:54]
#+filetags:   :kommunikation:zusammenleben:
#+identifier: 20230103T205451

* Kompetenzbeschreibung
[[#A1]] Menschen und ihre Lebensorientierungen - Beziehung verantwortungsvoll gestalten können – zu sich selbst, zu anderen, zur Schöpfung
[[#A1_KB1]] Die Schüler können sich in ihrer Interaktion mit der Mitwelt differenziert wahrnehmen und zu einem wertschätzenden Kommunizieren beitragen.

* AB / UH
[[#A1_AB1]] Kommunikationsformen
- Emotionale Ausdrucksfähigkeit,
- Rollen innerhalb einer Gemeinschaft,

* Wiederholung


* Erarbeitung
** Comic (S. 10)
1 Bei diesem Arbeitsauftrag geht es um das Einfühlungsvermögen in die andere Person. Theo und Elena kommunizieren auf unterschiedliche Art und Weise. Für Elena reicht das "Daumenhoch" als Bestätigung und Zustimmung Eis essen zu gehen. Theo aber würde dies gerne durch ausgesprochene Worte hören. Die Schüler*innen sollen erfahren, dass Kommunikation mehr als nur ausgesprochene Worte ist. Sie sollen achtsamer werden und auch nonverbale Kommunikation anhand von Gesten oder Mimik deuten lernen.
Einen Mehrwert würde es zusätzlich geben, wenn man hier auch Schüler mit Beeinträchtigungen mitdenken würde. Bei manchen würde dann die eine oder andere Art der Kommunikation wegfallen (nicht sprechen können, Muskeln nicht bewegen können, ...). Die Lehrkraft könnte auch die Diskussion in diese Richtung lenken, um möglichst vielschichtig in dieses Thema einsteigen zu können.

2 Dieser Arbeitsauftrag ist persönlich und individuell. Jeder Schüler versteht etwas   anderes unter Kommunikation. Introvertierte werden eventuell nur wenig von sich preisgeben, während extrovertierte mehr von und über sich erzählen werden.

3 Auch dieser Arbeitsauftrag ist individuell und persönlich. Jeder Schüler sollte sich mit der eigenen Kommunikation auseinandersetzen und sich bewusst machen, auf welche Art und Weise er*sie mit den Mitschülern*innen kommuniziert. In einem weiteren Schritt könnte man auch gemeinsam vergleichen und eventuelle Unterschiede und/oder Gemeinsamkeiten feststellen.

[[https://youtu.be/OfKJI6m0Kto][Checker Tobi - Kommunikation]]

** Mit jedem redest du anders (S. 11)
1 Die Schüler*innen sollen erkennen, dass jeder von uns in unterschiedlichsten Lebenssituationen unterschiedliche Sprache (Wortwahl, Ton, Dialekt – Schriftsprache, ...) verwendet.

Das Gespräch kann auch dahin gehend gelenkt werden, dass es durchaus auch dringend und wichtig ist, in den verschiedenen Situationen unterschiedlich zu reagieren.

2 Dieser Arbeitsauftrag zeigt Pauls Mutter in verschiedenen Situationen ihres Lebens:

  - Pauls Mutter als Verkäuferin: Sie bedient ihre Kundschaft nahezu "überfreundlich". Immerhin möchte sie den Rock auch verkaufen.
    
  - Pauls Mutter als Autofahrerin (in Eile): Wie viele Autofahrer*innen, die am Heimweg sind, ist Pauls Mutter nicht gerade freundlich. Im Schutz des eigenen Autos ist es auch leichter mit den anderen zu schimpfen – wenn diese es nicht hören. In den meisten Fällen ist bei einer Verkehrsüberlastung nicht ein einzelner Schuld daran. Sie möchte gerne, dass sie pünktlich nach Hause kommen.

  - Pauls Mutter als Mutter eines Kindergartenkindes: Fürsorglich und liebend – wie Mütter dem Klischee entsprechend sein sollten, wenn sie ihrem Kind nach einem langen Arbeitstag begegnen. Ein wenig über die Sorgen des Kindes geplaudert und schon ist alles wieder ein klein wenig leichter.

  - Pauls Mutter als Mutter eines 12jährigen: Sie bringt ihre Kritik direkt auf den Punkt, ohne Umschreibungen und ohne mit der Wimper zu zögern. Sie möchte Paul darauf hinweisen, dass die Unordnung in seinem Zimmer über ihre Toleranzgrenze hinausgeht und setzt klare Grenzen, was die Spielzeit am PC betrifft. Außerdem knüpft sie auch noch die Bedingung des Lernens daran.
    
3 Dieser Auftrag ist individuell zu beantworten. Den Schülern soll aber auch bewusstwerden, dass auch sie in verschiedene Rollen schlüpfen und sich dementsprechend verhalten und kommunizieren (mit der Familie, mit Lehrern*innen, mit Freunden*innen, ...) Auf die Frage warum es wichtig ist in unterschiedlichen Situationen unterschiedlich zu kommunizieren, sollen die Schüler selbst eine Antwort finden. Diese könnte man dann auch im Plenum diskutieren.


* Hefteintrag
[[https://youtu.be/8rnVRE0xRT8][Vier Ohren Modell einfach erklärt]]
