#+title:      [SW26] Bräuche und Traditionen
#+date:       [2023-03-04 Sa 11:33]
#+filetags:   :02:jahresplanung:
#+identifier: 20230304T113320

* Arbeitsauftrag 1
Die Schüler*innen erklären in eigenen Worten die Wichtigkeit der Bräuche und Traditionen. Damit sollen sie einen Bezug des Brauchtums mit ihrem eigenen Leben verknüpfen und so ihr Verständnis für verschiedene Traditionen erweitern.

* Arbeitsauftrag 2
2 Die Auseinandersetzung mit den Traditionen und Bräuchen aus dem ersten Arbeitsauftrag geht nun einen Schritt weiter. Das Textverständnis als auch die Deutung der einzelnen Bräuche sind gefordert und dadurch können unterschiedliche Antworten entstehen. Ein möglicher Lösungsvorschlag wäre: 

** Faschingsumzug in Tirol:
Der Faschingsumzug findet traditionellerweise am Faschingsdienstag statt, kann
aber auch am Faschingssonntag durchgeführt werden. Vor der Fastenzeit, die am
Aschermittwoch beginnt, soll noch einmal ausgelassen gefeiert werden.
Bei traditionellen Faschingsumzügen findet man, neben fantasievoll gestalteten
Faschingswagen, noch prachtvolle, handgeschnitzte Masken und aufwendige
Kleider. Die Figuren und Masken dieses bunten Brauchtums reichen mit ihren
Wurzeln in vergangene Zeiten zurück. Sie haben mit der Fruchtbarkeit des
Frühlings, dem Sonnenkult und dem Vertreiben von bösen Geistern, als auch der
Beschwörung der guten Lebensgeister zu tun.

** Maibaumaufstellen in Salzburg:
Der Brauch des heutigen Maibaumes hat seinen Ursprung in Bayern und ist mit der
Zeit auch nach Österreich gewandert. Der Maibaum ist ein Symbol für Stärke,
Fruchtbarkeit und Wachstum und wird traditionell am 1. Mai, begleitet durch ein
großes Fest, aufgestellt. Er soll die Region vor Unwetter, Unheil und Ungeziefer
schützen.

** Glöcklerlauf in Oberösterreich:
In der letzten Rauhnacht, am Vorabend des Dreikönigtages, laufen die
Glöckler*innen mit großen Glocken (z.B. Kuhglocken) und Lichterkappen auf dem
Kopf (die in Handarbeit von den Glöckner*innen hergestellt wurden) im
„Gänsemarsch“ durch die Ortschaften. Sinn des Glöcklerlaufes ist es, das Heil und
den Segen der guten Geister zu gewinnen und die bösen Geister zu vertreiben.

** Krampuslauf in der Steiermark:
Der Krampus ist eine Schreckgestalt, der den Heiligen Nikolaus im Advent
begleitet. Krampusläufe finden traditionell Anfang Dezember um den Krampustag
(5. Dezember) und dem Nikolaustag (6. Dezember) statt.
Oft wird ein Krampuslauf auch mit dem Perchtenlauf verwechselt. Perchten sind
aber keine Schreckgestalten, sondern sollen die bösen Geister des Winters
austreiben. Perchtenläufe finden zwischen Weihnachten und dem Dreikönigstag
statt.

* Arbeitsauftrag 3
Dieser Arbeitsauftrag ist persönlich, daher soll die Tabelle  individuell ausgefüllt werden. Die Begründung der Auswahl kann auch mündlich erfolgen. Für manche Schüler*innen ist es hilfreich, wenn vorher ausgiebig über Bräuche gesprochen wird, da ihnen dann verschiedene Beispiele in Erinnerung gerufen werden.

* Arbeitsauftrag 4
Dieser Arbeitsauftrag ist persönlich  und  individuell.  Es bietet sich allerdings eine Besprechung und/oder Diskussion der Hintergründe an ("Warum ist das bei dir so?"), wobei allerdings behutsam darauf geachtet werden sollte, dass manche Bräuche Ängste hervorrufen können.

* Arbeitsauftrag 5
Bräuche sind vermehrt in Übergangszeiten (Herbst/Frühling) als auch im Winter, der kalten Jahreszeit, verortet. Bräuche sind innerhalb einer Gemeinschaft entwickelte Gewohnheiten und Traditionen. Durch diese Traditionen gewannen die Menschen Sicherheit und ein besonderes Zusammengehörigkeitsgefühl. Bräuche bringen Ordnung in den Alltag, ermöglichen die Begegnung mit den Menschen und der Natur und helfen Krisen zu bewältigen. Immer wenn sich in der Natur viel verändert, greifen die Menschen auf vertraute, alte Gewohnheiten zurück.

