#+title:      [SW12] Beginn Advent - Singen von Adventliedern
#+date:       [2023-06-19 Mo 09:01]
#+filetags:   :01:sw12:
#+identifier: 20230619T090127


* Kompetenzbeschreibung
[[#C5]] Religiöse und weltanschauliche Vielfalt in Gesellschaft und Kultur: Medien, Kunst und Kultur im Kontext religiöser Weltwahrnehmung interpretieren, beurteilen und gestalten können
[[#C5_KB1]] Die Schülerinnen und Schüler können das Kirchenjahr mit seinen Festen als Rhythmus des Lebens verstehen und mitgestalten.

* AB / UH
[[#C5_UH1]] Vielfältige Zugänge zum Feiern von Weihnachten

* Wiederholung


* Erarbeitung
Wir sind im Buch so gut vorangekommen, dass wir jetzt ein aktuelles Thema einschieben können. Deshalb werden wir uns folgendem Thema zuwenden - Advent:

Bräuche Advent, Bibelstellen, Erwartung des Messias, Verheißungen im AT, ...

Im Heft eine Seite zu den Bräuchen des Advents gestalten.

Zeichnen und manche Bräuche erklären: woher kommt z.B. der Adventkranz?

Wie feiern Kinder in anderen Ländern Weihnachten? - Adventkalender vom letzten Jahr?

Oder: im Buch - "Ist da wer?"; die Frage nach Gott...

** Lösungsvorschläge S. 37
1 Je nach Auswahl einer Fragestellung ergeben sich hier unterschiedliche Schritte und Antwortmöglichkeiten. Anhand eines Beispiels soll der Ablauf verdeutlicht werden:

 - Beispielfrage: "Gibt es gute Gründe, an Gott zu glauben?"
 - Mögliche Fragen: "Welche Gründe gibt es?", "Welche Menschen können mir gute Gründe nennen?", "Was ist überhaupt ein guter Grund?" etc.
 - Die meisten Fragestellungen suchen nach guten Gedanken, wobei auch objektiv – im Sinne harter Fakten – festgestellt werden könnte, dass es viele Menschen gibt, die (für sich) gute Gründe nennen können.
 - Am überzeugendsten ist hier wohl die Methode des Gesprächs, der Diskussion und des gemeinsamen (Austauschs - ?). Wichtig ist vor allem, dass die Definition dessen, was ein guter Grund ist, den einzelnen Menschen überlassen bleibt – was für jemanden ein guter, überzeugender Grund ist, muss in der Freiheit des Einzelnen bleiben.

2 Dieser Arbeitsauftrag ist sehr persönlich und individuell. Hier ist besonders darauf zu achten, durch die Frage keinen Zwang auszulösen und auch ablehnende, negative Haltungen zur Frage nach Gott zuzulassen.

3 Auch dieser Arbeitsauftrag ist sehr persönlich und individuell. Anhand der gestalteten Gottesbilder lässt sich vielleicht ein erster Eindruck verschiedenster Vorstellungen gewinnen. Oft wandeln sich kindliche Gottesvorstellungen ab der Sekundarstufe I relativ rasch – der 2. Band von "Religion für uns" wird diese Vorstellungen in einem eigenen Kapitel aufgreifen.

* Hefteintrag


