#+title:      [SW25] Über mein Leben nachdenken / Impuls: Dankbar sein
#+date:       [2023-06-19 Mo 09:21]
#+filetags:   :01:sw:
#+identifier: 20230619T092126


* Kompetenzbeschreibung
[[#B4]] Gelehrte und gelebte Bezugsreligion: Kirchliche Grundvollzüge kennen und religiös-spirituelle Ausdrucksformen gestalten können
[[#B4_KB1]] Die Schülerinnen und Schüler kennen Reichtum und Vielfalt spiritueller und liturgischer Ausdrucksformen und können sie in ihrer Bedeutung nachvollziehen und gestalten.

* AB / UH 
[[#B4_UH1]] Arten / Formen des Gebets

* Wiederholung
4.2 Über mein Leben nachdenken

Die Reflexion über bewusstes und unbewusstes Handeln bzw. Wahrnehmung wird in diesem Unterkapitel geübt. Schülerinnen und Schüler erfahren hier, wie sie mit einfachen Fragen einen Tag im Leben reflektieren und so zum Nachdenken über das eigene Leben kommen können.

Den äußeren Einflüssen wird eine bewusste Beachtung geschenkt, jedoch wird die Aufmerksamkeit auf die „Innenwelt“, auf das Ich und seine Tätigkeit, gelenkt. Durch die Einteilung in bewusste und unbewusste Dinge baut sich eine Struktur, über einen Tag im eigenen Leben auf und macht ihn greifbar. Durch den Tagebucheintrag werden den einzelnen Gefühlen, Geschmäckern, Erfahrungen, und Gedanken eine Sprache gegeben.

- Luca
- Laurenz
- (Carolina)
- (Marko)
- (Matteo)
  

* Erarbeitung

** Über mein Leben nachdenken
1 Dieser Arbeitsauftrag ist sehr persönlich und individuell. Schülerinnen und Schüler können in Stichworten ihre Antworten ins Buch oder Heft schreiben.

2 Dieser Arbeitsauftrag soll die Schülerinnen und Schüler weiter anregen über ihr Leben nachzudenken. Wenn die Fragen der Klassen verglichen werden können weitere spannende Diskussionen entstehen.

3 Bei diesem Arbeitsauftrag ist es für ein späteres Reflektieren sinnvoll, wenn die Schülerinnen und Schüler in Stichworten alle Gerüche, Geschmäcker, Gefühle und Gedanken schriftlich festhalten. Da jeder etwas anderes empfindet ist dieser AA sehr persönlich und individuell.

4 Dieser Arbeitsauftrag regt die Schülerinnen und Schüler zur persönlichen Reflexion über ihr eigenes Leben an. Wenn die vorhergehenden Aufträge schriftlich bearbeitet wurden, kann dieser Arbeitsauftrag mit zwei Farben bearbeitet werden. Alle bewussten Dinge mit einer Farbe unterstreichen und für alle unbewusst gemachten Dinge eine weitere Farbe verwenden.

5 Der Tagebucheintrag soll den Schülerinnen und Schülern verdeutlichen wie das Nachdenken über einen Tag im Leben die Perspektive verändern kann. Den „kleinen Dingen“ mehr Achtsamkeit zu geben verändert das subjektive Empfinden der Erinnerungen. Für Lisa werden während des Schreibens viele Dinge klarer, der Geschmack des Mittagessens, die Geräusche im Park, etc. Auch welches Glück sie hat, überhaupt in den Reitstall zu dürfen und vieles mehr nimmt sie dankbar wahr.

6 Dieser Arbeitsauftrag dient dem Textverständnis und der Reproduktion der beschreiben Inhalte.
Am Beginn des Tagebucheintrages war für Lisa der Tag langweilig, am Ende war es ein ziemlich guter Tag. Lisa nimmt die Kleinigkeiten des Alltages wahr und bemerkt dabei auch Besonderheiten, wie z.B., dass ihre Mama den Kaiserschmarren extra für sich gemacht hat. Hinzu kommt, dass Lisa zum Schuss ihres Briefes auch ein Gefühl der Dankbarkeit empfindet.

7 Dieser Arbeitsauftrag ist sehr persönlich und individuell. Es ist sinnvoll für den Tagebucheintrag vorab die Arbeitsaufträge 1-3 von Seite 62 „Über mein Leben Nachdenken“ zu bearbeiten. Für Kinder, die sich mit ihrer Phantasie eher schwerer tun ist es sinnvoll den Tag, den sie beschreiben sollen, genau zu benennen. Paul und Elenas Fragen von Seite 6, eine Liste oder ein Brainstorming über den Tag kann für einen gelingenden Tagebucheintrag eine große Hilfe sein.

8 Mit diesem Arbeitsauftrag wird die Reflexion über das eigene Leben thematisiert und vertieft. Die Aufgabe stellt die Arbeitsaufträge 1-7 auf die Metaebene und regt die Schülerinnen und Schüler zur Diskussion über das Thema Nachdenken an und verknüpft es mit dem Wissen aus Kapitel 2 - Fragen, die uns bewegen.

** Impuls: Dankbar sein
Im Rahmen einer Impulsseite steht die kreative Auseinandersetzung im Vordergrund – in diesem Fall werden Schritte vorgestellt wie ein Dankgebet formuliert werden kann. Aber auch Bittgebete oder andere Gebete können nach diesem Schema verfasst werden.

Die Kurzgeschichte „Das Geheimnis der Dankbarkeit“ soll die Schüler*innen einladen über ihren Tag und das Gute was ihnen widerfährt nachzudenken.

Lösungsvorschläge wären für diesen Zugang destruktiv, da es hier kein „richtig“ und kein „falsch“ gibt. Wichtig ist, die Schüler*innen frei und kreativ Gebete formulieren zu lassen.

Die vier Schritte (Anrede – Dank aussprechen – Anrede – Amen) gibt den Schüler*innen eine Struktur vor, die aber so offen ist, dass diese die Kreativität sogar fördert.

Die vorgestellte Geschichte „Das Geheimnis der Dankbarkeit“ kann vertieft werden, indem den Kindern Bohnen ausgeteilt werden, die sie ermutigen sollen, doch auch einen Tag lang zu beobachten, wie viele Bohnen bei ihnen von einer Hosentasche in die andere wandern würde.

* Hefteintrag

