#+title:      [SW08] Fragen die uns bewegen (Kap. 2)
#+date:       [2023-06-19 Mo 08:51]
#+filetags:   :01:sw08:
#+identifier: 20230619T085157


* Kompetenzbeschreibung
[[#A2]] Menschen und ihre Lebensorientierungen - Sich mit den großen Fragen der Menschen auseinandersetzen können
[[#A2_KB1]] Die Schülerinnen und Schüler können für sie bedeutsame Fragen diskutieren und über existentielle Lebensfragen philosophieren und theologisieren.

* AB / UH
[[#A2_UH1]] Beantwortbare und letztlich unbeantwortbare Fragen:
- Gibt es (=existiert) Gott? Und wenn ja, wie sieht er aus? Warum können wir ihn nicht sehen?
- Wer ist der Mensch?
- Gott ist gut, warum gibt es das Böse?
- Der Sinn des Lebens?
- ...

* Wiederholung
Startseite & Comic

Das Kapitel „Philosophieren – die großen Fragen des Lebens stellen“ thematisiert philosophische und theologische Fragestellungen im Leben der Schüler*innen und bietet einen gezielten Zugang zum Philosophieren und Theologisieren mit Kindern. Der Lebensbezug des Kapitels setzt hier bei Alltagsfragen und sucht nach „großen Fragen“ in der Lebenswelt der Schüler*innen. Der Impuls lädt basierend auf einem Kunstwerk zu einer „Bildreise“ ein. Im Sachbezug werden wichtige Grundlagen des Fragens und der Suche nach Antworten geklärt sowie Grundbegriffe wie objektiv, subjektiv, Methode etc. reflektiert. Die entsprechende Methode bietet gezielt Schritte an, große Fragen zu formulieren und nach geeigneten Methoden des Antwortens zu suchen.

* Erarbeitung
RB S. 26-27

Lösungsvorschläge für die Arbeitsaufträge:

** eins
1 Der Comic thematisiert das Phänomen, dass dieselbe Fragestellung je nach Betonung zu unterschiedlichen Fragen werden kann. Während die erste Antwort auf die Frage „Warum sind wir eigentlich hier?“ konkret auf die aktuelle Situation eingeht, stellt die Betonung auf überhaupt eine „große Frage“ nach dem Woher im Leben. Anhand dieses Beispiels kann mit den Schüler*innenn nach ähnlichen Fragen gesucht werden – ein erster Zugang zum Philosophieren ist gelegt.

** zwei
2 Dieser Arbeitsauftrag ist sehr persönlich und individuell. Er regt im Anschluss an AA1 dazu an, die eigenen „großen Fragen“ des Lebens zu finden. Oft werden dabei sehr schnell Sinnfragen wie Was kommt nach dem Tod? oder Warum gibt es uns Menschen/die Welt? gestellt. Oft mischen sich darunter auch sehr konkrete Alltagsfragen, die bereits hier von den „großen Fragen“ des Lebens unterschieden werden können. Ein möglicher Ansatzpunkt ist dabei die Unterscheidung in beantwortbare Fragen (Fragen des Lebens, auf die es konkrete Antworten gibt) und nicht abschließend beantwortbare Fragen (Fragen des Lebens, auf die jeder Mensch andere Antworten geben wird).

** drei
3 Dieser Arbeitsauftrag ist sehr persönlich und individuell. Die sechs Sprechblasen laden dazu ein, Fragen an Personen oder Personengruppen zu formulieren. Es sollte außerdem darauf geachtet werden, dass v.a. zu den Fragen an Jesus und/oder Gott kein Zwang entsteht: Die Schüler*innen sollen hier Fragen stellen können, aber nicht müssen. Es bietet sich hier an, im Gespräch mit den Schüler*innenn Beispiele für jede „Kategorie“ zu sammeln. Die letzte Sprechblase bietet die Möglichkeit, individuell eine eigene Person oder Personengruppe anzugeben und zu befragen.

** vier
4 Auch dieser Arbeitsauftrag ist sehr persönlich und individuell. Hier wird vor allem die Begründung und Fundierung der einzelnen Fragen reflektiert und danach gefragt, welche Motivation die Schüler*innen haben, genau diese Frage an genau diese Person/Personengruppe zu stellen.



* Hefteintrag

