#+title:      Meta Propheten
#+date:       [2023-12-05 Di 08:13]
#+filetags:   :meta:propheten:
#+identifier: 20231205T081319

# Update =denote-org-dblock=: C-c C-x C-u

#+BEGIN: denote-links :regexp "propheten" :missing-only t
- [[denote:20221226T173738][Propheten]]
- [[denote:20230104T001024][Biblische Propheten]]
- [[denote:20230711T003732][[SW12] Biblische Propheten]]
- [[denote:20230711T003758][[SW13] Moderne Propheten]]
#+END:

* Was sind Propheten - Bsp Jesaja
Der Prophet Jesaja aus Jerusalem (etwa 740-701 v. Chr.) hat mit seiner Verkündigung den Grundstock des Buches geschaffen, das seinen Namen trägt. Aus dem Inhalt der von ihm überlieferten Prophetenworte schließt man, dass er, im Todesjahr des Königs Usija (739 v. Chr.) berufen (Kap. 6), in vier wichtigen Perioden der Geschichte Judas das Wort Jahwes verkündete. Zunächst befasste er sich in Drohworten (Kap. 1 - 3 und 5) mit den Zuständen in Juda und Jerusalem. Im Syrischefraimitischen Krieg (734/33 v. Chr.) warnte er vor einem Bündnis mit Assur (7,1 - 9,6). Beim ersten Versuch des Königs Hiskija, sich an einem Aufstand gegen die Assyrer zu beteiligen (716-711 v. Chr.), erhob er warnend seine Stimme (Kap. 18; 20; 28 - 30; auch Teile von Kap. 14). Endlich trat er beim Angriff des assyrischen Königs Sanherib (um 701 v. Chr.) auf, um das rettende Eingreifen Gottes gegen den überheblichen Feind anzusagen (Worte in den Kapiteln 10; 14; 28 - 30).

Vom Leben des Propheten ist uns wenig bekannt. Er dürfte den gebildeten höheren Kreisen entstammen; anscheinend war er mit einer prophetisch begabten Frau verheiratet (8,3) und hatte wohl mehrere Kinder (vgl. 7,3; 8,1-3). Die Worte Jesajas, die in Kap. 1 - 39 überliefert sind, wurden von seinen Schülern (8,16) und anderen vielfach kommentiert und beträchtlich erweitert; so wurden sie später in seinem Geist an jeweils neue Situationen angepasst. Dem Propheten kam es vor allem darauf an, die Menschen zu Glauben und Vertrauen gegenüber dem heiligen und erhabenen Gott aufzurufen, der nach seinem weisen Plan die Weltgeschichte und besonders die Geschicke seines Volkes lenkt. Dieses gläubige Hinschauen auf den Herrn bedeutet zugleich, seinem Willen zu entsprechen im politischen wie im sozialen Handeln, insbesondere den Armen gegenüber. Der Ernst der prophetischen Botschaft Jesajas drückt sich vor allem in den scharfen Gerichtsworten aus.

Verschiedene Überschriften (1,1; 2,1; 13,1) weisen darauf hin, dass der erste Teil des Buches (Kap. 1 - 39) eine lange Entstehungsgeschichte hat. Noch heute ist ihm anzusehen, dass einer ersten Sammlung (Kap. 2 - 5 und 9,6 - 11,16) die sogenannte Denkschrift des Propheten (6,1 - 9,5) eingefügt und schließlich Kap. 1 als eine Art Zusammenfassung seiner Worte vorausgestellt wurde. Jes 24 - 27 sind apokalyptische Texte (die sog. »große JesajaApokalypse«) und tragen das Kolorit einer späten Zeit an sich. Die Jesajaerzählungen (Kap. 36 - 39) sind fast ganz aus dem zweiten Königsbuch übernommen. So entstand ein Prophetenbuch, das wie bei der Denkschrift in großen Zügen das Grundschema erkennen lässt, nach dem die prophetischen Bücher zusammengestellt wurden: Drohungen gegen das eigene Volk (Kap. 1 - 12); Drohungen gegen andere Völker (Kap. 13 23); Verheißungen, die hier allerdings Drohreden einschließen, für das eigene Volk (Kap. 24 - 35); ein geschichtlicher Anhang rundet das Ganze ab (Kap. 36 - 39). Für das Neue Testament und die christliche Verkündigung sind in besonderer Weise die messianischen Texte wichtig (Kap. 7; 9,1-6; 11; 28,16f).

In eine ganz andere Welt versetzen uns die Kapitel 40 - 55. Hier befindet sich Juda im Babylonischen Exil; zu ihm spricht ein Prophet, der den Auftrag erhält (40,1-11), das unmittelbar bevorstehende rettende Eingreifen Gottes anzukündigen. Gott erweckt Kyrus (44,28 - 45,8), damit er das Volk aus der Gefangenschaft entlässt. Dann wird Jahwe, der als der alleinige durch Schöpfung und geschichtliches Handeln ausgewiesene Gott über die Völker herrscht, sein Volk in einem neuen, wunderbaren Exodus nach Zion heimführen. Dort wird er als König Israels herrschen, das er wieder aufblühen lässt. In diese überschwängliche Heilsprophetie sind vier Texte über den »Gottesknecht« eingefügt (42,1-9; 49,1-9; 50,4-9; 52,13 - 53,12), der als der Erwählte Jahwes zum »Bund des Volkes und Licht der Heiden« bestimmt, wie ein Prophet gesendet, mit Aufgaben für Israel und die Völker betraut, nach Leiden und Todesnot errettet und schließlich verherrlicht wird. Durch die sogenannten Gottesknechttexte hat dieser Teil des Jesajabuches weit in die Zukunft gewirkt. Die neutestamentliche Urgemeinde nahm sie auf und sah sie im Wirken und im Weg Jesu erfüllt. Der Verfasser von Jes 40 - 55 ist unbekannt. Man nennt ihn Deuterojesaja (Zweiter Jesaja).

In Jes 56 - 66 wechselt die Situation wieder. Hier sind verschiedenartige Texte zusammengestellt, die sich an die Heimgekehrten richten. Sie schöpfen vielfach aus Jes 40 - 55, sprechen aber deutlich die veränderte Lage an. Ein Prophet erhebt seine Stimme (Kap. 60 - 62), der sich durch Gottes Geist zur Verkündigung einer frohen Botschaft gesandt weiß (Kap. 61; vgl. Lk 4,16-19); man nennt ihn Tritojesaja (Dritter Jesaja). Dieser Teil des Jesajabuches enthält in loser Anordnung Heils- und Gerichtsworte. Besonders hervorzuheben sind die Verheißung für die Fremden (56,1-8), die Mahnung zur wahren Frömmigkeit (58,1-14), das leuchtende Bild von der Gottesstadt (Kap. 60 und 62), das Gebet zu Gott, unserem Vater, in Gestalt einer Volksklage (63,7 - 64,11). Mit dem Blick auf den neuen Himmel und die neue Erde (Kap. 66) schließt das Jesajabuch.

Unter den Funden von Qumran befand sich eine vollständig erhaltene Jesaja-Handschrift aus dem 2. Jahrhundert v. Chr. Sie ist damit etwa tausend Jahre älter als die meisten bisher bekannten hebräischen Handschriften des Alten Testaments.


* Denote dblock
#+BEGIN: denote-files :regexp "prophet" :sort-by-component title :reverse-sort nil :no-front-matter nil :file-separator t :add-links nil
#+title:      Biblische Propheten
#+date:       [2023-01-04 Mi 00:10]
#+filetags:   :bibel:gerechtigkeit:propheten:
#+identifier: 20230104T001024

* Kompetenzbeschreibung
[[#A1]] Menschen und ihre Lebensorientierungen - Beziehung verantwortungsvoll gestalten können – zu sich selbst, zu anderen, zur Schöpfung
[[#A1_KB1]] Die Schüler können die Bedeutung eines Einsatzes für ein gerechtes Zusammenleben erkennen und konkrete Handlungsoptionen entwickeln.

* AB / UH
[[#A1_AB1]] (Biblische) Propheten und Prophetinnen

* Wiederholung


* Erarbeitung
Material hier:
[[/home/matthias/NMS_Golling/Propheten/]]

Was sind Propheten?
Beispieltexte, besonders in Bezug auf Advent: Verheißung des Messias. (Quelle: Liturgie / Adventsonntag, Lexikon, ...)

[[id:b7ec9d9d-a0e7-4d98-9f07-e3aec92757dd][Messiaserwartung]]

Kein Film, kein Kahoot! Sondern "Action!" ... Schüler müssen beschäftigt werden, besonders in der 4b.

Also: Arbeit zu den Propheten.

* Hefteintrag


--------------------------------------------------


#+title:      Propheten
#+date:       [2022-12-26 Mo 17:37]
#+filetags:   :bibel:zusammenleben:
#+identifier: 20221226T173738

* Kompetenzbeschreibung
[[#A1]] Menschen und ihre Lebensorientierungen - Beziehung verantwortungsvoll gestalten können – zu sich selbst, zu anderen, zur Schöpfung
[[#A1_KB1]] Die Schüler können die Bedeutung eines Einsatzes für ein gerechtes Zusammenleben erkennen und konkrete Handlungsoptionen entwickeln.

* AB / UH
[[#A1_AB1]] (Biblische) Propheten und Prophetinnen


* Wiederholung


* Erarbeitung
Propheten in der Bibel
- Jesaja
- Jeremia
- Ezechiel
- Amos
- Jona

Berufung / Leben / Aufgabe ...

NT:
- Johannes der Täufer

Moderne Propheten(?):
- Kämpfer für die Menschenrechte
- Papst Johannes Paul II. (gegen der Kommunsimus)
  4 teiliger Film (YóuTube).
- Doku über Johannes Paul II: 
  

* Hefteintrag


--------------------------------------------------


#+title:      [SW12] Biblische Propheten
#+date:       [2023-07-11 Di 00:37]
#+filetags:   :04:sw12:
#+identifier: 20230711T003732


* Kompetenzbeschreibung
[[#A1]] Menschen und ihre Lebensorientierungen - Beziehung verantwortungsvoll gestalten können – zu sich selbst, zu anderen, zur Schöpfung
[[#A1_KB1]] Die Schüler können die Bedeutung eines Einsatzes für ein gerechtes Zusammenleben erkennen und konkrete Handlungsoptionen entwickeln.

* AB / UH
[[#A1_AB1]] (Biblische) Propheten und Prophetinnen

* Wiederholung


* Erarbeitung
Material hier:
[[/home/matthias/NMS_Golling/Propheten/]]

Was sind Propheten?
Beispieltexte, besonders in Bezug auf Advent: Verheißung des Messias. (Quelle: Liturgie / Adventsonntag, Lexikon, ...)

[[id:b7ec9d9d-a0e7-4d98-9f07-e3aec92757dd][Messiaserwartung]]

Kein Film, kein Kahoot! Sondern "Action!" ... Schüler müssen beschäftigt werden, besonders in der 4b.

Also: Arbeit zu den Propheten.

* Hefteintrag



--------------------------------------------------


#+title:      [SW13] Moderne Propheten
#+date:       [2023-07-11 Di 00:37]
#+filetags:   :04:sw13:
#+identifier: 20230711T003758

* Kompetenzbeschreibung
[[#A1]] Menschen und ihre Lebensorientierungen - Beziehung verantwortungsvoll gestalten können – zu sich selbst, zu anderen, zur Schöpfung
[[#A1_KB1]] Die Schüler können die Bedeutung eines Einsatzes für ein gerechtes Zusammenleben erkennen und konkrete Handlungsoptionen entwickeln.

* AB / UH
[[#A1_AB1]] (Biblische) Propheten und Prophetinnen


* Wiederholung


* Erarbeitung
Propheten in der Bibel
- Jesaja
- Jeremia
- Ezechiel
- Amos
- Jona

Berufung / Leben / Aufgabe ...

NT:
- Johannes der Täufer

Moderne Propheten(?):
- Kämpfer für die Menschenrechte
- Papst Johannes Paul II. (gegen der Kommunsimus)
  4 teiliger Film (YóuTube).
- Doku über Johannes Paul II: 
  

* Hefteintrag


--------------------------------------------------


#+END:

