#+title:      [SW10] Harte Fakten - gute Gedanken?
#+date:       [2023-06-19 Mo 08:57]
#+filetags:   :01:sw10:
#+identifier: 20230619T085724


* Kompetenzbeschreibung
[[#A2]] Menschen und ihre Lebensorientierungen - Sich mit den großen Fragen der Menschen auseinandersetzen können
[[#A2_KB1]] Die Schülerinnen und Schüler können für sie bedeutsame Fragen diskutieren und über existentielle Lebensfragen philosophieren und theologisieren.

* AB / UH
[[#A2_UH1]] Beantwortbare und letztlich unbeantwortbare Fragen:
- Wer ist Gott? Existiert Gott?
- Existiert überhaupt etwas?
- Wer ist der Mensch?
- Gott ist gut, warum gibt es das Böse?
- Der Sinn des Lebens?
- ...

* Wiederholung
2.4 Harte Fakten
Diese Seite führt den Begriff "harte Fakten" ein, reflektiert aber gleichzeitig seine "Härte". Sie eignet sich gut zur Gegenüberstellung mit 2.5 ("Gute Gedanken"). Beide Begriffspaare stehen als Denkweisen für wesentliche Zugänge zu Religion und Philosophie.

2.5 Gute Gedanken
Dieses Unterkapitel ergänzt den eher materialistischen Begriff "harte Fakten" um "gute Gedanken" und erfasst damit die Polarität von "subjektiv" und "objektiv". Es eignet sich gut zur Kombination mit 2.4 ("Harte Fakten") und kann so ein Gesamtverständnis für Zugangsweisen schaffen, das eine wesentliche Grundlage für ein tolerantes Miteinander bilden kann.

* Erarbeitung

** Lösungsvorschläge für die Arbeitsaufträge (S. 32)
1 Als „harte Fakten“ werden hier Aussagen beschrieben, die objektiv und unabhängig von Meinungen bewiesen werden können. Wichtig ist hier allerdings der Hinweis, dass objektiv und bewiesen nie eine Endgültigkeit meinen kann: In der Wissenschaft gilt ein Beweis so lange, bis der Gegenbeweis angetreten ist. Beispiele für „harte Fakten“ könnten sein: Das Alter der Erde, die Entfernung von einem Ort zum anderen, das Gewicht eines Gegenstandes etc.

2 Als „Methode“ wird hier die Art und Weise definiert, wie man zu Antworten auf Fragen zu gelangen versucht. Beispiele dafür könnten sein: Nachfragen, Abwiegen, ein Experiment machen, messen, beobachten, diskutieren, nachlesen...

3 Je nach ausgewählter Frage auf S. 31 bieten sich unterschiedliche Methoden auf dem Weg zur Antwort an. Beispiele könnten sein: „Wie viel wiegt die Erde“ - „Wiegen bzw. eher berechnen“ / „Wie lange fliegt man bis zum Mond?“ - „Messen, Berechnen, Zeit stoppen“ / „Was ist der Sinn des Lebens?“ - „Nachdenken, Diskutieren, Nachlesen“
4 Auch hier könnten unterschiedliche Lösungen richtig sein. Ein Vorschlag zur Beantwortung könnte so aussehen:

    - Heinrich Schliemann: Ausgrabungen anstellen, Nachlesen
    - Robert Goddard: Berechnungen anstellen, Teleskope benutzen
    - Jane Goodall: Tiere beobachten
   
***** Lösungsvorschläge für die Arbeitsaufträge (S. 33)
1 Als „objektiv“ werden Aussagen beschrieben, die unabhängig von Meinungen sind, als „subjektiv“ solche, die davon abhängig sind, was Menschen denken und glauben.

2 Die auf S. 31. vorab angegebenen Antworten sind grundsätzlich als objektiv zu bewerten. Je nach weiteren Antwortversuchen der Schüler*innen können dazu subjektive Antworten markiert werden.

3 Dieser Arbeitsauftrag soll dazu anregen, über mögliche Antworten auf die Fragestellungen der Leitfiguren zu diskutieren. Auch hier gilt: Den Antwortversuchen der Schüler*innen ist absolut Vorrang vor festen Antworten zu geben – vor allem dann, wenn es um Glaubensfragen oder Meinungen geht.

* Hefteintrag

