#+title:      Webpages
#+date:       [2023-12-18 Mo 08:15]
#+filetags:   :capture:
#+identifier: 20231218T081552

* Bildung ohne Schule - 
:PROPERTIES:
:CREATED: [2024-01-05 Fr 19:30]
:SOURCE: https://multipolar-magazin.de/artikel/bildung-ohne-schule
:END:
In Deutschland gibt es Schätzungen zufolge 1.000 Freilerner – Kinder, die unter Anleitung ihrer Eltern lernen, ohne eine Schule zu besuchen. In Österreich sind es rund 150, dazu kommen dort einige Tausend sogenannte „Homeschooler“. Was steckt dahinter?

* Das Corona-Tribunal - apolut.net 
:PROPERTIES:
:CREATED: [2024-01-05 Fr 19:32]
:SOURCE: https://apolut.net/das-corona-tribunal/
:END:
War´s das? Nach drei Jahren schwerster Beschädigungen der Demokratie bis hin zur Abschaffung, der Liquidierung, des Grundgesetzes durch eine Bund-Länderkonferenz, der Malträtierung unserer Kinder durch Isolierung, Bildungskastration und Maskenquälerei – soll es das jetzt gewesen sein? Nach drei Jahren der Krankheitsdiktatur, der Mediengleichschaltung, der Zwangs-Spritzung mit einem Stoff, der bestenfalls nicht sehr schädlich ist und in vielen Fällen zum Tod geführt hat; da soll die Schwammdrüber-Zeit beginnen?

* Kathedrale von Autun – Wikipedia
:PROPERTIES:
:CREATED: [2024-01-08 Mo 08:46]
:SOURCE: [[https://de.wikipedia.org/wiki/Kathedrale_von_Autun]]
:END:
Die Kathedrale von Autun ist eine romanische Bischofskirche für das Bistum Autun in der Bourgogne-Franche-Comté. Die dreischiffige Basilika ist dem Patronat des heiligen Lazarus anvertraut. Mit reichem Fassadenschmuck markiert sie den höchsten Platz der Oberstadt von Autun. Seit 1949 trägt sie den Titel einer päpstlichen Basilica minor. Das Kulturdenkmal wurde 1840 als Monument historique klassifiziert. 

* Traum der Könige, Burgund, römische Baukunst
:PROPERTIES:
:CREATED: [2024-01-08 Mo 09:31]
:SOURCE: https://www.kunst-meditation.it/gislebertus-traum-der-konige/
:END:
Das romanische Kapitell „Traum der Könige“ in der Kathedrale von Autun in Burgund gehört zu den berühmtesten Darstellungen dieser Art. Meister Gislebertus hat es um 1220 aus Stein gemeißelt. Zu sehen sind der Engel Gabriel und die Heiligen drei Könige. Über ihnen schwebt der Stern von Bethlehem. Mit dem ausgestreckten Zeigefinger der linken Hand weist der Engel energisch auf den Stern, mit dem Zeigefinger der rechten Hand berührt er zart den Ringfinger des obersten Königs. Das Thema ist nicht der Schlaf oder der Traum der drei Könige, sondern das Erwachen aus der Dunkelheit und der Aufbruch in das Licht!

