#+title:      [SW32] Jesus ist auferstanden
#+date:       [2023-07-11 Di 00:51]
#+filetags:   :04:sw32:
#+identifier: 20230711T005146


* Kompetenzbeschreibung
[[#B3]] Gelehrte und gelebte Bezugsreligion - Grundlagen und Leitmotive des christlichen Glaubens kennen und für das eigene Leben deuten können
[[#B3_KB1]] Die Schüler können Leiden, Sterben und Auferstehung Jesu Christi als Hoffnungsbild für Menschen reflektieren.

* AB / UH
[[#B3_UH1]] Jesus ist auferstanden


* Wiederholung
[[id:cf52e625-c3eb-4c05-b1a2-c04a796c6a36][Auferstehung_Bibel]]

* Erarbeitung

Die Auferstehung Jesu ist keine Erfindung, kein Symbol - sondern eine Tatsache.
Cf Firmstunde aus dem YOU-Firmbuch, S. 50-51!

* Bibelarbeit zum Thema "Auferstehung"

** Gruppenarbeit
Klasse in 4 Gruppen einteilen bzw zu 2 oder 3 über folgende Bibelstellen nachdenken:

 1. Joh 19,31-42: Untersucht den Text darauf, ob Jesus wirklich tot war?

    - Lanzenstich durch die Soldaten; ... 
    
 2. Joh 20,1-2.11-18: Wie erkennt Maria Magdalena, dass Jesus auferstanden ist? Welche Rolle spielt das leere Grab dabei?

    - Maria erkennt Jesus an seiner Stimme, wie er ihren Namen ausspricht. Das leere Grab ist kein ausdrücklicher Beweis für die Auferstehung, aber die notwendige Bedingung - Voraussetzung dafür. 
    
 3. Joh 20,1-2.11-18: In der Gesellschaft zur Zeit Jesu galten Zeugenaussagen von Frauen als unglaubwürdig. Was bedeutet das in Bezug auf die Auferstehung?

    - Die Jünger hätten eine Geschichte über die Auferstehung auch erfinden können. Dafür hätten sie jedoch glaubwürdige Augenzeugen (also Männer) benötigt. Da die ersten Zeugen der Auferstehung jedoch Frauen waren, zeigt doch, dass die Jünger die Geschichte der Auferstehung nicht erfunden haben - sie ist also wahr.
    
 4. Joh 20,24-28: Welche Hinweise gibt der Text auf die Frage, ob Jesus wirklich auferstanden ist oder nur in einem symbolischen Sinn?

    - Jesus kann durch verschlossene Türen gehen (was auch die Jünger denken lässt, sie sähen einen Geist - Gespenst). Jesus zeigt ihnen seine Wunden (und nach Lk 24: er isst auch vor ihnen ein Stück Fisch) - was bei einem Gespenst nicht möglich ist. Er lässt sich von Thomas berühren. 

Austausch der vier Gruppen - Raum für Rückfragen

*** Hintergrund für den Lehrer:

Die Auferstehung Jesu ist die Grundlage des christlichen Glaubens, würde man sie wegnehmen, so wäre der Glaube tot. Nur wenn Jesus auferstanden ist, ist Neues geschehen. Die Auferstehung sprengte den Erfahrungshorizont der Jünger. Ist Jesu Leiche wiederbelebt worden? (DAS wäre in der Tat belanglos!) Nein, die Auferstehung Jesu war der Ausbruch in eine ganz andere Art des Lebens, in ein Leben, jenseits von Stirb und Werde. Das geht alle an: es eröffnet sich eine neue Möglichkeit des Menschseins. Der Apostel Paulus stellt klar: die Auferstehung ist entweder ein universales Ereignis - oder gar nicht. So wie der jüdische Glaube sagt: die Auferstehung schließt den Leib mit ein - oder es gibt sie nicht.

*** Bibelsession 1 Kor 15,12-22
Zwei Punkte sind Paulus wichtig...

 - Jesus ist Gottes Sohn, nur so kann uns sein Tod am Kreuz erlösen.
 - Wäre Jesus im Grab geblieben, gäbe es auch für uns keine Auferstehung und kein ewiges Leben.

Austausch: Wie stellst du dir das ewige Leben vor?

** Auferstehung 
*** Youcat Nr. 106 + Austausch
Es gibt keine Beweise (naturwissenschaftlich) für die Auferstehung. Aber es gibt viele Augenzeugenberichte jener Menschen, die dem auferstandenen Jesus begegnet sind. Das ältestete schriftliche Zeugnis ist der "erste Brief an die Korinther", den der Apostel Paulus ca 20 Jahre nach Christi Auferstehung schrieb. Zwei Jahre nach Jesu Auferstehung begegnet Paulus selbst Jesus vor den Toren der Stadt Damaskus und findet in Jerusalem eine lebendige Überlieferung des christlichen Glaubens vor. Die Erscheinungen und Begegnungen mit Jesus gipfeln in der Himmelfahrt Jesu. Seither gab und gibt es bis heute Begegnungen mit dem lebendigen Herr: Jesus Christus lebt! Es folgt die Lebensgeschichte eines Mannes, der in der dunkelsten Stunde seines Lebens Gott begegnet:

*** Zeugnis von Torsten Hartung:
Hr. Hartung wächst in einer Familie auf, die von Gewalt geprägt ist. Eines Tages entscheidet er sich, vom Opfer zum Täter zu werden und wird zu einem gefürchteten Schläger, landet oft im Gefängnis. Als er wieder einmal frei ist, wird er Chef einer kriminellen Vereinigung, die Luxus-Autos nach Russland und Arabien verkauft. 

Er kommt in Einzelhaft und wird zu 15 Jahren Gefängnis verurteilt. Dort begegnet er Gott. Es beginnt ein längerer Heilungsprozess; er lässt sich taufen, weiht sich der Muttergottes. Nach dem Ende seiner Haftstrafe fährt er für 3 Wochen nach Südkorea, gibt in den Gemeinden Zeugnis. Er heiratet und arbeitet nun Vollzeit ehrenamtlich für Gott. Er leitet einen Seelsorge-Verein, der jugendliche Straftäter begleitet.

Sein Zeugnis geht wirklich unter die Haut:

[[https://www.youtube.com/watch?v=lpfXmymNQBI]]

*** YouTube Videos von Johannes Hartl - Auferstehung
[[https://www.youtube.com/watch?v=6_UQZVW8EWU]]

 - Worauf beruht der christliche Glaube?
   Eine Religion steht und fällt mit der Person des Gründers. Sind die Tatsachen wahr oder falsch? Im Christentum gibt es nur "wahr oder falsch"; entweder Jesus ist wirklich in der Eucharistie gegenwärtig, oder eben nicht.
   
 - Ist die Auferstehung nur etwas "Emotionales" / oder ein historisches Fakt?
 - Wie kann ich ein hist. Fakt "beweisen"?
   - Befund: leeres Grab, Glaube (genauer: ein sich ausbreitender Glaube (...) Augenzeugen im Land von Augenzeugen)
   - Quellen: alt, viele, glaubwürdig, Überlieferung
   - alternative Theorie

 Die ältesten Quellen:
  - leeres Grab bei Markus
  - Paulus-Formel (1 Kor 15)
  - Lukas: Paulus wurde 63 n.Chr. hingerichtet. Die Apg endet vor dem Tod des Paulus. Also wurde sie vorher geschrieben. Ebenso kennt Lukas die Topographie / Stadt Jerusalem, die 70 n.Chr. von den Römern zerstört wurde. Ein weiteres Zeichen, dass die Apg / das Ev. vorher geschrieben wurde.


* Hefteintrag
