#+title:      Religionsunterricht
#+date:       [2023-12-06 Mi 08:44]
#+filetags:   :meta:Project:
#+identifier: 20231206T084441
#+CATEGORY: RU_meta
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/RoamNotes/exports/Religionsunterricht.html

* Gedanken
Der Text ist nicht ganz genau unter dem Headline. Und der Text geht weiter. Der Text ist nicht ganz genau unter dem Headline. Und der Text geht weiter. Der Text ist nicht ganz genau unter dem Headline. Und der Text geht weiter. Der Text ist nicht ganz genau unter dem Headline. Und der Text geht weiter. Der Text ist nicht ganz genau unter dem Headline. Und der Text geht weiter.

#+BEGIN_NOTES
  Enter speaker notes here.
#+END_NOTES

#+ATTR_REVEAL: :frag (appear) 
   - I will grow.
   - I will shrink.
   - I rolled in.
   - I will fade out.
   - I don't fragment.

** Burnout?
:PROPERTIES:
:CAPTURED: [2023-12-06 Mi 10:00]
:END:
Im Moment geht's mir sehr schlecht. So ziemlich alles ist entmutigend. Den Schülern interessiert das Fach gar nicht. Besonders die drei vierten Klassen: Null Bock auf alles. Selbst Themen, die sie selbst auswählen, bearbeiten sie halbherzig, die Ergebnisse sind großteils erbärmlich. Klassische RU Themen gehen sowieso nicht. Die Klasse 3b gehört hier ebenfalls dazu. In der 3a hat das Arbeiten vor Kurzem ganz gut geklappt; aber ich kann auch nicht immer Gruppenarbeit machen. 

Disziplinär wird es von Jahr zu Jahr schlimmer. Einziges Interesse sind PC, Games, Handy - man sieht kein Kind draußen spielen (in Golling, wie in Grödig). Fast alle sitzen vorm PC und zocken - so wie ihre Eltern. 

Warum soll ich mich für Kinder aufreiben und die Frohe Botschaft von Jesus verkünden, wenn diesen Kindern alles egal ist, sie dieser Botschaft gleichgültig gegenüber stehen und dann noch den Lehrer respektlos behandeln? Muss ich mir das gefallen lassen?

Meine Direktorin stärkt mich da gar nicht, sondern will mir vorschreiben, was ich unterrichten soll: "Sicher keine Bibelthemen wie zB Propheten; sondern Ethik, deshalb habe ich ja auch diese Mappe gekauft."

Sollte ich mich zum Wechsel entscheiden: es wäre eben meine x-te Entscheidung, die quasi daneben geht. 


** Selbständigkeit
:PROPERTIES:
:CAPTURED: [2023-12-06 Mi 13:24]
:END:
Das war heute wieder ein schwieriger Tag; wie erziehe ich Kinder zur Selbständigkeit? Die Kinder erwarten, dass ihnen alles auf dem Silbertablet präesentiert wird. Eine HÜ in Religion machen einige Schüler "ins Handy"; ein anderer bringt nur Stichworte auf einem "Kaaszettel"; zwei Mädels eineinhalb Seiten ausgedruckt, offensichtlich copy+paste aus Wikipedia. Also muss ich in einer dritten Klasse explizit jeden Arbeitsschritt angeben. Manchmal auch in einer vierten Klasse!

** Workflow
:PROPERTIES:
:CAPTURED: [2023-12-06 Mi 20:06]
:END:
Ich sollte mir einen Workflow überlegen, der etwas einfacher ist. Im Moment ist das Alles ziemlich unübersichtlich. War es mit =org-roam= besser? Der Wegfall der database ist hingegen schon ein Vorteil.

Reflexionen zu bestimmten Schülern kann ich mit =org-capture= zu dem betreffenden Schüler eintragen. Auch ein Eintrag in eine Tabelle ist möglich.

Wie verwalte ich aber meine eigenen Gedanken zum Unterricht? Hier in dieser Datei - die einzelnen Headlines kann ich per Auswahl anzeigen lassen, oder? Und wenn ich mir Gedanken zu bestimmten Themen mache - dann erstelle ich eine neue Notiz, oder erweitere bereits bestehende.

** Berufung
:PROPERTIES:
:CAPTURED: [2023-12-14 Do 12:49]
:END:
The Chosen - 3. Staffel - Zu Zweit:
"Um Großes zu tun, brauchst du nichts fühlen. - Jesus braucht uns nicht, er will uns."

Wo trage ich eigentlich meine laufenden Gedanken ein? Idee: =inbox.org=

Begegnung Jesus mit (dem kleinen) Jakobus Thaddäus? - so stark; ... Warum soll jemand wie Jakobus, der humpelt, Kranke heilen? Er selbst hat Jesus noch nie um seine Heilung gebeten? ... "Du hast mich nicht geheilt. - Möchtest du geheilt werden? - Nur wenn es möglich ist. - Du weißt, dass es möglich ist. - Hör mir gut zu: Nach dem Willen des Vaters könnte ich dich heilen; es gibt schon so viele. Aber deine Geschichte: du bist nicht geheilt, und verkündest Gott. Leid und Schmerz geduldig ertragen und die Ewigkeit ohne Leiden. - ..."

** Weihnachten
:PROPERTIES:
:CAPTURED: [2023-12-20 Mi 14:09]
:END:
Mir geht's wirklich nicht gut. Je näher Weihnachten kommt, desto größer wird der Stesslevel. Vor allem dieser Druck, Geschenke machen zu *müssen*, ist erdrückend.

Auch wenn viele sagen: "Zu Weihnachten geht es doch nicht um Geschenke!" - so erwartet doch jeder Geschenke. Nur mal so ein Gedanke: Stell Dir vor - Du würdest wirklich gar kein (persönliches) Geschenk erhalten - was würde das mit dir machen? Wäre das immer noch ein schönes Fest für dich? Wirklich? Wenn du mit "Ja" antwortest: Hast du das schon einmal erlebt? Ich bin mir nicht so sicher. Ich habe es erlebt: vor ca zwei Jahren. Kein persönliches Geschenk! Und das Gefühl ist wirklich sch...

Und diese Weihnachten kann ich meinen Kindern eigentlich nix schenken, da mein Konto es nicht hergibt. Ich könnte, aber dann wird mein Konto eben sehr rot. Und meine Frau wünscht sich einen Monent der Entspannung zu zweit. Das heißt: Hotel, Restaurant, Kino, etc... kostet eben alles Geld. Das ich nicht habe...

Und das alles, gepaart mit der depperten Situation in der Schule, ist einfach zu viel für mich.

** [[denote:20230711T004403][[SW18] Glaube und Kunst]]
:PROPERTIES:
:CAPTURED: [2024-01-10 Mi 08:59]
:SUBJECT: [[denote:20230711T004403][[SW18] Glaube und Kunst]]
:END:
"Nicht einmal Ethik" interessiert die Schüler. Ich bin überzeugt, dass die Schüler gar nix mehr interessiert. Die Reaktionen und die Haltung der Kinder ist "verachtend, milde lächelnd, fadisiert, gleichgültig, ...".

Und zwar egal, ob Gruppenarbeit, zu zweit, alleine, ... Während ich rede, führen die Schüler Privatgespräche, null Teilnahme am Unterricht.

Ich hab dann auch kein Interesse mehr, irgend etwas noch zu tun. Natürlich kann ich die Kinder alles selbst erarbeiten lassen und dann die Ergebnisse beurteilen. Aber: ist das zielführend? Liebestank auffüllen? Da fehlt es prinzipiell an jedem Respekt mir gegenüber.

Was soll ich tun, damit wenigstens ich nicht untergehe? Jobwechseln? Unterricht komplett ändern? Wie? ...

Ist der Zug nicht ohnehin schon komplett abgefahren?

** [[denote:20221228T204513][A Klasse 2020-24]]
:PROPERTIES:
:CAPTURED: [2024-01-15 Mo 13:50]
:SUBJECT: [[denote:20221228T204513][A Klasse 2020-24]]
:END:
An Adrian, Luis und Nico einen perönlichen Brief schreiben:
Laut derzeitigem Stand würden sie ein Genügend erhalten... nur mehr eine Stunde als Chance; dann unterschrieben an die Eltern.

** Themenvorschläge
:PROPERTIES:
:CAPTURED: [2024-01-22 Mo 09:48]
:END:
Noch offene Themen aus dem Lehrplan:

- Sehnsüchte und Lebensträume, persönliche und berufliche Ziele, Utopien und Dystopien

- Erfahrungen von Scheitern und Neubeginn, Passionsgeschichte und Osterevangelium, Bedeutung des Kreuzes, österlicher Glaube als christliche Lebenshaltung

- Biblische Symbolik für den Geist Gottes, Vielfalt der Charismen Pfingstereignis (Apg 2)
  Ängste überwinden und Begabungen leben

- Lebensgestaltung in Freiheit, Befähigung zur oder Verlust der Eigenverantwortung, Gewaltstrukturen in ldeologien und Missbrauch von Religion und Autorität, Fundamentalismus

** Pausenaufsicht 2. Stock, Mi
:PROPERTIES:
:CAPTURED: [2024-01-24 Mi 14:20]
:END:
Das war heute ein Wirbel: einige Schüler der 3a, 4c und 4a waren im zweiten Stock. Ein paar Burschen aus der 4b brüllten meinen Familiennamen durch das ganze Stockwerk. Volles Chaos. Das geht alleine nicht. Frechheit von Seiten der Schüler.

** Unterrichtsvorbereitung
:PROPERTIES:
:CAPTURED: [2024-01-25 Do 12:10]
:END:
Ich sollte die Vorbereitung umstellen; dass die SW im Titel der Dateien steht, engt das Anpassen in der Jahresplanung sehr ein. Auf der Homepage des Schulbuches gibt es Jahresplanungen. Ich könnte diese Einteilung beibehalten. Soll ich das ändern? Das wäre eine zu große Arbeit...

Vorschlag? ...

Ist die Tabellenform der Jahresplanung die bessere Variante? Die Jahresplanung gibt nur einen groben Überblick. Daher bleibe ich bei meiner Einteilung und die SW bleibt im Dateinamen.

** Berufliche Weiterbildung
:PROPERTIES:
:CAPTURED: [2024-02-23 Fr 22:46]
:END:
Da mich meine Direktorin heute gebeten hat, eine Mathematik Stunde in einer vierten Klasse zu supplieren, habe ich meinen Wunsch geäußert, mich als Mathematik Lehrer weiterbilden zu wollen. Das wäre durchaus möglich, ich solle mich an die BD wenden, dort gäbe es eine Dame, die sich darum kümmere - meinte sie.

Ich finde es eine reizvolle Idde, die mir sehr gefällt; auch für später, in der Pension, lässt sich dadurch gutes Geld verdienen, etc.

Ich werde mich auf jeden Fall darum kümmern und mich erkundigen.

** Use ~org-coursepack~ to create teaching material
:PROPERTIES:
:CAPTURED: [2024-04-17 Mi 14:31]
:END:
- source :: https://github.com/joonro/Org-Coursepack
- documentation :: https://joonro.github.io/Org-Coursepack/index.html

Vielleicht kann dies hilfreich für meine neue Stelle in Abtenau sein?

* Tasks

** TODO Berufswechsel
:PROPERTIES:
:CAPTURED: [2023-12-06 Mi 11:23]
:END:
Wo liegen meine Stärken und Schwächen? Warum ist es im Moment so frustrierend?

Talentecheck (online ist nicht seriös)

Alternative Jobs:
- Schulform wechseln: zB in die VS als RL
- Oder: Fach wechseln; dafür werde ich wohl eine Zusatzausbildung machen müssen.
- Schulbuchverlage
- Erwachsenenbildung
- Jugendeinrichtungen
- Buchhandel?
- Journalismus?
- oder ganz was anderes (wofür ich eine neue Ausbildung absolvieren müsste)
- Politik?!

Vor einem Berufswechsel hab ich ziemliche Angst; würde es als erneutes Scheitern erleben. Und dann kommt die finanzielle Unsicherheit dazu. Und: ob ich überhaupt einen anderen Job finden werde?

Sollte ich bleiben - dann muss sich radikal was ändern? Da ich dies von den Kindern nicht erwarten kann - muss ich mich radikal ändern. Wie immer ... hmpf!

** TODO Workflow
:PROPERTIES:
:CAPTURED: [2023-12-06 Mi 20:24]
:END:
was ist zu tun?

** TODO Material
:PROPERTIES:
:CAPTURED: [2024-01-05 Fr 18:33]
:SUBJECT: [[denote:20221230T193456][B Klasse 2022-26]]
:END:
Was brauche ich?

** DONE Material besorgen
CLOSED: [2024-01-08 Mo 08:15] DEADLINE: <2024-01-05 Fr 21:00>
:PROPERTIES:
:CAPTURED: [2024-01-05 Fr 18:39]
:SUBJECT: [[denote:20230708T143857][A Klasse 2023-27]]
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2024-01-08 Mo 08:15]
:END:

** DONE Schreiben an Luis, Adrian und Nico bzgl RU Note
CLOSED: [2024-01-16 Di 22:06] DEADLINE: <2024-01-16 Di 13:00>
:PROPERTIES:
:CAPTURED: [2024-01-15 Mo 23:06]
:SUBJECT: 
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2024-01-16 Di 22:06]
:END:
Zuerst perönlich, nächste Stunde allerletzte Chance; wenn nicht - unterschrieben von Eltern zurück.

** DONE [#A] Bücher zum Thema "Religion/Entstehung"
CLOSED: [2024-02-28 Mi 21:10] DEADLINE: <2024-02-29 Do 22:00>
:PROPERTIES:
:CAPTURED: [2024-02-27 Di 07:59]
:SUBJECT: [[denote:20221230T193718][B Klasse 2020-24]]
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2024-02-28 Mi 21:10]
:END:
KPH Bibliothek fragen; sollte ich dort geeignete Bücher finde, ist die Schulbibliothek an der MS Golling interessiert (Mirjam Seiwald). Dafür gibt es ein Budget.

ZVAB: [[file:20231206T084441--religionsunterricht__meta_project.org][Religionsgeschichte von P. D. Chantepie de la Saussaye]]
(va 4. Auflage von 1925, 2 Bände; die ersten drei Auflagen erschienen vor dem Tod des Autors. Die vierte Auflage wurde stark überarbeitet und beinhaltet Artikel und Beiträge von namhaften Experten.)

Ich hab in der Bibliothek der Schule nachgefragt und ein paar Bücher gefunden. Die sind so lala, sie genügen für unsere Arbeit, sind aber leider nicht mehr ganz "up-to-date".

