#+title:      Leid hat viele Gesichter damit umgehen
#+date:       [2023-01-03 Di 21:14]
#+filetags:   :angenommen-sein:leid:
#+identifier: 20230103T211418

* Kompetenzbeschreibung
[[#A2]] Menschen und ihre Lebensorientierungen - Sich mit den großen Fragen der Menschen auseinandersetzen können

[[#A2_KB1]] Die Schüler können leidvolle Erfahrungen zum Ausdruck bringen und (christliche) Wege des Umgangs mit menschlicher Begrenztheit aufzeigen. 

* AB / UH
[[#A2_AB1]] Angenommen-Sein in Erfahrungen von Trennung, Verlust, Misserfolg und Krankheit


* Wiederholung


* Erarbeitung
1 Der Comic spielt darauf an, dass es manchmal leichter wird, wenn man seine Last teilt. Eine andere Möglichkeit wäre auch gewesen, dass Theo einiges seiner Last zurücklässt, loslässt. Im übertragenen Sinn sind natürlich nicht die Dinge gemeint, die sich in Theos Rucksack befinden, sondern die „psychische“ Last, die jede*r von uns mit sich trägt.

2 Dieser Arbeitsauftrag ist persönlich und individuell. Sorgen, die unsere Schüler*innen des Öfteren beschäftigen: Scheidung der Eltern, Migration, Umzug von Freunden oder einem selbst in eine andere Stadt, Streit mit den Freunden*innen, …

3 Bei vielen der Schüler*innen bemerken wir, wenn diese etwas belastet, das veränderte Verhalten. Manchen tut ein wohlwollendes Gespräch, eine Umarmung, Hilfe eines Erwachsenen, … gut.

4 Das Seil symbolisiert einerseits das Muster eines Herzschlages in der Medizin, andererseits aber auch die Höhen und Tiefen, die ein Mensch im Laufe seines Lebens erlebt. Manchmal ist das Leben ein Balanceakt und wir tänzeln wie Seiltänzer auf unserem „Lebensseil“ umher.

* Hefteintrag
