#+title:      Jesus Christus Mensch
#+date:       [2023-01-02 Mo 22:34]
#+filetags:   :jesus:theology:
#+identifier: 20230102T223430

RB S. 52:
3.9 Jesus, der Mensch

Dieses Unterkapitel betrachtet den Menschen Jesus. Durch die vorgestellten historischen Quellen der Geschichtsschreiber Tacitus und Flavius Josephus wird der historische Hintergrund zur Person Jesus von Nazareth beleuchtet. Die Schüler*innen beschäftigen sich eigenständig mit Quellen, die über Jesus berichten und machen sich auf die Suche nach Fakten, die seine Existenz belegen. Ein Sensorium für die Unterscheidung von historischer und narrativer Wahrheit kann dadurch geschaffen werden.

RB S. 53:
3.10 Jesus, der Christus

Dieses Unterkapitel wendet sich nun Jesus, an dem die Menschen glauben, zu – der Jesus Christus des Glaubens. Der Christus-Titel wird vorgestellt und mit Bedeutung gefüllt. Durch die Beschäftigung mit Christus-Darstellungen wird ein Zugang zu dem geschaffen, was der Christusglaube für Menschen bedeutet. In Fortführung zu den Inhalten, die im vorherigen Kapitel über den historischen Jesus besprochen werden, soll ein Gespür dafür entwickelt werden, dass die Darstellungen und der Titel Jesu keine historischen Angaben, sondern Glaubenszeugnisse darstellen. Das Anfertigen eines eigenen Christus-Bilds leitet über zur Auseinandersetzung mit dem eigenen, ganz persönlichen Glauben an Jesus Christus.

Hintergrundinformationen zu den beispielhaft ausgewählten Bildern:

 - Die Darstellung Jesu als Hirte in der Callixtus-Katakombe in Rom (Italien) ist eine der ältesten Jesus-Darstellungen der Kunstgeschichte. Sie zeigt Jesus als ungewohnt jungen Mann, noch ohne die übliche Langhaarfrisur, analog zu ähnlichen Darstellungen römischer Bürger dieser Zeit. Auf seiner Schulter trägt er ein Lamm, mit seiner rechten Hand hält er einen Wassertrog. Die Darstellung unterscheidet sich wesentlich von bekannten, meist verklärten Jesus-Darstellungen und verdeutlicht den Schülern, dass die Vorstellungen der frühen Christen anders waren als die der späteren Gesellschaften.
   
 - Die moderne, aber traditionell anmutende Statue "Christus der König der Welt" in Świebodzin (Polen) zeigt einen monumentalen König – ganz im Gegensatz zum schmächtigen, zurückhaltenden Jesus als Hirten. Die Königsstatue misst insgesamt 36 Meter, alleine die goldene Krone hat eine Höhe von drei Metern. Jesus wird als mächtiger König dargestellt, sein Blick ist streng. Dahinter steckt die Vorstellung eines weltlichen Königs, der über ein Volk herrscht. Diese Vorstellung wird mit der Person Jesu und seinem biblischen Titel "König (der Juden)" verbunden.
   
 - Die "Black Nazarene"-Statue (unten) in Manila (Philippinen) ist ein wesentliches Merkmal philippinischer Spiritualität und Volkskultur. An ihr wird deutlich, dass sich Christusdarstellungen auch durch ihr kulturelles Umfeld stark unterscheiden. Andere Beispiele dafür sind etwa Indio-Statuen oder ähnliche Christusdarstellungen aus der Aborigines-Kultur.

   * Religionsbuch - Jesus, der Mensch (S. 52):

1 Der Lernertrag dieses Arbeitsauftrags ist nicht nur für das religiöse Lernen, sondern auch für die Bewältigung tagtäglicher Herausforderungen von Bedeutung. Vertrauenswürdige Informationen zu finden wird wahrscheinlich immer schwieriger und deshalb ist es von großer Bedeutung, sich mit Quellenkritik auseinanderzusetzen. Die Schüler*innen zählen Informationsquellen auf und bewerten diese anhand ihrer Objektivität. Ein Vorschlag zur Erweiterung: Das Gespräch über Quellen kann auch auf andere Wissensgebiete ausgedehnt werden: Woher beziehen zum Beispiel Geograph*innen ihre Informationen?
2 Dieser Arbeitsauftrag beschäftigt sich mit dem historischen Hintergrund zur Person Jesus. Die Schüler*innen erfahren durch die Bearbeitung, dass sich die Existenz von Jesus auch durch außerchristliche Quellen belegen lässt. Aus Quellen, die gesichertes Wissen über die Zeit Jesu berichten, können Fakten über die Person Jesus aufgelistet werden.

Lösungsvorschlag: Was man über Jesus weiß
 - Name: Jesus
 - Hingerichtet unter Pontius Pilatus
 - ...

In einer abschließenden Reflexion kann darüber gesprochen werden, warum man überhaupt Wissen über Jesus aufgeschrieben hat. Ein erstes Sensorium für die Unterscheidung historischer und narrativer Wahrheit kann dadurch geschaffen werden.

3 Die beiden wichtigsten außerbiblischen Quellen zur Person Jesus, die vom römischen Geschichtsschreiber Tacitus und vom jüdischen Geschichtsschreiber Flavius Josephus (auch Josephus Flavius) stammen, zeigen einerseits, dass Jesus von Nazareth auch zeitgenössisch außerchristlich wahrgenommen wurde und schon früh nach seinem Tod als historische Person angesehen wurde. Andererseits verweisen sie auch auf die wenigen außerchristlich historisch belegten Fakten über sein Leben: Es lässt sich eindeutig sagen, dass Jesus gelebt hat, allerdings sind fast alle restlichen Angaben Verweise auf den Glauben der Christinnen und Christen.

|-------------------------------------------------+--------------------------------+------------------------------------------------|
| Gemeinsamkeiten                                 | Tacitus                        | Flavius Josephus                               |
|-------------------------------------------------+--------------------------------+------------------------------------------------|
| Jesus wurde ...                                 | hingerichtet                   | unter Pontius Pilatus                          |
| Jesus war ...                                   | männlich.                      |                                                |
|-------------------------------------------------+--------------------------------+------------------------------------------------|


|-------------------------------------------------+--------------------------------+------------------------------------------------|
| Unterschiede                                    | Tacitus                        | Flavius Josephus                               |
|-------------------------------------------------+--------------------------------+------------------------------------------------|
| Die Informationen über die Person Jesus sind    | sachlich und knapp             | bewundernde Informationen (unglaubliche Taten) |
|                                                 |                                |                                                |
| Was in den Berichten noch geschrieben steht ... | Keine Erwähnung von den        |                                                |
|                                                 | Anhängern und der Auferstehung | Anhängerschaft und Auferstehung wird erwähnt   |
|                                                 |                                | Jesus wird mit Propheten verglichen            |
|-------------------------------------------------+--------------------------------+------------------------------------------------|
 
4 Die Frage, ob es Jesus wirklich gegeben hat, begegnet im Alltag – und damit auch im Religionsunterricht – sehr oft. Die Antwort ist - aufgrund des Vorhandensein außerbiblischer Quellen, die unabhängig voneinander von der historischen Person Jesus von Nazareth berichten – ein gesichertes Ja. Mit Schülerinnen und Schülern kann im Anschluss an diese Aussage noch weiterdiskutiert werden, warum die in den Evangelien niedergeschriebenen Geschichten über Jesus sich von den Berichten der Gerichtsschreiber unterscheiden. Welcher Zugang zu Jesus wird erst durch die Evangelien möglich?

Katholisch für Anfänger - Wer war Jesus Christus?
[[https://www.youtube.com/watch?v=kab5FZH_iRY]]

Kathmedia - Videos über Jesus:
3MC, Christentum-Islam, ...

* Jesus, der Christus (S. 53)
1 Dieser Arbeitsauftrag stellt eine Annäherung an Jesus, den Christus, an den unzählige Menschen dieser Erde glauben und geglaubt haben dar. Der Christustitel ist ein Glaubenstitel, was für Schüler*innen nicht leicht zu fassen ist, denn Namen und Titel werden oft vermischt. In diesem Auftrag sollte eine Sensibilität für Titel im Allgemeinen geschaffen werden: Welche Menschen sind den Schüler*innen so wichtig, dass sie ihnen Titel geben? Schülerinnen und Schüler suchen Titel, die Menschen heute aufgrund ihrer Bedeutung gegeben werden können. Sie reflektieren über den jeweiligen Hintergrund, der hinter den Titeln stecken kann. Letztendlich ist auch die Anrede des Vaters – Papa – ein Titel, der zudem noch von Jesus im Vater unser verwendet wurde und bis heute tiefes Gottvertrauen ausdrückt.

2 Durch das Angebot dieser Aufgabenstellung soll den Schüler*innen Raum eröffnet werden, der es ihnen ermöglicht, selbst über ihre eigene Jesus-Beziehung nachzudenken. Das Betrachten der Jesusbilder und -texte auf dieser Seite ermöglicht ein Abwägen, inwiefern sie der eigenen Jesus-Vorstellung entsprechen. Dadurch kann in Folge das Formulieren einer ganz eigenen, neuen Jesus-Vorstellung möglich werden.

3 Dieser Arbeitsauftrag zielt methodisch auf eine Bildbetrachtung ab: Für den Unterricht bietet es sich an, dass die Schüler*innen die Bilder betrachten und in einem ersten Schritt nennen, was sie sehen. Danach können sie in einem weiteren Schritt die verschiedenen Christusdarstellungen beschreiben und voneinander unterscheiden. Durch das Nachahmen der Körperhaltung und der Blicke, die den Bildern zu sehen sind, kann ein ganzheitlicheres Lernen erfolgen: Die Schüler*innen können in einem weiteren Gespräch über Gefühle und Empfindungen reden, die sie beim Einnehmen verschiedener Körperhaltungen empfunden haben.

4 Der Arbeitsauftrag greift auf, was im dritten Schritt schon thematisiert wurde. Ein eigenes Jesus-Bild zu entwerfen geschieht hier nun in einer bildlichen Darstellungsweise. Einleitend dafür können wiederholt die Jesus-Bilder auf der Seite betrachtet werden. Aufbauend darauf können Schülerinnen und Schüler darüber nachdenken, was in ihrem persönlichen und individuellen Jesus-Bild bedeutsam sein müsste und werden angelehnt daran ein eigenes entwerfen.

5 Durch das Betrachten der Bilder soll ein Nachspüren darüber angeregt werden, was die Künstlerinnen und Künstler bewogen hat, Jesus genau so darzustellen: Was ist das Bedeutsamste an Jesus für die Kunstschaffenden? Wann wurde das Kunstwerk wo geschaffen und in welcher Weise war das beeinflussend? Ein Nachdenken über diese Fragen kann den Horizont öffnen, auch andere Jesus-Bilder zu betrachten und zu miteinander zu vergleichen. Verschiedene (Glaubens)Blickwinkel auf Jesus können auf diese Weise sichtbar gemacht werden.


* Heilige drei Könige:

Text aus dem Evangelium Mt 2,1-12

Das Wort "Sterndeuter / Magier" kann folgendes bedeuten:
 - Angehörige der persischen Priesterklasse; "Walter einer eigentlichen Religion"; Philosophie;
 - Inhaber; Ausüber eines übernatürlichen Wissens
 - Zauberer
 - Betrüger und Verführer

Das religiöse Suchen kann sich für Gott und Jesus öffnen - da spendet es Hoffnung und Heil. Wendet es sich gegen Gott, wird es dämonisch und zerstörerisch. Hier zeigt sich die Ambivalenz des Religiösen.

Die Magier in Mt gehören den ersten beiden Möglichkeiten an: religiöses und oder philosophisches Wissen, das den Weg zur Erkenntnis Jesu öffnet. Weltall: Konjunktion von Jupiter und Saturn im Sternbild der Fische ("Stern") in den Jahren 7-6 v. Chr. Diese Magier könnten Sternkundige gewesen sein. Damit ein Stern auf einen neuen König verweist, muss es eine Verheißung gegeben haben. Zur Zeit Jesu gab es Erwartungen, dass aus Judäa der zukünftige Herr der Welt hervorgehen werde. Diese Menschen waren "Weise", Menschen der inneren Unruhe, der Hoffnung: auf der Suche nach dem Wahren, dem wahren Gott - also Philosophie im eigentlichen Sinn. Im Suchen nach Christus geht es um das Überschreiten jeder Wissenschaft. Ähnlich wie Abraham. Vgl. Ps 72,10 und Jes 60: aus den Magiern werden Könige (und damit die Kamele und Dromedare). Die drei Magier / Könige stellen die drei bekannte Kontinente dar: Europa, Afrika und Asien. Plus die drei Lebensalter: Jugend, Reife, Alter. Die drei Weisen sind ein Anfang - den Aufbruch der Menschheit auf Christus hin.
Sie suchen Wahrheit; heute würden wir Wissenschaftler sagen. Auf jeden Fall sind es Menschen auf der Suche.

Stern:
gibt Orientierung; erfreut uns; weckt unser Staunen über die Größe des Weltalls;
Zur Zeit Jesu, genauer: in den Jahren 7-6 v. Chr. gab es eine Konjunktion der Planeten Jupiter, Saturn und Mars (Johannes Kepler; wird auch von modernen Astronomen geteilt). Dieses Ereignis gab es auch im Jahre 1604, plus eine Supernova. In China entdeckte man im Jahre 4. v. Chr. einen hell leuchtenden Stern, der über längere Zeit hin sichtbar war. Jupiter steht für den babylonischen Hauptgott Marduk, Saturn für das Volk der Juden.
Die drei Weisen müssen auch innerlich auf der Suche nach dem Stern gewesen sein.

Der Kosmos spricht von Christus. Die Schöpfung gibt dem Menschen eine Ahnung vom Schöpfer - aber wir können sie nicht vollständig enträtseln. Die Hoffnung, dieser Gott möge sich zeigen. Der Mensch soll und kann diesem Gott entgegen gehen.

Die Weisen kommen durch den Stern zunächst nur bis Judäa und gehen nach Jerusalem, denn nur dort kann der neue König geboren sein. Sie benötigen das Zeugnis der Heiligen Scrhiften, um endgültig den Weg zu finden. "König der Juden" ist heidnischer Ausdruck; Juden würden "König Israels" sagen. "Es erschrak ... ganz Jerusalem": verständlich - wenn es einen neuen König gibt, dann geht es Herodes an den Kragen; und dieser wird seinen Thron nicht kampflos überlassen, was nur Schlimmes für die Einwohner Jerusalems bedeuten kann. Gott stört die zufriedene Alltäglichkeit. Micha 5,1; 2 Sam 5,2. Das Große kommt aus dem irdisch Geringen. Warum erkennen zwar die Schriftgelehrten dies, ziehen daraus aber keine prakischen Konsequenzen?

huldigen:
verehren, sich niederwerfen. Die Weisen werden von großer Freude erfüllt: ihre Hoffnung bewahrheitet sich, sie finden und werden gefunden. Es fehlt Josef? Vll erinnert Mt an die Jungfrauengeburt Jesu und an seine Gottessohnschaft. Proskynese - Niederwerfen auf die Erde: nur vor dem Gott-König.
Gaben: Gold (König; unser Herz), Weihrauch (Gott; unser Gebet), Myrrhe (Begräbnis; Heiland; was ist wund in uns?) Als die Frauen am Morgen Jesus salben wollen (dem Tod entegegenwirken), ist Jesus schon auferstanden: er braucht die Myrrhe nicht. Die Weisen gehen auf einem anderen Weg heim in ihr Land: die Begegnung mit Jesus verändert unser Leben.

*****

*WJT Köln 2005:*

JP2: Botschaft - "Wir sind gekommen, um ihn anzubeten (um ihm zu huldigen)" (Mt 2,2)
Könige ließen alles hinter sich, um dem Stern zu folgen; unbekannte, gefährliche Reise. Stern zog vor ihnen her: sie ließen sich vom Stern führen - Zeichen Gottes erkennen. Wer Gott folgt, erfährt eine echte und tiefe Freude.

Dieses Kind ist anders: der eingeborene Sohn Gottes. Gott erniedrigt sich, wurde Mensch und starb am Kreuz Dankbarkeit gegenüber Gott?!

Bethlehem: Haus des Brotes Eucharistie. Das Weizenkorn stirbt und bringt Frucht. "Ich bin das Brot des Lebens". Weg der Armut Jesu: von der Krippe bis zur Verlassenheit am Kreuz welche Liebe Gottes zu uns. Derselbe Erlöser der Krippe und des Kreuzes ist in der Eucharistie gegenwärtig. Jesus ist im Fleisch, im Blut, in der Seele und in der Gottheit anwesend Er gibt sich uns als Speise, wir beten ihn an.

Zögere nicht, ihm in der Liebe zu antworten. In der Eucharistie Jesus als unseren Schöpfer, Herrn und Heiland anerkennen und anbeten, symbolisiert durch die drei Gaben:

 - Gold: die königliche Gottheit Jesu das Gold unseres Lebens - die Freiheit darbringen, Gottes Ruf folgen.
 - Weihrauch: Jesus ist Priester des Neuen Bundes Weihrauch unseres Gebets.
 - Myrrhe: Jesus ist Prophet, der durch sein Blut die Menschen mit dem Vater versöhnt dankbare Zuneigung.

Wahre Anbeter Gottes sein - Gott hat die erste Stelle in meinem Leben.

[[http://w2.vatican.va/content/john-paul-ii/de/messages/youth/documents/hf_jp-ii_mes_20040806_xx-world-youth-day.html][cf Botschaft JP2 für WJT Köln 2005]]

*****

*B16 Ansprache / Predigt*

Wenn die Weisen in Bethlehem ankommen, ist ihr äußerer Weg zu Ende, der innere Weg beginnt mit der Anbetung Jesu, welcher ihr ganzes Leben verändert: sie haben sich den neuen König sicher anders vorgestellt. Gott ist anders als wir ihn gewöhnlich uns vorstellen. Gottes Macht ist die wehrlose Macht seiner Liebe, die am Kreuz unterliegt und doch das Göttliche ist, Gottes Reich herauuführt. Gott ist anders wir müssen selbst anders werden, Gottes Art erlernen.

Jesus als König fordert von uns als Gabe: wir selbst, unser Leben. Sie müssen Menschen der Wahrheit, des Rechts, der Güte, des Verzeihens, der Barmherzigkeit werden. Frage: Womit diene ich der Gegenwart Gottes in der Welt? (nicht mehr: was bringt das mir?). Wer sich verliert, der findet sich.

Was bedeutet das für mich? Gott gibt Beispiele. Die große Schar der Heiligen. Sie haben nicht nach ihrem Glück gesucht, sondern erforscht, wie sie sich hingeben können. Sie waren vom Licht Christi getroffen worden. so wird man glücklich, ein Mensch.

Die wahre Revolution kommt von Gott her. Wer Gott weglässt und menschliche Maßstäbe absolut setzt Totalitarismus. Dies macht den Menschen nicht frei, sondern versklavt ihn. Die wahre Revolution geschieht in der radikalen Hinwendung zu Gott.

Das wahre Antlitz Gottes: "Wer mich sieht, sieht den Vater!" (Joh 14,9) Also kein privater Jesus, sondern jener Jesus der Heiligen Schrift, der Kirche. Jesus ist gleichzeitig mit uns und vor uns. Kirche ist eine menschliche Familie UND die Familie Gottes, mit dem Weizen *und* dem Unkraut das ist tröstlich. Jesus hat die Sünder berufen.

[[http://w2.vatican.va/content/benedict-xvi/de/speeches/2005/august/documents/hf_ben-xvi_spe_20050820_vigil-wyd.html][B16 WJT Köln 2005 Ansprache Vigil]]

******

Taufe Jesu (Mk 1,7-11)

Text lesen / versteckte Symbole entschlüsseln / "Du bist mein geliebter Sohn, an dem ich Gefallen gefunden habe." / Offenbarung der göttlichen Dreifaltigkeit.

eigene Taufe: Christen durch Salbung (Öl) - Christus, der Gesalbte. Symbol des Öls: Heilung, dringt ein, bleibt, schützt Haut, ... Hl. Geist, Gottes Gnade dringt ein, bleibt, heilt; macht mich fähig, am Gottesdienst teilzunehmen / teilzuhaben. Geschenk des Glaubens.

*Was ist Gnade?* Cf [[https://www.youtube.com/results?search_query=3mc+gnade][3MC YouTube "Gnade"]]

-----

* Hefteintrag
(Text überlegen!):

Geschichte vom vierten König vorlesen: Bilder einscannen.
Zusammenhang erkennen zwischen Weihnachten und Ostern: sonst verkommt Weihnachten zum "Kitsch".
Warum ist Gott in Jesus Mensch geworden? Um uns zu erlösen. Weihnachten steht nicht für sich allein, sondern ist auf Ostern hingeordnet. Das Hochfest der Epiphanie (Heilige Drei Könige) ist das älteste Fest des Kirchenjahres. Was fällt den Schülern zum Thema "Stern" ein? Hier offenbart sich Gott der ganzen Welt; die Geburt, das Kommen der Hirten - da blieb noch alles irgendwie "geheim".

** RB "Jesus der Mensch" S. 52
Übungsteil 3.12 f.

** RB "Jesus der Christus" S. 53
Übungsteil 3.12 f.
