#+title:      Konflikte lösen
#+date:       [2023-01-03 Di 21:00]
#+filetags:   :kommunikation:zusammenleben:
#+identifier: 20230103T210020

* Kompetenzbeschreibung
[[#A1]] Menschen und ihre Lebensorientierungen - Beziehung verantwortungsvoll gestalten können – zu sich selbst, zu anderen, zur Schöpfung
[[#A1_KB1]] Die Schüler können sich in ihrer Interaktion mit der Mitwelt differenziert wahrnehmen und zu einem wertschätzenden Kommunizieren beitragen.

* AB / UH
[[#A1_AB1]] Kommunikationsformen
- Emotionale Ausdrucksfähigkeit,
- Konflikt- und Streitkultur

* Erarbeitung

** Konflikte lösen
Auf der ersten Impulsseite wird beschrieben, wie der US-amerikanische Psychologe Marshall Rosenberg die Wortwahl und die Sprache (auch der Tonfall) Gespräche analysiert, die zu Streit, Missverständnissen und/oder Konflikten führen können.

Konkretisiert werden seine Gedanken in der Sprache der Giraffen und Wölfe.

Neben der Einteilung der Sätze, kann man auch zusätzlich die vier Sprachebenen von Friedemann Schultz von Thun mit einfließen lassen. Welche von Thuns Sprachebenen würden zwangsläufig zu Wolfs- oder Giraffensprache führen? Dennoch sind viele Aussagen nicht klar in eine der Sprachebenen oder Sprachen einzuteilen, da bei Kommunikation nicht nur Worte, sondern auch Tonfall und Mimik mit einbezogen werden müssen.

Bei der Giraffensprache werden auch oft ICH-Botschaften gesendet, hingegen bei der Wolfssprache oft ein "Du musst ...", "Du sollst ..." oder "Du hast schon wieder ..." an erster Stelle stehen.

Man könnte alltägliche Situationen der Schüler nachspielen lassen und diverse Dialoge in Giraffensprache übersetzen.

Auf der zweiten Impulsseite geht es darum, dass die Schüler ihre Sprachegewohnheiten überdenken und reflektieren.

Weiters wäre anzumerken, dass es keinem gelingt, immer nur Giraffe zu sein, dass Emotionen auch einmal überkochen und eskalieren können. Dann wäre es besonders gut im Anschluss an so einen Streit, dass man diese vier Schritte um eine Giraffe zu werden gut verinnerlicht, um so eine möglichst gute Konfliktlösungsstrategie zu entwickeln.

Peer-Mediation:

An manchen Schulen ist es bereits üblich, dass Schüler aus den höheren Klassen die Ausbildung zum Peer haben. Das bedeutet, dass sich ältere zu Vertrauensschülern entwickeln, die den jüngeren bei Konflikten untereinander aber auch mit Lehrern helfen und unterstützen. Viele unserer Schüler haben keinen Vertrauenslehrer und fühlen sich von Gleichaltrigen oder nur ein wenig älteren Schülern besser verstanden.

Sollte es an Ihrer Schule noch keine Peers geben, wäre es eine Überlegung wert, sich mit den älteren Schülern, dem Betreuungslehrer, SuSa, ... über eine Ausbildungsmöglichkeit zu informieren und die Peer-Mediation an der Schule einzuführen.
