#+title:      [SW01] Jesus ist die Quelle unseres Lebens
#+date:       [2023-07-11 Di 00:28]
#+filetags:   :04:sw01:
#+identifier: 20230711T002844

* Komepetenzbeschreibung
[[#A2]] Menschen und ihre Lebensorientierungen - Sich mit den großen Fragen der Menschen auseinandersetzen können
[[#A2_KB1]] Die Schüler können Perspektiven für ihr Leben entwickeln und  Zukunftspläne entwerfen. 

* AB / UH
[[#A2_UH1]] Sehnsüchte und Lebensträume

* Wiederholung


* Erarbeitung
Jesus = Quelle meines Lebens; das klingt, ist doch sehr abstrakt.

Joh 15:
"Ohne mich könnt ihr nichts tun." - Jesus ist hier sehr eindeutig: NICHTS. So lange wir das nicht verstanden haben, gehen wir am Wesentlichen des christlichen Glaubens vorbei. Wir sind als Geschöpfe total, komplett von Gott abhängig. Gott (Jesus) ist die Quelle unseres Lebens, des Friedens, der Freude, ... 

Quelle = Ursprung eines Flusses; frisch; lebendiges Wasser; ...

Joh 4: Jesus und die Samariterin

Das Wasser ist der Glaube, der ewiges Leben schenkt.

[[file:~/org/notes/2020-09-15-1042 Samariterin.org]]

Das Wort zur Schrift

( zum Evangelium zum 3. Fastensonntag Johannes 4, 5-42)

 

In unserem Kloster Heiligenkreuz befindet sich auf dem Josefsbrunnen im äußeren Stiftshof ein Relief von Giovanni Giuliani, das die Begegnung von Christus und der Samariterin am Jakobsbrunnen zeigt. An den beiden anderen Seiten des Brunnens sieht man zwei andere biblische Szenen: die dürstende Hagar in der Wüste, der ein Engel den rettenden Brunnen zeigt (Gen 21, 17) und Rebekka, die dem Knecht Abrahams zu trinken gibt (Gen 24, 18). In dieser Erinnerung an Abraham, Isaak und Jakob wird uns in den drei abrahamitischen Religionen Judentum, Christentum und Islam das Wasser als Quelle des Lebens und der Barmherzigkeit gezeigt.

 

Gerade im Gespräch zwischen Jesus und der samaritischen Frau wird spürbar, dass es nicht nur um das irdische Wasser geht, sondern um den Glauben. Der Glaube ist das Wasser, das Jesus uns gibt, und das in uns zur sprudelnden Quelle wird, die ewiges Leben schenkt.


Ich sage das gern den Eltern, die bei der Taufe ihres Kindes diesen Evangelientext wählen. "Von euch empfängt euer Kind die Beziehung zu Gott, die ihr selbst empfangen habt. So wie ihr Jesus kennengelernt und zum Glauben gefunden habt, kann auch euer Kind durch euer Vorbild dieses Wasser des Glaubens empfangen und einmal weiterschenken."

 

Das sieht man schon an dieser Frau, der Jesus sich im Gespräch offenbart: Sie behält die Erkenntnis, dass er der Messias ist, nicht für sich, sondern eilt in den Ort, um anderen diese Frohe Botschaft zu verkünden.


Wie ein Brunnen, er immerfort fließt, soll uns unsere Beziehung zu Gott dazu führen, anderen dieses Geschenk des Glaubens und der Liebe anzubieten. Dazu lädt Jesus uns ein.

 

Einer der großen zisterziensischen Mystiker des Mittelalters, der hl. Bernhard von Clairvaux, sagt: "Es ist etwas Großes um die Liebe, ... wenn sie zu ihrem Urquell zurückströmt, um von dem Brunnen zu schöpfen, von dessen Wassern sie immerzu fließt." So will ich mich heute an den Brunnen setzen, um von Jesus die Liebe zu empfangen, die ich dann anderen weitergeben soll. 

Symbol Wasser:
 - Wasser ist Basis des Lebens (so wie Brot); das wissen besonders die Menschen, die in der Wüste wohnen (Zeitgenossen Jesu)
 - Genauso wesentlich ist Jesus schlicht und exklusiv Grundlage des ewigen Lebens.
 - Wasser ist nicht machbar, sondern eine Gabe der Natur - meistens kommt es "von oben". Wenn das Wasser nicht von der Quelle, Teich oder Fluss kommt, ist der Mensch am Ende. 
 - Somit ist Wasser ein Symbol für die Abhängigkeit von Gott.
 - Trinkbares Wasser ist "lebendiges" Wasser, dh das Wasser fließt oder sprudelt aus der Quelle.
 - Wassertrinken ist kein Selbstzweck, sondern dient dem Hervorbringen von Worten, Werken, ... Bei Pflanzen sind dies die Früchte. Die Wirkungen kann man sehen.
 - Kontrast zu Wein: er ist Luxus und zum Feiern da. Beide, Wasser und Wein durchdringen das Lebenwesen komplett. So soll uns auch Gott, der Hl. Geist durchdringen.

Die Frau versteht die Metapher wortwörtlich. Jesus sagt der Frau auf den Kopf zu, wie ihr Privatleben war / ist. Das kann nur Gott, also ist Gott in Jesus anwesend - er ist der Messias. 

Zwischen Juden und Samariter herrscht "Krieg"; sie betrachten sich gegenseitig als Ketzer. Juden (Männer) sprechen daher nicht mit Samariter, und noch weniger mit Frauen in der Öffentlichkeit - schon gar nicht mit einer samaritischen Frau an einem Brunnen. 

Die Frau kommt zu Mittag zum Brunnen, so sonst keiner kommt, da es zu heiß ist. Man schöpft Wasser in der Früh oder am Abend. Brunnen ist ein Ort der Begegnung - und einige Liebesgeschichten begannen an einem Brunnen (Isaak, Jakob). Die Samariterin will also allein sein, vielleicht hat sie etwas zu verbergen. 

* Hefteintrag

