#+title:      [SW35] Hoffnung
#+date:       [2023-07-11 Di 00:53]
#+filetags:   :04:sw35:
#+identifier: 20230711T005338

* Gedanken

** Vieles in unserem Leben lässt uns die Hoffnung verlieren:
- Man arbeitet, zahlt seine Steuern und Abgaben, muss einen Kredit zurückzahlen. Wenn man gerade etwas Geld angespart hat - *peng* das Auto geht kaputt, die Waschmaschine muss repariert werden. Die Betriebskosten werden erhöht und erhöht, die Lebensmittelpreise steigen, Benzin - Strom - Gas werdeb teurer; man sieht, dass die Gemeinde plötzlich Geld hat, um den Vorplatz des Gemeindeamtes zu verschönern, ...
- Wer verdient mehr an meineḿ Gehalt: ich oder der Staat durch die Steuern?
- Hat der Bürger die Möglichkeit, an diesem System etwas zu ändern?
- Haben Wahlen jemals etwas verändert?
- Wo wird man mehr ausgebeutet: im Kapitalismus oder im Kommunismus?
- Gibt es andere politische Systeme, die die Bürger NICHT ausbeuten?
- Kriege, Naturkatastrophen, Streit, ...


** Was nährt unsere Hoffnung?
- Wo sehe ich das Schöne, das Wahre, das Gute?
- "Mein Gott, warum hast du mich verlassen?" (Markus 15,34)
- Sie sieht dem Schmerz und Elend ungeschminkt ins Auge.
- Zugleich drückt die Bibel in verschiedenen Bildern die Hoffnung auf Auferstehung, auf ein "Leben in Fülle", ein "Leben in Gott" aus.
- Die Hoffnung auf Auferstehung bietet keinen Weg an, Not und Ausweglosigkeit, Leiden und Sterben theoretisch zu verstehen. Sie kann aber einen Weg eröffnen, diese zu bestehen – und das vor allem in solidarischer Sorge um diejenigen, die um ihr Leben betrogen werden und vom Leid am meisten betroffen sind.
- Darauf macht Jesus mit seiner überraschenden Erzählung aufmerksam, worauf es am Lebensende ankommt: Es wird nicht gefragt, welche Glaubenssätze man im Kopf, sondern ob man für andere ein Herz hatte (vgl. Matthäus 25,31–46).
- Die christliche Hoffnung geht mit der Weigerung einher, Leid und Unrecht als schicksalhaftes "So ist es eben und so war es immer" hinzunehmen. Sie wirkt wie ein Anti-Resignativum, das vor Bequemlichkeit oder falscher Gelassenheit bewahrt.
- Den Willen Gottes tun?
- ...

* Kompetenzbeschreibung


* AB / UH


* Wiederholung


* Erarbeitung
Suchmaschine im Internet über Liebe?
Wie viele Lieder über Liebe?

Ist die Welt eine Welt der Liebe und Zärtlichkeit?

Lesungen des letzten Sonntags: 18mal Liebe - welche Liebe ist hier gemeint?

Wo siehst du das Elend, Schmerz, Hoffnungslosigkeit?

Was gibt dir Hoffnung?

* Hefteintrag
