#+title:      Toleranz Gleichheit
#+date:       [2023-07-26 Mi 21:37]
#+filetags:   :politics:
#+identifier: 20230726T213751

Interview mit Hans-Georg Maaßen
[[https://www.youtube.com/watch?v=QHlbsKdRaBs]]

* Unterschied Toleranz Gleichheit
Toleranz ist ein Wert und keine Pflicht.

Der Staat muss alle Menschen gleich behandeln.

Toleranz ist ein moralischer Wert. Ich muss nicht alle Menschen gleich behandeln müssen; ich bin nicht in der Pflicht eine bestimmte Frau zu heiraten oder in ein bestimmtes Restaurant zu gehen. Ich darf sagen dürfen: "Ich will nicht mit diesen Leuten..."

Jetzt zwingt mich der Staat zu Dingen, die nicht angehen.

* Meinungsfreiheit vs Propaganda
Ich darf alles sagen, zu allem äußern, ich darf Falsches sagen, ... ich darf aber nicht übel nachreden, nicht verleumden, ich darf nicht beleidigen oder zu Straftaten aufzufordern.

Hass und Hetze - das darf der Staat nicht verbieten: ich darf hassen. Über die Hälfte der Bürger ist der Auffassung, dass man nicht mehr sagen darf, was man will.

Medienpropaganda: Klima, Ukraine, etc. Medien haben besondere Rolle; Pressefreiheit - daher müssen sie wahrheitsgemäß in aller Breite berichten. Die Herrschenden zu kritisieren. Sonst macht Pressefreiheit keinen Sinn. Heute ist Journalismus ein Haktungsjournalismus - dh eine Ideologie. Journalisten kritisieren nicht mehr die Regierung, sondern die Bürger.

