#+title:      Verzeihen
#+date:       [2023-01-03 Di 21:21]
#+filetags:   :barmherzigkeit:leid:liebe:
#+identifier: 20230103T212146

* Kompetenzbeschreibung
[[#A2]] Menschen und ihre Lebensorientierungen - Sich mit den großen Fragen der Menschen auseinandersetzen können

[[#A2_KB1]] Die Schüler können leidvolle Erfahrungen zum Ausdruck bringen und (christliche) Wege des Umgangs mit menschlicher Begrenztheit aufzeigen. 

* AB / UH
[[#A2_AB1]] Angenommen-Sein in Erfahrungen von Trennung, Verlust, Misserfolg und Krankheit

* Wiederholung


* Erarbeitung

Wir sind bereits im Stoff im 3. Kapitel, cf [[id:02_SW15][[SW15] Von Gott sprechen / Impuls: 1+1+1=1]]
Dann werde ich wohl die Planung anpassen? Eher nicht...

** Verzeihen
1 Dieser Arbeitsauftrag ist sehr persönlich und individuell. 
Diese Aufgabe fordert die Schüler*innen heraus, sich in die Lage unserer vier Hauptcharaktere zu versetzen und Lösungsvorschläge zu finden. Die Hauptthemen sind a. Schuld, schlechtes Gewissen b. vergeben, verzeihen c. Schuld und Leid anderer, Nachhaltigkeit d. Regelverletzung, Konsequenzen

2 Auch bei diesem Auftrag sind die Schüler*innen aufgefordert, sich dem Thema Verantwortung zu stellen. Es braucht auch ein gewisses Maß an Vertrauen den anderen gegenüber, um selbst erlebte, ähnliche Situationen im Plenum der Klasse zu erzählen. Dies fällt den Schüler*innen bestimmt leichter, wenn sie vorher in einer Kleingruppe arbeiten könnten.

3 Eine Entschuldigung, die erzwungen oder befohlen wurde, hat meist keine besondere Wirkung auf den Geschädigten. Eine von Herzen kommende Entschuldigung hingegen schon. Sollten ein*e Lehrer*innen zu so einer Situation (Chatverlauf – siehe Kap. 1, S. 14)  dazu kommen, versuchen diese die Schüler*innen mittels Gespräche zu solchen Entschuldigungen hinzuführen. Wie solche dann beim „Empfänger“ ankommt, kann, selbst bei ehrlich gemeinten Entschuldigungen, ganz unterschiedlich sein: manche brauchen ein wenig länger, um zu verzeihen, manchmal geht es auch ganz schnell.
