#+title:      Was gibt es Neues
#+date:       [2023-09-25 Mo 20:41]
#+filetags:   :emacs:jesus:
#+identifier: 20230925T204119
#+DESCRIPTION: This text was generated using the After Dark post archetype.
#+HUGO_CATEGORIES: Emacs
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_BASE_DIR: /home/matthias/flying-toasters/
#+AUTHOR: Matthias Fuchs

* Schule
Anders als zum Ende des letzten Schuljahres angekündigt wird es dieses Jahr 2023/24 nur zwei statt drei 1. Klassen geben. Da sich zusätzlich in meiner anderen Schule sehr viele katholische Schüler vom RU abgemeldet haben, bleiben dort nur mehr vier (!) Schüler übrig. Das ergibt gerade einmal eine Stunde pro Woche - für eine Schule mit über 200 Schülern. Organisatorisch heißt dies: eine Doppelstunde alle zwei Wochen.

Ich habe laut Vertrag Anspruch auf eine volle Lehrverpflichtung, meine "Chefin" kümmert sich darum. Ich könnte in meiner Stammschule nachfragen, ob es eventuell für mich noch eine Stunde gäbe. Was ich mir kaum vorstellen kann - aber fragen kostet nichts.

Natürlich bedeutet dies ein wenig an finanziellen Einbußen. Vielmehr jedoch schmerzt das für die Moral - so viel Hingabe - kaum Retour. Im Gegenteil: alle Schüler vom vorigen Jahr haben sich abgemeldet. Das tut weh. Das spürt man keine Anerkennung, Dankbarkeit, ... was bleibt ist der Fade Geschmack von Gleichgültigkeit. Viele Christen werden oder sind gleichgültig.

* Jesus
Mein geistliches Leben bedarf dringend einer Neuorientierung und Vertiefung, sonst verhungere ich innerlich. Mehr Gebet, intensiveres Gebet, Bibellesen; geistliche Lektüre (B16, Romano Guardini, etc. - in meiner Bibliothek wimmelt es von guten Büchern).

* Update
Wie schnell kann es gehen, und unsere Welt kann sich "ändern". Gestern noch war ich in Sorge um unsere finanzielle Situation. Und heute hat mich unsere Direktorin während des Unterrichts herausgeholt und mir eine freudige Nachricht überbracht. Frau Steinberger (Schulreferentin für Hallein) hat für mich eine Stunde in einer Volksschule gefunden: GTS, am Mittwoch von 13h55-14h45.

Was zeigt mir das? Wenn ich meine Situation in Gottes Hände lege (und in jene meiner Vorgesetzten), dann wendet es sich zum Guten (vgl Römerbrief).

Mittlerweile sitze ich in der Kletterhalle Salzburg Nord und schreibe diesen Text. Gabriel beginnt seinen Kletterkurs in diesem Schuljahr. Leider hat Gabriel wieder einmal Schulmaterial vergessen und musste es in der Schule holen fahren. Ich hoffe, er bemüht sich in Zukunft besser, und bringt das nötige "Zeug" nach Hause.

Aber eigentlich hat dieses Schuljahr für Gabriel wesentlich positiver begonnen als das erste Schuljahr in der MS.

* Wie kann ich den Copyright-Eintrag in jedem Post ändern?
Das muss ich noch nachforschen? Gibt es wo eine post-Template dafür? Habe es gefunden: ich habe die Datei 'config.toml' geändert und beim Copyright-Eintrag (template?) das Jahr hinzugefügt.

So, jetzt wird dieser Eintrag gepostet.


