#+title:      [SW31] Ich gehöre dazu / ein gemeinsamer Glaube
#+date:       [2023-06-19 Mo 14:50]
#+filetags:   :01:sw31:
#+identifier: 20230619T145033


* Kompetenzbeschreibung
[[#B4]] Gelehrte und gelebte Bezugsreligion: Kirchliche Grundvollzüge kennen und religiös-spirituelle Ausdrucksformen gestalten können
[[#B4_KB2]] Die Schülerinnen und Schüler können Taufe und Eucharistie als Ausdruck der Zugehörigkeit zur kirchlichen Gemeinschaft verstehen.

* AB / UH 
[[#B4_AB2]] Glaubensbekenntis

* Wiederholung

*Methode: Glaubensaussagen deuten*

Glaubensaussagen deuten zu können ist ein wichtiger Schritt, um mit dem eigenen Glauben in seiner gesamten Dimension umgehen zu können.

Der Glaube durchläuft im Laufe eines Lebens verschiedene Glaubensstufen. /James William Fowler/ teilt diese Entwicklung in sechs Phasen auf. Schüler*innen befinden sich seiner Theorie zu folge noch in der zweiten Stufe, dem mystisch- wörtlicher Glaube. Das Kind kann hier seinen Glauben beschreiben. Das geschieht vor allem bildhaft durch Aussagen, wie z.B.: "Gott ist oben, das Böse ist unten". Auch Erzählungen sind in dieser Stufe von großer Bedeutung. Immer mehr versuchen sie die eigene Phantasie an die Realität anzupassen. So nimmt der Realitätssinn der Kinder stark zu, aber auch die ersten Zweifel über Glaubensaussagen treten auf. Dadurch erhöhen sich die Schwierigkeiten, den Glauben zu verstehen.

* Erarbeitung
1 Im ersten Schritt sollen Begriffe die nicht verstanden werden mit Hilfe der Lehrperson, eines Lexikons oder des Internets erklärt werden. In diesem Beispiel ist es der Begriff "Auferstehung".

2 Im zweiten Schritt ist in der Methodik wichtig, da die eigenen Vorstellungen zum Begriff bewusst gemacht werden sollen. Die eigenen Überlegungen werden im Anschluss mit den Vorstellungen anderer Menschen in Verbindung gebracht. Wichtig ist hier, dass es keine falschen Aussagen gibt, da hier die persönliche Erfahrung bzw. Vorstellung erforscht wird.
Im Beispiel am Begriff "Auferstehung" wird hier Hoffnung und Trost über den Tod der Oma angeführt.

3 Der dritte Schritt dient zum Austausch mit den Klassenkollegen. Die Erfahrungen/Vorstellungen der anderen kann eine neue Perspektive eröffnen. Auch die Vorstellungen die stark von der eigenen Vorstellung abweichen sind sehr hilfreich, um die Bedeutung der Glaubensaussage weiterzuentwickeln. Im Beispiel wird hier die bildliche Vorstellung von "davonfliegenden Toten" aufgegriffen und dem Leben nach dem Tod eine neue Dimension hinzugefügt.

4 Der vierte Schritt ist sehr persönlich und individuell. Die Schüler*innen sollen auf kreative Art und Weise ihre Deutung zum Ausdruck bringen.

* Hefteintrag
