#+title:      [SW05] Das große Durcheinander
#+date:       [2023-06-19 Mo 07:42]
#+filetags:   :01:sw05:
#+identifier: 20230619T074226


* Kompetenzbeschreibung
[[#A1]] Menschen und ihre Lebensorientierungen: Beziehung verantwortungsvoll gestalten können – zu sich selbst, zu anderen, zur Schöpfung
[[#A1_KB1]] Die Schülerinnen und Schüler können sich in ihrer gottgeschenkten Einzigartigkeit wahrnehmen und wissen um die Bedeutung von (Selbst-) Vertrauen für ein gelingendes (Zusammen-)Leben.


* AB / UH
[[#A1_UH1]] Selbstvertrauen

* Wiederholung
[cite:@Ceram1957]

* Erarbeitung
S. 18:
Chaos-Situationen in der Klasse...

Lösungsvorschläge für die Arbeitsaufträge:

1 Dieser Arbeitsauftrag ist sehr individuell und persönlich. Er zielt auf die Erfahrungen und Erzählungen der Kinder ab. Für gewöhnlich finden sie zahlreiche Beispiele und auch gute Begründungen und Reflexionen für die verschiedenen Gründe hinter Konflikten. Auch zeigen sie nicht selten (bereits in der Volksschule erworbene) Kompetenzen im Bereich der Konfliktlösung. Zunächst geht es hier vor allem darum, die Schüler*innen erzählen zu lassen und Beispiele zu finden, die im Weiteren bearbeitet werden können.

2 Im Anschluss an Arbeitsauftrag 1 können verschiedene Wege der Konfliktlösung gesammelt und gewichtet bzw. auf ihre Tauglichkeit in unterschiedlichen Situationen befragt werden. Die Beispiele aus AA1 können dabei als Vorlage dienen. Sollten hier wenige brauchbare Beispiele genannt werden, könnten als Möglichkeiten der Streit- und Konfliktlösung ins Spiel gebracht werden: "Aus dem Weg gehen", "Eine unbeteiligte dritte Person suchen, die moderieren kann", "Hilfe holen", "Gras über die Sache wachsen lassen", "ausdiskutieren", "einander ausreden lassen und kommentarlos zuhören" etc.

3 Mit diesem Arbeitsauftrag wird der Übergang zum sachbezogenen Teil des Kapitels eingeleitet, der sich mit Regeln, Normen und Gesetzen beschäftigt. Dahinter steckt der Gedanke, dass Regeln oft nicht (nur) einschränken, sondern Freiheit und Gemeinschaft letztlich erst ermöglichen (siehe auch 1.3). Bevor diese Thematik im Sachbezug aufgegriffen wird, können für die auf dieser Seite genannten Beispiele versuchsweise Regeln formuliert werden – etwa: "Ein Fußballspiel braucht gemeinsame Regeln, auf die man sich vorher einigt: Der Ball darf nur mit dem Fuß gespielt werden, ..." oder "Expertinnen und Experten sollen beurteilen, welche Inhalte von Filmen für Kinder geeignet sind und zu ihrem Schutz festlegen, ab welchem Alter man sie sehen darf" etc. Konkrete Beispiele liefert auch die Folgeseite (1.6), die lebensbezogene Erfahrungen aus 1.5 auf konkrete Regeln, Normen und Gesetze spiegelt.


** NT
Heilige Schrift - 2 Teile (AT / NT) Kontinuität / Neubeginn.
Was ist die Bibel? Das Besondere? Eine christliche Verkündigung kann es ohne das AT nicht geben. Ohne das AT lässt sich das NT nicht verstehen. Für die ersten Christen war die "Heilige Schrift" das hebräische AT. Sie verkündeten Jesus als den Messias / Christus durch die Bibel (=AT) und von ihr her. Ab dem 2. Jhdt als Gegenreaktion auf Irrlehren: Kirche legt 2teilige Bibel als Hl. Schrift fest. "Alt" bedeutet NICHT "überholt"! "Neuer Bund" einmal in Jer 31,31 / Paulus "Alter Bund" in 2 Kor 3,14  Korrelationspaar. Lassen sich im Bezug aufeinander verstehen. Alt geht neu voraus! Das Neue lässt sich ohne das Alte nicht verstehen. Im Lichte des Neuen lassen sich bestimmte Ereignisse des Alten erst "richtig" erfassen.

(Göttliche) Inspiration
Die Heilige Schrift ist Gottes Wort in Menschenwort.
Wie ist die Bibel entstanden?
Mündliche Überlieferung, schriftliche Überlieferung:
AT: ab ca. 1000 v. Chr. (Frühkönigszeit) Beginn der Verschriftlichung
NT: ab 50 n. Chr.; Briefe (1. Thess), Evangelien (50-70); Offb (100)

Was ist für die Kinder wichtig zu wissen? Was müssen sie wissen (Basiswissen)?
Wie bringe ich das Thema den Kindern nahe?

********

Hefteintrag:
Überlieferung
Gott offenbart sich durch Wort und Tat - wechselseitiger Bezug
Tradition ohne Tradition keine Heilige Schrift dh Schrift ja / Tradition nein ist eigentlich Unfug.

-----

Entstehung des NT (Lehrfilm)

Bedeutung der Bibel, ein Buch aus Büchern; Entstehungszeitraum: ca 1200 bis 1400 Jahren.

Aufbau: AT / NT; 2 Quellen Theorie für das NT.  nachprüfen: was ist *aktueller* Stand der Wissenschaft?

Arbeitsblätter - Auswahl!

-----

Verklärung: Vergleich der Texte in Mt, Mk, Lk.

* Hefteintrag
 
