#+title:      Missverständnis
#+date:       [2023-01-03 Di 20:56]
#+filetags:   :kommunikation:zusammenleben:
#+identifier: 20230103T205648

* Das war ein Missverständnis
1 Die Schüler*innen sollen anhand des „Vier-Ohren-Modells“ von Schulz von Thun folgende 4 Ebenen herausarbeiten:

    - Sachebene: Hier wäre völlig trocken anzumerken, dass in Lisas Zimmer tatsächlich großes Chaos herrscht
    - Selbstoffenbarung: Lisas Mutter verrät mit dieser Aussage, das sie sich in so einem Chaos wohl nicht mehr wohlfühlen würde und es ihr selbst zu unordentlich wäre
    - Beziehung: Hier ist von einer klassischen Mutter/Tochterbeziehung auszugehen. Die Mutter hat das Sagen und auch das Recht Kritik an der Tochter bzw. ihrem Sinn für Ordnung anzubringen.
    - Apell/ Aufforderung: Lisas Mutter möchte, dass Lisa sofort ihr Zimmer in Ordnung bringt.
      
2 Dieser Arbeitsauftrag wird von den Schülern individuell bearbeitet. Klar ist, dass Lisas Mutter möchte, dass das Zimmer aufgeräumt wird. Als Lösungsmöglichkeit käme folgender Satz in Frage: "Lisa, bitte räum dein Zimmer auf!" oder "Ich möchte, dass du bis heute Abend Ordnung in deinem Zimmer gemacht hast!"

3 Hier sind ausschließlich individuelle Antworten der Schülen möglich.

4 Aus Aufgabe 3 ergeben sich etliche Beispiele, die die Lehrkraft mit den Schülern*innen gut durcharbeiten kann.

Beispiel:

Lehrer zu Schüler*in: "Du warst auch schon einmal besser in Biologie."

   - Sachebene: Du warst schon einmal besser.
   - Selbstoffenbarung: Ich mach mir Sorgen um dich, weil ich einen Leistungsabfall bemerke und nicht genau weiß, ob es am Stoff, an mir als Lehrer*in oder an einer Überforderung liegt
   - Beziehungsebene: Lehrer – Schülerbeziehung die intakt ist
   - Apell/Aufforderung: Lern für den nächsten Test mehr.

5 Die Schüler*innen sollen über eine "gelungene" Diskussion zu Erkenntnis kommen, dass es face to face schwieriger ist, Menschen etwas direkt zu sagen. Auch böse Worte kommen, über ein Smartphone, ... leichter "über die Lippen". Die Hemmschwelle für Schimpfworte, usw. am Handy ist wesentlich geringer. Außerdem Fallen bei einem Diskurs am Handy viele Teile der Kommunikation, wie Gestik, Mimik, Ton, ... weg. Daher kommt es bei geschriebenen Worten auch häufiger zu Missverständnissen.
