#+title:      Elternsprechtag
#+date:       [2023-04-19 Mi 14:29]
#+filetags:   :schule:
#+identifier: 20230419T142927
#+CATEGORY: golling

Folgende Eltern haben sich angemeldet:

* Yagmur Durukan (Dalya Durukan, 2b) 
<2023-04-19 Mi 15:30-15:40>
Geht nicht in RU

Kommt wegen Physik, passt alles; Test kommt noch.

* Mladen Matkic (Mufidin Matkic, 2c) 
<2023-04-19 Mi 15:40-15:50>
Geht nicht in RU

* Stefanie Kurz (Oliver Kurz, 2a) 
<2023-04-19 Mi 15:50-16:00>
alles okay, ein wenig stiller; könnte etwas mehr mitarbeiten.

* Anna Prömer (Serah Prömer, 2c) 
<2023-04-19 Mi 16:40-16:50>
alles okay; zeichnet sehr viel während des Unterrichts, nimmt sonst kaum am Geschehen teil; sie wird wohl später einen künstlerischen Beruf, in der Grafik, Mode, ... ergreifen, oder?

Papa ist Künstler, Serah wird in diese Richtung sicher was machen. Haben noch über RU, Bibel, Nahtoderfahrungen, Rückbesinnung, Stille, etc gesprochen.

* Frau Keser (Leon Keser, 3b)
<2023-04-19 Mi 16:15-16:25>
Leon ist "auf einem guten Weg".

Leider haben sich die Burschen letzten Freitag beim Vorstellungsgottesdienst sehr schlecht in der Kirche benommen (gaben sich gegenseitig Knackwatschen, etc). Als es zur Kommunion kam, wussten die Burschen zuerst nicht, worum es geht. Sie stellten sich dann an und sagten bei der Kommunion "Der Friede sei mit dir." Sie zeigten keinerlei Respekt während des Gottesdienstes. Eigentlich sollte man (auch als Pfarre) darüber nachdenken, gewissen Burschen die Zulassung zur Firmung verweigern.

Das tut mir sehr leid. Ich sehe als einen Auftrag für den RU - und werde Eucharistie, Beichte und Formung inhaltlich mehr thematisieren im RU.

* Petra Seling (Valerian Seling, 1b)
<2023-04-19 Mi 17:00-17:10>
Äußerst unruhig; "always on the move"; ...
Wie kann man ihm helfen, ruhiger und aufmerksamer zu sein?



* Barbara Krallinger (Thomas Krallinger, 3b) 
<2023-04-19 Mi 17:20-17:30>
Thomas ist "auf dem Weg der Besserung"; auch seine Mitschüler haben bemerkt, dass sich die Situation merklich verbessert hat. Ich will ihn ermutigen, sich weiterhin zu bemühen und diesen Weg beizubehalten.

(Könnte es sein, dass Frau Krallinger auf den Vorstellungsgottesdienst zu sprechen kommt?)
