#+title:      [SW29] Die Gemeinschaft der Glaubenden
#+date:       [2023-06-19 Mo 14:49]
#+filetags:   :01:sw29:
#+identifier: 20230619T144913


* Kompetenzbeschreibung
[[#B4]] Gelehrte und gelebte Bezugsreligion: Kirchliche Grundvollzüge kennen und religiös-spirituelle Ausdrucksformen gestalten können
[[#B4_KB2]] Die Schülerinnen und Schüler können Taufe und Eucharistie als Ausdruck der Zugehörigkeit zur kirchlichen Gemeinschaft verstehen.

* AB / UH 
[[#B4_UH2]] Zeichen und Formen von Zugehörigkeit,

* Wiederholung


* Erarbeitung
1 Dieser Arbeitsauftrag soll die Schüler*innen anregen über ihre eigene Heimat zu reflektieren. Gebäude, die die Kirche als Gemeinschaft zeigen, können neben Kirchen, Kapellen und Pfarrzentren noch Krankenhäuser, Pfarrkindergarten, kirchlich geführte Jugendtreffs, Altenheime, Klöster, Notschlafstellen, etc. sein.

2 Dieser Arbeitsauftrag ist trotz Sachbezug sehr persönlich und individuell. Je nach kirchlicher Sozialisation fällt es den Schüler*innen schwerer oder leichter Orte zu finden, in der Kirche als Gemeinschaft gelebt wird. Kirchliche Einrichtungen können sein: Jungschar-, der Ministrantengruppe, Jugendtreff, Firmgruppen, Pfarrkindergarten, Klöster, Hilfseinrichtungen, Pflegedienste (z.B. Caritas), etc.

3 Dieser Arbeitsauftrag dient zur Vertiefung und persönlichen Reflexion des vorangegangenen Arbeitsauftrages 2. Hier wird der Schwerpunkt aber auf die Einrichtungen gelegt die der Altersgruppe der Schüler*innen entsprechen. Ministranten- und Jungschargruppen, Jugendtreffs oder sonstige Gruppen in der Pfarre/Diözese sollen unter die Lupe genommen werden.

4 Die auf den Bildern dargestellten Tätigkeiten bilden die drei Grundvollzüge der Kirche ab: Liturgia – Martyria – Diakonia.

 - Im ersten Bild wird ein Gottesdienst *(Liturgia)* abgebildet.
   Im ersten Bild sehen wir Menschen, die sich im Gottesdienst versammeln und gemeinsam ihren Gottesdienst feiern. Hier wird die Gemeinschaft sichtbar, da jeder am Gottesdienst teilnehmen darf.
   
 - Im Zweiten Bild handelt es sich in der Bibel-Lesegruppe um Menschen, die Zeugnis von ihrem Glauben geben. *(Martyria)*
   Im zweiten Bild sehen wir, wie sich Menschen treffen, um gemeinsam über die Texte in der Bibel zu sprechen. Sie tauschen ihre Erfahrungen aus und geben Zeugnis über ihren Glauben.
   
 - Das dritte Bild nimmt den Dienst am Nächsten, an den Notleidenden *(Diakonia)*, in den Blick. Eine Beschreibung der drei Grundvollzüge könnte so aussehen:
   Im dritten Bild sehen wir Menschen, die Essen bekommen haben. Für Christen ist es wichtig, nicht auf die Armen und Notleidenden Menschen zu vergessen und sich um sie zu kümmern.

   
* Hefteintrag
ein text 
