#+title:      Pädagogische Konferenz
#+date:       [2023-01-16 Mo 16:08]
#+filetags:   :konferenz:
#+identifier: 20230116T160833
* IKM+
wir liegen genau in der Mitte (Durchschnitt Ö) in D, M, ud E ...

cf Ergebnisse nach Klassen.

nach Geschlecht...

** Stellungnahmen
Hannes: im "Pflichtschullehrer" (Zeitschrift) gab es auch kritische Stimmen dazu.

* Umfrage: Wohlbefinden an der Schule 
Hochgestochene Fragen, die ein 10jähriger nicht versteht. (Manuela, Julia)

Wir werden nicht daran teilnehmen, da die Fragen nicht altersgerecht sind. (Birgit)

Wolfi: vorgegaukelte Anonymität; kontraproduktiv zum DG (Code, Klasse, etc) ... verweigert den Test für die Klasse.

Fr. Heinrich rückmelden: weder kindgerecht noch anonym.

Gertraud E.: gut, diese Reaktion; gute Medienerziehung.

* Anmeldung Mittelschule
Wer will noch dabei sein mit Mirjam? Christian - nix dagegen.

Lesefertigkeit, Legosteine, 

* KV nächstes Schuljahr 2023 / 2024
1a MINT: Mirjam Seiwald
1b Regelklasse: Gertraud Viertbauer
1c (fehlt noch)

* Blackout Plan + Krisenplan
zB Terrorist.
Turnhalle als Auffanglager bei Zug-Gestrandenen

Bei atomarer Kata... Kind in der Schule? Nach Hause?
Wann werden die Kinder abgeholt? Von wem?

Krisenteam: bitte melden!

* Allfälliges

** Verletzung Ebu
Schadensgeld + Anwalt

Mittelhandknochen gebrochen (vom kleinen Finger)
Wo war der Lehrer?

Wir erteilen keine Auskunft; erst wenn das Land an uns herantritt.

Tandiverdis wissen genau was sie wollen; sie wollen Ebu länger krank melden, damit das Schmerzensgeld höher ist. Geklagt ist Moritz; Wolfi war draußen, daher kein Dienstversehen.

** Moritz Gsenger
hat ihn verletzt

leichte, schwerer oder keine Körperverletzung, wurde nix angekreuzt
Anwaltschreiben kostet viel, auch für Hr. Tandiverdi.

** Wir ...
sind immer mit einem Fuß im illegalen Bereich.

Ansammlungen beim Klo; mit Essen auf dem Klo; sagt man was, ist man der Buh-Mann.

Wenn man bei Pausenaufsicht in einer Klasse ist und es passiert woanders, ist man dafür nicht belangbar.


** Förderstunden
1 Stunde mehr pro Klasse - IKT als Vorbereitung auf ECL Prüfung. als MDL geltend machen; Schüler haben massive Bedürfnisse aufgrund von Covid

** Faschingsdienstag 21.2.2023
Faschingsdienstag: wer? was? Wenn nix, dann ist Unterricht nach Stundenplan. (nicht mehr wie der Skitag)

Oder lieber gar nix? Alternative ein Wandertag - manche ja, manche nicht; Supplierplan. Entweder alle Fasching, oder alle Fasching.

Ersatzprogramm: Bowling Kegeln.

Es gibt ein Programm, und sonst nix!
Wenn Programm, dann etwas für die gesamte Klasse - aus.

Erwin: seit 50 Jahren hats geklappt; an S denken; uns nicht von jenen herunterreißen lassen, die nichts tun wollen. Sonst gehts sich blad nix mehr aus.

Irmi: weil Corona muss ich nicht zwanghaft alles nachholen. Schwerpunkt Unterricht.

Birgit: selbst kein Fan; für Kinder ists lustig, sich zu verkleiden. Krapfen kommen sicher. Bachreinlift gibts nimmer;

Ideen sammeln und abstimmen.

- Winterolympiade 7 Disziplinen, Schneeball weitwerfen, Wissen, Geschicklichkeit, ... (Christian) - 2 Stunden Unterricht; 2 Stunden Wettbewerb, Preisverleihung + Krapfen.
  2 Stunden Unterricht: nicht gut.
- Skifahren (bleibt die Hälfte daheim)
- Eislaufen
- Freistunde für Masken-Premiere; Spielen; ...
- Halbtagswandertag
- normaler Unterricht

Eher Entscheidung Klassenweise + jeder KV sucht sich Begleitpersonen.

Drei Dinge
a nix 4 
b Klassenweise 15 xxx
c Schulprogramm (Olympiade) 2 
d Dani und 2c macht nix!

13H30 Jause in der Schule.

* Notenkonferenz 6.2.2023
Mitarbeitergespräche noch einige fehlen.

Umfrage: Click und Check Polizei 3. Klassen 6.-8. Stunde eine Stunde pro Klasse

* Notenkonferenz
Nina, Christoph, Bernhard, Daniela für Jause
Geschirr mitnehmen

Schülerliga: Dressen nicht austeilen, es gehen drei Hosen ab.

Ein Lehrer Laptop bleibt übrig; ... wer hat Interesse? für die neuen ersten Klassen kommen neue Geräte + Lehrer dieser Klassen (nur KVs?) (Julia)

Mathematik die Zeit vergeht zu schnell; einmal eine Doppelstunde in den Hauptfächern (D, E nud M). (Julia)

In den dritten und vierten Klassen klappt das besser; in der ersten Klassen ists oft zuviel. (Bernhard)

Irmi: hängt von Klasse ab; in Mathematik - es sinkt oft die Konzentration; hängt auch von Stoff ab.

Hannes: Fällt der Tag mir den Doppelstunden aus, dann fehlt viel. Rentiert sich nicht;

Irmi: Hauptfach und Nebenfach, gleicher Lehrer; ausprobieren und rückmelden.

Zeichenwettbewerb Raika: wie sieht Zusammenhalt aus? (Barbara)

Nina: Mozartensemble: 27.1.2023, cf Kalender (1. + 2. Klassen)

Sarah: Film Zauberflöte (2.2.; oder Nachmittag) Kino Hallein; 3. + 4. Klassen; Dienstag Nachmittag 7.2. pro Klasse zwei Lehrer; ...


* Danke für alles!




