#+title:      [SW39] Die Erwartung des Messias
#+date:       [2023-06-19 Mo 21:48]
#+filetags:   :02:sw39:
#+identifier: 20230619T214855


* Kompetenzbeschreibung
[[#C6]] Religiöse und weltanschauliche Vielfalt in Gesellschaft und Kultur - Unterschiedlichen Lebensweisen und Glaubensformen reflexiv begegnen können

[[#C6_KB1]] Die Schüler können Grundzüge des Judentums beschreiben und die Nähe des Christentums zum Judentum darlegen.

* AB / UH
[[#C6_UH1]] Messiaserwartung

* Wiederholung


* Erarbeitung
[[https://www.youcat.org/de/credopedia/minicat/dreifaltigkeitssonntag/][Gott ist die Liebe | Minicat]]
Jedes Jahr feiert die Kirche am Sonntag nach Pfingsten den Dreifaltigkeitssonntag. Warum ist das so? Mit Pfingsten ist das Heilswerk der Erlösung abgeschlossen und ebenso ist mit der Offenbarung der Dreifaltigkeit Gottes die Offenbarung als Ganze abgeschlossen. Gottes Wille ist es, uns das innerste Wesen seiner selbst kundzutun. Warum? Weil Gott die Liebe ist. Wer liebt, der will, dass der andere ihn ganz und gar erkennt im tiefsten Innern seines Wesens. Die Selbstoffenbarung Gottes, in der er uns das Geheimnis seines Wesens kundtun will, ist im letzten die Offenbarung, dass Gott dreifaltig ist. Weil jeder von uns gerufen ist mit den drei Personen dieses einen Gottes in eine ganz persönliche Beziehung einzutreten.

[...]

Deswegen kann man nicht das Fest der Dreifaltigkeit feiern, ohne zu verstehen, dass die Dreifaltigkeit sich uns offenbart hat als ein unendlich barmherziger Vater, der seinen eigenen Sohn für uns in den Tod hineingegeben hat und dieser Sohn selbst aus Liebe für uns gestorben ist, damit der Heilige Geist kommen und in uns wohnen kann und uns hinein nimmt in diese ewige Gemeinschaft brennender Liebe.

Bibelstellen (Lesejahr C?):
- Sprüche 8,22-31
- Psalm 8,4-9
- Römer 5,1-5
- Joh 16,12-15

Zusätzliche Bibelstellen:
- Gen 18,1-15
- Ex 3,13ff

[[file:Schule_Themen/dreifaltigkeit.org][dreifaltigkeit]]

Videos:
 [[https://www.youtube.com/watch?v=a2I1-8SQRZw][Wer thront auf dem Gnadenstuhl - Hermit & Hog Via Alpina Sacra 35 - YouTube]]
 [[https://www.youtube.com/watch?v=mgYk5RrlkFU][Welche Bilder gibt es von der Heiligen Dreifaltigkeit? (3MC 19) - YouTube]]
 [[https://www.youtube.com/watch?v=FlDN-FIkyPQ][Dreifaltigkeit - Tauhid [At-Tariq 11 / Islam & Christentum] - YouTube]]
 [[https://www.youtube.com/watch?v=d3RZ2fXVZdM][Wie kann man sich die Dreifaltigkeit vorstellen?* (3MC 18) - YouTube]]
 [[https://www.youtube.com/watch?v=RiGM27ntef4][Wie kann man den Glauben an die Dreifaltigkeit zusammenfassen? (3MC 17) - YouTube]]

* Hefteintrag

