#+title:      Städte Zivilisation
#+date:       [2023-03-07 Di 15:49]
#+filetags:   :geschichte:mensch:
#+identifier: 20230307T154954



Oder: arte Doku Städte, Wiege der Zivilisation.
Türkei, Göbekli Tepe (vor ca 12.000 Jahren!):

Im Hochland von Anatolien bereitete sich eine der größten Revolutionen der Geschichte vor: Die Menschen entdeckten eine neue Lebensform.

Jahrtausendelang waren die Ersten unserer Art in kleinen Gruppen durch die Lande gestreift. Dann wurde alles anders – nicht von heute auf morgen, aber im Lauf einer langen Umbruchphase, geprägt von Entdeckungen und technischen Neuerungen.

Die Menschen ließen sich nieder, züchteten Tiere und bauten Getreide an. Aus Ton brannten sie Gefäße, in denen sie Vorräte lagern konnten, das mühsame Leben »von der Hand in den Mund« hatte für viele ein Ende. Bis vor wenigen Jahrzehnten lautete die gängige Theorie der Archäologen: Dieser radikale Umbruch – die so genannte Neolitische Revolution (von neos = neu und lithos = Stein) habe um 8000 v. Chr. im östlichen Mittelmeerraum (Syrien, Libanon, Israel) begonnen.

Doch neue Ausgrabungen in Anatolien zeigen etwas anderes. Schon vor 12000 Jahren sammelten sich erste Gruppen von Menschen auf dem »Nabelberg« (Göbekli Tepe) im Südosten der heutigen Türkei. Nach Schätzungen von Archäologen waren mindestens 500 (starke) Männer nötig, um die dortige Tempelanlage zu bauen, die älteste der Welt. Beim Schleppen der riesigen Brocken, die sie für unbekannte Götter zu Pfeilern aufrichteten und mit rätselhaften Piktogrammen versahen, müssen sie auch entdeckt haben: Gemeinsam sind wir stärker! 

[[https://de.wikipedia.org/wiki/G%C3%B6bekli_Tepe]]

Rund 2000 Jahre später war es dann soweit für den großen Entwicklungsschritt: Unweit von Göbekli Tepe, südöstlich der heutigen türkischen Stadt Konya, entstand Catal Hüyük – die erste Großstadt der Welt mit der für damalige Verhältnisse unglaublichen Zahl von 5000 Bewohnern. Göbekli Tepe und Catal Hüyük, beide entdeckt in den 1960er-Jahren, zum Teil aber erst intensiv erforscht seit 1995, gehören zu den größten Funden in der Geschichte der Archäologie. Beide gelten als die Entstehungsorte der menschlichen Kultur; von ihnen aus verbreitete sich die neue Lebensform in alle Himmelsrichtungen.

Ur (erste Stadt?), ...

Städte müssen ihre Bewohner ernähren können.
Umstellung auf Ackerbau: hatte zuerst schlechte Auswirkungen auf Körperbau, Gesundheit.
kleinerer Wuchs, schlechte Zähne, schlechte Gelenke, ... Warum?  Trotzdem: welche Vorteile?

Das erste Mal: Getreide gezüchtet!

Landwirtschaft war unentbehrlich für die Entwicklung der Städte, der Entstehung der Zivilisation. Städte - Sesshaftigkeit - Zuhause. 
