#+title:      Sinn der Arbeit
#+date:       [2023-01-03 Di 22:34]
#+filetags:   :arbeit:mensch:
#+identifier: 20230103T223442

* Komepetenzbeschreibung
[[#A2]] Menschen und ihre Lebensorientierungen - Sich mit den großen Fragen der Menschen auseinandersetzen können
[[#A2_KB1]] Die Schüler können Perspektiven für ihr Leben entwickeln und  Zukunftspläne entwerfen. 

* AB / UH
[[#A2_UH1]] persönliche und berufliche Ziele

* Wiederholung


* Erarbeitung
Warum arbeitet der Mensch? Nur wg des Geldes; oder weil es zur Natur (?) des Menschen gehört? Cf Relibuch "Komm mit", ab S. 72 (kopieren).

Gen 3 sagt uns, dass ab dem Sündenfall die Arbeit mühsam ist - und vorher? Vielleicht soll ich es anders verstehen: ausgehend von der Erfahrung einer mühsamen Arbeit stellt sich der Mensch, warum das so ist. Hm, das scheint mir zu leicht und nicht gerade ein tiefsinniger Ansatz.

Die Arbeit ist eine Pflicht des Menschen: Auftrag des Schöpfers, Erhalt der Familie, Entfaltung der eigenen Menschlichkeit. Wir sind Erben der Arbeit von Generationen und zugleich Gestalter der Zukunft für all die Menschen, die nach uns leben werden.

Die Arbeit bestärkt den Menschen - nach dem Bild Gottes erschaffen - in der Tiefe seiner Identität. Der Mensch ist der Treuhänder des Universums. In seinem eigenen Wirken ist der Mensch dazu berufen, das Antlitz Gottes widerzuspiegeln.

DoCat:
[[file:~/Dokumente/DC_Studyguide_Deu_7.pdf][Eine Wirtschaft, die den Menschen dient]]

[[file:~/Dokumente/DC_Studyguide_Deu_6.pdf]]

Geht uns die Arbeit aus?

[[https://jugend-und-bildung.de/fileadmin/user_upload_sozialpolitik/PDFs/schaubild-geht-uns-die-arbeit-aus.pdf]]

[[https://jugend-und-bildung.de/fileadmin/user_upload_sozialpolitik/PDFs/arbeitsblatt-geht-uns-die-arbeit-aus.pdf]]

[[file:~/Downloads/global_lernen_2017-1.pdf.pdf]]

Arten der Arbeit

Supplierstunde:
[[file:~/NMS_Golling/Die_schnelle_Stunde/Arbeitsunterlagen_Die schnelle Stunde Religion für die HS.pdf]]
 - Zukunft auf heute
 - 10 Wörter meines Lebens
 - Die Welt verändern

* Hefteintrag

