#+title:      [SW11] Vertrauen, die Stärke des Herzens
#+date:       [2023-06-19 Mo 21:17]
#+filetags:   :02:sw11:
#+identifier: 20230619T211715

* Kompetenzbeschreibung
[[#A2]] Menschen und ihre Lebensorientierungen - Sich mit den großen Fragen der Menschen auseinandersetzen können

[[#A2_KB1]] Die Schüler können leidvolle Erfahrungen zum Ausdruck bringen und (christliche) Wege des Umgangs mit menschlicher Begrenztheit aufzeigen. 

* AB / UH
[[#A2_AB1]] Angenommen-Sein in Erfahrungen von Trennung, Verlust, Misserfolg und Krankheit

* Wiederholung


* Erarbeitung

Wir sind bereits im Stoff im 3. Kapitel, cf [[id:02_SW15][[SW15] Von Gott sprechen / Impuls: 1+1+1=1]]
Dann werde ich wohl die Planung anpassen? Eher nicht...

** Vertrauen
1 Die Schüler*innen sollen sich in die Lage der Jünger hineinversetzen, denn sie hatten bei dem furchtbaren Wetter Todesangst. Jesus hingegen beruhigte seine Freunde nicht. Er zweifelte ihren Glauben an. Indirekt wird er mit der Aussage: „Hab ihr denn keinen Glauben“ auch gemeint haben, dass man im Vertrauen auf ihn und Gott keine Sorgen zu haben braucht, denn man ist geliebt und gewollt.

2 Jesus war ganz im Vertrauen auf Gott. Deshalb konnte er in Ruhe schlafen.

3 Dieser Arbeitsauftrag ist individuell zu lösen.

4 Dieser Auftrag dient zur Festigung der Methode „Bilder erschließen“. Nur wenn man ein wenig „hinter die Pinselstriche“ schaut, kann man ein Bild richtig erschließen und deuten.

5 Auch dieser Auftrag ist individuell zu lösen.

6 Dietrich Bonhoeffer bringt Gott sein Vertrauen entgegen.

Johannes Oerding bringt sein Vertrauen einem Engel entgegen. Er spricht wahrscheinlich von einem Menschen, der ihm immer zur Seite gestanden ist, einem Menschen, der für ihn ein Engel ist.

 
Julia Engelmanns Liedtext ist etwas schwieriger zu deuten. Am wahrscheinlichsten sind mit dieser Aussage ihre Eltern gemeint, denen sie voll und ganz vertrauen kann.

7 Dieser Arbeitsauftrag ist sehr persönlich und individuell zu lösen.

8 Sakramente mit Öl: Taufe, Firmung, Krankensalbung, Weihe
Alle diese Sakramente werden von einem Priester oder Bischof gespendet und drücken die besondere Beziehung zwischen Gott und den Christen*innen aus

** Verzeihen
1 Dieser Arbeitsauftrag ist sehr persönlich und individuell. 
Diese Aufgabe fordert die Schüler*innen heraus, sich in die Lage unserer vier Hauptcharaktere zu versetzen und Lösungsvorschläge zu finden. Die Hauptthemen sind a. Schuld, schlechtes Gewissen b. vergeben, verzeihen c. Schuld und Leid anderer, Nachhaltigkeit d. Regelverletzung, Konsequenzen

2 Auch bei diesem Auftrag sind die Schüler*innen aufgefordert, sich dem Thema Verantwortung zu stellen. Es braucht auch ein gewisses Maß an Vertrauen den anderen gegenüber, um selbst erlebte, ähnliche Situationen im Plenum der Klasse zu erzählen. Dies fällt den Schüler*innen bestimmt leichter, wenn sie vorher in einer Kleingruppe arbeiten könnten.

3 Eine Entschuldigung, die erzwungen oder befohlen wurde, hat meist keine besondere Wirkung auf den Geschädigten. Eine von Herzen kommende Entschuldigung hingegen schon. Sollten ein*e Lehrer*innen zu so einer Situation (Chatverlauf – siehe Kap. 1, S. 14)  dazu kommen, versuchen diese die Schüler*innen mittels Gespräche zu solchen Entschuldigungen hinzuführen. Wie solche dann beim „Empfänger“ ankommt, kann, selbst bei ehrlich gemeinten Entschuldigungen, ganz unterschiedlich sein: manche brauchen ein wenig länger, um zu verzeihen, manchmal geht es auch ganz schnell.

* Hefteintrag


