#+title:      Konferenz
#+date:       [2023-11-14 Di 16:01]
#+filetags:   :konferenz:
#+identifier: 20231114T160144
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+TODO: TODO(t) STARTED(s!) WAITING(w@/!) APPT(a) PROJ(p) NOTIZ(n) NEXT(x) BESPROCHEN(b) DELEGATED(g@/!) | DONE(d!) CANCELED(c@)
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width \linewidth
#+OPTIONS: toc:nil
#+export_file_name: ~/RoamNotes/exports/Konferenz.html
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com

* Begrüßung

** SEP / Projekte
Safer Internet
Digiplan
Digi Konzept
- was haben wir erreicht?
Tag der offenen Tür
Krisenteam
- Birgit stellt Idee vor (Vorgehensweise; wie gehen wir allgemein vor?)
Q Handbuch (Magdalena)

aktuelle Termine


* IKM+
betrifft L für 3./4. Klassen in HF

anmelden: email / pw
ab 20.11. - Zeitfenster

Rückmeldug ergeht an:
- Schüler, unterrichtende Lehrer, Birgit, Fr. Kaserer

  
* Tag der offenen Tür

Wie viele Kinder kommen? ca. 100.

** Stationenbetrieb?
auch heuer wieder? Ja.

Wer was macht?
- Welche Schüler führen durch Haus?
  Viertklassler

- Julia: IT Raum (+ Mädels aus IF)

- Manu: 6 Schüler

- Christian + 3-4 Schüler

- Jause (gekauft)

- In welche Klassen dürfen sie hinein (Regelunterricht)?
  - BE
  - Krippenbauen mit den dritten Klassen (Bernhard)
    
- Bibliothek

- Englisch



* Schoolfox / Elternsprechtag

Termine planen - eine Klasse wählen - Termindauer festlegen. weiße Felder sind Pausen. alle Klassen zuweisen. bis nächsten Mittwoch 15h00.

Raumvergabe bitte rechtzeitig sagen.

Jause: vierten Klassen

* MINT Messe (Bewerb)
Julia nicht so begeistert, da eher ein Wettbewerb

Projekte vorstellen - bestes wird prämiert.

Mint Messe (erste Juni Woche)

Man kann es ausprobieren; ist's nicht gut, nächstes Jahr nimmer. Kinder waren sehr begeistert. Z.B. Lollis ohne Zucker.

Julia: ja, bitte Kinder sollen forschen, aber bitte kein Wettbewerb. 

* ibobb
BO Tool
Material erhalten Kinder und Eltern 
siebte Schulstufe: Fragebogen auch von Zuhause aus; Wirtschaft drängt aus BO der Kinder.

* Schulgarten
gestalten; Sitzgelegenheiten
3 Vorschläge

Baum: seine Früchte kleben. Baum ersetzen? eigentlich klar. Wer spendet dann Schatten?

Bänke: Betonklotz, darauf Holz-Sitzflächen

Baum mit Bänken in den Ecken
Bänke im Quadrat im Zentrum
Bänke am Rand - viel Freiraum

Eher keine Abstimmung? Untergrund ist nicht eben... macht Betonarbeiten schwierig. Martin wünscht Var. drei. 


* Allfälliges

** Budget
ok

Tafeln? Gemeinderatsitzung beschließt.
4 pro Jahr; ...

** Mint Messe

** Gütesiegel Berufsinfo

** Pers. Gespräche (Teams HF)

** Kalender mit allen Terminen:
online Kalender wurde nicht genutzt und befüllt. Und wenn es Sylvia betreut?

** Förderschiene:
- Kinder haben frei / L da; und umgekehrt.
Daher: Christoph - NM dauert bis 16h00; Förderstunde in einer 6. Stunde. Am Mo haben die ersten Klassen 5 Stunden (und FöU); am Dienstag die zweiten (und FöU), etc...

Die Möglichkeit besteht, kein Muss. 

FöU ist keine Strafes, sondern eine Förderung, etwas Gutes.  (Q Handbuch)
Absicherung für etwaige Umstufungen und Beschwerden der Eltern.

** Adventplanung
ein großer Adventkranz + Segnung
Beitrag eines jeden Jahrgangs.

Gemeinsame Feier für alle. Jeden Freitag (während der vier Wochen) ...
(Event-Team) Bsp.: Lied + Gedicht / Geschichte + Wir sagen euch an...

6.12.:
Nikolaus kommen in die Schule / Krampus (ohne Körperkontakt)
Nikolaus Reim für die Klasse. Alles draußen? Oder von Klasse zu Klasse, ist wohl besser. Aber dann kein Lauf draußen.  

** Theater

G. Ellmauer
Unsere Gruppe spielt in der Gollinger Burg. 
10.-12.06.
17.-19.06. besserer Termin 
Mo Generalprobe
2 Tage Aufführung

Betrifft va die vierten Klassen. Prüfungen eben vorher / Lernbetrieb wird dadurch nicht gestört. Je voller man das menschl. Hirn macht, umso mehr geht hinein. Nur die Termine werden gebraucht. 

Bitte um Beteiligung: Bühne / Ton / Musik / Werken (Holz): 10-12 Stockerl 30x30x40cm

** Schulskitag 13.12.
Christoph - ist am Laufen
Sylvia: wer fährt nicht? Alternative Programm: Therme oder Schlitten;
alle fahren (Zauchensee).

Bus reserviert. 7h45 weg; 14h00 Abfahrt in Zauchensee. Tunnel? Eher 13h00 Abfahrt.
Mittagessen: Nudeln und Skiwasser
17 Euro für Bus.

Wer keine Ski hat? Russbach 10 Euro (Christian) - Gewicht und Shuhgröße.
Bitte keine Gelddiskussionen - denn die Handys der Kids kostet mehrere 100 Euros.

Therme ist teurer als Skifahren.

29 Lehrer / 10 Klassen: ca drei Lehrer pro Klasse.

** Lehrerausflug Frühjahr
Termine JuFa Bregenz 
15.-17. März 2024

Ende Juni - und die 4. Klassen: Abschlussfeier?

Programm:
- Blumeninsel
- Bregenz
- schöne

** kein Turnsaal 27.11.
Daniel Kraft - herrichten

** Bienewiese
linker Teil der Wiese (Konf. Beschluss)

** Lena
"Der Junge mit dem gestreiften Pyjama"

Historsich gaaaanz schlecht - alles falsch! Der Zaun hat 6000 Volt. Natürlich wussten die Deutschen über das KZ. Es ist naiv, dass ein deustcher Junge nix über das KZ wusste oder wer ein Jude ist.
"Der Junge mit dem gestreiften Pyjama" ist im Englischbuch der vierten Klasse (MORE) drinnen.
Bitte nimmer schauen.

Es gibt so viele arge, wahre Geschichten - bei den Tatsachen bleiben.

Die Nachbearbeitung im Unterricht ist zu aufwendig, um diese Falschinformationen wieder zu korrigieren. Das Buch zum Film wurde in wenigen Tagen, ohne große Recherche geschrieben; andere Filem wie z.B. "Schindler's Liste" sind besser.

La vita e bella - ebenso problematisch.

** Kinder und Jugendliche stärken (Irmi Messner)
Manuela Gruber:

Schilf - aufbauender Kurs
Aufmerksamkeitsübungen, ...
Bücher bei Manuela


** Christian Gruber
Ärzte ohne Grenzen 23.11.

Vortrag: "Das Glück helfen zu können"; unterstützt mit Ärzte ohne Grenzen Projekte u.a. in Bangladesch, Indien, Kenia, ... Gertraud besuchte mit ihm und anderen Bekannten eine Schule in Kenia: mitten im Nirgendwo. Schulweg der Kinder: eine Stunde.

Wenn wir uns eine Unterstützung vorstellen können, dann soll diese über mehrere Jahre laufen. Bsp.: regelmäßig ein Bazar, etc.; gesammeltes Geld direkt an diese Schule überweisen. Aktuelle Lage: durch Wasserknappheit können die Rinder nicht getränkt werden, daher müssen diese geschlachtet werden.

** Wichteln
wer will mitmachen? Bitte eintragen. Limit: 15 Euro.

** Laptop Schüler 
Laptop nur in der Stunde; und nur für den Unterricht. Kein Zocken und nicht in der Pause.

** Weihnachtsfeier
noch kein Termin
