#+title:      Semesterkonferenz
#+date:       [2024-02-05 Mo 15:00]
#+filetags:   :konferenz:
#+identifier: 20240205T150009
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/RoamNotes/exports/Semesterkonferenz.html



* Begrüßung
GB Kinder und Dank für Jause.

Viele Suppl. Stunden; Danke Michi für tollen Tanz;
- Szene: Tanz vor ausverkauftem Haus, alle Arten, ... "Wann wieder?"

Noten: Förderschiene / ...: es gibt viele Genügend und NG -->

Homepage neu: VS hat darauf verzichtet; VS machts mit Jimboo?
Bekannter IT: was würde er verlangen? (haben 1500 verplant)

Elternabend mit Polizei (3. und 4. Klassen):
- 8 (!) Mütter waren da
- war gut gemacht
- Termine für 3. und 4. Klassen für Cick und Check
- Beginn: März 2024

SA Termine 2. Semster

Klassenkonferenzen

Spint ausräumen

1a (MINT; Magdalena+Christoph) und 1b für SJ 2024 / 25

Die zweiten Klassen werden auf 3 Klassen aufgeteilt.

* Klassenkonferenz
Zufriedenstellend / Wenig Zufriedenstellend

Ich hab nur Tobias Egger ein WZ gegeben und ein paar Schülern ein "Z" (3a: Karlo; 1? Paula; 2b: Valerian und Bernhard; 3c: Tobi)

** GTS
eine Anmeldung, brauchen mind. 12? Unsere Begeisterung hält sich in Grenzen

** 1a (MS)
Verhalten: ein paar Z (11), kein WZ;
und einige G als Noten (kein NG), kein NG
MINT-Projekte - stellen ein Problem da, bei MINT und Nicht-MINT-Schülern?

** 1b (GV)
Verhalten: viele Z (7)
Noten: einige G, kein NG
sehr lebendig

** 2a (SiM)
Verhalten: Z (3)
Noten: einige G (Hauptfächer), kein NG

** 2b (BMartin)
Noten: kein NG; zwei Umstufungen
Verhalten: einige Z; 

** 3a (MBernhard)
Noten: kein NG; L-Niv-Ä.: D auf Standard Karlo; keinen Standard Genügend in den HF - gut.
Mario: neuer Schüler - Findungsphase
Verhalten: kein WZ; viele Z (7), ...
guter Zusammenhalt

** 3b (Lena)
Noten: kein NG; einige G;
L-N-Ä.:
Verhalten: Tobi (WZ) von *sieben* Lehrern; Polizei; mit Mama, ...

Maßnahmen? 

** 3c (Dani)
Noten: viele 4; 5mal 5 (Mufetin hat 4); Tobi 5 in M
Wie gehts weiter bei Mufetin? behalten, Poly nix für ihn; wird wiederholen. Beobachtet, nimmt nicht teil. Stört auch nicht. Eltern lassen ihn nicht bei Sportw. nicht mitfahren, weil er in der Schule schlecht ist. Ist doch SV? Wiederholt, sitzt wieder in der dritten. Sinnvoll? Mufetin hat keinen SPF.

Mufetin: passiv, schreibt bei D SA einen Satz. Sein Bruder (Slatko) ist aktiver.
Fördern fruchtet nix, wenn er Zuhause nix macht. Eltern ins Boot holen (wieder einmal).
Was steckt dahinter? Handysucht? ...

Vierte mit vielen NG - keinen Abschluss - keine Lehre.

--> Förderstunde für spezielle Kinder: Mufetin, Hannah (Daniel)
Hannah: auch sehr faul; ... Therapie/Begleitung?

L-N-Ä.: nix.

Verhalten: viele Z; kein WZ.

** 4a (BäM)
ein NG in GS;
meine Kuhflade haben gerne ihr Handy, verhalten sich sehr verdächtig; machen das absichtlich? Um uns zu ärgern, ...
Adrian: ist alles wurscht.

** 4b (EE, GM)
Noten: kein NG

** 4c (EG)
Noten: zwei Aufstufngen (Maid, Fabian) auf AHS; ...
Slatko: erfreut, sehr gut unterwegs, ...

Standard 1/2: automatisch aufstufen.

Hannah Seiwald: Ende April - Op am Rücken (WS); --> Intensivstation, Rekon., ... Therapie; ... Die S bis April fertig benoten, damit sie für den Rest des SS nicht mehr belastet wird. Hannah möchte nicht, dass dies "herumläuft" in der Schule. 


* Handyverbot an der Schule
Erwin (in seiner Klasse): Handyumgang ist erschreckend; hinten in der Hosentasche; "Aufs Klo gehen", ...
Wie konsequent sind wir?!

Im Haus ist Handyverbot - außer es wird im Unterricht erlaubt.
Handysafe!? Wieder Aufwand für uns! Änderung wird es keine geben.

Handy: *Im Spint, ausgeschaltet.* Wer sich nicht daran hält, abkassieren und zu Birgit. Beim zweiten Mal müssn es die Eltern abholen.

Eltern haben oft schon aufgegeben... "Bitte nehmt's das Handy ab."

In der Klasse brauche ich kein Handy, bei der Julia liegen 20 Windows-Tablets. Wenn ich es brauche: holen und dann wieder zurück. Nicht jeder L geht mit den S nach der letzten Stunde in die Garderobe. 

Polizei: unsere Regeln gelten!

Sportwoche: vll einmal komplett ohne Handy?

* Allfälliges
Freitag: 9.10. bis zur 6. Stunde!

Bilder (Gemälde, ...)  der Kinder aufhängen!

Kaugummis! "L sagt nix!" HO wieder neu durchmachen.

Was machen wir mit den Räumen ohne klare Definition? Dafür müssten wir keinen neuen Beamer bstellen, etc.

BE Saal - bis DO nicht benutzbar. Raum im Keller (NM) wird öfters für BE benötigt.

Do: nach der 2. Stunde, Marsch in den Ort; Programm bis 12:00; ... Umzug, ... 

* Zukünftige Termine
- 4.3.
- 9.4.
- 22.5.
- 20.6.
- 28.6.: Notenkonferenz
