#+title:      Konferenz
#+date:       [2024-01-18 Do 16:02]
#+filetags:   :schule:
#+identifier: 20240118T160226
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/RoamNotes/exports/Konferenz.html


* Begrüßung / Tagesordnung
Liebe Grüße an die Geb.-Kinder: Nina, Christoph

Vielen Dank an die Schikurs Org.

Info Elternabend MINT Klasse VS: Danke

Nächtes Jahr: 2 erste Klassen (einmal MINT, einmal regular);
wer wird KV

die jetzigen 2. Klassen werden auf drei Klassen aufgeteilt: Eva übernimmt die dritte Klasse.
Noten können eingetragen werden

Sinnloser Donnerstag 9.2. 10:30 - 12:30 im Markt; mit DJ (Verkleidet...); Thema: je nach Klasse (mind. einen Hut, oder Nase, ...)

Arbeitskonferenz - Thema: Konflikt und Kommunikation - Q-Handbuch

Freitag, 10.2.2024: in der 5. Stunde Schulnachricht: dann Ende.

* Termine
Dienstag, 23.1. 8h00-9h00 neuer Drucker installiert (vorher drucken und kopieren)
Donnerstag Hepatitis Impfung
Elternabend Polizei Click und Check 3. Klassen (Info über SchoolFox, macht Sylvia)

Noten bis 5.2., 10h00.

Notenkonferenz, 5.2., 15h00 - Essen vom Inder (schafft er das)? Wer?

8.2. sinnloser Donnerstag

2.2. Schule tanzt (Michi + Tänzer; wird vorher geübt)

8.2.+9.2.: Talente Check (3a, 3b, 3c)

6.3. BM Geräteturnen (AE, EH, MH, BärM)

MINT Projekttage

5.2.-7.2. Projekttage 1a+1b, 2a; 6.2. Haus der Natur

26.4. Mauthausen 4. Klassen

14.3. Englisch Theater

IF Projekttage 4. Klassen 21.5. - 24.5.

Golling Burg Theater: vorletzte Schulwoche; könnte Schule kommen? Natürlich, ...
Mo GP; Di+Mi Aufführungen

7.3. (Uhrzeit?) Theater 2. Klassen in Hallein?

* Verwaltungskurrende
Informiert 1-2x pro Monat: Dienstpflicht!

Kurzf. Einzelaussdendungen, Homepage, 

* Online Terminkalender ab 2024
Zugang über BTS
Kursabrechnungen über dieses "Ding"

Dienstbesprechung mit Fr. Kaserer: OÖ - ...

* Sprachsensibler Unterricht
Der Wortschatz sinkt dramatisch.
SuS sollen sich nach der 8. Schulstufe selbst präsentieren können
(S verwenden oft nur "gut" und "schlecht")

Fortbildungen zu diesem Thema - siehe PH

Kinder denken anders.

Lesekompetenz? sinnerfasstes Lesen? Wie viele Kinder lesen (noch)?

Neue Lehrpläne - vernetztes Denken - Begabungen entdecken, fördern - FöU für GUTE Schüler.

* Q-Handbuch
Wie gehen wir mit Konflikten um? Vielleicht könnten wir kleine "Regeln" erstellen? Ev. einen Komm.-Trainer holen?

1) die Sachlichkeit kann verbessert werden; manchmal brodelt es, dann bricht es aus wie ein Vulkan; abgearbeitet werden sie; (über dritte besprochen)
2) früher anfangen miteinander zu reden
3) abhängig vom Gesprächspartner und dem Problem; generell "ja"
4) ist ausbaufähig; wir kommen weniger zusammen und zum Reden; das Leben ist aber auch stressiger geworden; es gab früher weniger Konferenzen, da saßen wir öfters zusammen; Pausenaufsicht jetzt zu zweit, daher sind weniger im Konferenzzimmer (zum Reden). Es wird Zeit in die Problembesprechung investiert, viel Energie in die Lösungen, das Ergebnis ist dann manchmal dünn.

Konflikte:
- anhören
- Gesräch zuerst mit konflikt Lehrer, dann Direktion
- eine Nacht schlafen
- Personen informieren
- Termin
- Protokoll
- sachlich; wir beginnen, wir beenden;
- er ist Experte für sien Kind; wir in der Schule

Fixe Sprechstunden respektieren; zuerst anhören - ohne Kommentar!
Was erwarten die Eltern von uns? Als Frage formulieren...
"Falls wir etwas übersehen haben - tut uns sehr leid!"
Für den betroffenen L ist es verletzend, wenn dieser erfährt, dass bereits in der Direktion mit Dritte darüber gesprochen wurde. Nicht zw Tür und Angel. Fühlt man sich falsch verstanden, Spirale, schleppt es mit sich herum - deshalb: Zeit! Über Schüler ärgern - nicht abwertende Bemerkungen im Konferenzzimmer. Macht Stimmung. Konflikt soll dort bleiben, wo er hingehört. Zum Schluss eine Info: das war es - so wurde es gelöst. 
