#+title:      Religionsunterricht
#+date:       [2024-07-20 Sa 21:46]
#+filetags:   :meta:
#+identifier: 20240720T214626
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: num:nil toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/RoamNotes/exports/Religionsunterricht.html


* Gedanken
:PROPERTIES:
:CUSTOM_ID: h:e2382463-c212-4639-b0b9-8c07ee79c6d8
:END:

[cite:@Berger2004]

** 1b - Überraschung am Ende der Stunde
:PROPERTIES:
:CAPTURED: [2024-09-19 Do 09:55]
:END:

[[denote:20240908T214521][C Klasse 2024-28]]

Oh, am Ende dieser Stunde in der 1b (<2024-09-19 Do 09:25>) hat mich eine Schülerin mit einem Geschenk überrascht. Das hat mich so sehr berührt: ein Boot, gefaltet aus Papier; ich (oder Jesus?) drinnen, mit einem großen Lächeln, gestreiften Regenfarben Pulli (in einer Hand ein Weinglas, in der anderen Hand ein Brot).

** Gespräch mit Direktorin
:PROPERTIES:
:CAPTURED: [2024-09-28 Sa 17:50]
:END:
Das Gespräch mit Gabi (Direktorin von Abtenau) verlief ganz anders als ich es erwartete. Mir ging es nicht gerade super die letzten Tage. Gabi hat mir versichert, dass sie voll und ganz hinter mir steht. Sie hat so sehr dafür gekämpft, dass ich als RL komme.

Es gab gleich zu Beginn des SJ Beschwerden von Seiten der Eltern. Die Jahre davor haben die KVs den RU übernommen, zwar mit missio canonica, aber eben keine speziell ausgebildeten RL. Wie Gabi habe auch ich bemerkt, dass die Kinder es nicht gewohnt sind, im RU zu beten. Und daher kamen auch die Beschwerden, da ich angeblich den Kindern meinen Glauben überstülpe.

Naja, was habe ich in den ersten Wochen unterrichtet? Da war nicht viel spezifischer RU Stoff. Wahrscheinlich war es das Beten, Vater Unser geht gerade noch, aber ein Ave Maria geht gar nicht.

Zum Gebet sollen die Kinder hingeführt werden. Hm - aber wie? Z.B. wäre es eine wunderschöne Idee, wenn jeder Schüler sich selbst einen RK basteln könnte. Die Art, wie der RK in Pöllau geknüpft wird, ist relativ leicht umsetzbar. Es braucht eben viele Holzperlen in zwei Größen, kleine Holzkreuze und einige Superkleber - oder Heißkleber. Die Kreuze waren extra von "hinten" angebohrt. 

Gott, Jesus als Werkzeug dienen, Er soll wirken, ich soll Ihm nicht im Weg stehen. Oft, manchmal wirkt Er (auch) durch unscheinbare Mittel.

Beten, viel beten.

Natürlich wünschen sich viele Eltern und Lehrer einen Ethikunterricht.

** Was soll ich nur tun?
:PROPERTIES:
:CAPTURED: [2024-10-04 Fr 11:53]
:END:
Meine Arbeit macht mir einfach gar keine Freude mehr (die Frage ist, ob mir jemals eine Arbeit Freude bereitet hat.) Scheinbar steht auf meiner Stirn: Das ist Herr Fuchs, den kann man ungestraft verarschen! Denn ich werde so respektlos in vielen Klassen behandelt.

Viele Stunden werden durch die Schüler torpediert. Ich bereite Material im Internet vor und stelle es für die iPads zur Verfügung. Und komischer weise geht natürlich das Internet nicht. Für die HÜ funktionieren die iPads und das Internet wieder. Komisch!

Mir reicht es schon.

Ich werde dieses Schuljahr irgendwie noch überleben, denn für mehr reicht es nimmer. Und dann schmeiße ich alles hin. Mir reicht es wirklich! Von oben kommt null Hilfe, mir fällt nichts mehr ein. Was bringt Gebet, wenn Gott schwiegt??!!

** Neue Themen
:PROPERTIES:
:CAPTURED: [2024-11-10 So 10:49]
:END:
Für nächste Woche suche ich noch nach Themen, leider fällt mir derzeit gar nichts ein.

- Ersten Klassen :: Lernschiene; ... den "Sturm auf dem See" haben die ersten Klassen so gut wie fertig; jetzt kommt "Die Heiligen"


- Zweite Klassen ::
  - Lernschiene

    
- Dritte Klassen ::
  - Weltreligionen
  - Vielleicht hier weiter machen und gemeinsam den Islam und das Judentum erarbeiten
  - Grenzenlose Freiheit / Dekalog / Bergpredigt


- Vierten Klassen ::
  - das Buch der Offenbarung genauer weiter lesen (hat nur nicht so gut funktioniert in der 4c?); kein wirkliches Interesse
  - Heiliger Paulus, heiliger Petrus, die ersten Christen, Briefe des Apostel Paulus, seine Bekehrung, seine Missionsreisen

** Wie gehe ich mit Störungen um
:PROPERTIES:
:CAPTURED: [2024-11-11 Mo 11:47]
:END:
Heute gehe ich mit den Störungen im Unterricht gelassener um; hoffentlich hält das an. Im Grunde darf ich diese Störungen nicht persönlich nehmen, ein bisschen Humor / Sarkasmus hilft. Und trotzdem klar sein; z.B. in der 2a / Lernschiene: alle bleiben in der Klasse. In der 4b ließ ich ein paar Schüler hinaus. Die nächste Stunde dürfen andere zur Lerninsel.



* Tasks
Hier steht sehr viel Text.
