#+title:      Apokalypse
#+date:       [2024-02-01 Do 08:45]
#+filetags:   :04:hoffnung:
#+identifier: 20240201T084513

* Einstieg
Einleitend wird das Foto (M 1) als stummer Impuls gezeigt. Die Äußerungen der Schülerinnen und Schüler werden nicht kommentiert. In einem zweiten Schritt werden die Schülerinnen und Schüler aufgefordert, eine eigene Antwort auf die Frage „Wie stellt ihr euch eure Zukunft vor?“ zu formulieren und anonym auf kleine Zettel (DIN-A-6) zu schreiben. Die Zettel werden eingesammelt und von der Lehrkraft vorgelesen. Die Schülerinnen und Schüler nehmen Stellung zum Gehörten und äußern ihre Eindrücke. Die Methode ermöglicht einen offenen Einstieg und gibt erste Auskünfte über die Zukunftsvorstellungen der Schülerinnen und Schüler. Die Vorstellung, die ausgefüllten Zettel in zehn Jahren bei einem Klassentreffen noch einmal vorzulesen und mit der Wirklichkeit zu vergleichen, ist ein erster Denk- und Gesprächsimpuls.



* Baustein A
Leben ist nicht vollkommen planbar. Kleine oder große Ereignisse erfordern immer wieder Veränderungen des eigenen Weges. Ob Menschen bereit sind, die Zukunft dieser Welt mit zu gestalten, ob sie ihrem christlichen Glauben dabei etwas zutrauen, ob sie bei der Gestaltung der Zukunft eher selbstbezogen sind oder ob sie sich hilflos in ihr Schicksal fügen, verdeutlicht sich in Aussagen über das eigene Leben. Entsprechende Lebensgrundsätze stehen im Zentrum der folgenden Phase.

Die Schülerinnen und Schüler erhalten zur Erarbeitung die Aussagen mit den Lebensgrundsätzen verschiedener Menschen (M 2). In dieser Phase haben die Schülerinnen und Schüler in Einzelarbeit zwanzig Minuten Zeit, um die Aussagen zu erschließen, über ihren eigenen Lebensgrundsatz nachzudenken und diesen aufzuschreiben. Anschließend kommen die Schülerinnen und Schüler in Dreiergruppen zusammen, vergleichen die Aussagen der fiktiven Personen, stellen sich ihre eigenen Lebensgrundsätze vor und beantworten die Fragen des Arbeitsblattes. Schließlich werden die Gruppenergebnisse im Plenum vorgestellt und zusammengefasst. Hierbei sollte u.a. herausgearbeitet werden, dass Lebensgrundsätze Konsequenzen für die Gestaltung des eigenen Lebens haben.



* Baustein B
In der folgenden Phase wird ein Junge (Kyo) vorgestellt, der das Unglück von Fukushima überlebt hat. Einleitend wird den Schülerinnen und Schülern die Dramatik des Ereignisses vor Augen geführt. Entsprechende Filmsequenzen können bei Youtube (www.youtube.com) eingesehen werden. Im Anschluss steht die Anbahnung einer Identifikation der Schülerinnen und Schüler mit Kyo im Mittelpunkt. Dazu wird das Foto (M 3) gezeigt. Die Schülerinnen und Schüler äußern sich zu dem Foto und stellen Vermutungen über die Situation von Kyo an. Die Lehrkraft weist darauf hin, dass das Unglück plötzlich und unvorhersehbar über die betroffenen Menschen hereinbrach und Kyo bis zu dem Tag des Unglücks ein ganz normales Leben gelebt hat. Gemeinsam stellen die Schülerinnen und Schüler in der Lerngruppe Vermutungen darüber an, wie das Leben von Kyo ausgesehen haben könnte und schreiben im Anschluss in Dreiergruppen einen möglichen Tagesablauf von Kyo am 10. März (Tag vor dem Unglück) auf (M 4). Die Ergebnisse werden im Plenum vorgestellt und dienen als Vorgeschichte der nächsten Phase.



* Baustein C
In der folgenden Phase werden die Geschichte von Kyo und die Lebensentwürfe der in der Vertiefungsphase I eingeführten Personen zusammengeführt. Dazu wird ein vergrößertes Bild von „Kyo“ (M 5) in die Mitte der Tafel geheftet. Einleitend nimmt die/der Unterrichtende Bezug zu den von den Schülerinnen und Schülern vorgetragenen Tagesabläufen von Kyo und setzt die Geschichte des Jungen mit der Erzählung „Der Tag des Unglücks“ (M 6) fort.

Im Anschluss an die Erzählung erhalten die Schülerinnen und Schüler in einer ersten Phase genügend Raum, um sich zur Schilderung Kyos äußern zu können und ggf. ihre Betroffenheit zu verbalisieren. Im Anschluss werden die auf DIN-A4 Seiten geschriebenen Namen der Personen des Arbeitsblattes M 2 um das Foto von Kyo gruppiert. Die Schülerinnen und Schüler teilen sich in Dreiergruppen auf und werden aufgefordert, sich vorzustellen, Kyo würde einen dieser Menschen treffen und sie würden sich über ihre Zukunft unterhalten. Wie würde ein Dialog aussehen? Was käme darin zur Sprache? In einer Austauschrunde bringen die Schülerinnen und Schüler eigene Ideen hierzu ein. Die Lehrkraft könnte weitere mögliche Fragen für die Dialoge einbringen: „Welche Wünsche habe ich im Blick auf die Zukunft?“, „Was macht mir Angst?“, „Was macht mir Hoffnung?“, „Was kann ich im Blick auf die Zukunft beeinflussen?“, „Worauf kann ich vertrauen?“ oder „Was hilft mir, meine Zukunft zu gestalten?“

Im Anschluss werden die Dialoge in der Lerngruppe vorgestellt. Während der Auswertung sollte deutlich werden, dass die Einstellungen von Kyo und seinen Dialogpartnern sich unterscheiden. Mögliche Gründe hierfür sind im Unterrichtsgespräch zu erheben. Ebenso sollte deutlich werden, dass die eigenen Einstellungen und Erfahrungen Folgen für die Gestaltung der eigenen und der Zukunft von anderen haben.



* Ergebnissicherung
Das Ergebnis des Unterrichtsgesprächs wird im Bild einer sogenannten „Zukunftswaage“ (M 7) zusammengefasst. Im Zentrum dieser Phase steht die Frage, welche in den Dialogen genannten Aspekte sich für die Gestaltung von Zukunft als tragfähig erweisen. Hier geht es um individuelle Fähigkeiten, ggf. um den eigenen Glauben und um die Erkenntnis des Angewiesenseins auf den Nächsten. Entsprechende Äußerungen der Schülerinnen und Schüler werden in der einen Waagschale gesammelt. In der anderen Waagschale werden Aspekte zusammengetragen, die Ängste verursachen.

Als Ergebnis ist herauszuarbeiten, dass die Befüllung der eigenen „Zukunftswaage“ wesentlich zur Gestaltung und zum Gelingen der eigenen Zukunft beiträgt. Dadurch, dass der Mensch sein Leben bejaht und den Willen zur Gestaltung seines Lebens und der Welt zeigt, wird aus abstrakten Zukunftsvorstellungen eigenes, individuelles Leben. Theologisch gesprochen: Gottes Verantwortung für sein Volk in dieser Welt legt dem Menschen Verantwortung für das eigene Leben und das Leben anderer auf.
