#+title:      Glaube POP Musik
#+date:       [2024-01-15 Mo 09:01]
#+filetags:   :religion:
#+identifier: 20240115T090107
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/RoamNotes/exports/Glaube POP Kultur.html

* Glaubenssymbole in der Popkultur: positiver Ausdruck nach religiöser Sehnsucht bei Jugendlichen

Kaum ein Hardrocker, der nicht ein Kreuz über der Lederjacke baumeln lässt. In Videoclips und auf CD-Hüllen werfen sich Künstler wie Michael Jackson und Marius Müller-Westernhagen in Messiaspose oder erscheinen engelsgleich. „Blasphemie!“, schallt die Kritik aus kirchlichen Kreisen. „Madonna“ trieb ihr kokettes Spiel mit der Jungfräulichkeit Mariens sicher zu weit. Mit Kruzifixen und Rosenkränzen stilisierte sich die amerikanische Popsängerin zur männermordenden Klosterfrau. „Ich mag Kruzifixe, weil sie sexy sind – schliesslich ist ja ein nackter Mann drauf“, sagte die Trendsetterin. Kardinal Joseph Ratzinger, der Leiter der vatikanischen Glaubenskongregation, sah rot und setzte die Werke der selbst ernannten Mutter Gottes des Pop auf den Index. „Anything goes“ –alles ist möglich, lautet das Credo der Postmoderne, das sich auch die Jugendkultur zu Eigen gemacht hat. Pop- und Rockstars bedienen sich zunehmend aus dem Symbolschatz des Christentums.

* Ernsthafte Auseinandersetzung mit Religiosität und Glauben

Doch liberale Christen und Religionspädagogen sehen in der neuen Liebe zu christlichen Symbolen einen Ausdruck religiöser Sehnsucht bei Jugendlichen. „Patchwork-Religion“ nennt der Religionspädagoge Gerd Buschmann dieses Phänomen. Jugendliche mischten sich ihre Religion selbst, indem sie sich an Symbolen und Inhalten nähmen, was ihnen gefalle, sagt der Dozent an der Pädagogischen Hochschule Ludwigsburg. In vielen Jugendkulturen gelte das Tragen der Glaubenssymbole als schick. Kreuz, Friedenstaube und Fischsymbol würden neben dem chinesischen Ying- und Yang-Zeichen verwendet. Gründe für den Zeichengebrauch seien die Ästhetik – aber auch die provokante Kritik an einer als lebensfern und verknöchert empfundenen Kirche. In den meisten Fällen setzten sich Symbol tragende Popstars und ihre Fans ernsthaft mit Religiosität und Glauben auseinander, sagt Buschmann, der der Bundesarbeitsgemeinschaft „Populäre Kultur und Religion“ angehört. „Um kommerziell erfolgreich zu sein, muss man nicht die Kirche provozieren.“ Viele Texte der Pop- und Rockmusik griffen urchristliche Themen auf: die Nächsten- und Friedensliebe, den Wunsch nach der Bewahrung der Schöpfung. Die Kirche müsse „dankbar sein, dass die Popkultur religiöse Themen ins Spiel bringt“, sagt Buschmann. Stattdessen lege sie eine „ängstliche Hütermentalität“ an den Tag. Es sei ein „Grössenwahn“, wenn sich die christlichen Kirchen als alleinige Hüter religiöser Tradition sähen. Auch die christliche Symbolik unterliege „keinem Copyright“ der Kirche. Statt sich abzuschotten gegenüber neuen Zugängen zur Religiosität, müsse sich die Kirche öffnen. Die Kirche übersehe oft, dass „sie selbst zur Subkultur geworden ist“, so Buschmann. Die Verweigerungshaltung gegenüber einer Jugendkultur, die auch religiöse Inhalte formuliere, werde „zur weiteren Ghettoisierung der Kirchen“ führen. Der Dialog mit der Popkultur und ihren Heilsangeboten ermögliche aber erst „eine inhaltliche Konkurrenz“.
Keine kulturellen Stolpersteine aufstellen

Auch der Religionspädagoge Gotthard Fermor versteht „das religiöse Erbe der Popmusik als Herausforderung an die Kirche“. So lautet der Untertitel seines Buches „Ekstasis“, in dem sich der Bonner Theologe mit der religiösen Dimension der Popmusik auseinander setzt. Das ekstatische Erleben sei „das Scharnier“ zwischen Popmusik und Religiosität. Die Wurzeln der Pop- und Rockmusik lägen in der emotionalen anglo-amerikanischen Musikreligiosität der Gospels und Spirituals. Indem Popmusiker religiöse Inhalte und Symbole vermischten, zeige sich ihre „dogmenfreie Spiritualität“, sagt Fermor. Christliche Symbole und Texte mit religiösen Zitaten wiesen sehr oft eine grosse Ernsthaftigkeit auf. „Bekenntnishafte Aussagen schleudert man nicht einfach in den Raum.“ Die Kirche müsse jungen Menschen auf der Sinnsuche „Verwirklichungsräume anbieten und keine kulturellen Stolpersteine aufstellen“, sagt Fermor.

* Vorsicht vor Anbiederung

Als beliebteste Symbole hat der Popkenner neben Kruzifix, Marienbildern und Engeln eine Licht-Dunkel-Metaphorik, die Todes- und Wiederauferstehungssymbolik und Kirchenräume ausgemacht. Jugendliche leben ihr Bekenntnis in den Jugendkulturen, in Musik, Rhythmus, Starkult und Mode, sagt Michael Landgraf. Der Religionspädagoge aus Neustadt ist davon überzeugt, dass die Kirche viele junge Menschen nur erreicht, „wenn sie das Bekenntnis zum Rhythmus als wichtige konfessionelle Ausdrucksform wahrnimmt“. Jugendliche müssten ihren Glauben ihrem Lebensgefühl entsprechend entfalten können. Jugendgottesdienste verfehlten meist ihre Klientel, weil sie nicht die Lebenswelt junger Menschen ansprächen. Als Chance für die christlichen Kirchen sieht Landgraf, dass viele Jugendliche kirchliche Angebote als ein Angebot unter vielen akzeptierten. Mit der „Misch- und Klaukultur“ in Popmusik und Religion müssten die Kirchen leben und verstärkt das Gespräch mit der Jugend suchen. Annäherungsversuche über die Musik könnten allerdings als Anbiederung verstanden werden.

Die christliche Popmusik sei in Deutschland noch immer eine geschlossene Szene, analysiert Landgraf. Christliche Popbands übten oft einen bewussten Symbolverzicht und wollten ihr Christsein und religiöse Inhalte über die Musik transportieren. „Wenn überhaupt, dann klebt man sich als gemeinsames Symbol den ‚Fisch‘ verschämt auf den Gitarrenkoffer.“ Wenn christlicher Popmusik der „Stallgeruch“ anhänge, habe sie auf dem deutschen Musikmarkt keine Chance, urteilt Religionspädagoge Fermor. Ein Problem vieler christlicher Popgruppen sei es, dass die Musik funktionalisiert werde. „Hauptsache, das Evangelium kommt rüber“, laute der missionarische Eifer vieler Sakro-Musiker. Ob Musikprojekte „powered by Evangelische Kirche in Deutschland“ bei jungen Leuten Anklang finden, sei höchst fraglich.
Suche nach Halt und Orientierung

Die christliche Popband „Normal Generation?“ kommt ohne den plakativen Gebrauch von Kreuz oder Fischzeichen aus. „Wir verwenden solche Symbole kaum, versuchen jedoch den Glauben, für den diese Symbole stehen, zu leben und glaubhaft zu vermitteln“, sagt Bandmitglied Martin Walter. Die Musiker aus Altensteig im Schwarzwald, die sich mit ihrem Lied „Long for you“ beim Vorentscheid zum „Grand Prix d‘ Eurovision“ einen respektablen dritten Platz sicherten, erklären sich die Häufung christlicher Symbole in der Popkultur durch ein vermehrtes spirituelles Bedürfnis. „Wahrscheinlich brauchen wir Menschen etwas Sichtbares, um den Glauben an den unsichtbaren Gott für uns nahbarer zu machen,“ so Walter. Seinem Ziel, „Gott in die Charts“ zu bringen, glaubt Pfarrer Fritz Penserot indes ein gutes Stück näher gekommen zu sein. „Der Erfolg von ,Normal Generation?‘ ist ganz grossartig“, sagt der Senderbeauftragte der Evangelischen Kirche in Deutschland (EKD). Den dritten Platz beim Grand-Prix-Vorausscheid hätten die von der EKD unterstützten Musiker deshalb errungen, weil sie ihr Christentum glaubhaft lebten. Die „Generation Golf“ begebe sich nach dem allmählichen Werteverlust seit den 70er Jahren wieder auf die Suche nach Halt und Orientierung. Die neue Sinnsuche spiegele sich auch in dem verstärkten Gebrauch religiöser Symbole. In der Gesellschaft herrsche ein „spirituelles Defizit“. Die neue Symbol-Liebe sei deshalb auch eine Reaktion auf „eine Welt, die von der Säkularisierung relativ stark bedroht ist“.

Datum: 10.04.2002
Autor: Alexander Lang
