#+title:      Joh 8 Kommentar
#+date:       [2024-03-18 Mo 09:23]
#+filetags:   :bibel:
#+identifier: 20240318T092342

* Misericordia et misera – das Erbarmen und die Erbärmliche
Mit dieser auffallenden, das Aufhorschen der Hörer und die Aufmerksamkeit der Leser provozierenden Redefigur beschließt der heilige Augustinus rhetorisch geschickt seinen Kommentar zu einer Perikope aus dem Johannesevangelium (Joh 8, 1-11), wenngleich im Augustinustext die Erbärmliche zuerst, danach das Erbarmen genannt wird. Mit misera (Erbärmliche) meint Augustinus eine Sünderin, mit misercordia (Erbarmen) Jesus Christus.

Es ist das Evangelium von der Ehebrecherin. Jesus, der ohne Sünde gewesen ist, der einzig Gerechte, hätte das Recht gehabt, die Ehebrecherin wegen ihrer Sünde zu verurteilen. Er nennt die Sünde – den Ehebruch – beim Namen: „Geh und sündige von nun an nicht mehr“, aber er verurteilt die Frau nicht.

Der Heilige Vater, Papst Franziskus, bezieht sich in seinem jüngsten Apstolischen Schreiben auf dieses Evangelium und zitiert die beiden Worte des heiligen Augustinus. Der Text im Johannesevangelium und der Kommentar des heiligen Augustinus zeigen nach den Worten des Papstes das, „was wir im Heiligen Jahr, einer Zeit reich an Erbarmen, gefeiert haben. … (D)ieses Erbarmen verlangt, weiter in unseren Gemeinschaften gefeiert und gelebt zu werden. Die Barmherzigkeit kann nämlich im Leben der Kirche nicht ein bloßer Einschub sein, sondern sie ist ihr eigentliches Leben, das die tiefe Wahrheit des Evangeliums deutlich und greifbar werden lässt. Alles wird in der Barmherzigkeit offenbart; alles wird in der barmherzigen Liebe des Vaters gelöst.

Eine Frau und Jesus begegnen einander. Sie, eine Ehebrecherin und nach dem Gesetz zur Steinigung verurteilt; er, der mit seiner Verkündigung und seiner Ganzhingabe, die ihn ans Kreuz bringen sollte, das Gesetz des Mose auf seine echte ursprüngliche Absicht zurückgeführt hat. Im Mittelpunkt stehen nicht das Gesetz und die legale Gerechtigkeit, sondern die Liebe Gottes“ (Apostolisches Schreiben „Misericordia et misera“, Nr. 1).

Im folgenden veröffentlicht Kathnews den kurzen Kommentar des heiligen Augustinus und die betreffende Perikope aus dem Johannesevangelium:

* Aus dem heiligen Evangelium nach Johannes (8, 1-11)

1 In jener Zeit ging Jesus zum Ölberg. 2 Am frühen Morgen begab er sich wieder in den Tempel. Alles Volk kam zu ihm. Er setzte sich und lehrte es. 3 Da brachten die Schriftgelehrten und die Pharisäer eine Frau, die beim Ehebruch ertappt worden war. Sie stellten sie in die Mitte 4 und sagten zu ihm: Meister, diese Frau wurde beim Ehebruch auf frischer Tat ertappt. 5 Mose hat uns im Gesetz vorgeschrieben, solche Frauen zu steinigen. Nun, was sagst du? 6 Mit dieser Frage wollten sie ihn auf die Probe stellen, um einen Grund zu haben, ihn zu verklagen. Jesus aber bückte sich und schrieb mit dem Finger auf die Erde. 7 Als sie hartnäckig weiterfragten, richtete er sich auf und sagte zu ihnen: Wer von euch ohne Sünde ist, werfe als Erster einen Stein auf sie. 8 Und er bückte sich wieder und schrieb auf die Erde. 9 Als sie seine Antwort gehört hatten, ging einer nach dem anderen fort, zuerst die Ältesten. Jesus blieb allein zurück mit der Frau, die noch in der Mitte stand. 10 Er richtete sich auf und sagte zu ihr: Frau, wo sind sie geblieben? Hat dich keiner verurteilt? 11 Sie antwortete: Keiner, Herr. Da sagte Jesus zu ihr: Auch ich verurteile dich nicht. Geh und sündige von jetzt an nicht mehr!

* Aus dem Kommentar des heiligen Bischofs Augustinus zum Johannesevangelium 33,4-5

Seht, wie in dieser Geschichte die Feinde unsres Herrn seine Sanftmut auf die Probe stellen! Seine Feinde sagten bei sich: „Er gilt für aufrichtig, er macht einen sanften Eindruck. So müssen wir, was seine Gerechtigkeit angeht, eine List gegen ihn ersinnen. Bringen wir eine Frau zu ihm, die beim Ehebruch ertappt wurde, und sagen wir ihm, was darüber im Gesetz geschrieben steht. Wenn er ihre Steinigung anordnet, so ist er nicht sanftmütig; spricht er sich aber für ihre Entlassung aus, so verstößt er gegen die Gerechtigkeit. Sicher will er seinen Ruf, sanftmütig zu sein, nicht verlieren; der hat ihn ja bei den Leuten beliebt gemacht. Deshalb wird er zweifellos sagen, man solle sie gehen lassen. Damit haben wir dann einen Anhaltspunkt zur Anklage.“

Doch seht, der Herr bewahrt mit seiner Antwort die Gerechtigkeit, und er zeigt zugleich Sanftmut. „Wer von euch ohne Sünde ist, werfe als erster einen Stein auf sie.“ Was für eine weise Antwort! Er hat sie dazu gezwungen, vor ihrer eigenen Tür zu kehren! Zwar machten sie die Ehebrecherin ausfindig, aber in sich selbst warfen sie keinen Blick. Sie verlangten den Vollzug des Gesetzes nicht aus Liebe zur Wahrheit, so als könnten sie den Ehebruch aufgrund ihrer eigenen Keuschheit verurteilen. Jeder, der sich selbst betrachtet, findet, dass er ein Sünder ist. „Wer von euch ohne Sünde ist, werfe als erster einen Stein auf sie.“ Das ist die Stimme der Gerechtigkeit: Die Sünderin soll bestraft werden, aber nicht von Sündern. Das Gesetz soll erfüllt werden, aber nicht von Rechtsbrechern. Das ist ganz und gar die Stimme der Gerechtigkeit. Von dieser Gerechtigkeit wie von einem Speer getroffen, blicken sie in ihr Inneres und finden sich schuldig; und „einer nach dem andern“ geht fort. Zurück bleiben zwei: die Erbärmliche und das Erbarmen.
