#+title:      Jahresplanung 03
#+date:       [2024-07-09 Di 11:02]
#+filetags:   :03:schule:
#+identifier: 20240709T110253

* Schöpfung – das Geschenk Gottes bewahren (Kapitel 1)
September bis Oktober

** Thema / Inhalt
- Begriff Leben
- Wunder des Lebens
- Schöpfung
- Schöpfungsverantwortung – Laudato si – Enzyklika 
- Zukunftswerkstatt
  
** Kompetenz laut Lehrplan
Die Schülerinnen und Schüler können sich als Teil der Schöpfung wahrnehmen und wissen, zu ihrem Erhalt beizutragen.

** Hinweis / Alternativen
Liturgische (Mit)Gestaltung:
Zu Beginn des Schuljahres oder für eine vorösterliche Versöhnungsfeier könnte das Friedensgebet (S. 112–113) als Vorlage zu Hilfe genommen werden.

* Sinn – dem Leben einen Grund geben (Kapitel 2)
November bis Dezember

** Thema / Inhalt
- Glück
- Genuss und Sucht
- Verzicht
- Ehrenamt – Engagement
- Sinnsuche
- Mythos und Logos
- Schöpfungserzählungen und Schöpfungsmythen

** Kompetenz laut Lehrplan
Die Schülerinnen und Schüler können die Frage nach dem Woher anhand biblischer Schöpfungsvorstellungen und naturwissenschaftlicher Konzepte bearbeiten und deren Vereinbarkeit argumentativ darlegen. 
Die Schülerinnen und Schüler können die Sehnsucht nach einem „Leben in Fülle“ zur Sprache bringen und vielfältige Sinnangebote bewerten.

** Hinweis / Alternativen
Kooperation mit Pfarre
Wenn sich in der 7. Schulstufe die Mehrheit der Schüler*innen auf das Sakrament der Firmung vorbereitet, könnte das Thema zur Unterstützung der pfarrlichen Firmvorbereitung erarbeitet werden.

* Freiheit – auf Gottes Versprechen vertrauen (Kapitel 3)
Jänner bis März

** Thema / Inhalt
- Freiheit – Sehnsucht nach Freiheit – Sklaverei 
- Heilserzählung
- Israel – ein Volk auf dem Weg in die Freiheit
- Exodus 
- Dekalog – Gebote heute?
- Goldene Regel – Nächstenliebe – Feindesliebe
- Reich Gottes und Gleichnisse
    
** Kompetenz laut Lehrplan
Die Schülerinnen und Schüler können die Reich-Gottes-Botschaft erläutern und vom befreienden Handeln Gottes erzählen.
Die Schülerinnen und Schüler kennen christliche Grundlagen des Zusammenlebens und können Ideen für ein gelingendes demokratisches Miteinander entwickeln.

** Hinweis / Alternativen
Kirchenjahr – Fastenzeit
- Exodus (Kap. 3.4, S. 59)
- Eine bleibende Erfahrung (Kap. 3.5, S. 60)

* Tradition – verwurzelt sein (Kapitel 4)
März bis April

** Thema / Inhalt
- Sonntag
- Anfänge des Christentums
- Petrus und Paulus
- Schriftliche Quellen erforschen
- Kirche – Volk Gottes
- Sakrament Weihe – Ordensleben

 Anhang: Religion für mich! Die Geschichte der Kirche

** Kompetenz laut Lehrplan
Die Schülerinnen und Schüler können die Bedeutung des Sonntags für das Leben des Einzelnen und der Gesellschaft wahrnehmen und reflektieren. 
Die Schülerinnen und Schüler können die Anfänge der Kirche und ihre Strukturen beschreiben und Einblick in das Leben der Orts- und Weltkirche geben.

** Hinweis / Alternativen
Kirchenjahr - nach Ostern: 
- Besondere Tage (Kap 4.1, S. 77)
- Impuls: Mein ganz besonderer Tag
- Der Sonntag (Kap. 4.2, S. 80)
- Die ersten Christinnen und Christen (Kap. 4.4, S. 83)

* Medien – Chancen und Risiken verstehen (Kapitel 5)
April bis Mai

** Thema / Inhalt
- Handy 
- Neue Gebetsformen
- Nachfolge
- Glaubwürdigkeit und Fake News
    
** Kompetenz laut Lehrplan
Die Schülerinnen und Schüler können die Nutzung von Medien und deren Potential reflektieren.

** Hinweis / Alternativen

* Islam – dem einen Gott verpflichtet (Kapitel 6)
Mai bis Juni

** Thema / Inhalt
- Glauben leben – Vorurteile
- Friedensgebet
- Islam
- Interreligiöser Dialog


** Kompetenz laut Lehrplan
Die Schülerinnen und Schüler können Grundzüge des Islam beschreiben
und ausgehend von ihrem Wissen und ihren Erfahrungen Beiträge zu einem respektvollen Miteinander gestalten.

** Hinweis / Alternativen
Interreligiöser Dialog
Feste und Feiern im Islam über das Schuljahr hinweg ansprechen
