#+title:      Neurobiologische Grundlagen von Empathie
#+date:       [2024-01-20 Sa 08:50]
#+filetags:   :fb:
#+identifier: 20240120T085050

Vortragende: Anneliese Maresch + Bianca Tusswald

* Gedanken
Bin eingestiegen und hab nix verstanden...

Worum geht es da? Ist völliges Neuland für mich - auch spannend. 

* Bianca Tusswald
KG Pädagogin - Sbg

Autismus-Spektrumstörung / tiefgreifende EW Störungen
Initiative Autismus

Worum geht es? - viel.

* Kindliches Lernen

* Emotion / Lernen / Entwicklung


* Frage?

** Emotionale / soziale Intelligenz - Unterschied?
Erst wenn jmd bei sich angekommen ist, kann er mit anderen in Beziehung treten.

** Welche Fähigkeiten hat ein emotional und sozial gesunder Mensch?
- kann sich regulieren. Kann nicht alles ausleben, wie ich will.
- Kommunikation. Nähe und Distanz. Was habe ich ausgelöst?
- Anpassungsfähigkeit.
- Konfliktfähig - Kritikfähig (bin fähig im Konflikt zu bleiben). Selbstwert ist so stark, dass durch Konflikt mein Selbstwert nicht zerbricht.

** Welche Probleme, wenn nicht?
- Aggression
- in der Schule geht kongnitives Lernen gar nicht; solang emotional+sozial ned gereglt ist, geht Lernen gar nicht.
- Mobbing
- Missverständnisse, Frustration, Resignation
- Verteidigung und Angriff
- Regeln werden nicht eingehalten (die aber Sicherheit geben sollten)
- Rahmen soll sicher sein
- Regeln bewusst nicht einhalten für mehr Aufmerksamkeit
- etc.


* Lernen
dauerhafte Veränderung die durch Erfahrung entsteht Whg sind entscheidend!

Ist es zB okay, dass ich meine Emotionen zeige? Wir prägen die Kinder: wie werden sie als Kinder in der Welt wahrgenommen? wir sind erste Kontakte außerhalb der Familie.
Selbstständigkeit wächst vom KG bis zur Schule.

Herausforderungen: entweder siehe mich zurück; oder werde aggressiv...

Das brauchts zum Lernen:
Neugierde - innerer Antrieb - Motivation - angemessene Lebensumwelt

- Mag mich der Lehrer? die Schüler? ...


** Gedächtnisspuren
Interaktion mit Umwelt: Verbindungen werden intensiviert, neue werden gebildet; Durch Wiederholungen entstehen bestimmte Bahnen (Signale folgen demselben Weg) ... Gedächtnisspuren.

Bestimmte Gedächtnisspuren sind bei Kindern schon verhanden (weshalb versch. L mit gleichen S anders reagieren)

** Größter Lernerfolg
- Das Kind ist aktiv beteiligt!
- alle Sinne müssen reifen
- entecken lassen (Lass es mich tun?), weil es sich sicher fühlt?
- Erleben lassen!

Konfuzius:
Erzähle es mir - vergesse es.
Zeige es mir - erinnern.
Lass es mich tun - behalte es.

Lernen: positive Emotionen verstärke es - negative hemmen es.

Ruhe: K ist in der Lage, was geschieht eigentlich. In der Wut sagen wir Dinge, die wir hinterher bereuen.

** Angst und Stress und Widerstand
können das Lernen massiv stören.

** Grafik
Wieviele Sinneseindrücke pro Sekunde (bewusst *und* unbewusst)? über 3 Mio sind da, viele bewusst (Selektion) ...
Wieviele Whg bis zur Automatisierung? 10.000x

Bewusste Eindrücke gehen ins Sensorische Gedächtnis. Enkodierung. Kurzzeit- / Arbeitsgedächtnis. Konsolidierung Abruf. Langzeitgedächtnis.

Arbeitsgedächtnis (4-5 EH / 7 +- 2 EH):
- phonologische Schleife (Reden, Ton, ...)
- visuell räumlicher Notizblock
- episodischer Puffer (Verknüpfung von Infos)
- zentrale Exekutive

Was ist eine Einheit? ein Paket an Eindrücken...

** Exekutive Funktionen
- soziale emotionale Kompetenz
- Selbstkontrolle
- Organisation

(Grafik)

Wann muss ich "um die Schaufel kämpfen"? Wann ist es unangemessen?
Planvolles Handeln? Lösung vorgeben? Lernprozess entsteht erst, wenn es das K selbständig macht.
Perspektive wechseln ist so wichtig (Empathie).

Manche K brauchen Stille und Einsamkeit zum besseren Lernen; manche K brauchen Pausen.
Autismus-Spektrumstörung / ADHS: Arbeitsgedächtnis kann sich weniger gut mit dem Rest vernetzen. Andere Erwartungen gegenüber diesen Kindern.

*** Extrem Stressanfällig
Bei emotionaler Erschütterung (Wut, Angst, Verzweiflung, ...)  werden Prozesse / Funktionen blockiert.

Exekutive Funktionen benötigen in der Entwicklung viel Zeit!

- Zeit geben / Verständnis zeigen
- Du musst es lernen, damit Du in der Welt bestehen kannst.
- Handlungen in Schritte aufteilen
- Geduld!
- Wiederholungen!
- Erklärungen
- Professionellen Umgang mit der Entwicklung der Emotionsregulation
- Passende Umgebung
- Passende Raumstruktur und Spielmaterialien
- Erlaubnis Fehler zu machen

Wie kann ich mich als K durchsetzen - wird ausgetestet.

Arbeitsgedächtnis ist wie ein Häferl, es geht einmal über.

Konfliktsituation - STOP! - Was will ich statt fliegender Stein: "Leg den Stein auf den Boden!" Und dann: wie gehen wir weiter.

Stop Spiele:
- Laufen - Stop - Hüpfen - Stop - ....
- etc ...

Somit lernen K, ihre Handlungen zu stoppen.

(Pause - bis 10:25)

Tagesablauf:
1 h Mittagspause 12:30-13:30
Schluss: 16h00

(Ungünstige sensorische Infos) bringen das Häferl zum Überfließen.

STOP muss immer gehen.


*** Das emotionale Lernen
Emotionen der KK beachten; sind das Fundament; sonst klappt Lernen nicht. KK sollen lernen, ihre Emotionen zu benennen.

Wie fühle ich mich?

Ohne Gefühle geht nix - gar nix. Wir Erw. regulieren wieder zu viel. Kernimpulse menschlichen Erlebens. Sind hilfreich und notwendig. sie sagen mir, wie es mir geht. Sagen mir, was ungemessen ist - oder nicht? sie schützen mich.

Sie sind immer anwesend und beteiligt. Sie regulieren Beziehungen zu anderen Menschen. Auf positiv wird super schnell gelernt. Mit negativen Em. können wir schwerer umgehen.

Emotionen sind das soziale Organ.

Über die Emotionen definieren wir: was tut uns gut? wie reagiere ich? ... wie werde ich wahrgenommen?

Bsp.: "Machen wir das?" K: "Nein!" Hey, warum?

Sieben Grundemotionen (Paul Ekman)
- Freude
- Trauer
- Überraschung
- Wut
- Angst
- Ekel
- Verachtung

Kinder erkennen diese Emotionen bei sich und bei anderen (!) und können diese richtig einordnen. Jeder Mensch lacht, wenn er sich freut.

8 primäre Emotionen
(Grafik)

Emotionen-Rad
manche Emotionen stehen sich gegenüber: Trauer durch Freude "heilen".

*** Wie entstehen Emotionen (Plutchick 1993)
- Bewertung :: was bei mir ankommt, wird bewertet; nützlich / schädlich;
- körperliche Reaktion :: physiologische Reaktion durch das autonome Nervensystem; ...
- Gefühl :: Diese Reaktionen bestimmen das Gefühl. Als L: "Aha, du ärgerst dich gerade? Stimmts?" Dh ich nehme dich wahr und bringe dich mit der Umwelt wieder in Verbindung.

Bsp.: Situation eines sehr aggressiven Kindes; kommt schon mit vollem Häferl in den KG; was tun? Das Kind braucht va Ruhe.

Bei den meisten ist es entweder das Hören oder das Sehen, das die K überlastet. Entweder Augen oder Ohren entlasten. Bitte Kopfhörer immer in der ruhigen Umgebung runternehmen. Kann das K die Gruppe verlassen? Ruhige Kleingruppen Aktivitäten (zB zu zweit)?

Bei beißenden K: drücken gegen beißendes "Kiefer".

Immer klare Verhaltensalternative parat. Einheitlicher Umgang unter allen Pädagogen.

*** Emotionale Kompetenz
Ein umfassendes Wissen über Emotionen und die Fähigkeit, mit eigenen Emotionen umzugehen.

Voraussetzung für positive soziale Interaktion und den Aufbau stabiler Beziehungen

K müssen den Umgang mit den eigenen und den fremden Emotionen erst lernen!

Wut und Ärger sind erlaubt, aber ich darf nicht "Blöde Kuh!" sagen; ich kann stattdessen "Stop! Hör auf!" sagen.

Der Erwerb der emotionalen Kompetenz ist eine der wichtigsten Entwicklungsaufgaben im Kleinkind- und Vorschulalter. Eine Grundlage für viele andere Entwicklungsbereiche.

Wo spürst du Wut? Welche Farbe würdest du dem geben? ...

Emotionale Unreife - nicht kognitiv konzentrieren können - Schwierigkeiten im Alltag.

*** Was ist die Wut?
- Eine starke Kraft, die eigenen Grenzen zu spüren und aufzuzeigen.
- Sie hilft uns "Nein" zu sagen; Veränderungen in Gang zu setzen und mit Nachdruck ein Ziel zu erreichen.

Dh unsere Emotionen haben (auch) positive Seiten. Meine Wut ist gut. 

- Diese Verhaltensweisen sind universell.
- sind durch individuelle Erfahrungen geformt.

Als Erwachsene können wir die Emotionen anderer Erw besser akzeptieren.

Wut ist erlaubt - wichtige Erfahrung für Kinder. Auch als Erw darf ich laut werden, aber ich darf nicht aus der Beziehung mit dem Kind fallen. Und niemals ist aber das Kind für meine Emotionen verantwortlich. Okay: "Ich bin jetzt wütend, brauche Pause."

Aggression entsteht dann, wenn der Ruhige Fluss der Interaktion blockiert ist.
Erfolgreich kommunizierte Wut ist konstruktiv - ich schütze meine Grenzen. Dient der Selbstbehauptung.

*** Alle Emotionen sind erlaubt
K stoßen an ihre Grenzen
Gefühle aushalten lernen
- Ich bin Emotionen nicht ausgliefert
- Strategien

Sogar Kontakt zu sich selbst verlieren

*** Erwerb emotionaler Kompetenz
Eigener Emotionsausdruck - eigene Emotionen wahrnehmen
dann bei anderen Emotionen wahrnehmen
Sprachlicher Emotionsausdruck sowie
Emotionswissen und -verständnis

Sekundäre Eomotionen: Scham

Empathie

*** Wie erleben K ihre Emotionen?
über den Tag...
Grafik - es steigert sich und schaukelt sich immer mehr auf ... (Grafik)

Was liegt dem zu Grunde? Was bringt das Faß zum Überlaufen? Welches Grundbedürfnis?

*** Praxis
gute Bücher - immer nachschauen

Was habt ihr im KG kennengelernt? SO genial war der KG!

*** Emotionsregulation
... von Emotionen übermannt zu werden.

Stell Dir vor: wie geht es dem Kind, den ganzen Tag so?

Jene Teile des Nervensystems, die Emotionen produzieren, reifen früher heran, als jene Hirnregionen, die für die Em-regulation und -steuerung verantwortlich sind!

Emotionen organisieren unseren Verstand
- Elemantare Überlebenssignale - Emotionen von Geburt an vorhanden.
- je älter Kinder werden, ....


*** Denke an das Lernen und den Arbeitsspeicher
- Begrenzte Speicherkapazität
- Warten lassen können - jener Bereich der arbeitet - Infos zusammenträgt, entscheidet, ...
- Keine Überforderung-Überreizung,


*** Amygdala
Geschwindigkeit der Genauigkeit

System 1: intuitive Reaktion ohne Nachdenken

System 2:
- (Weg über die Hirnrinde) - ich verstehe was passiert - kontolliert
- Interpretation, Regulierung, ...
- Dieses System muss erlernt werden - Gedächtnisspuren aufbauen - Co-Regulation


*** Emotionskoffer für die Praxis
Kuscheltier, Taschentücher, Clownnase, Heimwehtropfen, Wutsackerl, Polster, Buch, Salbe, Bildkarten, ...

Gut reden - Situation erklären - ...

Oder: mit Handpuppen den Streit nachspielen

- Wie geht es dir?
- Gefühle?
- welche Hilfe?
- Morgenkreis
- neue Emotionen benennen, wie ZB Eifersucht.
- Strategien
- Regeln erarbeiten, was ist erlaubt, bis wohin. Aber: keinen anderen verletzen, mich selbst verletzen, keine Gegenstände zerstören.
- Akzeptanz

Gutes Buch für Empathie: So war es! Nein so! Nein so!

Im KG: Karten - Fotos von Kindern in Angst, Freude, ... daraus Puzzle. 

*** Positiver Umgang mit Emotionen (von meiner Seite)
Kind weiß
- Ich bin gesehen
- wahrgenommen
- geborgen

  Ich kann auf mich und andere vertrauen; ich bin wunderbar; ich bin geliebt;

  Ein Kind entsteht vom du zum ich. Was andere über das K sagen, wird die Identität des K bilden, zu einem beachtlichen Teil. Unterschiedliche Wahrnehmungen von E und P, wird für das K sehr schwierig.


*** Bindungstheorie
- Wunsch nach sicherem Hafen
  Bindungsverhaltensweisen

  - Signalverhalten
  - Annäherung...

  
- Entdeckungen
  - sichere Basis sein als P: Ausgangspunkt, um Umwelt zu erkunden. 
  - Greifbar sein! Aktivierungsniveau muss passen.


*** Kleingruppe

**** Was braucht es, damit ein Kleinkind eine sichere Beziehung aufbauen kann?
- Regeln einfordern
- Rituale
- Kinder ernst nehmen
- eigene Vorbereitung
- gutes Essen (bei eigenen Kindern), Erinnerungen aus Kindheit
- Umgang mit eigenen Ressourcen (Erholungsphasen sind wesentlich)
- Rituale vorher erklären


**** ?
- eigene Haltung
- Glaubenssätze des Kindes
- Eltern, ... sie sind ganz wichtig!
- Eltern gut ankommen lassen
- selber authentisch sein
- ...


Präsent sein; was mich am Montag stört, das stört mich auch am Dienstag. Und was mich beim Maxi stört, das stört mich auch bei der Susi.


* Sichere Bindung
das K speichert Beziehungserfahrungen - sie sind veränderbar.

- Die sichere Bindung ist immer Aufgabe der Erw.
- Wir sind dafür verantwortlich und müssen in Beziehung bleiben.

darum:
ist die Zeit ein Regulationszeit? am Feuerlöschen? Oder ist es eine qualitative Beziehungszeit?

sei emotional offen, feinfühlig unf authentisch.

- wahrnehmen von Signalen = Zugänglichkeit - Erkennen von Bedürfnissen
- richtiges Interpretation
- angemessene Reaktion
- Promptes Handeln
- Emotionale Zuwendung

Verständnis für Gefühle der Kinder
Regelmässiger und angemessener Körperkontakt
Kontakt zu Eltern nicht über Kinder, sondern direkt mit ihnen.

** das Bedürfnis nach Orientierung und Kontrolle
Regelmässig und Verlässlichkeit

Das Bild vom Leitwolf - zB in der Pause / Freispielphase. Wie agieren die Kinder? 

* Was macht es manchmal so schwierig?
Wenn die Last des Kindes zur Last der Fachkräfte wird.

In dieser Situation können wir durch ... Sätze ... durch die wir aus der Beziehung gehen. Wir verändern unser Bild auf das Kind.

* Sprache
verbale Ausschreitungen sind genauso schlimm wie körperliche Gewalt!

** Handlungsfähig bleiben!
Ja, ich lasse dich in Ruhe! Aber ich lasse dich nicht alleine.
Die aktive und intensive Beobachtung hat den stärksten Einfluss auf die Haltung.

Erkenne die Ursache von herausforderndem Verhalten.
Erforsche das Grundbedürfnis!

Ganz wichtig: ich bleibe / wir bleiben in Beziehung. Wenn es nimmer geht: Beziehung übergeben.

* Grundbedürfnisse
- Sicherheit
- Freiheit
- Verbundenheit
- Ruhe
- Zeit
- Autonomie
  
- emotional

- sozial

- vital

- kognitiv

Manche Kinder brauchen mehr Zeit und wollen lieber beobachten; und es ist gut zu hören: "Das ist gut! Beobachte!" Schließe ich ein bestimmtes K aus? Die Klasse wird dieses Verhalten übernehmen. 

* Befreidigungsrad der Bedürfnisse

- Bedürfnisse werden gesehen und wahrgenommen
  - Komfortzone :: Bedürfnisse sind zu 60-100% erfüllt
  - Lernzone :: 40-60% der Bedürfnisse gedeckt. Was ist neu?
  - Risikozone ::

- Beziehung verletzt
  - Rad sieht anders aus: Risikozone wird übermächtig.


* Eisbergmodell
Welche Emotionen stehen hinter dem Verhalten?
Emotionen weisen auf Bedürfnisse hin - Bedürfnisse - Erinnerungen / Erfahrungen / Glaubenssätze des Ks


* Handlungsbegleitende Sprache
Achte auf deine Sprache

Besser:
"Brauchst du was? Ich bin für dich da."

"Bist du wütend? Erzähl mal."

Reflektiere was du wahrnimmst und siehst, fasse den Gefühlszustand und Situation des Kindes in Worte.
"Hm, jetzt sitzt du da unter der Decke. - Wie du weggelaufen bist, hab auch ich mich erschreckt. Was können wir uns ausmachen, dass du dich fix unter der Decke versteckst. Dann komme ich."
Denn: bevor das Kind spricht, handelt es!
Es braucht Menschen an seiner Seite, die ihm seinen Zustand begreifbar machen.

* Richtiges Loben

** Personenorientiert
- Eigenschaften loben
- ist negativ! Denn bei Fehlern entstehen Scham, Angst, Schuld, ...
- Bist du intelligent! Dh ich kann nix dafür. Und wenn ich was nimmer verstehe: dann bin ich dumm?

** Ergebnis
- Toll!
- Spitze!
Aha - was dann? 

** Prozessorientiert
- steigert den Selbstwert.
- beschreibe was du siehst
- ... den Aufwand
- ... den Fortschritt
- ... die Anstrengung

Ich weiß, dass dir das schwer gefallen, hast durchgehalten, ....
Lange geübt, ...

Ein Kind braucht nicht Anerkennung für das Erreichte, sondern dafür, dass es sich bemüht hat.

* Emotionsregulation durch Co-Regulation
Dh die Emotion des Kindes wird durch die Erw. begleitet.

Das geht nur, wenn ich selber reguliert bin. Ich muss ruhig sein. Wie mache ich das? Wie reguliere ich mich selbst? Knapp vor der Überforderung?

ist schwer während dem Unterricht...

Konkrete Schritte:
- *durchatmen* (langsam zählen)
- Stop! sagen.
- wie gehe ich in die Klasse? mit welcher Einstellung? mit welchem Gesicht?
- ich muss eigentlich schon Zuhause lernen, in der Familie, ruhig zu werden und zu bleiben.
- Plan B überlegen für besondere Situationen
- Hilft Humor?
- Wie leer ist das Liebes-Häferl (beim Kind)?
- Von mir weg auf das Kind schauen: was braucht es?
- Abstand, rausgehen, ...
- Ordnung schaffen
- Gebet / Singen ist ganz wichtig für die positive Emotionen / neurobiologisch
- Metaebene: wenn sich Kinder trauen, so wild zu sein, wie sie sind, dann kann das mein eigenes Selbstwert steigern (Ego pinseln), Zeichen des Vertrauens.

Bücher von Dr. med. Claudia Croos-Müller
- Übungen für den Akutfall ...
- ... um innere Balance


* Co-Regulation
Grenzen anderer respektieren

** Spiele der tiefgreifenden Rückversicherung
Rollen, fallen, hochsteigen, sich wiegen, getragen werden, sich verstecken, fangen, sich umhüllen, ....

** Wie gehe ich mit der Emotion um?
Atme durch, und dann sag es mir noch einmal ganz ruhig.

- Wut ::
  Wie kannst du deine Emotion ausleben? Was kannst du mit der Emotion machen? Hauen, schubsen, beißen, zwicken, schreien, treten, spucken, ...

  Wo erlebst du deine Emotion? zB in der Hand: Trommeln, reib die Hände, unter die Achseln, ... dies auch in der Ruhe üben. "Deine Wut geht in die Hände." (Schubsen) Selbständig einen Schritt zurückgehen, manchmal muss ich schreien, aber keine Schimpfwörter, stampfen, ... Spuck auf den Boden.

- Angst ::
  braucht geschützten Raum, ...

Erst müssen wir die Emotionen regulieren; dann sozialer Prozess. Schüler fragen: bist du bereit zum Gespräch?


* Entwicklungsschritte begleiten
viele kleine Schritte + Erfolge, um im Großen erfolgreich zu sein. 

* Soziale Kompetenz
- Kommunikation
- Teamfähig
- Konfliktlösefähig
- Identitätsentwicklung
- Selbstwert und Selbstwirksamkeit

Reißverschluss ist zach - helfen? Na. Dann nicht helfen.

Besser Zurückhalten.

"Das kleine Wir" - sehr schöne Bücher (KG von Leopold).

Anne-Sally-Geschichte
Wo glaubt Sally, dass ihr Ball ist?

Perspektivenwechsel: stabil nach dem KG. In der MS soll sich jedes K in andere hinein versetzen können. Wenn nicht - Gespräch mit den Eltern suchen.

Kann das Kind bei Emotionskarten die Emotionen der Anderen benennen?

* Theory of mind
die spezielle geistige Fähigkeit, sich in andere hinein zu versetzen, um deren Wahrnehmungen, Gedanken und Absichten zu verstehen.

- Empathie und Einfühlungsvermögen: sehr hoch, wenn ich mich zurücknehmen kann, um anderen den Erfolg zu gönnen.
- Vorstellungen, Ideen, Gefühle, Gedanken, Wünsche, bei anderen erkennen


** Spiegelneuronensystem
- Netzwerk von Nervenzellen im Gehirn
- Fähigkeit Handlungen anderer zu verstehen und diese vorherzusagen
- Senden Signale aus,
- Nachahmung


* Freundschaft
- Du gehörst zu uns
- Blöde Ziege, dumme Gans
- Waschbär findet neue Freunde
- Lasst uns Freunde sein

Warum ist das so wichtig für den eigenen Selbstwert?
weil Freunde selbst ausgesucht sind - er hat sich freiwillig für mich entschieden

Kompetenzen
- langsame Annäherung
- Fragen
- Reaktionen abwarten
- erst nach Zustimmung nächsten Schritt setzen
- sich in die Gruppe hinein spielen

Pos. Selbstbild - VH - Zustimmung - Selbstwirksamkeit - ich werde gemocht (Kreislauf)
Was braucht Rudi - das ihm zeigen.

* Praxisanregungen

Ich bin ich.
- was sind meine Interessen
- ...

(cf PPP)

* Bei Problemen
bei Kleinen: Bilder
- einer spricht der andere hört zu
- dann umgekehrt
- Wie geht es dir jetzt?
- Was möchte ich? Was brauche ich?
  ICH-Sätze ... zB "ich brauche rote Bausteine" "ich möchte mitspielen"
- wie könnt ihr es lösen?

Im besten Fall: Kinder lösen selber den Fall. Nix vorgeben. Kreativität fördern. Andere Kinder mit ins Boot holen.

- Problem ist gelöst! Manchmal auch nicht - dann haben wir auch was gelernt: wir werden warten müssen.

