#+title:      Das Wunder des Lebens
#+date:       [2024-09-09 Mo 21:52]
#+filetags:   :03:gemeinschaft:
#+identifier: 20240909T215228

* 1 Mögliche Beschreibungen, wie gläubige Menschen das menschliche LEben empfinden, könnten sein:

    - das Leben ist ein Geschenk Gottes
    - dass das menschliche Leben einen (tieferen) Sinn hat
    - das jedes Leben einzigartig ist
    - das menschliche Leben kein Zufall ist, …


    
* 2 Dieser Arbeitsauftrag regt zum
Theologisieren an und kann sehr individuell ausfallen.
Eine mögliche Antwort könnte folgend lauten: „Dass Gott die Menschen liebt und möchte, dass es den Menschen gut geht.“

* 3 Dieser Arbeitsauftrag ist sehr persönlich und individuell.
Hier bietet es sich an die Schüler*innen zu zweit oder in Kleingruppen zusammenarbeiten zu lassen, um gemeinsam ihr eigenes Leben zu reflektieren.

* 4 In dieser Diskussion ...
können die biologischen und theologischen Sichtweisen erörtert werden.
Auch hier bietet es sich an, der Frage: „Wem oder was verdanken wir unser Leben?“ in Kleingruppen zu besprechen und erst im zweiten Schritt die Ergebnisse in der Klasse zu diskutieren.

* 5 Bei diesem Arbeitsauftrag spielen
Moraltheologie und ethische Fragen eine bedeutende Rolle. Auch die Frage, ab wann spricht man vom Leben (Befruchtung oder erst ab Geburt) könnte hier zum Thema gemacht werden.
Aus dem christlichen Gesichtspunkt hat das menschliche Leben von Beginn an eine unantastbare Würde und eine unsterbliche Seele.

* 6 Die Bearbeitung des Arbeitsauftrages
erfordert ein fächerübergreifendes Denken. Hier könnte man den einzelnen Bildern eine Überschrift geben und den Zeitstreifen der Seitenspalte zur Hilfe nehmen.

    Bild: Samenzelle trifft auf Eizelle
    Bild: Beginn der Zellteilung
    Bild: erster Herzschlag
    Bild: Embryo am Utraschall 
    Bild: Geburt
    Bild: Kind enteckt sein "ICH"
    Bild: Kind lernt gehen
    Bild: Kind lernt selbständig essen
    Bild: Kind entdekt die Umgebung
    Bild: Pubertät beginnt
    Bild: erstes verliebt sein
    Bild: erwachsen sein


* 7 In der Diskussion
sollte einerseits die biologische Ansicht (Gene, Alterungsprozess) aber auch die ethische Sichtweise (Charakterentwicklung) mitgedacht werden.


* 8 Die Reflexion
über die Veränderung des eigenen Lebens anhand der Fotos kann für die Schüler*innen ein aufschlussreiches Erlebnis sein. Hier könnte man auch eine kreative Bearbeitung des Themas anschließen: Z.B: Gestalte ein Plakat mit den Fotos über die Entwicklung des eigenen Lebens bzw. der eigenen Persönlichkeit.

