#+title:      Ukraine
#+date:       [2024-01-08 Mo 21:29]
#+filetags:   :frieden:
#+identifier: 20240108T212947

* Link to [[https://multipolar-magazin.de/artikel/konfliktreiche-referenden][Konfliktreiche Referenden -]]
denote-link / URL: [[https://multipolar-magazin.de/artikel/konfliktreiche-referenden]]

* Ideen / Citation:
Die vier ukrainischen Gebiete Luhansk, Donezk, Saporischja und Cherson
trennten sich im Herbst 2022 nach Volksabstimmungen von der Ukraine
und wurden Teile Russlands. Der langjährige NDR-Journalist Patrik Baab
reiste für sein Buch „Auf beiden Seiten der Front“ auch in diese
Region und recherchierte vor Ort. Einige deutsche Medien machten
daraufhin Stimmung gegen Baab und bezeichneten ihn fälschlicherweise
als „Wahlbeobachter“. Die Universität Kiel entzog ihm unmittelbar
darauf seine Lehraufträge als Journalismus-Dozent. Baab siegte
anschließend vor Gericht gegen die Uni und ihre rechtswidrige
Kündigung. Multipolar veröffentlicht aus Baabs neuem Buch das Kapitel
über die Referenden in der Süd- und Ostukraine.

