#+title:      Göpekli Tepe
#+date:       [2024-03-05 Di 08:04]
#+filetags:   :history:religion:
#+identifier: 20240305T080432

* Doku
Göbekli Tepe [45min]
[[https://www.youtube.com/watch?v=rXLN_GNJ2kE][6.000 Jahre älter als Stonehenge - Göbekli Tepe - Ursprünge einer verschwundenen Zivilisation]]

* Artikel:

* Andere Quellen und Videos:

* Göpekli Tepe, der erste Tempel der Welt?

** Merkmale
Alter: über 11.500 Jahre alt; manche Teile sind noch älter: 12-14.000 Jahre alt.

Bau: um einen Stein zu transportieren braucht es 50 Menschen; diue ganze Anlage wurde in ca 6 Monaten (bis 12 Monaten) gebaut.

** Wer baute das? Wozu?
- Diese Mesnchen waren noch Jäger und Sammler (Knochen beweisen es); erst danach kam es zur Landwirtschaft. Dh die Religion war der Ursprung für Landwirtschaft.
- Totenkult? Toten fehlt der Kopf

Um dies bauen zu können, muss man fähig sein, so viele Menschen ernähren zu können, es braucht Plan, Werkzeug, ...

Stadt in der Nähe: man sagt, Abraham sei hier geboren worden. 11.000 Jahre alte Siedlung. Museum: Statuen mit Gesichtern; im Tempel - ohne Gesicht (weil Götter dargestellt wurden?)

** Theorie
Theorie: Landwirtschaft --> Siedlung --> Religion --> Tempel --> Stadt
Göpekli Tepe: Siedlung --> Religion --> Landwirstschaft --> ...

Warum? Vll verschafft dieses Umdenken einen Vorteil, um Tiere zB zähmen zu können. 


** Wie sah sich der Mensch? Welche Religion?
- Tiere als Wächter
- Mensch begann, sich den Tieren überlegen zu sehen
- Cf alte Höhlen: kaum Menschen dargestellt, va Tiere; Mensch sah sich als Teil der Natur.
- Essen nicht mehr sammeln
- sondern Nahrung produzieren
- Darstellungen des Jenseits; Totenkult?


** Ende des Ortes
Bau wurde zugeschüttet (nach über 1000 Jahren) und darauf kleinere errichtet - warum?

es wurden kleinere ähnliche Bauten in der Umgebung gefunden.

Nach 2000 Jahren verschwindet es ganz. Warum?
30 km entfernt: Siedlung mit öffentlichen Platz mit einer Art "Dorfkirche".

Nachfolger der Jäger waren Bauern und brachen mit den Traditionen der Jäger. Landwirtschaft war die Zukunft. Doch ... was besteht bis heute? Cf Auferstehung?

** Glaube?
400km entfernt - Bauern errichteten eine Siedlung; Glauben - 
