#+title:      Themen dritte Klassen
#+date:       [2024-03-04 Mo 13:14]
#+filetags:   :03:
#+identifier: 20240304T131431


* 3a
Wir könnten vielleicht über die 10 Gebote etwas auf dem Laptop arbeiten. Die 10 Gebote zeichnen. Ein Video über das aktuelle Thema anschauen, damit wir es besser verstehen. Kahoot selber erstellen.

Keine unwichtigen Themen machen, sondern Themen, die uns im Leben weiterbringen und etwas sinnsolles lernen wie z.B. das "Vater unser". Um es besser verstehen zu können.

Da die Firmung im Juni ansteht, vielleicht irgendwas über die Firmung, dass wir wissen, was da so geschieht und dass wir über das alles besser aufgeklärt werden.

Selber forschen im Internet.

Zu einem Text eine Zeichnung machen und dies dann besprechen.

Ein Legebild zu einem Thema.

Video zu einem Thema anschauen.

** Vater unser
Einzelne Bitten zeichnen; in anderen Sprachen lernen; ...

** Firmung
siehe YouCat Firmbuch
- Heiliger Geist
- Ablauf der Firmung
- Geschichte der Firmung / Taufe
- Gaben des Heiligen Geistes
- Jugendliche / Erwachsene erzählen, was es bedeutet - dem Hl. Geist zu folgen. Was hat sich verändert?
- ... etc


