#+title:      Mail an FPÖ
#+date:       [2024-03-02 Sa 09:32]
#+filetags:   :politics:
#+identifier: 20240302T093240
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width linewidth
#+OPTIONS: toc:nil
#+STARTUP: fnadjust
#+STARTUP: showall
#+export_file_name: ~/RoamNotes/exports/Mail an FPÖ.html


wir wenden uns an Sie, sehr geehrte Politiker der FPÖ, nicht um zu jammern, sondern um unsere Erfahrungen mit Banken, Teuerung, Hausverwaltung, etc in gewisser Weise öffentlich zu machen. Wir wollen uns zum Sprachrohr all jener mache, denen es ähnlich ergeht und nichts sagen. Wir kennen leider all zu viele, die sagen: "Da kann man eh nichts machen!" Oder - noch schlimmer: "Was die Poltiker beschließen ist gut, denn schließlich sind sie von uns gewählt." Ich weiß, dass sich auf der anderen Seite sehr wohl viele Menschen an Sie wenden.

Wir sind eine vierköpfige Familie: meine Frau (Französin) arbeitet in der Gastronomie als Köchin und Kellnerin in einem Bistro in der Stadt Salzburg (in der Linzergasse). Ich bin Religionslehrer an zwei Mittelschulen und hab in diesem Jahr auch eine Ganztagesstunde an einer Volksschule übernommen (sonst wäre ich nicht auf eine ganze Lehrverpfichtung gekommen). Unsere Söhne (12 und 7 Jahre) gehen in die Mittelschule bzw Volksschule in unserem Wohnort.

Vor ca sieben Jahren sind wir zur Raika Grödig gegangen und haben einen Wohnungskredit aufgenommen, um uns endlich unseren Traum einer Eigentumswohnung leisten zu können. Damals waren die Zinsen noch gering, wir wussten, dass die Rückzahlung eine große Herausforderung ist, aber sie war für uns meisterbar. Der Kreditvertrag ist mit flexiblen Zinsen.

Seit sieben Jahren leben wir hier und sind eigentlich zufrieden - was die Wohnung betrifft. Wir leben sehr gerne hier, die Wohnung ist traumhaft schön. Allerdings haben sich die Konditionen des Kredits in einer Weise geändert, die uns dazu bewegt hat, uns an Sie zu wenden. 

Die Kreditzinsen sind z.B. innerhalb des letzten Jahres von März 2023 mit 3,5% auf 5,25% im Dezember 2023 gestiegen (werden die Zinsen auf 7% steigen?). Das bedeutet, dass allein die Zinsen im Jahr 2023 insgesamt 9.800 Euro ausmachten, bei einer Kreditrate von insgesamt 18.000 Euro (1500 Euro pro Monat). Wegen diesen Anstiegs hat sich die restliche Kreditlaufzeit fast verdoppelt. Dazu kommt noch, dass vor Kurzem der Chef der Raika Grödig und Anif uns bei einem Termin eröffnet hat, dass die Bank - falls die Zinsen noch weiter steigen werden - auch die monatliche Kreditrate anheben will. Er hat uns aber versichert (mündlich!), dass die Bank dies in nächster Zeit nicht machen wird, da sich die Lage eher entspannen würde. Naiv haben wir unsterschrieben. Keine Woche war vergangen, da erhielt ich einen Biref, dass die Bank die Kreditrate um ca 30 Euro angehoben hat.

Auf jeden Fall sind wir, meine Frau und ich, äußerst geschockt. Wir sind finanziell nicht in einer Notlage. Aber wir denken in Ruhe über notwendige Schritte nach. In einem ersten Schritt will meine Frau ihr eigenes Girokonto bei der Raika kündigen und zur Konkurrenz (Sparkassa Erste) wechseln. Vielleicht mache ich einen ähnlichen Schritt.

Wir haben auch einen Brief an den Leiter der Raika Grödig, die Kreditabteilung und unserer Kundenberaterin bei der Raika Grödig verfasst.

Es hat sich in letzter Zeit vieles erhöht, zB stiegen die Betriebskosten unserer Wohnung um 100 Euro auf aktuelle 570 Euro pro Monat (inklusive Strom+Gas). Sollten die Zinsen auf 7% steigen, werden wir in absehbarer Zeit die Wohnung verkaufen und uns nach einer wesentlich günstigeren Bleibe in der Nähe von Golling (meinem Arbeitsplatz) umsehen müssen. Wir denken dabei, keinen Kredit aufzunehmen, sondern von der Verkaufssumme direkt die neue Wohnung zu bezahlen. Auch wenn die Wohnung wesentlich kleiner sein sollte - dies ist uns bewusst und das ist auch okay für uns.

Ich mag Österreich - aber wir sind es leid, ständig für alles immer mehr und mehr zahlen zu müssen. Wütend macht uns die aktuellen Politiker unserer Versager-Regierung. Hier sind wir Ihnen so dankbar für Ihren unermüdlichen Einsatz, um diese verlogene und miserable Politik des Versagens aufzudecken. Die Liste würde zu lang werden und dieses Mail endgültig sprengen.

Es gibt Freunde, die mir raten, den Beruf zu wechseln und in die Politik zu gehen. Aber da bin ich mir nicht sicher, ich kenne mich und glaube fest daran, dass Gott einen Plan für mich und unsere Familie hat. Es ist gut, dass ich Lehrer bin - ein wunderschöner Beruf. Und wie jeder andere auch, hab ich ebenfalls mein "Pakerl" zu tragen. 10-14 Jährige den katholischen Glauben näher zu bringen ist schön und herausfordernd, und das ist gut so. Gerade in Zeiten wie diesen sind die Werte, die der christliche Glaube vermittelt, umso wichtiger (siehe die aktuellen fürchterlichen Ereignisse unter den Jugendlichen in Wien, und auch in Frankreich passieren aktuell ähnlich schreckliche Dinge).

Manchmal denken wir auch über das Auswandern nach - aber dies ist ein allzu großer Schritt, und wer weiß, ob es im Ausland so viel besser ist. Meine Frau beherrscht Chinesisch und hatte vor einiger Zeit in Taiwan gelebt - das wäre eine Option. Manchmal überlegen wir, so quasi völlig "auszusteigen" und irgendwo autark zu leben. 

Wir wünschen uns endlich eine echte Erneuerung in der Gesellschaft und Politik, oft träume ich von der Zeit vor Corona - und va vor den Anschlägen 2001; diese Zeit kommt mir viel freier vor. Jetzt hat sich alles geändert, nichts ist mehr wie zuvor. Im täglichen Umgang, im Straßenverkehr - die Menschen werden immer aggressiver. Das Rad der Zeit lässt sich zurückdrehen, klar. Wir wünschen uns Politik FÜR die Menschen, dies würde uns ein wenig Hoffnung geben. Die Alternative zur jetzigen Politik ist in meinen Augen nicht direkte Demokratie (wenn gleichzeitig das aktuelle System unverändert bleibt - indem va Reiche und große Firmen profitieren und die Politik beeinflussen). Wir müssten grundlegend über Demokratie nachdenken und das ganze System auf komplett neue Füße stellen. Demokratie - JA, aber so, dass wirklich wir das Volk davon profitieren. Ich zitiere Volker Pispers: "Man kann im Kapitalismus keine Politik machen, von der 80% der Bervölkerung profitieren können."

[Abschluss, Bitte?]
