#+title:      Schulbuchaktion 2024/25
#+date:       [2024-03-22 Fr 09:44]
#+filetags:   :Project:schule:
#+identifier: 20240322T094428
#+CATEGORY: Schulbücher

* TODO [#A] Schulbuchlisten pro Fach [7/10]
DEADLINE: <2024-04-12 Fr>
- [X] Mathematik
  Wenn möglich ein Lösungsheft (nicht digital) in Lehrerstärke für Erarbeitungsteil
  Bernadette: ein Exemplar "Zahlen bitte e + E Book+" (nur eines)
- [X] Deutsch
  "Vielfach Deutsch Grammatik" 1-4, nur ein Exemplar, für L.
- [X] Englisch
- [ ] Musik
  "Club Musik"
  Wird da eig. etwas bestellt? Das Liederbuch, oder?
- [X] Geografie
- [X] Geschichte
- [X] Biologie
- [ ] Physik / Chemie
  "Mehrfach Chemie" (AH allgm)
  Christian fragen.
- [X] Religion (katholisch)
- [ ] Religion (islam)
  Wen frage ich hier?


* TODO [#A] Schulbücher bestellen [2/6]
DEADLINE: <2024-04-12 Fr>
- [X] Schülerlisten aus Sokrates erstellen
- [X] auf der Homepage Klassen anlegen; Daten übernehmen?
- [ ] Bücher eintragen
- [ ] Budget abgleichen? Digital / Normal?
- [ ] Zuweisen (Buchhandel)
- [ ] Bestellung abschicken

  Leider ist schon wieder das Budget für das Digitale weit überschritten. Entweder manche Bücher ins "normale" Bücherbudget eintragen; oder einige Lehrer fragen, ob wir statt E-Books+ normale E-Books bestellen können. (Frau Weninger fragen)


* TODO Schulbücher angekommen [0/3]
- [ ] bestätigen?
- [ ] Austeilen (pro Klasse)
- [ ] Reduktionen
