#+title:      Abschlusskonferenz
#+date:       [2023-07-07 Fr 09:17]
#+filetags:   :konferenz:schule:
#+identifier: 20230707T091743

Herzlichen Dank an alle.

* Lehrfächerverteilung

* Stunden D
Da kenne ich mich nicht aus...

Stundenverteilung birgt Konfliktpontential; so weit ich es verstehe, sind in den D Stunden einmal in der Woche nur ein Lehrer in der Klasse. Der Zweite kümmert sich um die Schüler mit spezieller Förderung. (Warum sträubt man sich con Seiten der D-Lehrer?)



* Unverbindliche Übungen

** Darstellendes Spiel
Gertraud E.

** Chor
Barbara K.?

** English Conversation
Lena

* Schülerzahlen
siehe Sokrates; hoffentlich springt kein Schüler ab, sonst verlieren wir eine erste Klasse.

zusätzlicher Schüler (Tobias 3b)
4a: noch eine neue Schülerin zusätzlich (Emma)
Schulbücher!

Manuela Gruber Schulbücher!

Weitere Anfrage bzgl 3. Klasse - Umsprengelung wahrscheinlich nicht möglich. (Hallein nach Golling)

Eine ao Schülerin: Olia?

Viviene: Anzeige geht raus; darf nicht mehr kommen. Jugendamt ist drauf.

3 Lehrer gehen: 6 neue Lehrer kommen. Aber davon nimmt nicht jeder eine volle Verpflichtung. Einige der Alt-Lehrer übernehmen mehr Stunden.

WH Prüfung: Hanna P. (Beisitzer gesucht)

* Erste Schulwoche

Mo
09:30 U-Schluss

11:00 Eröffnungskonferenz

Di
08:00 Eröffnungsgottesdienst

Mi
Wandertag

Do+Fr
KV Tage bis 11:30

* Stundenplan
bis 16:05

* Klassenkassa
Lehrer hat Karte
Eltern verwalten Konto
"es darf nix kosten"

* Klassenräume
3a + 3c würden in die ehemaligen 4a + 4b (im ersten Stock); plus die drei dritten Klassen.

1a: in jetziger 3b (Erwin)
1b: in jetziger 3a (Magdalena)
1c: in jetziger 3c (Gertraud)

3b: in Gruppenraum?

Standardgruppen in der Nähe des Turnsaals.

Dann könnten alle ersten Klassen oben sein (plus eine vierte Klasse)

Neue Lehrer: in der Induktionsphase - Begleitlehrer:
- Barbara E.
- Bernhard
- Gertraud V.


* Allfälliges
Einwurf Bernhard:
so viele kleine Baustellen: die Gemeinde kümmert sich um nix! Fenster seit 2 Jahren; Wasserhahn seit drei bis vier Jahren; Fenster im Gang; ...

Sport-Kustos: Julia übernimmt.
