#+title:      Notenkonferenz
#+date:       [2023-02-06 Mo 14:57]
#+filetags:   :konferenz:semester:
#+identifier: 20230206T145756
#+OPTIONS: broken-links:t H:6
#+filetags: :01:jahresplaung:
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+TODO: TODO(t) STARTED(s!) WAITING(w@/!) APPT(a) PROJ(p) NOTIZ(n) NEXT(x) BESPROCHEN(b) DELEGATED(g@/!) | DONE(d!) CANCELED(c@)
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org

* Begrüßung

Gratulation an alle Geburtstagskinder

Danke an alle für die Supplierungen; Deisl A. kann es noch nicht sagen, wann sie kommt. Birgit selber nicht ganz fit. Starke Antibiotika - Magen.

Wer für Astrid suppliert - ist bezahlt; bis Astrid wieder zurück ist.

Corona hat Spuren hinterlassen: Empfindlichkeiten der Eltern, etc. Beschwerden sollten besser bei Birgit landen, als direkt bei Fr. Kaserer. Versuchen, Kinder nicht bloßzustellen, sondern sie wachsen lassen.

* Corona und seine Auswirkungen
Wie war das Klima in der Klasse? Daran denkne Schüler. Nicht wenige Eltern sind nicht gleich einsichtig, wenn Kinder abgestuft werden. Erst Abstufung, wenn Förderungen angeboten werden. Gute Heftführung ...

Z.B.: SA Mathematik in der 3. Klasse; Hannes: SA nicht gut (muss wiederholt werden). Leichte Schulstufe - mit Schnellhefter. Vorher 3 Hefte mit blauem Umschlag. Mit Schnellhefter probiert, bei manchen hats gut geklappt, bei anderen nicht. Eigenverantwortung. Eltern beschweren sich, va von den leistungsschwachen Schülern.

Julia: SÜ Heft + Ordner für HÜ; ...

* Vetragverlängerung
Herabsetzungen bis 13.3.2023 

* Klassenkonferenzen
- 1a kein NG; kein WZ
- 1b kein NG; ein WZ für Lucian (seine Mutter hat zwei taube Ohren)
- 2a kein NG; Änderungen noch nicht; Betragen okay 
- 2b Vivien NG in allen drei Hauptfächern + BU; Betragen okay; Abstufungen (?); Vivine WZ wegen Schulschwänzen (nicht im Unterricht, aber im Cafehaus, unentschuldigt). 
- 2c ein NG Ivana in D; auch Leistungsabfall in E; einige Z, kein WZ.
- 3a NG Adrian in GW; kein WZ;
- 3b Mathematik: Schönauer und Höllbacher Änderung; sechs WZ (s.u.); ...
- 3c kein NG, Umstufung nein; zwei Z für Slatko und Maid (?), eher WZ? eigentlich WZ wegen unentschuldigtes Fernbleiben vom Unterricht; Belügen des Lehrers; ...
- 4a kein NG; Leistungsänderung Johanna Strubreiter in E; 
- 4b Carlos ist von Schule abgemeldet; Umstufungen keine; Markus Kaindl nach AHS?; kein NG; Markus aus disziplinären Gründen nicht nach Wien; ...

Wolfi: wegen angeblicher mangelnder Unterstützung als "Türkenhasser" bechimpft; Mutter direkt in Direktion; ...

Erwin: Ein WZ ist kein Problem; ein NZ wird haarig. 

Julia: türkische Mädchen "So dürfen sie nicht mit uns reden." - Mädchen erhalten ein WZ.

Christoph: Wenn das schwarze Buch leer ist, sind Diskussionen umsonst. 

Irmi: Was ist schulschwänzen? unentschuldigtes Fernbleiben vom Unterricht; ... Wenn man Schüler beim Spar sehe, der offiziell krank und entschuldigt ist? Vivien kommt in die Schule, erscheint nicht im Unterricht, denn retour in der Garderobe.

Birgit: Nachfrage bei Juristen; Vivien nicht nur schwänzen, sondern generelles Verhalten gegenüber der Schule.

Erwin: nur wenn es während der Unterrichtszeit ist. Alles andere wird haarig.

Hannes: alles, was jemand zur Genesung dient kann er tun.

* Notenkonferenz

** Betragensnoten 3B
Maximilian Fischhofer *
Andreas Rußegger *
Lukas Wagenhofer (8.)
Leon Keser (8.)
Thomas Krallinger *
Florian Steiner (8.)

WZ, weil: seit Beginn des Semesters massivste Störungen im Unterricht. Nach mehrmaligen Ermahnen keine Besserungen; zum Elternsprechtag Eltern herinnen, versprachen Verbesserung. IN der SchoolFox Nachricht wurde WZ angedroht. Keine Verbesserung, also WZ.

* Allfälliges
Nach den Ferien sind Schuleinschreibungen: 3x 1. Klassen; Eva die 3. KV

Schulnachrichten ausdrucken.

Freitag 5. Stunde, Unterrichtsende.

Programm steht für Faschingsdienstag - eintragen.

Eva: neue Homepage, gemeinsam mit VS Golling; Über Bildungsdirektion; VS hat ein Angebot. Neue Homepage kostet mehr als 3000 Euro. BM und Gernot wissen Bescheid. 

* Ergänzungen (durch Manuela Singer)

Förderschiene: 1. Klasse - 1. Std / Woche für alle im Stundenplan eintragen als fixe Förderstunde. z.B. 4 Std. im Block D oder M.

Verhalten der Eltern (zunehmend ein Problem); deshlab wichtig: ein guter Zusammenhalt im Kollegium

Porfessionelle Distanz bezüglich der Eltern wäre günstig. Warum mischen sich Eltern so viel ein?

SA-Termine für das 2. Semester festlegen.
