#+title:      Wien Migration
#+date:       [2023-02-09 Do 01:13]
#+filetags:   :gesellschaft:politics:
#+identifier: 20230209T011307

* Peter Westenthaler
- 46% der EW Wiens sind Migranten
- in 2-3 Jahren werden es mehr als die Hälfte sein
- 35% der EW Wiens haben keine österreichische Staatsbürgershaft
- Schaut's nach im 10. Bezirk; kein Wiener Geschäft, ...
- Schulen: 10.000 Schüler sind a.o., davon sind 60% in Wien geboren; dh Integrationsverweigerung
- 2 von 10 Kindern erreichen die Bildungszielen in Wien nicht.

Die Schüler im Studio - wer hat sie dorthin geschickt, wie kommen sie dort hinein? Wer hat sie gebrieft? Wer stellt ihnen die Fragen zur Verfügung? Haben die gesagt: Hui, ich will unbedingt dorthin, wo der Walhäusl ist! - Sind sie nicht bewusst ausgesucht worden, um bewusst zu provozieren.

Sehr viel Sturm im Wasserglas, ... aber auch viel Wahrheit.

Letzte Jhd war die Zuwanderung nach Wien aus Europa. Jetzt kommen sie aus Asien und Afrika. Z.B. Quellenplatz: Kabul oder Damaskas. 

* Josef Cap
Natürlich soll es eine kontrollierte Zuwanderung geben; schwierig, weil die WK und IV sind für eine qualifizierte Zuwanderung.


