#+title:      Was gibt es Neues
#+date:       [2024-04-25 Do 14:32]
#+filetags:   :hugo:
#+identifier: 20240425T143237
#+DESCRIPTION: This text was generated using the After Dark post archetype.
#+HUGO_CATEGORIES: family
#+HUGO_AUTO_SET_LASTMOD: t
#+HUGO_BASE_DIR: /home/matthias/flying-toasters/
#+AUTHOR: Matthias Fuchs

* Privat
Zuhause erfahren wir neue Herausforderungen in der Erziehung der Kinder. Gabriel tritt in die Pubertät ein. Sagt prinzipiell zu allem "Nein"; und in der Schule lässt er nach einem ausgezeichneten ersten Semester etwas nach. Gabriel ist wohl in der Phase zu mehr Selbständigkeit. Loslassen können ist schwer; die Kunst besteht darin, dies nicht aus (persönlicher) Enttäuschung zu tun, sondern zum Wohl des Kindes. Gerade in diesem Alter ist der Schritt zur Selbständigkeit so wichtig. Gabriel tut sich dabei besonders schwer.

Wir werden ihn nie fallen lassen; Schritt für Schritt soll er diesen steilen Weg gehen. Er schafft dies bestimmt. Besonders Kinder wie Gabriel werden später zu großartigen Persönlichkeiten. Zu leicht lassen wir uns von Gabriel's Scheitern, Unzulänglichkeiten, etc täuschen, geben auf. Entscheidungen sollen niemals aus dem Affekt heraus getroffen werden - und diese Versuchung ist groß. Wie schnell ist man als Papa oder Mama enttäuscht ...

Leopold geht einen ganz anderen Weg - ist in der ersten Klasse VS selbständig. Im Lernen und Erledigen der HÜ ist er sehr gewissenhaft, genau und wird immer schneller. Seine Schwäche ist der Zorn; da können die "Pferde" schnell einmal mit ihm durchgehen. Diese zu zügeln ist die große Aufgabe und Herausforderung für Leopold.

* Familienrat
Aus all diesen Erfahrungen heraus haben wir entschieden, uns am Sonntag für einen ersten Familienrat zu treffen. Jeder soll den anderen ein Kompliment sagen - und einen Punkt, in dem er selbst sich verbessern möchte. Bin sehr gespannt; hoffentlich kann dies auch das Verhältnis zwischen den Brüdern befrieden.


