#+title:      Konferenz
#+date:       [2024-05-28 Di 16:07]
#+filetags:   :schule:
#+identifier: 20240528T160713
#+LANGUAGE: de
#+BIBLIOGRAPHY: ~/RoamNotes/references/Literatur.bib
#+SETUPFILE: ~/RoamNotes/config/latex_setup.org
#+ATTR_LATEX: :environment tabularx :placement [h] :center t :width \linewidth
#+OPTIONS: toc:nil
#+export_file_name: ~/RoamNotes/exports/Konferenz Mai.html
#+AUTHOR: Matthias Fuchs
#+EMAIL: matthiasfuchs01@gmail.com

* Tagesordnung

** Feste Zusage
Huber Stefan, feste Zusage (12 Stunden), kommt doch nicht (PH und CH Stunden)
Zeindl Verena kommt sicher (E und Sport)

Wer würde diese Fächer übernehmen?
- Bernadette wäre bereit; nicht alles?

** Helferkonferenz Hannah
Dr. Ellensohn, Fr. Pickrahn, Fr. Ebner (Pro Juventute), Angelika Lichtenegger, DMS Birgit Lichtenegger, Barbara Essl;

Hannah ist im siebten Schuljahr, bei WH ist sie wieder in der 2. Klasse
Liste für Noten eintragen
Hannah ist bei der gesamten Konferenz dabei.

Ziel: wie soll es weitergehen?

Martin: geht es nur zw 4-5?
Hannah erhält keinen SPF; damit hilft man ihr nicht; sie könnte die Schule schaffen. 

Schulwechsel? Heilstättenschule? Einweisung, Mutter einverstanden, ...

Barbara: Wird es Hannah nicht zu viel, wenn sie ALLES hört? 

** Hilfe für Mario Ainberger
Hat Dr. Ellensohn für ihn Zeit? Sportwoche war gut, aber jetzt kommt er zB nicht in die Schule. ZB Manuela hat ihn kaum gesehen.

Wir machen schon mehr als genug.

** Theater auf der Burg
Viele Vorbereitungen
Martin: Karten, Einladungen

Bitte: alle helfen mit!

- So, 23.6.: Aufbau
- Mo, 24.6.: Generalprobe
- Di, 25.6.: 10:00 Schulen, 19:30 Erw
- Mi, 26.6.: ebenso

Bar: Christian, Anton, Mirjam, Gertraud V.
- Gläser, Kühlschrank, etc
- Soda
- Saft mitbringen?

So ist fertig

*** Mo/VM:
- Leihtechnik bei KeyWi holen: Markus
- Bühnenaufbau fertig
- Technik: macht Profi von KeyWi
- Ton: Profi
- Licht: 
- Kostüme in Garderobe: Erwin
- Sessel aufstellen: Restliche Schüler der mitspielenden Kinder (+ Lehrer: Erwin, Manuela Gruber)
- Bühne umbauen Probe:


*** Mo/NM:
- Soundcheck

  18h00 Generalprobe
- Souffleuse: Manuela
- Betreuung der Garderobe (Kostüme, Headsets, Ruhe): (Erw) "Ritterkammer"
- Nach der Aufführung: Aufräumen


*** Di/VM
- eingeladene Schulen, reservierte Karten, Verkauf (Spenden)
- Schminken: 
- Frisuren: wer kann das? (Malter Lena Mama?)
- Umkleiden:
- Karten"verkauf", reservierte Ḱarten, Spendenbox: Barbara Essl + Schüler
- Platzanweise: Lehrer + 2 Schüler; Ehrengäste: Rudi
  
- Aufführung
- Souffleuse: Manuela
- Betreuung der Garderobe:
- Pause Elternverein: "Problem"? weil die Kinder von versch. Schulen kommen. Kinder sollten selbst Jause mitnehmen
- Auffräumen: besonders im Zuschauerraum ist viel zum Auffräumen (ca 12h00); Restklassen (4b, 4c, ...)


*** Di/Abends
Aufführung um 19h30; Einlass: 18h30
- Karten: Birgit, Gertraud
- Schminken, Frisur:
- Umkleiden
- Vorbereitungen: Gertraud E.
- Platzanweiser: freie Platzwahl; nur für Ehrengäste
- Aufführung / Souffleuse: Manuela Gruber
- Betreuung hinter der Bühne:
- Pause:
- Auffräumen: alle.


*** Mi/VM
- eingeladene Schulen, reservierte Karten, Verkauf (Spenden)
- Schminken: 
- Frisuren: wer kann das? (Malter Lena Mama?)
- Umkleiden:
- Karten"verkauf", reservierte Ḱarten, Spendenbox: Barbara Essl + Schüler
- Platzanweise: KVs der einzelnen Klassen bzw L
  
- Aufführung
- Souffleuse: Manuela Gruber
- Betreuung der Garderobe:
- Pause: 
- Auffräumen: besonders im Zuschauerraum ist viel zum Auffräumen (ca 12h00); Restklassen (4b, 4c, ...)


*** Mi/Abends:
- eingeladene Schulen, reservierte Karten, Verkauf (Spenden)
- Schminken: 
- Frisuren: wer kann das? (Malter Lena Mama?)
- Umkleiden:
- Karten"verkauf", reservierte Ḱarten, Spendenbox: Birgit + Gertraud
- Platzanweise: freie Platzwahl; reservierte Plätze für Ehrengäste
  
- Aufführung
- Souffleuse: Manuela
- Betreuung der Garderobe:
- Pause Elternverein: "Problem"? weil die Kinder von versch. Schulen kommen. Kinder sollten selbst Jause mitnehmen
- Auffräumen: besonders im Zuschauerraum ist viel zum Auffräumen (ca 12h00); Restklassen (4b, 4c, ...)
- Bühne abbauen; Abtransport (Wirtschaftshof, Schule, ...): Niki Malter
- Sessel: zurück; alles säubern, besonders Bar.


*** Do/VM:
- Leihtechnik zurück: Gertraud od GV?
- Kontrolle der Kostüme: Name, Liste, Nummer, ...


*** Sonstige Tätigkeiten

**** Flyer falten
Manuela und Manuela

**** AKM anmelden

**** Abrechnung

**** Anbringen der Plakate
Schüler in den Geschäften
(Eltern von Musikumkindern)

**** Gutschein für "Ausrian Doctors"
Barbara Essl

**** Vervielfältigung des Films
für Schauspielerinnnen

**** Abendessen 

**** Fotos

**** Bühnenbild
Daniela, Bernadette, Ulli, Barbara K., Michaela

**** 2 Funkstrecken bei Republic ausleihen

**** Digitale Einspielung von Musik

**** Kostüme sammeln L + E Liste

Bei fast jeder Probe hat mind. ein Schüler gefehlt; 21.6. Projekttag (u o 20.6.) für Proben


** Charity Run
Uns geht's gut - und es gibt Kindern, denen es "weniger gut" geht. Für sie stellen wir was auf die Beine: eine Hilfe. Wir laufe, Leistung steht nicht an erster Stelle, sondern wir nehmen als Gemeinschaft daran teil. Diese Botschaft an die Kinder vermitteln. Positive Einstellung; jeder macht mit.

Folder sind ausgedruckt;

20.6.
- Beginn: (Beginn 07h45 in der Klasse); Start 08h30
- Ende: 12h30
- Zeit frei wählen über Wings of Life App
- Zwei Versorgungs-Stationen: Herbert, Martin; Barbara, Julia, Berna; 
- Grillen: Würstel (Bernhard, Christoph); Brot (Holztrattner); 
- Rote Nasen: können zur Verfügung stellen - Start Ziel Banner, Holzfahnen, Nasen, Startnummern, ...
- Einteilung: wer läuft mit? Streckenposten? ...
- KVs: Morgen + Mo - Event nahe bringen; Infozettel an Schüler weitergeben
- Firmen: Klassensponsor? Info nach Hause; Jede Klasse läuft zw 80-120km; pro km 1 Euro; so findet man pro Klasse mehrere Sponsoren ... so erläuft eine Klasse ca 500 Euro.
- Sponsoren Zettel
- Zuerst fragen: wer würde sponsoren?
- Diesen Kindern gibt man Sponsoren Zettel mit
- Meistens sponsoren dies Firmen, als Private.
- Im Extremfall gibt es Buffersponsoren
- 11h00 / 11h30 Siegerehrung: Sachpreise, Aqua Salza, Pokale / Medaille 1.-3. pro Klasse, meiste km Burschen / Mädels; ...
- Wer weiß noch Sachpreise? Trinkflaschen, RedBull, ...
- Wer vom Auto eingeholt wird; geht zurück zur Schule.
- Start: schnelle vorne, langsame hinten; ("Auto" ist über App; Strecke zu Ende gehen; ...)
- Strecken Ende: nicht bei Radständer, sondern der Straße entlang.
- Dürfen Eltern mitlaufen? Eher nicht? Sponsoren schon?
- Koordination mit Sponsoren (s.o.): KVs
- Info per SchoolFox / Zetteln


* Allfälliges

** Bei Überweisungen
wer, was, wann? bei Verwendungszweck

** Uneburteilt

** Digitales Lernen
Bitte mitfahren!

** 5.6. Schülerliga
Daniel 

** 6.6.
Moped WS

** 12.6. BM Leichtathletik
Anton, Eva, Daniel, ...

** 14.6. / 15.6.
Presse der Gemeinde: Mediensaal gesperrt

** 20.6. / 21.6.
Charity Run + Konferenz

** 21.6.
erste Klasse nach Abtenau (Musical)

** 27.6
Fototermin: Martin Leube

** 24.6. Dienstbesprechung Birgit

** 28.6.
Notenkonferenz

** 7.5.2025
Mental Health Day
Psychische Gesundheit
Experten kommen an die Schule 
